### ISSUE TITLE
select multiple via ctrl/shift mouseclick not working (webkit)

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#1001]
Hi,
it appears there is some quirk with the `<select>` tag with multiple selection mode using mouse.
in a trivial testing page like
```html
<select multiple>
<option value="01">01</option>
<option value="02">02</option>
<option value="03">03</option>
</select>
```
I can only select single item (with cursor keys or left mouse button), or multiple subsequent items via Shift+Up/Down keys
the usual way via Ctrl/Shift + Left mouse button doesn't work. 
I am not sure, whether this is a quirk in the rendering of `<select>`, like another one mentioned in
https://github.com/OtterBrowser/otter-browser/issues/940
or possibly some interference in handling the mouse events.
This is on Otter weekly 99, 32bit; webkit; Win7;
Interestingly, using test-qtwebkit.exe multiple select using mouse is working as expected (which might suggest some specific problems in handling of the mouse events).

regards,
  vbr

**Comment by Emdek** [comment]
@vbr, it looks like regression after implementing #77.
