### ISSUE TITLE
The first result of URL completion is broken

### ISSUE THREAD

**Issue by D101101** [OtterBrowser/otter-browser#1003]
The first option is always the search on DuckDuckGo and it search "DuckDuckGo" on DuckDuckGo...
![_2015-11-30_01-13-11](https://cloud.githubusercontent.com/assets/8783865/11460619/c3289f3c-9700-11e5-85c7-08461310f2e1.png)
![_2015-11-30_01-13-45](https://cloud.githubusercontent.com/assets/8783865/11460618/c326c248-9700-11e5-8f6f-ffa63e277e05.png)
version: 0.9.07.r270.g41e8645

**Comment by D101101** [comment]
hm...you fixed search, but now it does not offer anything except search

**Comment by Emdek** [comment]
@D101101, works for me and couldn't affect that.
Perhaps you experienced something like this #938.

**Comment by D101101** [comment]
@Emdek I use Arch linux
![2015-11-30 09 34 30](https://cloud.githubusercontent.com/assets/8783865/11465018/4d6c76c4-9746-11e5-8f91-bdac3b056024.png)
![_2015-11-30_09-35-02](https://cloud.githubusercontent.com/assets/8783865/11465022/50c7e2c2-9746-11e5-9151-abe4a98df36f.png)

**Comment by Emdek** [comment]
@D101101, try with www. prefix, currently it is not skipped yet (I'll add that before release).

**Comment by D101101** [comment]
@Emdek It works.
Ok, one more problem
The default is active the first result from the list - a search but must be active address bar (I mean, press «Enter» on it)

**Comment by Emdek** [comment]
@D101101, try now.

**Comment by D101101** [comment]
@Emdek, works great. I think this is a good reason to change my main browser.
