### ISSUE TITLE
Set default font sizes in pt instead of px

### ISSUE THREAD

**Issue by pierreporte** [OtterBrowser/otter-browser#1009]
In the configuration panel, it is possible to set the default font sizes for default text, for monospace text and the minimum font-size for all the text. Currently, the values are in pixels. It is not the best option since there is more and more hiDPI screens on the market where a text displayed in X px height on a standard screen would look like X/2 px height on a hiDPI screen. Not mentioning that pixel size and DPI settings is different from a screen to another, independently of hiDPI.

So, The text sizes should be expressed in pt and not in px.

**Comment by Emdek** [comment]
@pierreporte, I'm not sure if this is really an issue, Qt is supposed to scale that for us anyway, using logical pixel size instead of hardware pixel size.

**Comment by xploSEoF** [comment]
Nothing wrong with using px as a form of measurement. The browser converts "pt" to "px" anyway, then, through a magical factor known as "pixel density" translates this to a real-pixel value.

Ultimately, 1px is not 1 actual pixel on the screen, but instead, a specific angle of measurement, resulting at a certain size at specific distances from the eye.

For more reading:
http://alistapart.com/article/a-pixel-identity-crisis
Oh, and Google will also help you find the actual measurement (essentially, the angle of reference)

**Comment by Emdek** [comment]
I've just confirmed that Qt will indeed scale them to logical pixels anyway, so there is no real issue with that. ;-)
