### ISSUE TITLE
Entering an URL without providing a protocol that matches a directory in $HOME navigates to it using the file:// protocol

### ISSUE THREAD

**Issue by mulander** [OtterBrowser/otter-browser#1015]
Tested on OpenBSD otter-browser beta 8.

Steps to reproduce:
1. mkdir $HOME/google.com 
2. start otter-browser
3. type google.com in the addres bar and hit enter

Expected:
navigate to https://google.com or http://google.com

Actual:
navigates to file:///home/mulander/google.com

**Comment by Emdek** [comment]
@mulander, cannot reproduce under Linux, using both Qt 5.5 and 5.3.
It could be caused by some issue with ``QFileInfo`` here:
https://github.com/OtterBrowser/otter-browser/blob/master/src/core/InputInterpreter.cpp#L117

**Comment by mulander** [comment]
Try reproducing by launching otter from the command line. I tested with otter launched that way and that's the reason why it detected folders in my current working directory. Changing the CWD changes the 'detected' folders.

**Comment by beastie1** [comment]
Same here under FreeBSD. If I type **bin** in the address bar, instead of searching the keyword **bin** with the default search engine, Otter browses my user binary directory.

**Comment by beastie1** [comment]
Qt 5.4.1, BTW.
