### ISSUE TITLE
Favicon of current pinned tab disappears

### ISSUE THREAD

**Issue by pierreporte** [OtterBrowser/otter-browser#1018]
When you pin a tab and if this is the current tab, its favicon disappears. The favicon shows up again when switching to another tab.

*Version 357a692 with Qt 5.5.1 under up to date Archlinux.*

**Comment by Emdek** [comment]
@pierreporte, cannot reproduce, could you please attach screenshot illustrating this issue?

**Comment by pierreporte** [comment]
Actually, it’s a bit more complicated that thought: the favicons disappear *only* if the last tab is pinned. 
You can have any number of tabs, pinned or not, but to reproduce, the last tab must be pinned. Not the last pinned tab is affected but all of them.

Screenshots:

![Last tab is not pinned](https://cloud.githubusercontent.com/assets/2029853/11610440/68583ad4-9ba3-11e5-8d73-4321b3a0e882.png)

![Last tab is pinned](https://cloud.githubusercontent.com/assets/2029853/11610443/7f477174-9ba3-11e5-9986-d2c39f72b80b.png)

**Comment by xploSEoF** [comment]
I've had a few scenarios where this has happened on KDE4 - will verify replication instructions at some point soon.

**Comment by pierreporte** [comment]
I did not notice it at first but, as you can see on the screenshots, the close button of every non-pinned tabs also disappears. This time, however, it appears when selecting a tab (but only for the selected tab).

**Comment by pierreporte** [comment]
The favicon-related issue was fixed in 5ddf0a7 but not the close button-related one as reported in my last comment.

**Comment by Emdek** [comment]
@pierreporte, I can't reproduce that one, maybe it is somehow style dependent.
