### ISSUE TITLE
OpenGL support must be optional

### ISSUE THREAD

**Issue by DI555** [OtterBrowser/otter-browser#1020]
latest builds (I tested win32 builds) are with forced OpenGL support ((( This may cause troubles on some video cards...So great to be this function be optional!

**Comment by Emdek** [comment]
@DI555, OpenGL is kind of requirement for QtWebEngine at least, under Windows it can be provided by [ANGLE](https://en.wikipedia.org/wiki/ANGLE_(software)) which should be bundled already (at least for QtWebEngine enabled builds).
What kind of issues are you experiencing?

**Comment by DI555** [comment]
some built-in v.cards cause troubles with opengl accelerated browsers...
could be possible may be just delete dependencies to gl libs?
so after that might be possible (for example win builds) just delete Qt5OpenGL.dll and other gl files   for the browser working without opengl? (I did this trick with Chromium...)

there must be a way to turn off accelerating!!!... even oldOpera did the switch!
Could it be working without Angle? or possible Angle be switchable ?

**Comment by xploSEoF** [comment]
Correct me if I'm wrong, but I was of the impression OpenGL was different to hardware acceleration?

I can confirm there are a lot of PCs that require hardware acceleration to be turned off, otherwise unforeseen issues arise: blue tinge, jumpy frame-rate, or even just inability to process video.

**Comment by DI555** [comment]
@Emdek
I found one compiling option about it ...(in QT configuration options)
-no-opengl       (Do not support OpenGL)

could it be injected to about:config options ?
or may be as  --no-opengl  command-line parameter for executable file?

**Comment by DI555** [comment]
upd

@Emdek
I found two compiling options about it ...(in QT configuration options)
-no-opengl   ..........  Do not support OpenGL
-no-eglfs  ..........   Do not support EGLFS (EGL Full Screen/Single Surface)

could they be injected to about:config options ?
or may be as   --no-opengl   and   --no-eglfs     command-line parameters for executable file?

**Comment by DI555** [comment]
if not possible implement command lines or about:config parameters...., may be possible implement another executable file with noGL support.... and library files I hope with it must be the same !!!

it would be very useful - Otter without OpenGL... especially for live systems loading with cd/dvd/usb_flash- where GL is a very unstable!

**Comment by Emdek** [comment]
@DI555, I still have no idea what exactly is the issue here.
ANGLE was invented for cases where OpenGL is neglected.
OpenGL, native or not (ANGLE), is simply required.
