### ISSUE TITLE
support User Styles in ToDo

### ISSUE THREAD

**Issue by DI555** [OtterBrowser/otter-browser#1021]
I just saw only UserJS support in the nearest ToDo list (((
Would be great past there and User Styles also!

**Comment by Frenzie** [comment]
If you mean user styles like how Opera had display as text browser and such, that is definitely planned as well, but the most important type of user CSS is already in website preferences. ;)

**Comment by DI555** [comment]
wow, great,thank you! I haven't seen custom .css there !!!  (but yes, I mean a little more...)
And now - waiting very much to see .user.js also  there !!!

**Comment by DI555** [comment]
But is there an automatic install (from userstyles.org for example) like in Stylish ?

**Comment by Frenzie** [comment]
No, you have to set them yourself.

**Comment by xploSEoF** [comment]
User styles has already been developed and integrated. I'm grateful as I use it every day!
