### ISSUE TITLE
dealing with numerous tabs

### ISSUE THREAD

**Issue by msjasinski** [OtterBrowser/otter-browser#1023]
Most browsers have a UX problem with opening many (e.g. 28+) tabs. I dislike the scrolling mechanism that Otter/Firefox/Qupzilla/etc. offer. It is clumsy. Chrome and Vivaldi don't offer anything, which IMHO is better. Opera Classic (and some Firefox extensions) used to offer many solutions such as multiple tab rows (which took too much space). There was also a nice menu triggered by CTRL+TAB.

My suggestion: please introduce the icon to see all tab list similar to the one in Firefox/Qupzilla (in the top right corner of the screen).

Perhaps there are other better solutions I am not aware of.

**Comment by Emdek** [comment]
@msjasinski, this one can be solved only by #190, and that topic was already discussed some time ago.
