### ISSUE TITLE
problems with keyboard shortcuts (default.ini)

### ISSUE THREAD

**Issue by msjasinski** [OtterBrowser/otter-browser#1024]
Three issues.

---

[GoBack]
shortcuts=Ctrl+Left

Ctrl+Left is also used (system-wide) to move cursor one word back. As it is now, in address field it works fine, but in text field (e.g. as I'm typing now, it goes back in tab history, when the cursor should go back one word.

---

[GoForward]
shortcuts=Ctrl+Right

Same thing, substitute 'back' for ' forward'.

---

[GoToParentDirectory]
shortcuts=Ctrl+Backspace

This shortcut is also used, when it text mode, to delete one word.

---

Proposed solution: disable these shortcuts or if possible contextualize them.

**Comment by ManiacDC** [comment]
Found this issue as well while replying to an email in gmail. These should be contextualized... it works fine in Opera and Chrome.

**Comment by Chocimier** [comment]
[https://bugreports.qt.io/browse/QTBUG-56632](https://bugreports.qt.io/browse/QTBUG-56632) is related to Ctrl+Backspace in addressfield.

**Comment by Emdek** [comment]
This issue was fixed long time ago (at least for QtWebKit, where we are actually able to fix it).
