### ISSUE TITLE
File uploading segmentation fault

### ISSUE THREAD

**Issue by NeverLoved** [OtterBrowser/otter-browser#1025]
Segfault while uploading multiple (3+) pictures to facebook.com post. Otter segfaults not every time, one upload can be fine, another breaks browser. 
Reproducing fails for other file-upload forms and popular social networks (vk.com, ok.ru).

Traceback: [`$ otter-browser`](https://github.com/OtterBrowser/otter-browser/files/55879/otter-segfault.txt)
Strace output: [`$ strace otter-browser`](https://drive.google.com/file/d/0B7cPbUTCzHXmN2M1TFd1WU9Qekk/view)
Sorry for the google-drive link, log is too big for github or pastebin.

Otter version is 0.9.09 (cloned a few hours ago via otter-9999 ebuild), but this bug is true for previous versions.
Qt version is 5.5.1
System is Gentoo ~amd64.

**Comment by Emdek** [comment]
@NeverLoved, this looks like internal crash in QtWebKit, please try to reproduce it using this test application:
https://github.com/OtterBrowser/test-qtwebkit

**Comment by NeverLoved** [comment]
@Michal, test application works fine (tested 10 times).

Otter segfault is still present.

2015-12-09 0:20 GMT+02:00 Michał <notifications@github.com>:

**Comment by Emdek** [comment]
@NeverLoved, does it crash after disabling Java or plugins?

**Comment by NeverLoved** [comment]
Should I clone & build latest version or use one I've installed before?

**Comment by Emdek** [comment]
@NeverLoved, you can use the same one.

**Comment by NeverLoved** [comment]
@Emdek, no luck, segfault is still present.

**Comment by Emdek** [comment]
Now I'm pretty sure that it was some assert in QtWebKit, since Gentoo by default enables them and these are known to crash QtWebKit in edge cases.
If it is still relevant you can try to build QtWebKit (I would suggest revived version) with disabled asserts but with debug information (so if it reproducible it will at least produce more useful backtrace).
