### ISSUE TITLE
Mayhem.

### ISSUE THREAD

**Issue by textbrowser** [OtterBrowser/otter-browser#1026]
Performed this in a new Otter instance.

1. Add an Address Field tool bar item.
2. Paste https://ru.wikipedia.org/wiki/%D0%97%D0%B0%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D0%B0%D1%8F_%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0 into the field.
3. Place input focus on the address field and press Enter.
4. Destroy the tab.
5. Paste the aforementioned address into the address field and press Enter.
6. Again, place input focus on the address field.
7. While holding the Control key, press the Enter key.

Two new tabs appear. If you repeat this carefully, you can generate a growing list of duplicate tabs by holding down the Control key while pressing Enter. Sometimes two new tabs appear, sometimes more. Wild.

"Debug: QNetworkReplyImpl::_q_startOperation was called more than once ((null):0, (null))"

**Comment by ZarkBit** [comment]
Confirmed on my side, even managed to open 7 tabs at once lol.

Windows 7 x64
Otter Browser Weekly 101

**Comment by Emdek** [comment]
@textbrowser, it's feature, not a bug.
When using modifiers you can open URL / search results in new tab (background or foreground).
Although I start to dislike it and it may end up being removed or at least become configurable.
See #1007 789.

**Comment by textbrowser** [comment]
Yes, but a single press of the Enter key should not open two duplicates. One, sure. The other user was able to produce seven duplicates.
