### ISSUE TITLE
Right click not functioning with QtWebEngine

### ISSUE THREAD

**Issue by pwnage-pineapple** [OtterBrowser/otter-browser#1028]
When using the QtWebEngine backend, right clicking does absolutely nothing.

**Comment by Emdek** [comment]
@pwnage-pineapple, it was already noted in #615 that this backend is currently broken. :-P

**Comment by vernjensen** [comment]
I am experiencing this as well, using Qt 5.,6.2. Does anyone know what versions of Qt 5.6.x, 5.7.x, and 5.8.x will contain this fix?

**Comment by Emdek** [comment]
@vernjensen, current master contains another change that should work around remaining quirks of `QWebEngineView`.
