### ISSUE TITLE
3rdparty/libmimeapps/Index.cpp:255: bad erase ?

### ISSUE THREAD

**Issue by dcb314** [OtterBrowser/otter-browser#1030]
3rdparty/libmimeapps/Index.cpp:261]: (error) Iterator 'application' used after element has been erased.

    knownApplications_.erase(application);

Suggest RTFM for C++ erase. The return value from the erase has to be used.

**Comment by Chocimier** [comment]
We are using C++98 where erase return type is void, so can not use it.

**Comment by dcb314** [comment]
>We are using C++98 where erase return type is void, so can not use it.

Agreed, but the code still looks wrong, because it skips over elements.
Maybe --application inside the if would fix it.

**Comment by dcb314** [comment]
The new code still looks wrong. I don't think it will work right if
there are two consecutive elements to be deleted.

Has it been tested or single stepped through a debugger ?

Something like

    for (application = knownApplications_.begin(); application != knownApplications_.end();)
	{
 		if (application->second->types().empty())
   		{
 			delete application->second;
 
			knownApplications_.erase(application);
		}
		else
		{
			++application;
 		}
 	}

looks more plausible.
