### ISSUE TITLE
downloading from links containig a tab character 

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#1031]
Hi,
I just encountered a strange problem with links containing a tab character in the label - the linked content apparently can't be downloaded in Otter. it can be seen with html code like
```html
<a href="empty_jpg.jpg">empty	jpg.jpg</a> 
```
- i.e. empty<tab>jpg in the link label.

Clicking on a link directly works ok (the image is displayed in the browser), however calling "save link target as..." does not. - the filetype is not recognised (although the href attribut does contain just an ascii filename with the correct extension).
But more importantly, if I try to save the file, no data is downloaded (the download item stalls by 0 %, the resulting file has 0 B)
Other browsers, e.g. Opera 12 seem to handle this correctly.
I do see, that such html code is likely buggy in itself, but probably even such cases could be handled in a more robust way.
(win 7, Otter 32bit weekly 102)
regards,
    vbr

**Comment by Emdek** [comment]
@vbr, could you please provide link to some full example?
I've tried to simulate it in this fashion but without luck, although it could be some Windows specific issue too.

**Comment by vbr** [comment]
Thanks for investigating this - I created a sample html file with such link
http://www.vbr.wz.cz/test_link_tab.html
(the link point to an empty white jpg file).
I"ll also try to enhance the formating of the initial post.
regards,
   vbr

**Comment by Emdek** [comment]
@vbr, thanks, apparently this is some Windows specific issue, I can reproduce that only under Windows.
Hopefully it will be possible to workaround that somehow.
