### ISSUE TITLE
Acid3 test failure

### ISSUE THREAD

**Issue by pierreporte** [OtterBrowser/otter-browser#1032]
I ran the [Acid3](http://acid3.acidtests.org) test with Otter and it fails. Actually, it’s pixel perfect with the [reference rendering](http://acid3.acidtests.org/reference.html) except the red text “you should not see this at all”. The dialog box says (to display it, click above the blue and purple boxes):

> Failed 0 tests.
> Test 65 passed, but took 40ms (less than 30fps)
> Total elapsed time: 6.05s

I ran the test with Epiphany (GNOME built-in web browser which is based on Webkit, like Otter) and while on these two browsers the test is slow to start, only Otter “fails” it.

Screenshot of the test:

![Acid3 test](https://cloud.githubusercontent.com/assets/2029853/11875319/64e0a2ca-a4e4-11e5-8aad-50037fde5068.png)

Screenshot of the reference rendering:

![Acid3 test reference rendering](https://cloud.githubusercontent.com/assets/2029853/11875334/73bbb87a-a4e4-11e5-8f92-786783ae50df.png)

Difference between the two screenshots:

![Comparison between the test and the reference rendering](https://cloud.githubusercontent.com/assets/2029853/11875354/83a3dd6c-a4e4-11e5-9d1e-90f071f9d5e5.png)

**Comment by The-Compiler** [comment]
Note otter is based on QtWebKit, which is quite different from WebKitGTK - it's basically a webkit fork.

Either way, there's nothing Otter can do about this, as it's a backend thing. I'd guess it's better with the upcoming QtWebEngine/Chromium backend.

**Comment by Emdek** [comment]
@The-Compiler, it seems to be more complex issue, it works fine in *test-qtwebkit*...
But this doesn't make sense, as according to Web Inspector that element has white text. :-|
Also I have no idea what could cause that, I've disabled user stylesheets etc. and... I've got 99 / 100.

**Comment by Emdek** [comment]
It seems that I've found a reason, it expects that `QtWebKitHistoryInterface::historyContains()` will return true for that random URL that stays red (for example http://acid3.acidtests.org/empty.html?1450380343156).

**Comment by Emdek** [comment]
It's annoying that for some reason QtWebKit only allows to fully reimplement all methods instead of just wrapping it and reusing their way of storing these URLs in in-memory storage...

**Comment by pierreporte** [comment]
I just ran the Acid3 with the last version (7a62da48f9148c12c7b893061cc25161845444ec) and it works perfectly, without displaying “you should not see this at all” in red.

**Comment by Mouvedia** [comment]
cf http://ln.hixie.ch/?start=1270240159&count=1
