### ISSUE TITLE
AutoHide option for bars and sidebars

### ISSUE THREAD

**Issue by DI555** [OtterBrowser/otter-browser#1034]
it would be very useful for bars and sidebars to have a visibility option - AutoHide !!!
The way when moving a cursor to the place where bar or sidebar must be - bar or sidebar will be appeared!
and if not - will be hidden...

I hope it'll be great especially for full screen mode using!!!

**Comment by lollox** [comment]
I think it's a duplicate of this: https://github.com/OtterBrowser/otter-browser/issues/764#issuecomment-88393397 :)
