### ISSUE TITLE
transfers window - column resizing, file size sorting

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#1035]
Hi,
many thanks for the recent improvments in the tabular pages with columns. However, in a prominent one - transfers manager the behaviour is a bit strange. The width of the filename column can't be resized directly and defaults to a rather unsufficient value. I can make it wider only by narrowing some other tabs - the gained space is then used by this column.
The width also doesn't seem to be persistent - even in different calls within the same program run - the filesize column alwas shrinks to some minimal width. (The modified order of the columns seems to be persistent though.)
I would prefer to have the standard behaviour here, e.g. like the history window, where all columns can be adjusted directly.
There seems to be a problem in sorting of the file size column in the transfers window - the sorting is probably done lexicographically instead of taking the size value into account (both with respect to the decimal point as well as the different "units" - B, KB, MB ...)
I couldn't find whether this is the only place with this kind of issue, or there are others - like dates in the history dialog.

Best wishes for the New Year...
         vbr

**Comment by Emdek** [comment]
@vbr, remembering section size is separate task, generic feature for all views, and it wasn't decided yet how exactly it should work (saving percentage instead of pixels might be interesting since views can be resized, but it may also introduce unwanted complexity and side effects).

**Comment by vbr** [comment]
Thanks for this fix (and othere current enhancements or fixes in other issues)!
Now I can realise, that there are indeed multiple aspects, which are partly independent.
This newly introduced better deault sizing of columns helps a lot; the planned persistence of the widths would be nice too (in some next step); the same aplies about a meaningful sorting of the entries depending on the content of the column (but I see, that it is a completely different issue).
Thanks and regards,
     vbr
