### ISSUE TITLE
Cookies manager - <Expires> field shows 4x repeated am/pm

### ISSUE THREAD

**Issue by ZarkBit** [OtterBrowser/otter-browser#1037]
https://dl.dropboxusercontent.com/s/kvrdxtqbnv8j3t5/2016-01-02_20-23-20.jpg

That's from Cookies Manager, it shows ante merīdiem (am) or post merīdiem (pm) repeated about 4 times.

**Comment by Emdek** [comment]
@ZarkBit, probably translator mistranslated syntax for time and date for this field.

**Comment by ZarkBit** [comment]
English: MM.dd.yyyy HH:mm (**M**onth**M**onth.**d**ay**d**ay.**y**ear**y**ear**y**ear**y**ear **H**our**H**our:**m**inutes**m**inutes)
Portuguese: MM.dd.aaaa HH:mm (**M**ês**M**ês.**d**ia**d**ia.**a**no**a**no**a**no**a**no **H**ora**H**ora:**m**inutos**m**inutos)

So I guess that string should not be translated in this case. It's properly translated.
