### ISSUE TITLE
Port multimedia support to Gstreamer 1.0

### ISSUE THREAD

**Issue by s8321414** [OtterBrowser/otter-browser#1038]
I can see we have gstreamer0.10 in optional dependencies, if they are ported to gst1.0 is great!

**Comment by Emdek** [comment]
@s8321414, this is a task for distributions or Qt if something is till missing to get it working.

**Comment by s8321414** [comment]
So if I build otter from source, it can choose 0.10 or 1.0 to build against?

**Comment by The-Compiler** [comment]
AFAIK you'd need to build QtWebKit from source.

**Comment by s8321414** [comment]
Ah OK, so it depends on QtWebkit use gst 1.0 or 0.10, right?

**Comment by The-Compiler** [comment]
indeed
