### ISSUE TITLE
update check between weekly and beta

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#1039]
Hi,
Many thanks for the enhancements in the current release and best wishes for 2016!

I noticed a possible incompatibility between different release modes with regard to update checker.
Weekly 102 could find 103, however, beta 9 was not reported.
In the settings of the updater, all the release types are selected to be checked.
(I am not sure, whether this is a problem of the updater code or of some online available datafile with the current version.)
Regards,
    vbr

**Comment by Zero3K** [comment]
I think this issue should be looked at more closely.

**Comment by vbr** [comment]
Hi,
I'd like to add some further observation to this issue - even between weeklies, where the check for new version works ok, there might be some glitches with identifying the right version.
The update dialog is shown, and the button for "more info" points to the right download folder of the newest weekly, but the direct download button is greyed out, with an explanation, that some versions for my operating system may be missing.
I am using win7 (Czech) and Otter 32 bit webkit in portable mode and the weeklies in 7z archives .
regards,
  vbr

**Comment by vbr** [comment]
Hi, thanks for the current RC1 - just an observation on a similar topic like this original issue - the update check for the previous weekly 195 doesn't recognise the newest RC1, which was already available.
I didn't noticed this issue in the meantime, but I haven't paid a close attention to different releases (weekly, beta, currently RC).
I am also not sure, whether there is some problem with the updater check itself or just some metadata on the server is missing.
regards,
I am using 7z files (64bit) and manual unpacking to the program directory; on win7)
 vbr

**Comment by vbr** [comment]
Hi, I just noticed that the version check in weekly 203 doesn't recognise the current RC3 as a new version. The setting is the same like in the previous posts - Win7 and the respective versions (64bit) unpacked form 7z files.
Could this possibly depend on some specific configuration on my side, as this bug was supposed to be solved?

hth,
   vbr

**Comment by Emdek** [comment]
@vbr, try again, server was not up to date.

**Comment by vbr** [comment]
Hi, actually, the update checker in weekly 204 still doesn't see the RC3 version, even on the freshly unpacked install, just with the update channels schecked; 
on the other hand, in RC2 both weekly 204 as well as beta 0.9.93 are displayed as available updates - even though no update channel is checked in the settings - I kept the default settings, just unpacked the 7z archives to a new folder and added --portable via arguments.txt
(using otter 64bit from the 7z versions).
Win 7, 64bit.

regards,
  vbr
