### ISSUE TITLE
Site override of UserAgent not working

### ISSUE THREAD

**Issue by xploSEoF** [OtterBrowser/otter-browser#1040]
Site preferences for the User Agent string don't seem to be taking precedence...

System: Kubuntu 14.04 (LTS) 64 bit
Otter version: Beta 9 (it's been an issue before this point, but I've finally got the time to raise the issue)
QT version: 5.2.1

The network settings are:
![user-agent-selected](https://cloud.githubusercontent.com/assets/7510900/12089450/c1b792b4-b2dc-11e5-8e1d-440765a32698.png)

The reported user-agent sent to the site is:
![user-agent-reported](https://cloud.githubusercontent.com/assets/7510900/12089484/224b6ba0-b2dd-11e5-953d-056778ebec74.png)

**Comment by chusopr** [comment]
The site you are using, whatsmyagentstring.com, doesn't actually use User-Agent header to build that agent string, it uses JavaScript instead, as you can check if you disable JavaScript for that site: it won't render any agent string.
If you use any other site that actually uses User-Agent header, like whatip.org, you will see that User-Agent override actually works.

**Comment by xploSEoF** [comment]
That's fair, but unfortunately, still an issue! Opera 12.x changes the UA string to the JS as well - which is how a lot of sites seem to detect the browser.

**Comment by Emdek** [comment]
@xploSEoF, so far QtWebKit doesn't allow to completely overwrite User Agent.

**Comment by Emdek** [comment]
OK, my bad, I've checked it in wrong way.
