### ISSUE TITLE
Tabs on titlebar

### ISSUE THREAD

**Issue by zakius** [OtterBrowser/otter-browser#1041]
I'd like to be able to put tabs (and menu button) on title bar (or on it's replacement if it have to be hidden to achieve this) to
- save some space
- make tab clicking easier (if tabs touch upper border of screen it's much easier to click them)

**Comment by ZarkBit** [comment]
This has been addressed on #30

**Comment by opticyclic** [comment]
@Emdek shouldn't this be closed as a duplicate?

**Comment by Emdek** [comment]
@opticyclic, yeah, right now I'm in spring cleanup mode. ;-)
