### ISSUE TITLE
2 bugs

### ISSUE THREAD

**Issue by SonicBit** [OtterBrowser/otter-browser#1042]
• If holding the LMB on an EMPTY! place Express panel (Speed Dial), move mouse on a few cm \ mm and drop (Drag and drop) overflows RAM and pagefile = hang-up and departure (death)

• When you try to create a new search from the context menu it is not created at all=( although correctly completed dialog box is displayed as it should be [OK] ! what is surprising: under the same conditions but previously added by clicking on the button on the panel "Create Search..." everything works and is maintained properly.
________________________________________________
XP, 1.25GB RAM, Otter 9b v2 (0.9.09  01-01-2016)
… & Virtual PC

P.S. Translated from Russian (it is not clear, ask)
Thanks for new Opera

**Comment by ZarkBit** [comment]
Can confirm the fist bug.

As for the second bug, it creates the search, but if the search engine provides a "I'm Feeling Lucky" search, it forces its use. Checked on Google which has this feature and also ThePirateBay which also has the lucky feature.

Google Search Query: hl=en&source=hp&biw&bih&q={searchTerms}&btnG=Google Search&btnI=I'm Feeling Lucky&gbv=2&oq&gs_l

ThePirateBay Seach Query: q={searchTerms}&lucky=I'm Feeling Lucky&page=0&orderby=4

Otter v0.9.10 Weekly 106
Windows 7 x64

**Comment by SonicBit** [comment]
"Can confirm the bug fist"
Because of the difficulties of translation I did not understand the phrase, so I attach video proof:
[Swf screen movie.zip](https://github.com/OtterBrowser/otter-browser/files/92994/Swf.screen.movie.zip)
As for the second bug
I was able to understand the reason! (and it's not my fault or any particular website (I tried 1000, including Google))
In order to simulate my actions need freshly mounted Otter with a completely clear the default profile
0 - try to create a search in Google or Yandex or ThePirateBay, anywhere no matter what code. How would you not tried a new item on the search list won't be added(
![default](https://cloud.githubusercontent.com/assets/16567853/12373753/74197ae6-bc95-11e5-86d6-d730929902f7.png)

BUT=) . . . . . . . . . . . . Next solution...
1 - Now we remove 1 from standard searches, lets say "Bing" it doesn't matter what (it's even possible there also to return to the place, no matter Otter already "unlocked")
2 - repeat step №0 but this time everything is added perfectly=)

So your browser is just not just has been installed so you have everything added, check on pristine!

**Comment by ZarkBit** [comment]
I meant that I am able to replicate the first bug
Я имел в виду, что я в состоянии воспроизвести первую ошибку

The second bug appears to happen with Windows XP
Второй ошибкой происходит только с Windows XP

**Comment by ZarkBit** [comment]
LMB on speeddial overflows RAM and pagefile = hang-up and departure
Still present on Weekly 108

Unable to check second bug (XP related), for now.

**Comment by Emdek** [comment]
@SonicBit, first part of your submission has now own ticket: #1059.
I will check what is wrong with the latter part later, it should ignore unchecked options.
You can manage existing search engines in Preferences.

**Comment by Emdek** [comment]
The latter issue is not reproducible, works fine with both backends here (using current master).
But the detail with submit buttons being picked up is valid.
