### ISSUE TITLE
A change in menuBar.json not backwards-compatible

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#1043]
After an update, Bookmarks menu was invisible, while Bookmarks manager was doing fine. The problem on the user side was fixed by changing the word Addbookmark in menuBar.json to BookmarkPage.

**Comment by Emdek** [comment]
@ersi-dnd, well, some changes might break stuff, this is why we don't call it final yet. ;-)
I'm trying to avoid breaks, but the might happen from time to time.
