### ISSUE TITLE
Enable JavaScript action not working as icon on toolbar

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#1044]
I've added that action but it doesn't do anything with JavaScript neither globally nor with the current tab.

Of course I'd prefer it to affect the current tab only.

In fact if I toggle the icon "on" in some tab, it will stay that way, and it will be toggled "off" for all other tabs. But it just doesn't have any effect in any tab.

**Comment by uahim** [comment]
any news on this?

**Comment by Emdek** [comment]
@uahim, this action (and few related) is not implemented, only declared.
F12 menu uses different implementation, but it should switch to standard actions.

**Comment by uahim** [comment]
ah, F12 is fine then; I was using about:config in the sidebar which was a little annoying after a while.
thanks!

**Comment by beastie1** [comment]
Great! It works perfectly. Thanks.
