### ISSUE TITLE
[Content Blocking]  parsing bug crash Otter

### ISSUE THREAD

**Issue by k3dar** [OtterBrowser/otter-browser#1045]
if activate Content Blocking / EasyList, then Otter crash in page load, or load only "white page" and crash after right mouse button

i find that problematic rule from easylist.txt is:
### adframe:not(frameset)

if this 2 line is commented using !, then Content Blocking working

tested with 0.9.99~git20160109+r7~ubuntu14.04.1

**Comment by bajasoft** [comment]
@k3dar: Please, try latest weekly to check if the problem still occurs

**Comment by k3dar** [comment]
tested "0.9.10-dev109-1" on "Xubuntu 14.04.3 i386" with exact (unmodified) easylist.txt as in me previous test and also with up-to-date now updated easylist.txt... both work fine without crash... thanks :)

**Comment by SJ-Diamond** [comment]
Still experiencing crashes like that under Windows

**Comment by bajasoft** [comment]
@SJ-Diamond: Does it happen on some specific page? You can also try to delete entire "blocking" directory from your profile. It will refresh all content blocking profiles after next restart.

**Comment by Emdek** [comment]
@SJ-Diamond, any news for this issue?
