### ISSUE TITLE
Don't allow http xhr calls originating from https connections

### ISSUE THREAD

**Issue by mulander** [OtterBrowser/otter-browser#1046]
```
22:13 < bmercer> hah, otter-browser is the only one willing to do an http xhr call originating from an https connection
22:13 < bmercer> (which is useful despite being a bit... terrible)
22:14 < mulander> bmercer: oh wow, you should report that
22:14 < bmercer> no, because then I won't have a tool in my toolbag!
```

You can be nice by adding a --no-security flag to enable behavior like this.

**Comment by knowmercy** [comment]
I'm doing something like this. 

####
var self = this

this.on('mount', function(){
  var request = new XMLHttpRequest();

  request.open('POST','http://anotherhost:9090/api/socketinfo/', true)
  request.onload = function() {
    if(request.status == 200){
      spinner.classList.add("hide")
      sockets.classList.remove("hide")
      var results = JSON.parse(request.responseText)
      self.update({ message: results.Message })
      self.update({ sockres: results.ConfiguredSockets })
    }
  }

  request.onerror = function() {
      spinner.classList.add("hide")
      self.update({ message: "Error getting socket information" })
  }

  setTimeout(function(){
    spinner.classList.remove("hide")
    request.send()
  })

})

**Comment by Emdek** [comment]
According to discussion at #qtwebkit it is upstream issue, possibly related to CORS headers.
