### ISSUE TITLE
Look and feel

### ISSUE THREAD

**Issue by zakius** [OtterBrowser/otter-browser#1047]
While you mention in FAQ that Otter is meant to feel look and feel native I can see two problems with that
- QT seems to draw controls it's own way even if you set it to system style (at least on windows)
- it would be inconsistent between platforms

Other browsers completely dropped native look idea and went for consistency across platforms, they look and feel (or try to) the same wherever you run them

While I'm aware that it is minor issue I feel like it would be nice to have it sorted out somehow, or at least direction set before first stable release, all currently available styles feel too rough, especially main window tabs that are not using styles feel at all

**Comment by Chocimier** [comment]
I do not think that inconsistency between platforms is a problem, because:
* if you use only one platform, you have consistency between applications
* if you use more than one platform, you don't do it to use portable  
applications, but available only there, probably with native look, so you  
know how native applications behave

**Comment by Frenzie** [comment]
I'm not really sure what you mean by saying that other browsers completely dropped native look and feel? The only example I can think of is Vivaldi.

**Comment by zakius** [comment]
They don't try to use native controls, and even if they do they style them own way
No matter if you run them on win xp, 10 or gnome most of controls look the same, actually only titlebar and window border are drawn completely by OS, and even not every one is like this.
By native I mean: When I run it on xp it follows luna style, if I run it on xp with luna disabled everything changes colours and shapes because they are indeed native controls presented by OS libraries
And Qt just have own controls letting you style them as you want, but I've never seen Qt really using OS look, just trying to mimic it, but failing miserably when you ran it on newer version or uncommon theme

**Comment by Emdek** [comment]
@zakius, we try our best, but as noted in TODO polishing up UI details to look more native (there is still room for improvement, as you noted, mainly under Windows and MacOS X).
Theming is also planned, see #36, but I'm not planning to use some fully custom style by default.
