### ISSUE TITLE
Problem with new history system in Otter for Windows

### ISSUE THREAD

**Issue by SJ-Diamond** [OtterBrowser/otter-browser#1049]
There are several bugs/strange things i experience:

1) Can only partly delete history items, some are stuck when i try to delete them, but i can if i restart the browser

2) After clicking few times on address/title/date categories right above actual history items, it can happen that a new entry is landing instead in "today" in a new category called "earlier that month"

**Comment by ZarkBit** [comment]
So far, been able to reproduce all reported bugs. Confirmed, I guess.
https://dl.dropboxusercontent.com/s/gctu4ftirqnz9ol/Otter Browser - History.gif

Otter 0.9.10 weekly 107
Windows 7 x64

**Comment by Emdek** [comment]
@SJ-Diamond, @ZarkBit, are there any remaining issues left (except of course of missing favicons) in recent weekly?

**Comment by SJ-Diamond** [comment]
if i click in history on the sorting categories, clicking a bit around there, and if i open a new tab with some page and close it, it does not land in today but instead in earlier this month or in earlier this week. It looks like sorting seems to screw up history - and new history entries are just inserted elsewhere but not under today category where they belong

**Comment by ZarkBit** [comment]
still present 
https://dl.dropboxusercontent.com/s/m00e0ubvoe9pfnc/Otter Browser History Problem Weekly 108.gif

The duplicate problem seems to be gone when Otter is installed from scratch, but still present if installed on top of the previous weekly

Otter 0.9.10 weekly 108
Windows 7 x64

**Comment by SJ-Diamond** [comment]
Any updates about that bug? Can it be fixed?

**Comment by Emdek** [comment]
@SJ-Diamond, proper fixing of this issue requires finishing work on proxy models (the one which also brings multiple columns to some views that are missing that feature) but it still has issues with selection.
