### ISSUE TITLE
Save url into .url file, drag&drop url form address bar into file system folder

### ISSUE THREAD

**Issue by theusernamelessone** [OtterBrowser/otter-browser#1051]
This feature is present in most browsers as a drag&drop function from the address bar icon, to the desktop, or some folder, or some file manager program (total commander, double commander). A ctrl+s approach, or a save all open tabs at once upgrade would be neat too.

File name should be the page Title with replaced  forbidden characters, and the contents are  something like this (at least on windows, don't know how Linux dose it):

```
[InternetShortcut]
URL=https://github.com/OtterBrowser/otter-browser/issues/new
```

**Comment by pierreporte** [comment]
In addition, this should be also possible when you drag & drop a link in the page.

**Comment by theusernamelessone** [comment]
+multiple links dropped -> multiple new tabs will open (after the warning dialogbox)

**Comment by theusernamelessone** [comment]
An other nice thing I've just realized in the old Opera, that you can drag&drop an image to the desktop and it will be saved as a file! Never used that one, but a good feature to have on board and it connets to the one about d&d a link from page into url file.

**Comment by Emdek** [comment]
@theusernamelessone, such behavior should be achievable by adding extra MIME data, right now we only set *text/uri-list*.
Same should apply to images, but that one might be backend dependent.

**Comment by pierreporte** [comment]
@theusernamelessone your two last ideas are great but I think I was misunderstood. I meant that if you drag a link that is placed in the page (a username on Github for example) to a folder on your computer, it creates a .url file (just like as if you dragged and dropped the URL in the URL field).
