### ISSUE TITLE
Left click after scrolling causes additional scrolling

### ISSUE THREAD

**Issue by PStokman** [OtterBrowser/otter-browser#1052]
When you scroll a page with the mouse button and left click without moving the mouse around, the page scrolls about the same distance again. This is very annoying as you can miss a link or click on the wrong one.

I don't really remember when it started exactly, but it's been a problem for a couple of months already. It isn't platform specific either, I've succesfully repeated it on my main OS (Debian Unstable, with the Ubuntu Vivid weekly packages and Qt 5.5.1) and on Windows 10 in a VM.

Steps to reproduce:

1. Open a website that you need to scroll on (e.g. the issues overview)
2. Scroll a few notches down or up, depending on your position, don't go to the end of the page
3. Left click (or right click, depending on your mouse button settings for primary button)
4. The page scrolls the length you just scrolled, or until it hits top/bottom, depending on direction and how much is left.

Expected result:
The page does not scroll when left-clicking.

Current work-around:
Move the mouse cursor around before clicking.

**Comment by ZarkBit** [comment]
Able to reproduce.

Otter 0.9.10 weekly 108
Windows 7 x64

**Comment by PStokman** [comment]
The extra scrolling isn't limited to the tab you're scrolling on. If you scroll on one tab, then with ctrl+tab switch to another one and click without moving the mouse, the now focussed tab will scroll.

**Comment by PStokman** [comment]
@Emdek, should this fix be in weekly 112? I would expect it to be, but I just tested and it isn't. At least not on the Ubuntu PPA weekly builds.

**Comment by ZarkBit** [comment]
Same on Windows, this bug is still present on weekly 112.

**Comment by PStokman** [comment]
With weekly 113, it is still not solved. Just updated the browser on a Windows VM and it still scrolls after a left click.

I have no idea why this issue was closed two weeks ago, as it is clearly not solved.

**Comment by PStokman** [comment]
Well I'll be. It no longer happens with weekly 118. :+1: :)
