### ISSUE TITLE
QNetworkAccessManager lock up on connection loss

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#1054]
Hi all,
recently I noticed some strange behaviour of Otter on password protected sites (e.g. webmails) in connection with some network errors.
If a server request is attempted and no network connection is available (it can be simulated e.g. be disabling wlan etc.), the browser displays an appropriate error page - Like Error 3 - site address not available ...
However, after reanabling the connection and reloding the page tab, the invalid data seems to be somehow kept and the error page is repeated.
If I then open the same site in a new tab - manually or using "clone tab", the page is displayed correctly (even without reentering the credentials).
Could it possibly be some cache invalidation issue?
I wasn't able to verify this using test-qtwebkit.exe, as there seems to be no visible activity e.g. on clicking links without a usable network connection - i.e. no error page etc.
(Otter weekly 110, 32bit webkit; win7)
regards,
    vbr

I am not sure I

**Comment by Emdek** [comment]
@vbr, it looks like manifestation of *QtNetwork* issue when ``QNetworkManager`` becomes useless after disconnecting network (especially WiFi), and since each tab has own instance of that class it could explain that it works after cloning, but not when reloading.
