### ISSUE TITLE
Allow to edit cookies

### ISSUE THREAD

**Issue by midluk** [OtterBrowser/otter-browser#1055]
I have noticed that in the Privacy tab of the Website Preferences (from right click menu on webpages) all cookies show with "Path" given as "/". You can see the value, but not the name of the cookie. And the "Add", "Edit" and "Delete" buttons are all grayed out.

The name of the cookies is shown properly in the Cookies item in the Sidebar (but not the value of the cookies), in the Cookies Manager (from Tools->Cookies) everything is shown, but also there only the "Delete" button is available (all fields to edit and "add" button grayed out).

This is with current git version on Fedora 23 x86_64

**Comment by Emdek** [comment]
@midluk, path is shown properly for me.
Name apparently got somehow overlooked, I'll add that column.
Editing is not yet available (it is not so hard to do, but I'm not 100% convinced yet that it should really be so easy).

**Comment by midluk** [comment]
I the website preferences I can now see "Domain" (which is correct), "Name", "Path" (which always seems to be "/"), "Value" and "Expiration Date".
What is "Path" expected to show? I expected this field to show what is now available as "Name".

Also it would be great if at least the "delete" button worked in the Website Preferences, if full editing is not implemented.
