### ISSUE TITLE
Missing margin-right for dropdown history icon

### ISSUE THREAD

**Issue by francoism90** [OtterBrowser/otter-browser#1057]
The search-icon on the SearchWidget has a margin on the right, but the dropdown icon for the Address Field does not.
Not a big issue, just so the UI looks a bit nicer. :)

Thanks.

PS. I have tried editing AddressWidget.cpp, but no luck so far. :/
PS2. The adblocker/content-blocker doesn't work when using qtwebengine as backend.

**Comment by Emdek** [comment]
Uhm, I'm not sure if this ticket is still valid.

**Comment by francoism90** [comment]
True, will test if this is still valid and reopen if needed.

**Comment by Emdek** [comment]
@francoism90, that was fast. ;-)

**Comment by francoism90** [comment]
@Emdek Was checking my email.. 👍
