### ISSUE TITLE
Crash when right clicking directly after left clicking link on start page

### ISSUE THREAD

**Issue by midluk** [OtterBrowser/otter-browser#1059]
I'm seeing crashes when I right click directly after left clicking onto a site on the start page. I see the right click menu opening and seemingly at the time the new site finishes the inital loading and would normally start displaying otter crashes.

When I run this in gdb I get a backtrace directly when crashing, but the backtrace that is generated when gdb is instructed to do so seems much more helpful.
I have pasted the output into a gist because I didn't want to paste it into this report directly:
https://gist.github.com/midluk/0bb098ca49fbdeda9011

This is with latest git revision 33b7dfbc70127962d6f520d40d8b4f31ac3401fc on Fedora 23.

**Comment by midluk** [comment]
Left clicking on a site on the start page and immediatelly again left clicking, holding mouse button and dragging the site screenshot also causes a crash.

**Comment by Chocimier** [comment]
@midluk Is the bug still present?

**Comment by midluk** [comment]
Yes. Both methods to cause the crash still work.

**Comment by midluk** [comment]
The "right click directly after left click" crash seems to be fixed.

The "left double click+drag" crash still happens.

**Comment by midluk** [comment]
The double click+drag crash still happens with current git master.

Exact steps to reproduce:
1. Click a site on the start page (preferably a site that is slow to load)
2. directly after clicking, click again, hold the button and drag the site icon
3. stop moving the mouse before the page displays => the site properly loads
5. move the mouse =>crash

So it seems to be caused by the code that during normal drag on the start page causes the other site icons you hover over to be highlighted, which likely references already destructed objects.

It happens at slightly different places in the code (I have generated two different backtraces, but didn't want to spend more time to generate more without request.
https://gist.github.com/midluk/b0c108e4697fb4ae896980065976abf4
https://gist.github.com/midluk/64b44805bb82bf16e52207d7425cbacf

**Comment by cofi89** [comment]
Reproducable here as well, using the steps @midluk outlined above.  
Debian Jessie, QT 5.3, latest git.

**Comment by midluk** [comment]
Crash as outlined in https://github.com/OtterBrowser/otter-browser/issues/1059#issuecomment-222544282 still happens with current git and QT 5.6.1

**Comment by midluk** [comment]
Commit 9884fbbba4122cffa9430ec17e08335609a4a289 seems to have reintroduced the "double click + drag" crash.

**Comment by Emdek** [comment]
@midluk, indeed, I guess that it would be best to simply disallow drag once loading starts, that should be also the simplest and cleanest way.
Alternative could be use of `QDrag::cancel()` but it was introduced by Qt 5.6 and there are a lot of older versions out there (plus why to allow to drag it in the first place if it will have to be cancelled)...

**Comment by midluk** [comment]
That fix does not seem to work 100% reliable. I mostly fail to reproduce the problem now, but every third or fourth time I can still trigger it.

**Comment by midluk** [comment]
@Emdek, with the patch it's definitely harder to reproduce, but still not 100%. Every tenth time or so i still manage to make it crash. Previously if you kept your mouse perfectly still after starting to drag, it would crash only if you move your mouse again. Now shortly after the page is loaded the drag seems to be canceled and this causes the crash.

**Comment by Emdek** [comment]
@midluk, damn, that means that it requires non simple solution or we have some sort of Qt bug there too.
Well, in fact it is sort of Qt bug anyway, since it crashes while deleting widget with drag in progress, it should cleanup it itself, since that drag is completely handled by `QListView` (I'm now just trying to prevent drag start when it is likely to be followed by deletion).

Another idea is to save timestamp of last call opening URL and disallowing dragging for one or more seconds after it, no matter if loading started or not.

**Comment by Emdek** [comment]
@midluk, what about this one?
```diff
diff --git a/src/modules/windows/web/StartPageWidget.cpp b/src/modules/windows/web/StartPageWidget.cpp
index 0749398..dac11e6 100644
--- a/src/modules/windows/web/StartPageWidget.cpp
+++ b/src/modules/windows/web/StartPageWidget.cpp
@@ -400,6 +400,8 @@ void StartPageWidget::triggerAction(int identifier, const QVariantMap &parameter
 
 	if (url.isValid() && mainWindow)
 	{
+		m_urlOpenTime = QTime::currentTime();
+
 		mainWindow->getWindowsManager()->open(url, hints);
 	}
 }
@@ -462,6 +464,8 @@ void StartPageWidget::openTile()
 
 		if (mainWindow && bookmark && bookmark->rowCount() > 0)
 		{
+			m_urlOpenTime = QTime::currentTime();
+
 			mainWindow->getWindowsManager()->open(bookmark, hints);
 		}
 
@@ -478,6 +482,8 @@ void StartPageWidget::openTile()
 
 	if (mainWindow && url.isValid())
 	{
+		m_urlOpenTime = QTime::currentTime();
+
 		mainWindow->getWindowsManager()->open(url, hints);
 	}
 }
@@ -723,6 +729,8 @@ bool StartPageWidget::eventFilter(QObject *object, QEvent *event)
 
 						if (mainWindow)
 						{
+							m_urlOpenTime = QTime::currentTime();
+
 							mainWindow->getWindowsManager()->open(url, WindowsManager::calculateOpenHints((m_window->isPrivate() ? WindowsManager::PrivateOpen : WindowsManager::DefaultOpen), Qt::LeftButton, keyEvent->modifiers()));
 						}
 					}
@@ -732,6 +740,8 @@ bool StartPageWidget::eventFilter(QObject *object, QEvent *event)
 
 						if (contentsWidget)
 						{
+							m_urlOpenTime = QTime::currentTime();
+
 							contentsWidget->setUrl(url);
 						}
 					}
@@ -749,7 +759,7 @@ bool StartPageWidget::eventFilter(QObject *object, QEvent *event)
 	{
 		QMouseEvent *mouseEvent(static_cast<QMouseEvent*>(event));
 
-		if (mouseEvent && mouseEvent->buttons().testFlag(Qt::LeftButton) && m_window->getLoadingState() != WindowsManager::FinishedLoadingState)
+		if (mouseEvent && mouseEvent->buttons().testFlag(Qt::LeftButton) && ((m_urlOpenTime.isValid() && m_urlOpenTime.msecsTo(QTime::currentTime()) < 1000) || m_window->getLoadingState() != WindowsManager::FinishedLoadingState))
 		{
 			return true;
 		}
@@ -811,6 +821,8 @@ bool StartPageWidget::eventFilter(QObject *object, QEvent *event)
 
 						if (mainWindow)
 						{
+							m_urlOpenTime = QTime::currentTime();
+
 							mainWindow->getWindowsManager()->open(url, WindowsManager::calculateOpenHints((m_window->isPrivate() ? WindowsManager::PrivateOpen : WindowsManager::DefaultOpen), mouseEvent->button(), mouseEvent->modifiers()));
 						}
 					}
@@ -827,6 +839,8 @@ bool StartPageWidget::eventFilter(QObject *object, QEvent *event)
 								hints |= WindowsManager::PrivateOpen;
 							}
 
+							m_urlOpenTime = QTime::currentTime();
+
 							mainWindow->getWindowsManager()->open(url, hints);
 						}
 					}
diff --git a/src/modules/windows/web/StartPageWidget.h b/src/modules/windows/web/StartPageWidget.h
index f013b26..fb43dda 100644
--- a/src/modules/windows/web/StartPageWidget.h
+++ b/src/modules/windows/web/StartPageWidget.h
@@ -21,6 +21,7 @@
 #ifndef OTTER_STARTPAGEWIDGET_H
 #define OTTER_STARTPAGEWIDGET_H
 
+#include <QtCore/QTime>
 #include <QtWidgets/QListView>
 #include <QtWidgets/QScrollArea>
 
@@ -97,6 +98,7 @@ private:
 	QListView *m_listView;
 	SearchWidget *m_searchWidget;
 	QPixmap m_thumbnail;
+	QTime m_urlOpenTime;
 	QModelIndex m_currentIndex;
 	bool m_ignoreEnter;
 
```

**Comment by Emdek** [comment]
@midluk, above commit is most likely unrelated to your issue and might break above patch, so in case of issues you can try it on previous revision.

**Comment by midluk** [comment]
@Emdek, neither patch (the second patch you posted and 0d9abc2) seems to change much.

**Comment by Emdek** [comment]
@midluk, then I'm afraid that we cannot do much more. :-/
I think that I'll include it anyway, mixed with optional `QDrag::cancel()`, since it at least makes it harder to fail.

**Comment by Chocimier** [comment]
@midluk, what about following patch applied onto 9884fbb?
If it does not help, are you able to crash d02b956?

```diff --git a/src/modules/windows/web/WebContentsWidget.cpp b/src/modules/windows/web/WebContentsWidget.cpp
index e7058bab..e5d08f99 100644
--- a/src/modules/windows/web/WebContentsWidget.cpp
+++ b/src/modules/windows/web/WebContentsWidget.cpp
@@ -93,7 +93,7 @@ void WebContentsWidget::timerEvent(QTimerEvent *event)
  	}
  	else if (event->timerId() == m_deleteStartPageTimer)
  	{
-		if (m_startPageWidget && m_startPageWidget->findChildren<QDrag*>().isEmpty())
+		if (!m_startPageWidget || !m_startPageWidget->findChildren<QDrag*>().isEmpty())
  		{
  			return;
  		}
```

**Comment by midluk** [comment]
@Chocimier, with both solutions I am able to easily start the drag, but on mouse release or moving the icon it does NOT crash.
I noticed however that when I release the icon, the page seems to reload (not sure if this was also the case directly after the initial fix from last year).
And with d02b956a9d03226c0a7f5fc0ca95e886c456f6df (the last working commit I found with bisecting yesterday) any start page created after the primary one is just empty.

**Comment by midluk** [comment]
Are there any plans to adapt and commit the fix from Chocimier to current master? This seems to work (not sure if this is completely correct, though):
```
diff --git a/src/modules/windows/web/WebContentsWidget.cpp b/src/modules/windows/web/WebContentsWidget.cpp
index 98a455e..c19ab44 100644
--- a/src/modules/windows/web/WebContentsWidget.cpp
+++ b/src/modules/windows/web/WebContentsWidget.cpp
@@ -43,6 +43,7 @@
 #include "../../../ui/Window.h"
 
 #include <QtGui/QClipboard>
+#include <QtGui/QDrag>
 #include <QtGui/QMouseEvent>
 #include <QtWidgets/QApplication>
 #include <QtWidgets/QInputDialog>
@@ -93,6 +94,11 @@ void WebContentsWidget::timerEvent(QTimerEvent *event)
        }
        else if (event->timerId() == m_deleteStartPageTimer)
        {
+               if (m_startPageWidget && !m_startPageWidget->findChildren<QDrag*>().isEmpty())
+               {
+                       return;
+               }
+
                killTimer(m_deleteStartPageTimer);
 
                m_deleteStartPageTimer = 0;
```

**Comment by Emdek** [comment]
@midluk, yes, in a bit cleaner form.
