### ISSUE TITLE
Scroll the page with the middle mouse button click

### ISSUE THREAD

**Issue by Katarn** [OtterBrowser/otter-browser#106]
Subj. :)

**Comment by Katarn** [comment]
I found two problems.

1. If you stop the scrolling by pressing the right mouse button, a context menu appears.
2. Scrolling begins earlier than I expected. In Opera you need to move the mouse about 2 times more than now.

**Comment by Frenzie** [comment]
@Katarn

> Scrolling begins earlier than I expected.

It's slightly different, but it doesn't bother me. However, autoscroll doesn't behave right when zoomed in or out. Not only does it start scrolling immediately when zoomed in, but it also starts to become unbearably slow. The scroll speed should probably be multiplied by the zoom factor or some such. Note, however, that in Opera autoscrolling when zoomed out becomes unbearably slow.

While I think IE speeds up a little too fast, as far as consistent autoscroll behavior goes it's overall a better example.

**Comment by Emdek** [comment]
@Katarn, first one was already fixed, apparently I've referenced wrong ticket from that commit...

@Frenzie, odd, I haven't seen any differences in speed depending on zoom.
