### ISSUE TITLE
Search engine dialog keyword validation

### ISSUE THREAD

**Issue by wincak** [OtterBrowser/otter-browser#1061]
Search engine configuration seems to have some issues concerning keywords:
1) User does not get noticed if the keyword he wants to use is already in use.
2) It is possible to add a search engine without a keyword - should it be so?

I have attached a draft of a solution for the first issue.
(Don't take that patch too seriously, I'm quite new to all this)

[CheckForUsedSearchKeywords.patch.zip](https://github.com/OtterBrowser/otter-browser/files/139677/CheckForUsedSearchKeywords.patch.zip)

**Comment by VSHY** [comment]
@wincak 
> 2)
A keyword is necessary for programmatic access only. Otherwise, why?

@Emdek 
Add please the handling of double-click on Search Engine, it should correspond the Edit button.

**Comment by wincak** [comment]
@VSHY @Frenzie 
Aha, it is not necessary to have a keyword defined, I see the search box now... *facepalm*
However, there are still some related things bugging me:
3) When adding a new search engine with a keyword that is already in use (as returned by SearchEnginesManager::getSearchKeywords() - this list contains even inactive search engines from the Add->ReAdd menu), the new search engine gets added without a keyword. But you can't see which existing inactive search engine is in conflict until you ReAdd them one by one and check.
4) While ReAdding inactive search engines, their keywords are not visible until the dialog is closed and reopened.
Possible solution: how about making one list of all defined search engines and differentiate between them by active/inactive checkbox? I'll try to make another patch to explain better.

**Comment by Emdek** [comment]
@wincak, anything left to be done in this issue?

**Comment by wincak** [comment]
@Emdek no, everything seems fine to me now.
