### ISSUE TITLE
Some fonts are lacking anti-aliasing

### ISSUE THREAD

**Issue by vext01** [OtterBrowser/otter-browser#1064]
Already mentioned on IRC, but some fonts look wrong in otter:

![otter](https://cloud.githubusercontent.com/assets/604955/13247495/ce81a532-da11-11e5-9b70-d4e18c1e0f74.png)

This is otter-0.9.09 on OpenBSD.

The CSS font for the `OtterBroswer/otter-browser` elements in the above screen shot is:
```
13px / 1.4 Helvetica, arial, nimbussansl, liberationsans, freesans, clean, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"
```

Setting it instead to `sans-serif`, makes the fonts look nicer, although otter says this is invalid (should be ok, no?):

![otter2](https://cloud.githubusercontent.com/assets/604955/13247635/85435cc0-da12-11e5-8199-6a50186e4bdd.png)

Perhaps related:
https://github.com/The-Compiler/qutebrowser/issues/1322

**Comment by vext01** [comment]
FWIW, several fonts look bad in otter, notably helvetica:

![otter3](https://cloud.githubusercontent.com/assets/604955/13250990/65bbe634-da25-11e5-9b91-11041062b753.png)

**Comment by Emdek** [comment]
@vext01, can you reproduce that using *test-qtwebkit*?
https://github.com/OtterBrowser/test-qtwebkit

**Comment by vext01** [comment]
Sorry for the delay.

In the test program the result is the same:

![test](https://cloud.githubusercontent.com/assets/604955/14067906/f59f3b2c-f468-11e5-82fe-4148671e54d4.png)

Maybe this is the same as:
https://bugs.launchpad.net/midori/+bug/1304800
