### ISSUE TITLE
Delayed detection of spelling errors

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#1067]
Sonnet detects an erroneous word only after the first (or sometimes second) letter of another word is typed.

Expected behavior: a word becomes a word as soon as a space is typed. So any error should be detected at that time.

**Comment by Emdek** [comment]
It's limitation of APIs provided by QtWebKit, not related to Sonnet at all.
Perhaps it will improved by recent third party efforts to revitalize it after deprecation, but for now we cannot do anything about that.
