### ISSUE TITLE
Issue with Content Blocking

### ISSUE THREAD

**Issue by Zero3K** [OtterBrowser/otter-browser#1069]
It messes up certain sites/images (such as breaking Twitter.com and random avatars on certain forums) when using the EasyList filter list.

**Comment by SJ-Diamond** [comment]
Can confirm, most Twitter pictures are not getting shown and it crashes the browser sometimes during startup

**Comment by Zero3K** [comment]
I have another issue. Some of the images in the left box on http://www.pixiv.net/mypage.php are showing up as question marks instead of being removed.
