### ISSUE TITLE
Qt Webengine logon issues

### ISSUE THREAD

**Issue by resbro** [OtterBrowser/otter-browser#1071]
When trying to log into several websites (Woot, my bank, etc.) the number nine on my keypad adjust the zoom level down. I think the Qt webkit version did this a long time ago also, but has long been fixed. 114 webkit works as expected on this issue.

Otter Weekly 114 x 32 Webengine
Win 10 x 64

**Comment by SJ-Diamond** [comment]
Can recreate that. There seem still to be some serious issues going on.

**Comment by Emdek** [comment]
@resbro, do you have single key shortcuts enabled?
If yes, then try disabling them. You can also simply nuke this specific shortcut.

**Comment by resbro** [comment]
Yup, unchecking single key shortcuts did the trick. Thanks!

**Comment by midluk** [comment]
Why is this closed? This is definitely an unfixed issue (with qt 5.7.0 and current otter git) that does not occur with qtwebkit. Unchecking single key shortcuts is a workaround but no fix.
