### ISSUE TITLE
Crash when moving a tab

### ISSUE THREAD

**Issue by Zero3K** [OtterBrowser/otter-browser#1075]
I have just encountered a crash when moving a tab. A Crash Log that has been generated with WinCrashReport is attached.
[Otter Crash Log.zip](https://github.com/OtterBrowser/otter-browser/files/190240/Otter.Crash.Log.zip)

**Comment by Zero3K** [comment]
I have figured out how to replicate it. It crashed when I opened an instance of Otter Browser that has 10+ tabs open and tried moving one of them. Another Crash Log is attached.
[Otter Crash Log #2.zip](https://github.com/OtterBrowser/otter-browser/files/190247/Otter.Crash.Log.2.zip)

**Comment by Zero3K** [comment]
Here's another Crash Log with a different function causing the crash.
[Otter Crash Log #3.zip](https://github.com/OtterBrowser/otter-browser/files/190373/Otter.Crash.Log.3.zip)

**Comment by midluk** [comment]
If with "moving a tab" you mean drag and drop in the tab bar, I can not reproduce on Fedora 23.
I opened 13 babs in otter, draged them around in the tab bar and nothing unexpected happened.

**Comment by Zero3K** [comment]
Try with 20+ tabs.

**Comment by Emdek** [comment]
@Zero3K, it looks like something that could be style dependent.
Try to reproduce it using different one, you can set them in Preferences -> Advanced -> Appearance (note that going back to system theme might require restarting application).

**Comment by Zero3K** [comment]
Its not style dependent. I switched to the Fusion widget style and the crash still occurred.

**Comment by Emdek** [comment]
@Zero3K, please attach such crash log for different style, it could be helpful.

**Comment by Zero3K** [comment]
Ok. It is attached.
[Otter Crash Log #4.zip](https://github.com/OtterBrowser/otter-browser/files/191006/Otter.Crash.Log.4.zip)

**Comment by Emdek** [comment]
@Zero3K, thanks.
It mentions ``QCommonStyle``, so it could be platform specific but affecting all styles under Windows, or it could be just misleading and real issue is to be found elsewhere.

**Comment by Emdek** [comment]
@Zero3K, is this still reproducible?

**Comment by Zero3K** [comment]
I cannot reproduce it at the moment. So, it seems to be fixed.

**Comment by Emdek** [comment]
Great.
