### ISSUE TITLE
Phantom Network Connection Issue

### ISSUE THREAD

**Issue by Zero3K** [OtterBrowser/otter-browser#1076]
When auto-reloading multiple tabs for a while or visiting certain sites, they will get stuck in the loading status. The only way to get them unstuck it is by doing a manual refresh. One site that has this issue is https://www.twitch.tv/directory/following.

**Comment by mathman12** [comment]
Can reproduce in Otter weekly 116. As mentioned in Reply #302 on: 2016-02-23, 21:29:10 (1456259350) in the official forum for Otter, this behavior does not happen in Otter week 98, Otter week 96 or other versions before wk96.  Never stop loading was an issue with Opera as well.  Maybe a fix soon?  Note: OS Windows 7, 64bit with 32 bit Otter.  Sincerely, Mathman12

**Comment by Zero3K** [comment]
Oh, it turns out that my issue was caused by Ad Muncher. I fixed it by installing Proxomitron, configuring Otter to use it as the proxy server and having Ad Muncher filter it instead of Otter.
