### ISSUE TITLE
Cleanup handling of language lists

### ISSUE THREAD

**Issue by GreenLunar** [OtterBrowser/otter-browser#1080]
Sort preferred webpage language by language code, not by language title.

**Comment by Emdek** [comment]
@GreenLunar, why and where?

**Comment by GreenLunar** [comment]
Because, according to language code, I expect to see languages such as Arabic (ar) at the top of the list, not at the bottom.

See Tools > Preferences > Edit...

**Comment by GreenLunar** [comment]
By the way, that is the best language selection list I have seen thus far. How did you manage to generate that list with non English text?

**Comment by Frenzie** [comment]
> Because, according to language code, I expect to see languages such as Arabic (ar) at the top of the list, not at the bottom. For instance, Help > Switch Application Language... is sorted by language code.

In that case, shouldn't the language code be displayed first? Which I'm perfectly fine with, btw. I just think having the thing you're sorting by hiding at the end isn't very intuitive.

Incidentally, that selection dropdown is a bit short. Is there perhaps an easy way to make it longer, provided sufficient vertical space is available? There's probably enough space on my screen to forgo on scrolling altogether, yet it's all squeezed together.

**Comment by GreenLunar** [comment]
> In that case, shouldn't the language code be displayed first?

Yes.

**Comment by Chocimier** [comment]
> How did you manage to generate that list with non English text?
@GreenLunar QLocale::nativeLanguageName()

> shouldn't the language code be displayed first?
Then we will lost possibility of typing language name.

**Comment by GreenLunar** [comment]
> > shouldn't the language code be displayed first?
> Then we will lost possibility of typing language name.

Should we, then, list languages similarly to `Qt Linguist > Edit > Translation File Settings...`,in this case?
