### ISSUE TITLE
Import PrefBar or support .btn addons

### ISSUE THREAD

**Issue by GreenLunar** [OtterBrowser/otter-browser#1081]
I am not sure if porting is the proper way, but if porting would not allow to OtterBrowser and QupZilla users to make use of `.btn` files for [PrefBar](http://prefbar.tuxfamily.org/) without further modifications, then a similar implementation would be preferable.

PrefBar started as a simple toolbar to get easy access to common preferences like Javascript, Flash, the proxy used for web access, ... Over the time, PrefBar got further developed to be a container for nearly everything, that can be placed on a button, checkbox or menulist.

All items may be placed and grouped freely on PrefBar's bar. The bar itself may be moved using the browser built-in "toolbar customize" feature to anywhere you like (even in foreign toolbars, next to the menubar, ...).

See also https://github.com/QupZilla/qupzilla-plugins/issues/56

**Comment by lollox** [comment]
Maybe you're not an old Opera user, am I right? ... for what I can see, the quick preferences menu is what you're looking for 

http://i.imgur.com/obG37Br.jpg

**Comment by GreenLunar** [comment]
> Maybe you're not an old Opera user, am I right? ... for what I can see, the quick preferences menu is what you're looking for

> http://i.imgur.com/obG37Br.jpg

Last time I was using Opera was in 2009, and I recall there was a quick preferences bar at the bottom.

> and obviously in opera (and Otter ?) you could add/remove/edit any of that commands, or show them in a toolbar, in a button, or whatever you like ;)

I noticed it. I guess I have ignored it when I have opened this issue. Maybe I should request new buttons and menulists (combo box).

Anyhow, PrefBar has a menulist button to switch user-agent, and Otter has a quick preference for user-agent  in main menu.

**Comment by Emdek** [comment]
@GreenLunar, I'm not sure that we really need to support alternative button system targeting different architecture, so many options wouldn't work at all or would require mapping them.
We have our own system for long time and it makes more sense to simply extend it.
See #42.
