### ISSUE TITLE
[Accessibility] Show Full Screen menu item in menu button in Full Screen Mode

### ISSUE THREAD

**Issue by GreenLunar** [OtterBrowser/otter-browser#1084]
Show Full Screen menu item in menu button (appears once Show Menubar is unchecked) once user enters Full Screen Mode, for quick accessibility.

**Comment by Emdek** [comment]
@GreenLunar, we provide that action in default configuration of context menu which is more accessible than some menu button on auto hidden toolbar.
Also we don't support conditional menu items right now and we can't hardcode it as it would break custom menus.
