### ISSUE TITLE
Issue with Previous Session dialog box

### ISSUE THREAD

**Issue by Zero3K** [OtterBrowser/otter-browser#1085]
It sometimes doesn't show up when running it after it has crashed.

**Comment by Zero3K** [comment]
Will any work be done on this soon or not?

**Comment by Zero3K** [comment]
I guess it depends on what caused the crash.

**Comment by Emdek** [comment]
If crash happens before session is marked as dirty then you won't get that dialog.
In such cases you can use *Minimal restart* option in Crash Reporter.
