### ISSUE TITLE
Make the status bar optional

### ISSUE THREAD

**Issue by pierreporte** [OtterBrowser/otter-browser#1087]
The status bar takes a lot of place just to display the URL of the hovered link and the zoom selector. In fact, the URL is displayed only less than a second and is rarely read at all, and the zoom selector may not be the most used feature in a browser. Plus, note everyone will add things through editing toolBars.json (or a future more user-friendly interface). For this reason, I propose that the user should be able to display or not the status bar.

Without the status bar, the URL of the hovered link could be displayed in a tooltip. By default, the tooltip is on the left of the window but if the hovered link is in the zone when the tooltip would mask it, then it is displayed on the right on the window. This is the behaviour of Firefox.

The zoom sliding rule could be duplicated in the main menu, in a way similar to the new Opera or Firefox (see screenshots below). With the status bar, the zoom selector would still be present in the main menu and the bottom bar at the same time.

The extra things the user might have added to the status bar with toolBars.json would just not be displayed elsewhere since if he or she wants do disable the status bar, it’s because he or she don’t want anything there in the first place.

![Firefox main menu](https://mdn.mozillademos.org/files/6809/action-button-menu.png)

![](http://www.memoclic.com/medias/var_forum/2013-51/MenuOpera.jpg)

**Comment by Emdek** [comment]
@pierreporte, you can disable it already.
Also you can control tooltips in independent way (not like Opera that glued that to visibility of status bar, and not even visibility of status message widget :-|).
