### ISSUE TITLE
Opening a new tab no longer places focus in the address bar

### ISSUE THREAD

**Issue by elebow** [OtterBrowser/otter-browser#1093]
Using latest master and Qt 5.6.0 with QtWebEngine.

**Comment by midluk** [comment]
Can confirm this with QT 5.7.0 and qtwebengine on Linux.

**Comment by Emdek** [comment]
It seems `QWebEngineView` has issues with handling `focusInEvent()` properly, seems to receive it only after switching tab.
Perhaps I'll need to think about some alternative way to trigger it., perhaps using `showEvent()` instead.

**Comment by Emdek** [comment]
After some debugging it seems that it could be worse, probably `focusWidget()` of `QWebEngineView` is stealing focus from address field (code path which sets focus on it is successfully executed but we end up without focus after `QWebEngineView` is created).

**Comment by beastie1** [comment]
This is the case for legacy WebKit too, not just WebEngine and the above commits don't fix it.

Of course, if **StartPage/EnableStartPage** is set to **Yes**/**True** it does place focus in the address bar. It only fails if the start page is disabled.

**Comment by Emdek** [comment]
@beastie1, it's a bit different issue, the one from this ticket was QtWebEngine specific, as it steals focus.
I'm researching this case right now.
