### ISSUE TITLE
Error pages left over when using the content blocking function

### ISSUE THREAD

**Issue by Zero3K** [OtterBrowser/otter-browser#1097]
It would be nice if Otter Browser could block those.

**Comment by Zero3K** [comment]
Will any work be done on this soon or not?

**Comment by bajasoft** [comment]
Can you provide a few links, where the problem occurs? I will investigate this issue when I will have some time.

**Comment by ZarkBit** [comment]
He's referring to the Errors that are presented within the ads, when they are blocked

![0cm 1](https://cloud.githubusercontent.com/assets/4160341/14295816/0d60db50-fb6f-11e5-8394-660773e1b880.jpg)

**Comment by Zero3K** [comment]
Here are some examples of sites where this issue is occurring:

https://thepiratebay.se/browse
http://www.pixiv.net
http://www.hulkusc.com/cnn-news-live-streaming/
http://fileforum.betanews.com/

**Comment by Zero3K** [comment]
There's still one error page being shown in Reddit.com. All the others are now gone.
