### ISSUE TITLE
tab bar occasionally loses focus when you hover mouse over it

### ISSUE THREAD

**Issue by msjasinski** [OtterBrowser/otter-browser#1099]
Hard to explain, you have to experiment to see for yourself.
The tab bar goes to the right, outside the screen.

Tested on Windows XP and 7.

**Comment by Zero3K** [comment]
I don't know if its the same thing but when I have Tab Preview enabled and am hovering over a few tabs then move off of the tab bar, the width of the tabs gets all weird for a second or so.

**Comment by msjasinski** [comment]
Yes, this is exactly what I was trying to say.

**Comment by Zero3K** [comment]
Ok. I also think that it should be fixed.

**Comment by ZarkBit** [comment]
![bdldver 1](https://cloud.githubusercontent.com/assets/4160341/16093928/d02a29e0-3335-11e6-9133-80c8f0b5c2c2.png)
 this?

**Comment by Zero3K** [comment]
Yes, I believe you're also having the issue being mentioned.

**Comment by ZarkBit** [comment]
https://dl.dropboxusercontent.com/s/q0cu4xwlvd1cfv0/2016-06-15_20-52-28.mp4?dl=0

I wonder if it's related to having multiple monitors? Do you all have multiple monitors?

**Comment by Zero3K** [comment]
Nope, I just have one monitor.

**Comment by Emdek** [comment]
I'm pretty sure that it was fixed already as part of #190, if not, then it will be. ;-)
