### ISSUE TITLE
[Art] 3D model of Otter and a kart for SuperTuxKart

### ISSUE THREAD

**Issue by GreenLunar** [OtterBrowser/otter-browser#1100]
An otter figure for [SuperTuxKart](http://supertuxkart.sourceforge.net/) in 3D would assist in marketing Otter Browser.

**Comment by aurhat** [comment]
In what way?

**Comment by GreenLunar** [comment]
Designing a kart and an Otter figure for the STK video game.

**Comment by aurhat** [comment]
But when a kart with otter will be created, but how it will help just in Otter Browser marketing, an internet browser?

**Comment by pierreporte** [comment]
The only way I see it work is that players would ask themselves where does this otter come from. They would eventually find out and, if they are interested, there is a chance that they adopt Otter Browser and even contribute.

It is hard to believe that a lot of new users will be gained this way, considering that making someone to switch to a new browser is very unlikely, let alone an opera-like browser, and the low amount of SuperTuxKart players. I mean, a lot of people in the FOSS “community” know that the game exists, but are there any *real* players?

That being said, if someone were to make an otter character there is absolutely no reason to refuse even though its usefulness is questioned. For a better marketing, it would be better to write about Otter Browser everywhere on the Internet and asking to news sites to review it. However, the essential step is to actually make the browser stable with enough features to be perfectly usable with the same quality as Firefox, Chrome, and their competitors.

**Comment by GreenLunar** [comment]
I don't care at what rate this would help in marketing Otter Browser.
Just hope for an Otter Browser fan to do this task.
