### ISSUE TITLE
To play video doesn't work on windows

### ISSUE THREAD

**Issue by oliver1111333** [OtterBrowser/otter-browser#1110]
I try to use otter to play an html5 video it plays just the sound but no video on windows.
from issue #830 (https://github.com/OtterBrowser/otter-browser/issues/830) I know the reason.
but I didn't solve it.
 **## Can we provide ways to support gstream on windows by compiling qt?**
Please help for users on windows.
For windows user, it is so important to play video. It is a basic feature.
I try to compile qtmultimedia to support gstream, but failed. Or, 
If our installer or portable executable file support video playing on windows, otter will be more powerful.

**Comment by myier** [comment]
For me, the win64 weekly builds are able to play video. It doesn't work well, for example if you switch tabs then the image becomes partly black, but otherwise, the codec is there and it works.

**Comment by oliver1111333** [comment]
I try weekly #116 version on windows 7 64-bits, it cannot play video.

**Comment by Emdek** [comment]
@oliver1111333, we can't do anything about that, QtWebKit currently can use only system wide codecs under Windows, you need 32 bit codecs pack for 32 build and 64 bit one for 64 bit build.

**Comment by Zero3K** [comment]
Annulen has found something that might be workable. You can see details of it by going to:

https://github.com/annulen/webkit/issues/36
