### ISSUE TITLE
scripting

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#1116]
Hi,
I'd like to ask about the current status of user scripts - are the announcements in the recent weeklies
basic support for UserJS, initial work on Addons Manager suggesting that this feature is already usable? or are there only some preliminar stubs in
about:addons - User Scripts
which will be implemented in future? (The context menu "Add addon..." doesn't seem to be working.
Or could it be, that user scripts can already be copied manually to some designated folder?
Is there some documentation about the API and the supported features for user scripts?

Thanks and regards,
    vbr

Edit: It seems, there is some info in the issue:
Improved Greasemonkey compatibility #1091
but probably no definitive documentation yet(?)

**Comment by Emdek** [comment]
@vbr, that ticket is also meant to keep track of development of Addons Manager, so this one is basically duplicate.
Currently the main blocker is UI design for enabling scripts.
