### ISSUE TITLE
desktop entry file otter-browser.desktop lacks key Icon

### ISSUE THREAD

**Issue by pmattern** [OtterBrowser/otter-browser#1118]
In 52a07f9 key "Icon" was removed from `./otter-browser.desktop` so the icon of Otter Browser doesn't get displayed in panel menus, desktops and the likes right now.

**Comment by Emdek** [comment]
@pmattern, yeah... It was removed from desktop file since Transifex exposed that key as translatable. :-/
And I've forgot to readd it manually after merging translations using script.
