### ISSUE TITLE
Issue with about:cache

### ISSUE THREAD

**Issue by Zero3K** [OtterBrowser/otter-browser#1119]
Trying to go to it in the latest weekly causes it to crash. A crash log is attached.
[crashlog.zip](https://github.com/OtterBrowser/otter-browser/files/216156/crashlog.zip)

**Comment by uahim** [comment]
happens here too, but only with my 'old' profile; about:cache in a fresh/empty profile works fine.
deleting the cache directory itself does not help.

OS is WinXP if that matters

**Comment by Emdek** [comment]
Perhaps above change will solve this issue, let me know when new weekly will be ready.

**Comment by Emdek** [comment]
@Zero3K, @uahim, any change when using latest weekly?

**Comment by uahim** [comment]
@Emdek no change here

**Comment by Zero3K** [comment]
@Emdek Still crashes for me

**Comment by Emdek** [comment]
@uahim, @Zero3K, cannot reproduce, using both 32 bit and 64 bit builds under Windows 10 VM.
Any new backtraces?

**Comment by uahim** [comment]
thanks for trying. as I said, it works fine with empty/new user profiles, just not the old one I use. I even tried to track it down starting with a new one and confirguring it to my liking, but I don't remember after which setting change it began.
I will try to repeat this once I find the time and then report back here.

**Comment by Emdek** [comment]
@uahim, then perhaps you could set contents of your cache folder to me for testing?

**Comment by uahim** [comment]
@Emdek  not quite sure if this is what you meant, but for now, here are my cache settings - which I never touched anyway:
DiskCacheLimit Integer 51200
PagesInMemoryLimit Integer 5

**Comment by Emdek** [comment]
@uahim, nope, zipped folder containing cached files. ;-)

**Comment by uahim** [comment]
ah! here it is (old profile)
[otter-cache.zip](https://github.com/OtterBrowser/otter-browser/files/321904/otter-cache.zip)

**Comment by Emdek** [comment]
@uahim, thanks but so far I can't reproduce it, at least under Linux. :-/

**Comment by ZarkBit** [comment]
@uahim can you provide the whole Otter folder? I could see if it crashed on my side and maybe get to the source of the problem.

**Comment by uahim** [comment]
so after installing today's build. I re-built my Otter settings, so to say - by simply copying the appropriate files to a "fresh" profile and so far, the aforementioned bug does not appear anymore. weird.

@Emdek thanks for trying

@ZarkBit I'd rather not do that, but thanks

**Comment by Emdek** [comment]
I'll try to reproduce that under Windows soonish.
