### ISSUE TITLE
Translation like Chrome

### ISSUE THREAD

**Issue by srgloureiro** [OtterBrowser/otter-browser#112]
I think I don't need to explain. Everythime a user goes to a site written in a language that is not on the language list, the browser should present a toolbar asking whether the user wants translation or not.

People who had used Chrome know about this. This is one of the few issues where it made sense to Opera get features copied from Chrome.

**Comment by Zero3K** [comment]
I also hope to see an auto-translate extension made available once extensions are supported.

**Comment by Emdek** [comment]
It should be doable using User Scripts, which are already available.
