### ISSUE TITLE
crash: QPainter error

### ISSUE THREAD

**Issue by mmirco** [OtterBrowser/otter-browser#1120]
Hi, Otter just crashed with the following error messages left over:

```
Warning: QPainter::begin: Paint device returned engine == 0, type: 2 ((null):0, (null))
Warning: QPainter::setRenderHint: Painter must be active to set rendering hints ((null):0, (null))
Warning: QPainter::setBrush: Painter not active ((null):0, (null))
Warning: QPainter::pen: Painter not active ((null):0, (null))
Warning: QPainter::setPen: Painter not active ((null):0, (null))
Warning: QPainter::end: Painter not active, aborted ((null):0, (null))
Warning: QPixmap::scaled: Pixmap is a null pixmap ((null):0, (null))
Debug: QNetworkReplyImpl::_q_startOperation was called more than once ((null):0, (null))
Bus error (core dumped)
````

Qt version 5.5.1
Otter 0.9.09 beta 9
WebKit Backend 538.1.
SSL library version: OpenSSL 1.0.1r 28 Jan 2016
OS: DragonFly BSD 4.4.2

**Comment by Emdek** [comment]
@mmirco, can you try to produce some backtrace?
This log doesn't tell much and might be completely unrelated to crash itself.

**Comment by mmirco** [comment]
@Emdek: I'm a real noob, don't know how to produce backtrace. But I will learn about that and next time it happens, hopefully I can satisfy you with that :-)

**Comment by The-Compiler** [comment]
Any chance that was on npmjs.com?

**Comment by mmirco** [comment]
@The-Compiler, sorry I can't remember. But that site doesn't lock familiar to me at all.

**Comment by Emdek** [comment]
@mmirco, you can try this guide, it should work fine also for BSD:
https://wiki.archlinux.org/index.php/Step-by-step_debugging_guide#Segmentation_faults
