### ISSUE TITLE
Issue with Popup Blocker

### ISSUE THREAD

**Issue by Zero3K** [OtterBrowser/otter-browser#1123]
The popups on http://www.tnaflix.com (NSFW) aren't being blocked by it and are also causing it to crash.

**Comment by bajasoft** [comment]
@Zero3K: Do you still have this problem? If so, provide a more accurate testcase please. I'm not getting any popups or crash on your link with TP4 WebKit.

**Comment by Zero3K** [comment]
https://www.thepcmanwebsite.com/pop_up_test.shtml opens a popup when clicking the "Click Test Link" link.

**Comment by bajasoft** [comment]
This is correct behavior across all browsers. Popup opened by click on link (or image) shouldn't be blocked. However we may consider some modification, which could allow user to change this.

**Comment by Zero3K** [comment]
Pop-Unders aren't being blocked by it.

**Comment by Zero3K** [comment]
http://www.direct-torrents.com/ has some popups that aren't being blocked by it.

**Comment by bajasoft** [comment]
@Zero3K: Provided site doesn't work any more. You can post updated testcase here if the problem still occurs with some of the latest versions. I'm closing this issue until that.
