### ISSUE TITLE
The source viewer is empty

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#1124]
The source viewer has stopped working in most recent builds. It shows nothing when you want to view a page's source code.

**Comment by Frenzie** [comment]
I thought it was something in my profile. Yeah, it still worked a couple of
weeks ago.

**Comment by beastie1** [comment]
What OS?

It works fine here under FreeBSD with the latest sources. And it worked fine with a week-old build too.

**Comment by ersi-dnd** [comment]
Linux.

**Comment by uahim** [comment]
+Windows (XP)

**Comment by Frenzie** [comment]
Linux here too.

**Comment by uahim** [comment]
whoops, I just re-read the OP - different issue here, in my default profile, the menu item itself is _greyed out_.

**Comment by Frenzie** [comment]
@mihau that's my issue too

**Comment by PStokman** [comment]
Linux here and when I right click I can view the source code of this page. All the code is there. Using Weekly 121 atm.

**Comment by Frenzie** [comment]
@ersi Have you tried a clean profile? (Seeing how that works for me and @uahim.)

**Comment by ersi-dnd** [comment]
I thought I had tried it so before reporting. 

Meanwhile I have updated to the latest build and the source viewer works both with a clean profile and my old one. Issue over and out :)

**Comment by uahim** [comment]
still doesn't work here with my standard profile --- I tracked it down to toolBars.json, if I delete/rename it, "source viewer" is not greyed out in the page context menu; otherwise, it is. I have attached it below, maybe someone has an idea?

[toolBars.json.txt](https://github.com/OtterBrowser/otter-browser/files/252505/toolBars.json.txt)
