### ISSUE TITLE
[RTL] Back/Forward buttons are reversed

### ISSUE THREAD

**Issue by GreenLunar** [OtterBrowser/otter-browser#1125]
Back/Forward buttons are setup in their respective positions, but the icons are not, so they appear like this [-->] [<--], instead of this [<--] [-->].  Same with back/forward menus.

Run `otter-browser -reverse`.

**Comment by Emdek** [comment]
@GreenLunar, it's normal, Qt simply reverses layout, I don't see any completely sane way to deal with it other than creating special setup. :-/

**Comment by GreenLunar** [comment]
You are correct.

Please see a similar case:
https://github.com/MaartenBaert/ssr/issues/280#issuecomment-68188928
https://github.com/MaartenBaert/ssr/commit/0d879ae5a0337003bf7ad2c963c7f107e1e788a1#diff-6e510e0fb7cd35b249890fe99a544c1eL30

```
	if(QApplication::layoutDirection() == Qt::RightToLeft) {
		g_icon_go_previous = QIcon::fromTheme("go-next");
		g_icon_go_next = QIcon::fromTheme("go-previous");
	} else {
		g_icon_go_previous = QIcon::fromTheme("go-previous");
		g_icon_go_next = QIcon::fromTheme("go-next");
	}
```
