### ISSUE TITLE
page error otter-browser.org - 400 Bad Request Cookie Too Large

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#1126]
Hi,
I'd like to ask about a strange page error, I keep getting for http://otter-browser.org/
400 Bad Request
Request Header Or Cookie Too Large
nginx

using Win7, Otter win32 webkit, for several of the latest weeklies (currently 119).

I suspect, this might be some cache or other suplemental data issue, as this doesn't happen in private tabs - in this case the page is displayed correctly.
I have tried deleting the cache folder, but the mentioned problem persists.
Are there some other places for cached data or other settings, which might influence this?
thanks and regards,
    vbr

**Comment by Zero3K** [comment]
I can't replicate this issue even with the same set-up.

**Comment by vbr** [comment]
Hi,
thanks for the investigation, actually; I can't replicate this problem on any other computer either.
I guess, there might be some invalid cached data or something similar. - opening the mentioned page in a private tab works ok, the same is true for opening in a separate otter install of the same version - living in another folder (both with the --portable flag).
However, I couldn't find out sofar, how this problem can be solved for my primary instance of Otter or where else to look for possibly problematic cached data or other potential problem sources.
regards,
   vbr

**Comment by Zero3K** [comment]
Did you try deleting the cache and/or cookies of that profile?

**Comment by vbr** [comment]
Thanks for the hint!
It was indeed a cookie issue, apparently - there was, for some reason - an 8 kB cookie for the domain otter-browser.org; after deleting it, the page can be accessed normally.
Thanks again,
   vbr

**Comment by xploSEoF** [comment]
Oddly, I've had the same issue for the last year. It occurred with an update, but I thought it would have been resolved with another update. I guess not.

Only problem I seem to face: I can't delete the cookie. The only way I can find the cookie is to look at "website preferences", but the buttons for managing the cookies are greyed out and not click-able.

**Comment by vbr** [comment]
Hi, I believe, you could display all cookies in a special page - just entering 
about:cookies
in the address bar. You should be able to locate the offending domain and delete the cookies as needed from there.
hth,
   vbr

**Comment by CyberC123** [comment]
Hey,
I have the same problem after a while on github.com when I logged in.
Normal access after delteting the cookies, but after a while the same problem again.

Version:
	Main Number         0.9.91
	Weekly Number       183
	Context              weekly 183
	Web Backend         WebKit-Backend 602.1

Environment:
	System Name                   Windows 7 SP 1 (6.1)
	Build ABI                     x86_64-little_endian-llp64
	Build CPU Architecture        x86_64
	Current CPU Architecture      x86_64
	Build Qt Version              5.9.1
	Current Qt Version            5.9.1
	Locale                        de_DE
