### ISSUE TITLE
[Fullscreen] some bugs

### ISSUE THREAD

**Issue by lollox** [OtterBrowser/otter-browser#1130]
If you go fullscreen, Otter will not really use a fullscreen mode. 

For example, if you have the sidebar toggle activated (the small vertical bar to open the sidebar), opening a youtube video in fullscreen will not occupy the whole screen, but that toggle will still be visible (and a small horizontal bar on top too)

So my impression is that Otter simply enlarges it and hide the various toolbar. But, for what I know, this behavior is not a fullscreen mode and has some implications when you have to deal with games for example.

Otter x64 weekly build 120, QTWebengine backend, Win10 x64

**Comment by Emdek** [comment]
@lollox, could you please provide some screenshot?
It would be best with the latest weekly, since it uses new version of QtWebEngine.

**Comment by lollox** [comment]
Just tried, bur otter-browser-win64-weekly127-qtwebengine doesn't start at all

**Comment by Emdek** [comment]
@lollox, any specific error messages?
Perhaps it is missing some DLL.

**Comment by lollox** [comment]
Nope, nothing appears. I looked at the task manager and I see the Otter process starting and quitting in about 1 sec

Cleaned all (main directory and profile directory), redownloaded and nothing changed. The weekly 125 works as expected


PS
I get also some messages from antivirus, but I also tried without its monitor service with the same result

**Comment by Emdek** [comment]
@lollox, then it looks more like instant crash, I'll try to debug it later.
Anyway, could you please provide such screenshot using older build?

**Comment by lollox** [comment]
This is quite interesting. it seems I'm not able to screenshot or videocapture it. If I try (with several tools) they capture the Otter window UNDER the fullscreen video.

**Comment by Emdek** [comment]
@lollox, dunno, I'm not familiar with current limitations of Windows. ;-)
What about some photo then?

**Comment by lollox** [comment]
you're right: http://i.imgur.com/dGxsm7j.jpg

**Comment by lollox** [comment]
OK, finally fixed ;)

**Comment by lollox** [comment]
It happens again now with a sidebar "strip" on the left when you're fullscreen
