### ISSUE TITLE
Wheel scrolling

### ISSUE THREAD

**Issue by BorutAtGit** [OtterBrowser/otter-browser#1132]
Under Windows (Win XP and Win 7 at my place) there is a system setting for defining how much scrolling happens for a scroll wheel changing a single nudge/detent position. It may be defined to scroll for a predefined number of lines (one or more), or to scroll a whole "page"/screen.

Otter seems not to observe that setting and to always scroll for one line. Opera 12 and others do observe that setting. Would this be possible to implement (since it is a detail with a big effect for those used to have >1 line setting)? 

Or am I doing something wrong?

Might be related to: https://github.com/OtterBrowser/otter-browser/issues/922

**Comment by Emdek** [comment]
@BorutAtGit, are you able to reproduce this issue using `test-qtwebkit.exe`?

**Comment by ZarkBit** [comment]
Confirmed, was able to reproduce with test-qtwebkit, same thing happens with qtwebengine build.

**Comment by Emdek** [comment]
Then it looks like upstream issue, if it is supposed to affect all scrollable views (not only web views) then I guess it can be fixed properly only on Qt level...
