### ISSUE TITLE
Allow to make Otter the default browser without admin rights

### ISSUE THREAD

**Issue by pierreporte** [OtterBrowser/otter-browser#1134]
In the General tab of the Preferences window, it is said that Otter has to be executed with administrator rights to make it the default browser.

1. It is wrong, at least on Linux where I can perfectly select Otter as my default browser (not in Otter itself but the control panel allows me to do that).
2. The default browser setting is a choice of the user and it shouldn’t be necessary to bother with the administrator of the system (regardless of the fact that the user can be the administrator).
3. Every other browsers on the market give this feature to simple users.

**Comment by Emdek** [comment]
This is how Firefox does it, perhaps it will be useful as reference implementation:
https://dxr.mozilla.org/mozilla-central/source/browser/components/shell/nsWindowsShellService.cpp#809

**Comment by pierreporte** [comment]
Now, under Linux, the button to set Otter as the default browser is disabled. It is then impossible to set it as the default browser in Otter itself.

**Comment by Emdek** [comment]
@pierreporte, it is disabled since that feature is not available.
This is really messed up on X11 platforms, and so far I haven't seen solution that simply works for all desktop environments and distributions.
