### ISSUE TITLE
Update Screenshots On Website

### ISSUE THREAD

**Issue by opticyclic** [OtterBrowser/otter-browser#1135]
It would be nice to have some updated screenshots on the website and include images from the different O/Ss that are supported.

**Comment by Frenzie** [comment]
Here's one from me on Xfce with Redmond window decorations.

![screenshot_2016-05-01_08-11-46-fs8](https://cloud.githubusercontent.com/assets/202757/14940416/782f964c-0f74-11e6-9174-51802a5014d2.png)

**Comment by resetnow** [comment]
Fedora 23, Gnome

![screenshot from 2016-05-01 13-09-22](https://cloud.githubusercontent.com/assets/2057191/14941282/a2984758-0fa6-11e6-90a4-fd9b51c88cca.png)
![screenshot from 2016-05-01 13-11-00](https://cloud.githubusercontent.com/assets/2057191/14941283/a299daaa-0fa6-11e6-87b8-8592ddb0ea9f.png)
![screenshot from 2016-05-01 13-09-14](https://cloud.githubusercontent.com/assets/2057191/14941281/a296c266-0fa6-11e6-92ea-e74317242ec3.png)

**Comment by ZarkBit** [comment]
Windows 7
Classic Theme
Fusion Widget Style

![okm7ub8 1](https://cloud.githubusercontent.com/assets/4160341/14942509/c055e9de-0fb6-11e6-8aba-3bcb296c81dd.png)

![dcz9rax 1](https://cloud.githubusercontent.com/assets/4160341/14942505/abbe6d16-0fb6-11e6-9b70-24b192354a30.png)

**Comment by pierreporte** [comment]
Otter Browser under Gnome 3 with the Adwaita theme:

![capture du 2016-05-01 20-12-38](https://cloud.githubusercontent.com/assets/2029853/14943424/6795e4ca-0fd9-11e6-94bd-baacb9ad0581.png)

**Comment by ZarkBit** [comment]
Windows 10

![6vrygeo 1](https://cloud.githubusercontent.com/assets/4160341/14953498/0428d1f2-1062-11e6-8533-5fbf697c9812.png)

![eqveqfj 1](https://cloud.githubusercontent.com/assets/4160341/14953508/180726b0-1062-11e6-91b1-6ed783daf370.png)

**Comment by Emdek** [comment]
Done:
http://otter-browser.org/screenshots/

**Comment by Frenzie** [comment]
lookin' good! :=)
