### ISSUE TITLE
QtWebEngine does not scale properly with Qt 5.6 and QT_SCALE_FACTOR

### ISSUE THREAD

**Issue by resetnow** [OtterBrowser/otter-browser#1136]
Qt 5.6 improved high-dpi support by allowing to adjust the application scaling factor with an environment variable. In Otter Browser UI seems to work well with this feature enabled but the webpage itself does not scale.

![screenshot from 2016-05-01 12-59-20](https://cloud.githubusercontent.com/assets/2057191/14941238/785fac34-0fa5-11e6-9d85-6707353a58b2.png)

```
$ QT_SCALE_FACTOR=1.4 ./otter-browser
$ lsb_release -a
Distributor ID:	Fedora
Description:	Fedora release 23 (Twenty Three)
Release:	23
Codename:	TwentyThree
$ dnf info qt5-qtbase
Name        : qt5-qtbase
Arch        : x86_64
Epoch       : 0
Version     : 5.6.0
Release     : 9.fc23
$ git log -n1
commit e5dc86a808d628ad876c571761017c55a9e985a7
Author: Michał Dutkiewicz <...>
Date:   Sat Apr 30 22:32:45 2016 +0200

    Define API for passwords storage backend, references #832

```

**Comment by Emdek** [comment]
@resetnow, cannot reproduce (Qt 5.6 from official SDK) it looks like something wrong in *QtWebEngine* itself or perhaps some issue with packages from distribution.
This is how it looks here:
http://p.im9.eu/bs2636.jpg
It simply should work out of the box.

**Comment by resetnow** [comment]
I agree that it's probably an upstream issue. Also, I think you launched Otter with an integer scale factor, because it works for me with QT_SCALE_FACTOR=2 too.

**Comment by Emdek** [comment]
@resetnow, indeed, I can reproduce it using 1.5, also using 5.7 beta.
