### ISSUE TITLE
Improve the startup configuration

### ISSUE THREAD

**Issue by pierreporte** [OtterBrowser/otter-browser#1138]
This is the current startup configuration of Otter:

![selection_521](https://cloud.githubusercontent.com/assets/2029853/14961290/2bc40a60-1099-11e6-8efd-0e9c60a87c04.png)

I think that it is flawed and that it could be greatly improved in order to make it clearer, more flexible, and with more features.
1. The major problem with the current solution is that when you set a home page URL but forget to change the startup behaviour to open that page, it won’t be opened.
2. The second problem is that the name of the speed dial, “start page”, is not consistent with what is displayed in the tab title, “blank page”. In that way, it is easy to be confused by the “empty page” entry that is actually about:blank. This has to be changed: the tab should be called “Speed dial” or “start page”.
3. The third problem is that the button to restore defaults only clears the home page text field and do not restore the startup behaviour.

My proposition is to modify this part of the settings window like this:

![selection_522](https://cloud.githubusercontent.com/assets/2029853/14961510/30136ff6-109a-11e6-9225-2e114919c040.png)

The choice of the behaviour is now a radio button list. For each behaviour, only the relevant controls are activated. The home page URL is now only settable when the button is checked and other behaviours are inactivated. You will notice two new behaviours:
- **Module.** When the future mail client and RSS client will be present, the user might want to open them at startup. Then, he or she checks the “module” button and selects the wanted module in the drop-down list. Before these features are implemented or if they are disabled, the line will obviously be absent.
- **Custom.** This feature is completely new. It is meant to open a custom selection of tabs at startup. Clicking on the button “Startup configuration” opens a dialog box which content is presented in the screenshot below. It is possible to open web pages (URLs), widgets, and special pages (speed dial and about: pages). The user can chose to pin tabs and to order them (by clicking on the arrows) and to delete entries. When the tab groups will be implemented, the list should be changed to a tree-style list and groups would be special lines containing classic entries.

The “Restaure to defaults” (sic) then just checks the default line.

![selection_526](https://cloud.githubusercontent.com/assets/2029853/14961713/505e54b4-109b-11e6-8cad-1fdb2a72967e.png)

This solution is better than the current one: it is not possible anymore to be mistaken with inconsistent naming and activated controls, everything is exposed and the user has more choice to have the startup configuration he or she wants.

The mockups are only examples and could be improved as well.

**Comment by pierreporte** [comment]
I just thought that the dialog for custom startup configuration would be better with a button to replace the content of the list with the current session. This button would have a very similar feature to the one writing the current URL page to the URL field.

**Comment by Emdek** [comment]
@pierreporte, 1. and 3. work almost exactly the same way in Firefox (it was source of inspiration).
Your proposal makes it more complex. ;-)

**Comment by pierreporte** [comment]
Well, it is more complex indeed. But what about radio-button list without *Module* and *Custom* entries?

**Comment by Emdek** [comment]
@pierreporte, not enough space to do so, it fits more to close to empty pages, and splitting it into more tabs will make it harder to find.

**Comment by pierreporte** [comment]
Then we should at least have better names (my second point) and disable the URL field when the selected behaviour is not to open that URL.

**Comment by Emdek** [comment]
@pierreporte, why disable?
It can be used separately, there is action to go to home page and it can still be accessed in startup dialog.
