### ISSUE TITLE
Superfluous directory '~/.Otter' on Linux

### ISSUE THREAD

**Issue by pmattern** [OtterBrowser/otter-browser#1139]
Running recent checkouts of Otter Browser on Linux a directory `~/.Otter` gets created in addition to the well-known `$XDG_CACHE_HOME/Otter` and `$XDG_CONFIG_HOME/otter`. Given the other two directories already exist that additional directory doesn't make any sense, in fact it seems to remain empty all the time anyway, so its creation should be avoided in the first place.

Seen on Arch Linux hence using Qt 5.6. It doesn't matter whether QtWebKit or QtWebEngine is used as backend.

**Comment by lollox** [comment]
On Windows too. Otter creates ".Otter" and ".QtWebEngineProcess" in the user folder but doesn't use them

**Comment by Emdek** [comment]
There is no explicit call that would create it.
".QtWebEngineProcess" is surely out of our control.

**Comment by Emdek** [comment]
And now I've got confirmation, they are created by at least QtWebEngine itself based on application name.

**Comment by pmattern** [comment]
> There is no explicit call [...] ".QtWebEngineProcess" is surely out of our control [...] confirmation they are created by at least QtWebEngine itself based on application name

Do you have any corresponding upstream source to track this? Also, in the meantime I saw that indeed other applications are affected as well, so is there already an upstream issue or shouldn't we open one otherwise?

**Comment by The-Compiler** [comment]
There's [QTBUG-54258](https://bugreports.qt.io/browse/QTBUG-54258), though that only mentions Windows.

**Comment by pmattern** [comment]
@The-Compiler 
Thanks for the link. I added a note about Linux.
