### ISSUE TITLE
Pulseaudio volume controls set to very high value when playing video

### ISSUE THREAD

**Issue by midluk** [OtterBrowser/otter-browser#1144]
Every time I play a HTML5 video in otter (e.g. on youtube, but I have seen it on different pages), it resets the volume control in Pulseaudio to a very high value (I think I have seen 100%, but during the last test it was around 90%) for the master channel as well as for the "otter-broswer: playback stream" (currently get 75% there).
Usually a setting around 20% is good with my headphones.
Reloading the page with the video resets the volume again, it is not just the first loading of a video that does this.

I'm seeing this for some time now. I can't remember having the problem at the very beginning of me using otter, I think it started some time in the last weeks/months, perhaps with an update from qt 5.5 to qt 5.6.

I'm using git master (currently 8bc9a499ed745c108a60580a245c1ce2c72c5630) of Otter with Qt5WebKit backend and QT 5.6.
My system is Fedora 23 x86_64 with KDE4.

**Comment by Frenzie** [comment]
I suspect it's more likely a PulseAudio problem than an Otter/Qt problem. See http://fransdejonge.com/2015/10/pulseaudio-how-to-decouple-application-volumes-and-global-volume/

**Comment by midluk** [comment]
OK, that definitely helps. Now master volume is unchanged.
But I think it is still a bugl that the volume of "otter-broswer: playback stream" is not remembered and always reset to 75%.

**Comment by Frenzie** [comment]
True. Is that Flash or HTML5?

**Comment by midluk** [comment]
I think it is HTML5, at least I have plugins disabled.
The volume that is set seems to differ between different videos. I have seen various values between 51% and 100%, but for the same video it always seems to be the same value.

**Comment by Emdek** [comment]
@midluk, it's indeed upstream issue, to fix it QtWebKit needs to be aware of PulseAudio, which is unlikely to happen any time soon.
It's simply broken default configuration shipped by probably most of distributions...
