### ISSUE TITLE
Error 102 shown when downloading file

### ISSUE THREAD

**Issue by midluk** [OtterBrowser/otter-browser#1145]
Every time I open a link to a file that is not displayed in otter (e.g. pdf, in contrast to html), an error page "Error 102" is shown. The download dialog is still displayed and the download happens normally.
I would expect that the original page containing the link is still displayed (+ the download dialog) instead of the error page. If the download link is opened in a new tab, this tab (empty, but not showing an error) should be closed after an action  is chosen in the download dialog.
This is with current otter git master, qt5.6 and QtWebKit backend on Fedora 23

> Error 102
You tried to access the address http://example.com/example.pdf, which is currently unavailable. Please make sure that the web address (URL) is correctly spelled and punctuated, then try reloading the page.

>Frame load interrupted by policy change

**Comment by Emdek** [comment]
@midluk, could you please copy entry from Error Console (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>O</kbd>) shown when this error page is shown?
It might be side effect of this:
https://codereview.qt-project.org/#/c/143281/

**Comment by midluk** [comment]
[Fri Jun 10 08:35:06 2016] Network - http://tenet.dl.sourceforge.net/project/otter-browser/otter-browser-weekly127/otter-browser_0.9.11-dev127-1_amd64.deb
WebKit error #102: Frame load interrupted by policy change

**Comment by Emdek** [comment]
@midluk, thanks.
I'll try to find out if this one can be safely blacklisted, as long as it is not shared by some real errors it won't be a problem.
