### ISSUE TITLE
Extend Browser/EnableImages option to allow to completely disable images and load only these already cached

### ISSUE THREAD

**Issue by AlbertOpen** [OtterBrowser/otter-browser#1146]
Add functionality of Opera12 to easy switch images off (and not download them to save expansive traffic), right-click in image border -> show one image, show cached images and so on...

**Comment by Emdek** [comment]
@AlbertOpen, there is already option to disable image loading.
Currently there is no way to switch it to load only cached images (might be doable, but probably on for QtWebKit backend).

> right-click in image border -> show one image, show cached images and so on...

I don't understand this part, could you please elaborate more?

**Comment by Emdek** [comment]
Apparently documentation of `QWebEngineSettings::AutoLoadImages` and `QWebSettings::AutoLoadImages` is not clear enough and this flag allows to show cached images.

**Comment by AlbertOpen** [comment]
@Emdek 
Thanks for reply.
I just want to OtterBrowser work with images as Opera12 which is perfect.
On each tab it can independently load/not load images (triangle in right bottom corner near size of page). If images not loaded I see borders (squares) of images on the page and can right-click in square and load one image to save internet traffic.
For example, google.ru
In Opera12 I see border above search string, can right click in it and choose show image.
In OtterBrowser with unchecked Turn on load images I see nothing above search string and when right-click there I can download image only. This is not good for me.

**Comment by Emdek** [comment]
@AlbertOpen, ah, I wasn't aware of that feature before.
I'll ask upstream developers about that, see #1149.
