### ISSUE TITLE
make fails on Ubuntu xenial

### ISSUE THREAD

**Issue by rohshall** [OtterBrowser/otter-browser#1150]
`
 ~/otter-browser/build (git)-[master]- % cat /etc/lsb-release                                                                                                                              
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu Xenial Xerus (development branch)"
`

`
 ~/otter-browser/build (git)-[master]- % cmake ..
 ~/otter-browser/build (git)-[master]- % make
`

`
[ 62%] Building CXX object CMakeFiles/otter-browser.dir/src/ui/TabSwitcherWidget.cpp.o
[ 63%] Building CXX object CMakeFiles/otter-browser.dir/src/ui/TextLabelWidget.cpp.o
/home/swadnerkar/otter-browser/src/ui/TextLabelWidget.cpp:22:30: fatal error: QtGui/QApplication: No such file or directory
compilation terminated.
CMakeFiles/otter-browser.dir/build.make:2819: recipe for target 'CMakeFiles/otter-browser.dir/src/ui/TextLabelWidget.cpp.o' failed
make[2]: *** [CMakeFiles/otter-browser.dir/src/ui/TextLabelWidget.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/otter-browser.dir/all' failed
make[1]: *** [CMakeFiles/otter-browser.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by Emdek** [comment]
@rohshall, ah, once again I've managed to mix in header location from Qt4 times, sorry.

**Comment by rohshall** [comment]
@Emdek , now it fails on another include:
"/home/swadnerkar/otter-browser/src/ui/TextLabelWidget.cpp:25:24: fatal error: QtGui/QStyle: No such file or directory"

**Comment by Emdek** [comment]
@rohshall, fixed.
It's annoying side effect of splitting QtGui into two modules in Qt5...

**Comment by rohshall** [comment]
Thank you so much. This is fastest response I have seen to a issue opened :)

**Comment by Emdek** [comment]
@rohshall, you are lucky, in recent weeks typical response time was around one month. :-P
