### ISSUE TITLE
Click-to-play for revived QTWebKit doesn't work

### ISSUE THREAD

**Issue by lewisje** [OtterBrowser/otter-browser#1151]
I suspect this is something still being worked on for that backend.

**Comment by Emdek** [comment]
@lewisje, as noted [here](https://github.com/annulen/webkit/wiki/Comparison-with-QtWebKit-5.6) as of TP1 plugins are not supported.
And it will take some time before they will land.
In fact it is the main show stopper for ditching legacy QtWebKit and replacing it with version currently known as NG.

**Comment by lewisje** [comment]
That's NPAPI, but it looks like it still supports PPAPI Flash (I don't know how to enumerate the plugins loaded in this browser, which is another issue entirely), or at least Otter is *somehow* still running Flash applets.

**Comment by Emdek** [comment]
@lewisje, nope, PPAPI is supported only by Blink (QtWebEngine).
This feature won't work properly until it will be fixed upstream.
