### ISSUE TITLE
Visual glitch in the navigation bar

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#1157]
Somewhere between the 19th and today, something went wrong with the navigation bar.

The location of the second icon (showing Forward in the default configuration) shows 2 overlapping icons.

**Comment by midluk** [comment]
I did some bisecting, it was introduced with cde10a1ce9a89ef49e80acb3a422a69da99a7a65
I also attached a screenshot of the problem. The main bar as well as the navigation bar show  an additional "back" button.
![otter-toolbar-bug](https://cloud.githubusercontent.com/assets/366536/16499045/ec680742-3efe-11e6-81e0-2bca82f76ed2.png)

**Comment by Emdek** [comment]
@midluk, good catch, thanks.
One of lines was missing ``else``...
