### ISSUE TITLE
Dependency problems on Debian testing

### ISSUE THREAD

**Issue by mariokamenjak** [OtterBrowser/otter-browser#1158]
When I try to install otter browser witth gdebi it reports the following unsatisfied dependencies:
otter-browser depends on libhunspell-1.3-0 (>= 1.3.3); however:
  Package libhunspell-1.3-0:amd64 is not installed.
 otter-browser depends on qtbase-abi-5-3-2; however:
  Package qtbase-abi-5-3-2 is not installed.

Funnily enough I have libhunspell-1.4.1-2 installed.

**Comment by Frenzie** [comment]
That seems to be a packaging problem with Stretch right now, not with Otter as such. `qtbase-abi-5-3-2` is a virtual package provided by `libqt5core5a`, but only by the version in unstable, not in testing. I imagine that'll trickle down soon enough. 

That being said, I think normal applications generally aren't *supposed* to depend on qtbase-abi but only on libqt5core5a, so I'm not entirely sure why `shlibs:Depends` expands to include it. Maybe it has something to do with the increasingly outdated Qt 5.3 in Jessie.

**Comment by mariokamenjak** [comment]
On that matter... would it be a tough job for you guys to contact the guys at Debian and get otter into the Debian archive?
It would give a lot of coverage for otter, and Ubuntu and Mint also still take packages from the Debian archive.
https://www.debian.org/doc/manuals/distribute-deb/distribute-deb.html#adding-packages-to-debian
http://www.debian.org/devel/wnpp

**Comment by Emdek** [comment]
@mariokamenjak, AFAIK hunspell 1.4 is ABI incompatible with 1.3, so package created for Debian stable could crash there.
It seems that the best solution for now would be to try to go for #1148, which would allow us to provide some package containing revived QtWebKit which will take some time to reach distributions.

**Comment by mariokamenjak** [comment]
Is it ok if I myself send the Debian guys a request trough wnpp? Maybe some of them are willing to help?
