### ISSUE TITLE
Weekly 132 - 64 bit installer - The program can't start because Qt5WebKitWidgetsd.dll is missing from your computer.

### ISSUE THREAD

**Issue by ManiacDC** [OtterBrowser/otter-browser#1164]
I just upgraded from weekly 131 to 132 using the 64 bit windows installer. I get this error message:
The program can't start because Qt5WebKitWidgetsd.dll is missing from your computer. Try reinstalling the program to fix this problem. The regular download version doesn't work either, but the webkitng one does.

**Comment by Emdek** [comment]
@ManiacDC, fixed, somehow 64 bit build switched to debug mode after QtCreator upgrade and was looking for debug symbols...

**Comment by ManiacDC** [comment]
Great, thanks! Works fine now.
