### ISSUE TITLE
invisible page area on startup after opening only one tab via startup dialog

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#1165]
Hi,
I just noticed a strange cornercase behaviour, which shows up on a new start of Otter from a startup dialog (e.g. after a crash) if there is only one page/tab left to be displayed. In this case the tab is created with the expected label, but the main page area is inactive. The page can be displayed by opening another tab and switching back to the first one or by calling some of the "arranging" functions in the context menu of the tab (e.g. Arrange - Maximise).
Could it be that there is some initialisation missing? 
This does not occur if one tab is opened on new start via restoring the previous session (i.e. without the startup dialog).
Using Otter Webkit 32bit, weekly 132 on Win 7.

Regards,
    vbr

**Comment by Emdek** [comment]
@vbr, it seems that sometimes we end up without selecting active tab and all are hidden, for me the easiest way to reproduce it (but not 100% success rate) is to use startup dialog with old session and uncheck it's active page (it uses bold font).

**Comment by Emdek** [comment]
Now it should fallback to first not minimized tab when active index is invalid (previously it was applied only if index was smaller than 0).
