### ISSUE TITLE
Weekly version ignores CSS

### ISSUE THREAD

**Issue by tmysik** [OtterBrowser/otter-browser#1166]
Today, my Otter Browser has been updated to Otter 0.9.11 weekly 131 (I use Ubuntu PPA). On every website I load, all its CSS are completely ignored - see screenshot.

![otter](https://cloud.githubusercontent.com/assets/331924/16948717/9366583a-4db6-11e6-857f-1de067f9a835.png)

Thanks.

**Comment by uahim** [comment]
@tmysik this was fixed in weekly 132
#1162
