### ISSUE TITLE
Build error (commit 2ba6df7e96b4b260d2951ab910c35d9d1ff6df78)

### ISSUE THREAD

**Issue by SchweinDeBurg** [OtterBrowser/otter-browser#1168]
```
[100%] Building CXX object CMakeFiles/otter-browser.dir/otter-browser_automoc.cpp.o
In file included from /home/elijah/rpmbuild/BUILD/otter-browser-0.9.11-git/0.9.11-i686-redhat-linux-gnu/otter-browser_automoc.cpp:53:0:
/home/elijah/rpmbuild/BUILD/otter-browser-0.9.11-git/0.9.11-i686-redhat-linux-gnu/moc_QtWebKitPage.cpp: In static member function 'static void Otter::QtWebKitPage::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)':
/home/elijah/rpmbuild/BUILD/otter-browser-0.9.11-git/0.9.11-i686-redhat-linux-gnu/moc_QtWebKitPage.cpp:140:21: error: 'class Otter::QtWebKitPage' has no member named 'handleConsoleMessage'
```

**Comment by Emdek** [comment]
@SchweinDeBurg, which Qt version are you using?
It's in ``ifdef`` to be enabled only when using revived QtWebKit.
And works fine for me with legacy QtWebKit from Qt 5.6.

**Comment by SchweinDeBurg** [comment]
My environment is following:
- CentOS 6.8 32-bit
- Qt 5.6.1 packages are installed from EPEL repo
- GCC 5.3.0 built by myself using Fedora project patches

**Comment by SchweinDeBurg** [comment]
Maybe this information will be helpful:

Top CMakeLists.txt contains:
```
    if (${Qt5WebKitWidgets_VERSION_MINOR} GREATER 600)
        list(APPEND OTTER_BACKENDS_WEB "QtWebKit")
    else (${Qt5WebKitWidgets_VERSION_MINOR} GREATER 600)
        add_definitions(-DOTTER_ENABLE_QTWEBKIT_LEGACY)

        list(APPEND OTTER_BACKENDS_WEB "QtWebKit (legacy)")
    endif (${Qt5WebKitWidgets_VERSION_MINOR} GREATER 600)
```
In my case (with Qt 5.6.1) cmake uses else branch of this and adds ```-DOTTER_ENABLE_QTWEBKIT_LEGACY``` to the compilation flags. But ```src/modules/backends/web/qtwebkit/QtWebKitPage.h``` contains
```
#ifndef OTTER_ENABLE_QTWEBKIT_LEGACY
    void handleConsoleMessage(QWebPage::MessageSource category, QWebPage::MessageLevel level, const QString &message, int line, const QStri
#endif
```
Look at #if**n**def - I think the problem is localized but unfortunately I am a server-side developer not using Qt, so currently I don't understand how to fix this problem.

**Comment by Emdek** [comment]
@SchweinDeBurg, it's intentional, this method in both files is guarded using the same ``#ifndef OTTER_ENABLE_QTWEBKIT_LEGACY``.
Maybe try clean rebuild.

**Comment by SchweinDeBurg** [comment]
rpmbuild always perform a full and clean rebuild

**Comment by Emdek** [comment]
@SchweinDeBurg, uhm, maybe try clang then?
It's simply weird, since it should be removed or kept in both files, condition is the same.

**Comment by SchweinDeBurg** [comment]
clang version 3.6.2 (tags/RELEASE_362/final):
```
[100%] Building CXX object CMakeFiles/otter-browser.dir/otter-browser_automoc.cpp.o
In file included from /home/elijah/rpmbuild/BUILD/otter-browser-0.9.11-git/0.9.11-i686-redhat-linux-gnu/otter-browser_automoc.cpp:53:
/home/elijah/rpmbuild/BUILD/otter-browser-0.9.11-git/0.9.11-i686-redhat-linux-gnu/moc_QtWebKitPage.cpp:140:21: error: no member named 'handleConsoleMessage' in 'Otter::QtWebKitPage'
```

**Comment by Emdek** [comment]
@SchweinDeBurg, could you please paste somewhere and link that auto generated file?

**Comment by SchweinDeBurg** [comment]
http://zarezky.spb.ru/temp/moc_QtWebKitPage.cpp

See ```void Otter::QtWebKitPage::qt_static_metacall()```, the problem child is a line starting with ```case 9:``` Removing this line completely solves my problem.

**Comment by SchweinDeBurg** [comment]
Hurray! Finally I've found the solution - just add ```set(CMAKE_AUTOMOC_MOC_OPTIONS -DOTTER_ENABLE_QTWEBKIT_LEGACY)``` immediately after ```add_definitions(-DOTTER_ENABLE_QTWEBKIT_LEGACY)```. Here is a complete patch:
```
diff -up otter-browser-0.9.11-git/CMakeLists.txt.orig otter-browser-0.9.11-git/CMakeLists.txt
--- otter-browser-0.9.11-git/CMakeLists.txt.orig	2016-08-05 09:33:27.594106142 +0300
+++ otter-browser-0.9.11-git/CMakeLists.txt	2016-08-05 09:33:37.638268037 +0300
@@ -347,6 +347,7 @@ if (Qt5WebKitWidgets_FOUND AND ENABLE_QT
 		list(APPEND OTTER_BACKENDS_WEB "QtWebKit")
 	else (${Qt5WebKitWidgets_VERSION_MINOR} GREATER 600)
 		add_definitions(-DOTTER_ENABLE_QTWEBKIT_LEGACY)
+		set(CMAKE_AUTOMOC_MOC_OPTIONS -DOTTER_ENABLE_QTWEBKIT_LEGACY)
 
 		list(APPEND OTTER_BACKENDS_WEB "QtWebKit (legacy)")
 	endif (${Qt5WebKitWidgets_VERSION_MINOR} GREATER 600)
```
With that patch applied ```moc``` utility generates correct ```moc_QtWebKitPage.cpp``` file and the code builds successfully. So I am closing this issue.

**Comment by Emdek** [comment]
@SchweinDeBurg, that is odd, it shouldn't be needed, which CMake version are you using?

**Comment by SchweinDeBurg** [comment]
2.8.12

**Comment by Emdek** [comment]
@SchweinDeBurg, ah, that could explain that, it's the oldest version that works at all, while I would happily bump required to 3.1 (for example it allows to set C++11 requirement without messing with flags), but stable Debian and some other distributions got stuck at 3.0...

**Comment by SchweinDeBurg** [comment]
In CettOS 6.x we have version 3.5.2 too (in the EPEL repo), but none of the OSS project I am currently using *really* required that version. :-)

**Comment by Emdek** [comment]
@SchweinDeBurg, it's hard to bump that requirement when caring for Debian stable. ;-)
