### ISSUE TITLE
Refreshing page doesn't work

### ISSUE THREAD

**Issue by chief-kh** [OtterBrowser/otter-browser#1169]
I'm using Lubuntu 16.04 operating system. I have unstable internet connection. After losing connection I receive an error - it's OK. But then I reconnect and press refresh button. Otter continues to show me error. The only solution is to close tab and re-open it.
Thanks.

**Comment by The-Compiler** [comment]
What error do you get?

**Comment by mariokamenjak** [comment]
I think he implied the 404 error.

**Comment by chief-kh** [comment]
Error 99
You tried to access the address http://www.radioroks.ua/player/, which is currently unavailable. Please make sure that the web address (URL) is correctly spelled and punctuated, then try reloading the page.

**Comment by Emdek** [comment]
@chief-kh, are you using WiFi or have network issues?
Then it's "normal", QtWebKit (or more like QtNetwork) has issues when network reconnects.

**Comment by chief-kh** [comment]
I'm using CDMA EV-DO Rev.B USB modem.

**Comment by Emdek** [comment]
@chief-kh, yeah, it looks exactly like that issue. :-/
Hopefully it will get some solution on the level of QtWebKit or QtNetwork.
Until then the only workaround is to reopen tab when it happens.

**Comment by chief-kh** [comment]
Did you send bug report to them? I can do it myself, but I think you will do it more ably. Thanks.

**Comment by The-Compiler** [comment]
I can only find [QTBUG-55025](https://bugreports.qt.io/browse/QTBUG-55025) right now, but there are various upstream bugs about this already.
