### ISSUE TITLE
Navigation context menu does not open 

### ISSUE THREAD

**Issue by Matthias-Fauconneau** [OtterBrowser/otter-browser#1171]
Holding a navigation button pressed does not open the context menu.
The menu can be opened by moving the mouse (while pressed).
(Possibly a Qt/Wayland issue, not sure if their are other Qt5 software with this widget I could test.)

**Comment by Emdek** [comment]
@Matthias-Fauconneau, what exactly do you mean by navigation button and navigation context menu?

**Comment by Matthias-Fauconneau** [comment]
Back button.

**Comment by Emdek** [comment]
@Matthias-Fauconneau, just as I've expected but I wanted to be 100% sure. ;-)
Do you mean context menu of that button (which works fine under X11) or menu shown after holding down left mouse button (just fixed)?

**Comment by Matthias-Fauconneau** [comment]
holding down.

**Comment by Emdek** [comment]
@Matthias-Fauconneau, then try current master, it was blocked by gestures recognition.

**Comment by resbro** [comment]
This seems to be fixed in weekly 138. at least in windows (10)

Win 10 x 64
Weekly 138 x 32 win.exe

**Comment by Emdek** [comment]
Closing since most likely now it is no longer reproducible on Wayland anyway.
