### ISSUE TITLE
Suggestion: use Appimages instead of weekly builts for various distros

### ISSUE THREAD

**Issue by msjasinski** [OtterBrowser/otter-browser#1174]
I've just learnt about AppImageKit: "Using (...) you can package desktop applications as AppImages that run on common Linux-based operating systems, such as RHEL, CentOS, Ubuntu, Fedora, debian and derivatives. http://appimage.org"). I think it is a good solution for Otter. Obviously, weekly Linux releases are not working, especially RPMs. Maybe this method would be better? Krita and some other packages are using it already.

**Comment by Emdek** [comment]
Duplicate of #1148.
