### ISSUE TITLE
Integrate breakpad to collect crash information

### ISSUE THREAD

**Issue by Emdek** [OtterBrowser/otter-browser#1176]
Since debugging under Windows is painful and most of crashes happen there then it is time to automate them which should allow to improve both our code and state of revived QtWebKit.
The best solution seems to be Google Breakpad which is used by Mozilla, there exist some documentation on how to use it with Qt:
https://github.com/JPNaude/dev_notes/wiki/Using-Google-Breakpad-with-Qt
We will also need end point to be installed on our server.
By default it should be enabled only for Windows, only for official builds, by using explicit CMake option to enable it.

**Comment by pierreporte** [comment]
Is there any sort of interaction with Google servers?

**Comment by Emdek** [comment]
@pierreporte, no, it was simply developed by Mozilla and Google, apparently before Google decided to move financial support to own browser...

**Comment by pierreporte** [comment]
OK then. I feared that the user data could potentially be collected by Google in the process. Since Otter is a web browser, a lot of personal informations could be gathered. At least, would you let the user decide to send crash data or not?

**Comment by Emdek** [comment]
@pierreporte, we have full control over data transfer, plus of course it won't be obligatory, but using dialog similar to that used by Opera.
I'm not sure how rich these reports will be, but yes, some tools produce reports which can contain stuff like parts of visited page etc.

**Comment by Emdek** [comment]
Crash Reporter is ready and we now we also have basic end point too.
