### ISSUE TITLE
Crash at the entrance to Google Drive

### ISSUE THREAD

**Issue by VSHY** [OtterBrowser/otter-browser#1177]
FAULTING_IP: 
Qt5WebKit!JSC::ControlFlowProfiler::basicBlockExecutionCountAtTextOffset+18c03
5ded02c3 52              push    edx

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 000000005ded02c3 (Qt5WebKit!JSC::ControlFlowProfiler::basicBlockExecutionCountAtTextOffset+0x0000000000018c03)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000001
   Parameter[1]: 000000000bccf514
Attempt to write to address 000000000bccf514

FAULTING_THREAD:  000011f8

DEFAULT_BUCKET_ID:  INVALID_STACK_ACCESS

PROCESS_NAME:  otter-browser.exe

Details: [google-drive_crash.txt](https://github.com/OtterBrowser/otter-browser/files/460306/google-drive_crash.txt).

Env: Win7 64-bit, otter-browser-win32-weekly140.zip.

This already occurs during about the two months.

**Comment by Emdek** [comment]
@VSHY, could you please try to reproduce that using 64 bit build?

**Comment by annulen** [comment]
`JSC::ControlFlowProfiler::basicBlockExecutionCountAtTextOffset` is not the culprit, this function is only called by `jsc` command line JS interpreter, and not by QtWebKit libraries. Also notice offset value is huge: `18c03` - means that actual failure point is far away from `basicBlockExecutionCountAtTextOffset`

**Comment by VSHY** [comment]
@annulen 
Thanks for your contribution!

@Emdek 
Just in case: yes, crash was reprodused on 64-bit build.

**Comment by Emdek** [comment]
@VSHY, can you try to reproduce it using beta 11 packages?
They are based on updated QtWebKit.

**Comment by VSHY** [comment]
@Emdek 
In beta 11 that crash does not occur. But upload of file all also don't work.
