### ISSUE TITLE
Add FLIF support to Otter Browser

### ISSUE THREAD

**Issue by sviscapi** [OtterBrowser/otter-browser#1180]
Hi,

Could you please add FLIF support to Otter Browser ?

http://flif.info/index.html
http://flif.info/software.html

Cheers, Sam a.k.a "Magic Sam" from the Open Pandora community

https://pyra-handheld.com/boards/

**Comment by Emdek** [comment]
@sviscapi, it needs to be added in backends, so you should ask developers of Blink (for QtWebEngine support) and WebKit or Qt (for QtWebKit).
