### ISSUE TITLE
WebCore::RenderObject::arenaDelete(): otter-browser killed by SIGSEGV

### ISSUE THREAD

**Issue by martinkg** [OtterBrowser/otter-browser#1183]
Hi,

I am package maintainer of the otter-browser package for fedora.
A user opened a ticket in fedora bugzilla for this issue:

https://bugzilla.redhat.com/show_bug.cgi?id=1376935

can someone have a look on it ?
Thanks

**Comment by The-Compiler** [comment]
Looking at the stacktrace this looks like an issue in QtWebKit, not Otter.
