### ISSUE TITLE
Remove “— Otter Browser” from the titles of internal windows and dialogs

### ISSUE THREAD

**Issue by pierreporte** [OtterBrowser/otter-browser#1185]
Every window (like the preferences window) or dialog has the suffix “— Otter Browser” after its own title:

![preferences-window-advanced-tab-browsing](https://cloud.githubusercontent.com/assets/2029853/18810700/2d978a9e-829d-11e6-9472-c5af8c34ce69.png)

![startup-dialog](https://cloud.githubusercontent.com/assets/2029853/18810690/d1ea8d04-829c-11e6-98f5-189f608a6193.png)

![speed-dial-add-tile-window](https://cloud.githubusercontent.com/assets/2029853/18810696/1786488a-829d-11e6-89c6-89a8a2ac34eb.png)

It seems useless to me. When opening the preference window or when a dialog box appears, it is always clear that it belongs to Otter. Removing it would be clearer.

**Comment by Emdek** [comment]
It's side effect of `QGuiApplication::applicationDisplayName()` and we can't do anything about that.

**Comment by Frenzie** [comment]
Not useless if they're non-blocking.
