### ISSUE TITLE
Residual translation in the toolbar menu

### ISSUE THREAD

**Issue by pierreporte** [OtterBrowser/otter-browser#1186]
The toolbar menu accessed by **Menu / Toolbars** or **Customize / Toolbars** (after a right click on the GUI) shows a residual French translation after switching to English:

![menu_535](https://cloud.githubusercontent.com/assets/2029853/18810892/1f14f4f2-82a2-11e6-888f-2a23eb306599.png)

The menu in French is highlighted. It is for status bar.

When right-clicking on the status bar, its name appears in French as well:

![menu_537](https://cloud.githubusercontent.com/assets/2029853/18810932/1832749c-82a3-11e6-97b8-e293ac480fbb.png)

**Comment by Emdek** [comment]
@pierreporte, although in your case it was most likely caused by manually modified toolbar, when you modify standard toolbar then its title is set to translated value and it won't be translated to current language anymore.
