### ISSUE TITLE
Planet.com website slides not working

### ISSUE THREAD

**Issue by myier** [OtterBrowser/otter-browser#1187]
A simple issue, example: https://www.planet.com/gallery/copenhagen-20160918/
The slider is supposed to be moving while being pressed, and for me it isn't. I'm using version 142 for win64.
Thank you

**Comment by pierreporte** [comment]
It doesn’t work for me either, but it is far worse because the page doesn’t even load properly:

![planet copenhagen otter browser_538](https://cloud.githubusercontent.com/assets/2029853/18869380/68b8f2be-84ac-11e6-82e9-1e94756702d2.png)


I use version 8114548c1325fe59d80512d3ae4fb7290555ce0b on Archlinux 64 bits.

**Comment by Emdek** [comment]
@myier, try setting User Agent (View menu) to Mask as Safari, apparently this site depends on UA sniffing...

@pierreporte, I would suggest to switch to revived QtWebKit. ;-)

**Comment by pierreporte** [comment]
@Emdek According to the About dialog, I already use QtWebKit. It says:

> Web backend: WebKit Backend (legacy) 538.1

**Comment by Emdek** [comment]
@pierreporte, exactly, as it says, **legacy**. :-P
You can find revived QtWebKit here:
https://github.com/annulen/webkit

**Comment by pierreporte** [comment]
What do I have to do exactly? The sources are *huge* and it is not very clear what the “releases” are for.

**Comment by myier** [comment]
I had the default setting, which configures UA as Safari already, I tried with Safari/MacOS anyway, but it's the same, I have a proper display of the page with the slider between the two images but I cannot move it.

**Comment by annulen** [comment]
@pierreporte Use this repo instead, it much leaner: https://github.com/annulen/qtwebkit-snapshots (I'll import fresh snapshot soon)

**Comment by Emdek** [comment]
@pierreporte, here are build instructions:
https://github.com/annulen/webkit/wiki/Building-QtWebKit-on-Linux
You can always wait for appimage but that might take some more time...

@myier, I've just tried weekly 142 under Windows and it works fine there after masking as Safari.

**Comment by myier** [comment]
That's strange. I'll wait for 143 to verify. Maybe a configuration item is wrong. I installed 142 with the package otter-browser-win64-weekly142.7z .

**Comment by myier** [comment]
I confirm that this is working with UA as safari in beta11. Thanks
