### ISSUE TITLE
overriding user agent is not working

### ISSUE THREAD

**Issue by myier** [OtterBrowser/otter-browser#1188]
Setting an overriden user agent in website preferences has no effect. Reopening the website preferences after validations shows it's still using the general setting, checkbox is unchecked.

**Comment by Emdek** [comment]
Cannot reproduce, checked using both Linux and Windows.

**Comment by myier** [comment]
Ok I made more tests and it doesn't work only when overriding with 'Default'. Otherwise it seems to work.

**Comment by Emdek** [comment]
@myier, indeed.
