### ISSUE TITLE
Math rendering is very small

### ISSUE THREAD

**Issue by myier** [OtterBrowser/otter-browser#1191]
Equations rendered in MathML, for example on wikipedia like [this one](https://en.wikipedia.org/wiki/Navier–Stokes_equations#Incompressible_flow) appear very small and are hard to read. Zooming in doesn't change anything.

**Comment by pierreporte** [comment]
With my version, everything is readable and with the right size, either with QtWebkit (legacy) or QtWebEngine.

**Comment by Emdek** [comment]
@myier, rendering issues / backend bugs should be reported directly to proper tracker.
You can use bundled *test-qtwebkit.exe* to compare with basic browser and *-xp* package to compare with legacy QtWebKit.
Regressions in revived QtWebKit (issues happening for version 602 but not for 538 from *-xp* package) can be reported here:
https://github.com/annulen/webkit/issues
Issues that affect both 538 and 602 should be reported here (component QtWebKit):
https://bugreports.qt.io/

**Comment by The-Compiler** [comment]
AFAIK neither of those engines support MathML, so I'd expect those to simply be images.
