### ISSUE TITLE
problems with displaying some png images

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#1193]
Hi,
I recently noticed problems with displaying some png images in Otter.
Some parts of the image only shows a dotted outline on contrast/colour boundaries instead of full colour.
cf. e.g.
http://historje.tumblr.com/post/151047189508/
image path:
http://67.media.tumblr.com/11de3a85491ceecb28bfe9e0bbc74b77/tumblr_oe7ipogp0J1rm3mxeo1_500.png

compared to others, such as:
http://historje.tumblr.com/post/150063501858/

http://67.media.tumblr.com/b4f9d8b7e32453b64e7dcf7d2bd5eec6/tumblr_od4bzfU5LX1rm3mxeo1_500.png

I am not sure, what the problematic feature of this minority of png files is (maybe the transparency?), but I don't see any problems in other browsers or image viewers.
However, if I resave the file in Irfanview using the default options, the resulting copy can be displayed in Otter correctly.

(using otter-browser-win64-weekly142 on win7, 64bit).

regards,
    vbr

**Comment by Emdek** [comment]
It's Windows specific issue in QtWebKit TP3, hopefully it will be fixed in next release.

**Comment by Emdek** [comment]
@vbr, updating to TP4 solved that issue for me, BTW, it was 64 bit specific.
