### ISSUE TITLE
Crash by pressing Back-button on YouTube

### ISSUE THREAD

**Issue by VSHY** [OtterBrowser/otter-browser#1196]
STR:
1. Open youtube.com and click on any video.
2. Click to any video image on the right panel.
3. Press Back button on browser toolbar.

PROBLEM_EVENT_NAME: APPCRASH
FAULTING_IP:
Qt5Multimedia!QAbstractVideoSurface::isActive+3
7474da83 8a4010          mov     al,byte ptr [eax+10h]
EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 000000007474da83 (Qt5Multimedia!QAbstractVideoSurface::isActive+0x0000000000000003)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
 ExceptionOffset: 0003da83
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: 0000000000000010
Attempt to read from address 0000000000000010
FAULTING_THREAD:  000013c4
DEFAULT_BUCKET_ID:  NULL_CLASS_PTR_READ
PROCESS_NAME:  otter-browser.exe
APP_VERSION:    0.9.1.1
LAST_CONTROL_TRANSFER:  from 000000006b651db9 to 000000007474da83
STACK_TEXT:
WARNING: Stack unwind information not available. Following frames may be wrong.
002ad728 6b651db9 00652270 169cfaa0 0065a9e0 Qt5Multimedia!QAbstractVideoSurface::isActive+0x3
002ad74c 6b6512bb 14492ac8 6d632b6b 1cf6a080 wmfengine+0x11db9
00000000 00000000 00000000 00000000 00000000 wmfengine+0x112bb
FAILURE_BUCKET_ID:  NULL_CLASS_PTR_READ_c0000005_Qt5Multimedia.dll!QAbstractVideoSurface::isActive
FAILURE_IMAGE_NAME:  Qt5Multimedia.dll
FAILURE_IMAGE_VERSION:  5.7.0.0

Environment: Win7 x64, Otter 32-bit weekly 142.

**Comment by Zero3K** [comment]
Please try the latest weekly. It fixed the issue that you mentioned.

**Comment by myier** [comment]
I confirm that I don't have this issue anymore with the beta12.

**Comment by VSHY** [comment]
You are right, guys. Thanks!
