### ISSUE TITLE
Otter won’t start on Windows (missing DLL)

### ISSUE THREAD

**Issue by pierreporte** [OtterBrowser/otter-browser#1197]
I convinced someone to try Otter. He installed it using *otter-browser-win64-0.9.11-weekly142-setup.exe* but the browser won’t start due to a missing DLL:

![](https://framapic.org/bvMDvLe2uQUA/Dx6CPtWkIQec.gif)

Translation:

> **otter-browser.exe - System error**
> Impossible to start the programme because api-ms-win-crt-runtime-l1-1-0.dll is missing on your computer. Try to reinstall the programme to fix the problem.

Both 32 bits and 64 bits installers had been tried with the same result.

I don’t have more informations at the moment but I can try to get more if needed.

**Comment by vbr** [comment]
Hi,
I can confirm this problem for some of the computers I tried (Win 7); as a fallback, the legacy "xp" version of Otter can be used on these machines.
Could it be a problem or limitation of the current webkit-NG engine? 
If (technically and legally) possible, it would be best to include such files in the distribution of Otter, even in 7z archives etc. in order to support the portable no-install deployment too.
regards,
   vbr

**Comment by mathman12** [comment]
If you would rather not use the "xp" version, then you can download the vc_redist.x64.exe file from
       http://www.microsoft.com/en-us/download/details.aspx?id=48145
After you install this file, the recommended version of Otter for Windows7-64bit should run. However, I found a problem. Specifically, if the zoom level is greater than 100% in any used session file (including the automatic default file), the resulting enlarged display of a webpage is not handled correctly.  Good luck.

**Comment by Emdek** [comment]
There is another solution, we can ship these annoying DLLs (41 files, seriously?...) ourselves:

> Updated September 11, 2015:  App-local deployment of the Universal CRT is supported. 

https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/

**Comment by pierreporte** [comment]
If these DLL are missing, does that mean that Otter is compiled using Visual Studio (I mean, its compiler) for Windows? Why don’t support only one compiler like Clang/LLVM or something else available for all systems? With only one compilation chain supported, we would have more control and the ability to cross-compile Otter.

**Comment by Emdek** [comment]
@pierreporte, currently there is no alternative, some Windows specific features simply require Visual Studio, blame Microsoft. ;-)

**Comment by Dylanmc6** [comment]
Does anyone here know how to fix the "api-ms-win-core DLL files are missing" error in the installation?

**Comment by Dylanmc6** [comment]
> If you would rather not use the "xp" version, then you can download the vc_redist.x64.exe file from http://www.microsoft.com/en-us/download/details.aspx?id=48145 After you install this file, the recommended version of Otter for Windows7-64bit should run. However, I found a problem. Specifically, if the zoom level is greater than 100% in any used session file (including the automatic default file), the resulting enlarged display of a webpage is not handled correctly. Good luck.

Windows 10 said I already had vc_redict.x64 installed.
