### ISSUE TITLE
All keyboard shortcuts disappeared

### ISSUE THREAD

**Issue by pierreporte** [OtterBrowser/otter-browser#1201]
I was browsing the preferences window when I went to the keyboard shortcuts section. Since the list of profiles is empty by default, I added a new one to see how it is. After closing the dialog and removing the unused profile, all keyboard shortcuts did not work anymore (just every single one).

This issues is present since I did this manipulation earlier this week.

**Comment by Emdek** [comment]
Try on clean profile, that list is not empty by default but these defaults were broken several commits ago.

**Comment by pierreporte** [comment]
It solved the problem.
