### ISSUE TITLE
Use system icon when available.

### ISSUE THREAD

**Issue by s8321414** [OtterBrowser/otter-browser#1203]
As title says, please use system icons then they are available.
Ex: I use Breeze series icon set on my GNU/Linux system, but otter browser shows Oxygen icon set for me.

**Comment by Emdek** [comment]
Enable *Interface/UseSystemIconTheme* in about:config, it will be later exposed in Preferences dialog.
It used to be enabled by default but due to Qt bug it caused crashes with some icon themes, see #889.

**Comment by s8321414** [comment]
ah OK, hope we see that option in next release :smiley:

**Comment by nortexoid** [comment]
I just enabled it, restarted, went back here to comment on asking to expose this under "Appearance" in preferences, and my browser kept crashing. I see why the setting is not even exposed in the GUI!

**Comment by Emdek** [comment]
@nortexoid, it should be finally fixed in Qt 5.8, I also have an idea how to workaround it, as long as I'll be able to reproduce it myself.
https://bugreports.qt.io/browse/QTBUG-49061

**Comment by nortexoid** [comment]
A lot of icons are not inherited by the system theme, such as the folder icon on "start page", and I think every icon in the url bar (at least the world and star). Since many are black, it becomes illegible with a dark theme, such as breeze dark in plasma/kde. It would be nice to fully conform to freedesktop.org's standards and to *always* use system icons.

**Comment by Emdek** [comment]
@nortexoid, icon themes simply do not provide all needed icons...
Don't worry about color in default theme, it will be customizable and probably it will default to switch between light and dark variant depending on background color used by style.

**Comment by nortexoid** [comment]
I would guess there are enough icons, though you may have to be creative with filenames. In any case nice to hear that it won't be a problem. Cheers!

**Comment by Emdek** [comment]
@nortexoid, well, it all depends on the actual icon theme, not all have the same icons, AFAIK spec doesn't specify any list of icon names, just how to construct such names.

**Comment by Flashwalker** [comment]
in 2020 it still black icons on dark theme...
