### ISSUE TITLE
[Request] Build in Flash Stopper and Pop-up Blocker

### ISSUE THREAD

**Issue by hakking** [OtterBrowser/otter-browser#1204]
Two Firefox addons I like. Try to have their Otter version, if not here.

Flash Stopper: No video and audio autoplay until you click on the Flash items.

https://addons.mozilla.org/en-US/firefox/addon/flashstopper/

Pop-up Blocker: One click on an icon on the toolbar to switch between blocking all pop-up windows and allowing pop-ups.

https://addons.mozilla.org/en-US/firefox/addon/strict-pop-up-blocker/

**Comment by Emdek** [comment]
First one is material for user script, not full blown extension.
We already have support for user scripts and it should be pretty easy to at least do that for just HTML5 video.
Maybe there already exists proper cross browser user script.

The latter feature is already available, you can configure it globally in Preferences, per host in Website Preferences or per tab using F12 menu.
