### ISSUE TITLE
Doesn't work with banking site First Direct

### ISSUE THREAD

**Issue by mykurtaccount** [OtterBrowser/otter-browser#1208]
(Works in qupzilla, Firefox and Chromnium)

I goto the First Direct homepage (http://www1.firstdirect.com/1/2/) and click on the "Internet Banking" link on the top of the page. I should get a new Window/Tab openning so I can give my logon info. instead I get:-

	
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:wairole="http://www.w3.org/2005/01/wai-rdf/GUIRoleTaxonomy#" xmlns:x2="http://www.w3.org/2002/06/xhtml2" xmlns:aaa="http://www.w3.org/2005/07/aaa">

<head>

<title>first direct internet banking</title>
<meta name="viewport" content="width=750, maximum-scale=1" />
<meta name="summary" content="balances" />
<meta name="description" content="balances" />
<meta name="keywords" content="" />
<meta name="robots" content="noindex, nofollow" /> 
<meta name="name" content="first direct internet banking" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="Content-Style-Type" content="text/css" />
<meta name="rating" content="GENERAL" />

<link href='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/images/apple-touch-icon.png' rel="apple-touch-icon" type="image/png"/>	

<link href='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/css/uics.css' rel="styleSheet" type="text/css" media="all" />

<script src='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/../commonTheme/scripts/common-script-top.js' type="text/javascript"></script>
<script src='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/js/scriptaculous/lib/prototype.js' type="text/javascript"></script>
<script src='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/js/scriptaculous/src/scriptaculous.js' type="text/javascript"></script>
<script src='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/js/uics.js' type="text/javascript"></script>
<script src='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/js/tablekit.js' type="text/javascript"></script>
<script src='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/js/menus.js' type="text/javascript"></script>
<script src='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/js/panels.js' type="text/javascript"></script>
<script src='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/js/form.js' type="text/javascript"></script>
<script src='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/js/resizable.js' type="text/javascript"></script>
<script src='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/js/calendar.js' type="text/javascript"></script>
<script src='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/js/listBuilder.js' type="text/javascript"></script>
<script src='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/js/jhx_action.js' type="text/javascript"></script>
<script src='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/js/jhx_clientValidators.js' type="text/javascript"></script>
<script src='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/js/searchselect.js' type="text/javascript"></script>
<script src='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/fd/js/misc.js' type="text/javascript"></script>
<script src='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/fd/js/firstdirect.js' type="text/javascript"></script>

<link href='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/css/onehsbc/theme.css' rel="styleSheet" type="text/css" media="all" />

<style type="text/css" media="screen" id="no-js">
/*  <![CDATA[  */	
@import url('/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/css/noJs.css');
/*  ]]>  */
</style>
<script type="text/javascript">
      var noJs = $('no-js');
      if(noJs != null){
         noJs.disabled = true;       
         Element.remove(noJs);
      }
</script>

<link href='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/css/onehsbc/layout.css' rel="styleSheet" type="text/css" media="all" />

<link href='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/css/onehsbc/addOn.css' rel="styleSheet" type="text/css" media="all" />

<link href='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/css/onehsbc/handheld.css' rel="styleSheet" type="text/css" media="handheld" />
<link href='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/css/onehsbc/print.css' rel="styleSheet" type="text/css" media="print" />

<link href='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/../commonTheme/css/fdCommon.css' rel="styleSheet" type="text/css" media="all" />
<link href='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/fd/css/firstdirect.css' rel="styleSheet" type="text/css" media="all" />

<script type="text/javascript">
	oldIE = false;
</script>

<script type="text/javascript">
	if (!oldIE) {
		var head = document.head, link = document.createElement('link')
		link.type = 'text/css';
		link.rel = 'stylesheet';
		link.href = '/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/../commonTheme/css/menu_styles.css';
		head.appendChild(link);
	}
</script>	

<script language="javascript" type="text/javascript" src='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/../commonTheme/scripts/webtrends_top_section.js'></script>

<script language="javascript" type="text/javascript">
HSBC.PAGE.seg_1= "Customer";
HSBC.SITE.rgn="Europe";
HSBC.SITE.subrgn="UK";
HSBC.SITE.cnty="United Kingdom";
HSBC.SITE.ent="First Direct";
HSBC.SITE.brand="first direct";
HSBC.DCS.ID="dcse2j1285twkf1mbliutrv4s_2m7b";
HSBC.SITE.language="en";
HSBC.SITE.cam="30";

HSBC.SITE.logon="logins";
HSBC.PAGE.seg_2="General";

HSBC.SITE.custgrp="PFS";
HSBC.SITE.busline="General";
HSBC.SITE.prodline="Other";
HSBC.PAGE.cg_n="IB;PIB";

//split the SiteType and populate site and ibtype
var strSiteType = "IB;PIB";
var arrSiteType = strSiteType.split(";");

HSBC.SITE.site = arrSiteType[0];
HSBC.SITE.ibtype = (arrSiteType.length>1)? arrSiteType[1] :"";
</script>
</head>
<body class="csV-3 cs">

<script language="javascript" type="text/javascript">
	var printing= false;
	var submitAllowed = false;
	var clicksAllowed = false;
	var blnFocus = true;
</script>	

<div class="oh">

<div id="panelModal" class="csOverlayContainer csHide">
<div class="csPanel csPanelOverlay csOverlayShadow">
	<div class="csPanelTopLeft"><div class="csPanelTopRight">
		<div class="csPanelHeading" >
			<div class="csHeadingCol">
				<div class="csNav-x">
				</div>
			</div>
			<h3 class="csPanelToggle" tabindex="0">
				<span class="csPanelOverlayHeading">Default Panel Heading</span>
			</h3>
		</div>
		<div class="csPanelContent">
			<div class="csPanelScroll"></div>
		</div>
	</div>
	</div>
	<div class="csPanelBottomLeft"><div class="csPanelBottomRight"></div></div>
</div>
</div>

<div id="panelOverlayHelp" class="csOverlayContainer csHide">
	<div class="csPanel csPanelEm">
		<div class="csPanelTopLeft"><div class="csPanelTopRight">
			<div class="csPanelHeading">
				<div class="csHeadingCol">
					<div class="csNav-x">
					<ul class="csNavList">
						<li class="csNavItem-0 csNavFirst csNavIcon csIconClose">
							<div class="csNavWrap">
								<a href="#" class="csOverlayClose csClick">Close</a>
							</div>
						</li>
					</ul>
					</div>
				</div>
				<h3 tabindex="0" class="csPanelToggle">
					<span class="csPanelOverlayHeading csHideForSR">Help Panel</span>
				</h3>
			</div>
			<div class="csPanelContent">
				<div class="csPanelScroll"></div>
			</div>		
		</div>
		</div>
		<div class="csPanelBottomLeft"><div class="csPanelBottomRight"></div></div>
	</div>
</div>

<div id="panelOverlay" class="csOverlayContainer csHide">
	<div class="csPanel csPanelOverlay">
		<div class="csPanelTopLeft"><div class="csPanelTopRight">
			<div class="csPanelHeading">
				<div class="csHeadingCol">
					<div class="csNav-x">
					<ul class="csNavList">
						<li class="csNavItem-0 csNavFirst csNavIcon csIconClose">
							<div class="csNavWrap">
								<a href="#" class="csOverlayClose csClick">Close</a>
							</div>
						</li>
					</ul>
					</div>
				</div>
				<h3 tabindex="0" class="csPanelToggle">
					<span class="csPanelOverlayHeading">Default Panel Heading</span>
				</h3>
			</div>
			<div class="csPanelContent">
				<div class="csPanelScroll"></div>
			</div>				
		</div>
		</div>
		<div class="csPanelBottomLeft"><div class="csPanelBottomRight"></div></div>
	</div>
</div>

<div id="panelLightBox" class="csOverlayContainer csHide">
	<div class="csPanel csPanelOverlay csOverlayShadow">
		<div class="csPanelTopLeft">
			<div class="csPanelTopRight">
				<div class="csPanelHeading">
					<div class="csHeadingCol">
						<div class="csNav-x"></div>
					</div>
					<h3 class="csPanelToggle" tabindex="0">
						<span class="csPanelToggleText csShow">Hide</span> 
						<span class="csPanelToggleText csHide">Show</span>
						<span class="csPanelOverlayHeading">Panel</span>
					</h3>
				</div>
				<div class="csPanelContent">
					<div class="csPanelScroll"></div>
				</div>
			</div>
		</div>
		<div class="csPanelBottomLeft">
			<div class="csPanelBottomRight"></div>
		</div>
	</div>
</div>

<div class="csClick csFader csHide" id="csFader"></div>

<div id="csContainer" class=" csFixedLayout csCenterLayout">

	<div id="csContainerWrap">	
	
		<div id="csContainerCalendar">
				<div class="csPanelCover"></div>
				<div id="csPanelCalendar" class="csPanelCalendar"></div>
				<div id="csCalendarChevron" class="csChevron csChevronTop"></div>
		</div>
	
		<div id="csSearchNSelect" class="csNav-x csMenu-x csClick csAccordian csSearchNSelect">
		<div class="csPanelCover"></div>
			<ul class="csNavList">
				<li class="csNavToggle-0 csNavFirst csMenuContextual csNavShow" >
					<div id="csSearchNSelectContent" class="csNavContent">
						<div class="csPanel">
							<div class="csPanelTopLeft"><div class="csPanelTopRight">
								<div class="csPanelContent"><div id="csSearchNSelectScroll" class="csPanelScroll"></div></div>
							</div></div>
							<div class="csPanelBottomLeft">
								<div class="csPanelBottomRight"></div>
							</div>
						</div>
					</div>
				</li>
			</ul>
		</div>
	
		<div id="csMenuContextual" class="csNav-x csMenu-x csClick csAccordian csMenuContextual">
		<div class="csPanelCover"></div>
			<ul class="csNavList">
				<li class="csNavToggle-0 csNavFirst csMenuContextual csNavShow">		
					<div id="csMenuContextualContent" class="csNavContent">				
						<div class="csPanel">
							<div class="csPanelTopLeft"><div class="csPanelTopRight">
								<div class="csPanelContent"><div id="csMenuContextualScroll" class="csPanelScroll"></div></div>
							</div></div>
							<div class="csPanelBottomLeft">
								<div class="csPanelBottomRight"></div>
							</div>
						</div>
					</div>
				</li>
			</ul>
		</div>
	
	
		<div id="csPanelHint">
			<div id="csPanelHintWrap">
				<div class="csPanel csPanelHint">
					<div class="csPanelTopLeft">
						<div class="csPanelTopRight">
							<div class="csPanelContent">
								<div id="csPanelHintScroll" class="csPanelScroll"></div>
							</div>
						</div>
					</div>
					<div class="csPanelBottomLeft">
						<div class="csPanelBottomRight"></div>
					</div>
					<div id="csHintChevron" class="csChevron csChevronTop"></div>
				</div>
			</div>
		</div>

		<div class="csColumns">
			<div class="csColumnsWrap">
				
				<div id="csMain">
					

				
					
<div class="fdMenuSeparator"></div>
<div id="fdFooterDiv" class="footerContainer">
	<div class="footerLinks">	
		<ul>
		  <li><a href="javascript:void(0);" onclick="javascript:smGet('/1/3/ourDetails?BlitzToken=true');return false;">Contact us</a></li>
		  <li><a href="javascript:void(0);" onclick="javascript:smGet('/1/3/ourProductsAndServices?BlitzToken=true');return false;">Products &amp; services</a></li>
		  <li><a href="javascript:void(0);" onclick="javascript:smGet('/1/3/ssmCompose?BlitzToken=true&subject=mgm');return false;">Recommend a friend</a></li>
		  <li><a href="javascript:void(0);" onclick="javascript:smGet('/1/3/mastheadMenuSecurity?BlitzToken=true');return false;">Security</a></li>
		  <li><a href="javascript:void(0);" onclick="javascript:smGet('/1/3/mastheadMenuRates?BlitzToken=true');return false;">Rates</a></li>
		  <li><a href="javascript:void(0);" onclick="javascript:smGet('/1/3/mastheadMenuLegals?BlitzToken=true');return false;">Legals</a></li>
		</ul>
	</div>
	<div class="footerText">
		<p><strong>first direct</strong> is a division of HSBC Bank plc. &copy; HSBC Bank plc 2008. All Rights Reserved. <span class="italicText">Member</span> <strong><span class="hsbcLogoText">HSBC</span></strong> <img src='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/images/hsbcmember_footer.gif' width="20" height="14" alt="" /> <span class="italicText">Group</span>.
		<br />Because we want to make sure we're doing a good job, we may monitor or record our calls. We hope you don't mind.</p>
	</div>
</div>
				</div> 
				
				
			
			</div>
		</div>
		
	</div>

 </div>
</div>

<script type="text/javascript" language="javascript">
	allowClicks();
</script>

<script language="Javascript" type="text/javascript">
</script>
<script language="Javascript1.1" type="text/javascript">

</script>
<script language="Javascript1.2" type="text/javascript">
</script>
<script language="Javascript1.3" type="text/javascript">
</script>
<script language="Javascript1.4" type="text/javascript">
</script>
<script language="Javascript1.5" type="text/javascript">
</script>

<noscript>
<img name="dcsimg" width="1" height="1" alt="" border="0" src="https://www1.member-hsbc-group.com/dcse2j1285twkf1mbliutrv4s_2m7b/njs.gif?dcsuri=/nojavascript&amp;WT.js=No" />
</noscript>
<script language="javascript" type="text/javascript" src='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/../commonTheme/scripts/common-script.js'></script>
<script language="javascript" type="text/javascript" src='/htse-fsdt-themeskins-servlet/themes/html/firstdirect_HSBCPortal_theme_oh_fixed/../commonTheme/scripts/webtrends_bottom_section.js'></script>

</body>
</html>

**Comment by mytskine** [comment]
This site explicitly tells the browser that the page is not HTML. The HTTP header contains
`Content-Type:text/plain` even though it serves an XHTML content.

I suppose other browsers can work around broken sites like this by guessing the content's type and ignoring the header, but it also has drawbacks. It would be better to fix the web site.

**Comment by mykurtaccount** [comment]
I'm no website expert so please excuse me. In Firefox I clicked on the same link and then viewed source and no where could I find "text/plain"

I tried a search in Otter as well and again no where do I find "text/plain".

**Comment by pierreporte** [comment]
@mykurtaccount You won’t see it in the source. When a file is downloaded through the Internet, there is two parts, the headers (informations on how to manage the file) and the content itself. Think of an envelope containing a letter. The source code is contained in the letter while the header is what is written on the envelope.

**Comment by mykurtaccount** [comment]
Mystery deepens. If I delete all the conf files:-

./.cache/Otter ./.config/otter ./.config/otter/otter.conf ./.Otter

The website works fine. I haven't been able to pin down what setting kills it yet as it doesn't seem to be consistent

**Comment by Emdek** [comment]
@mykurtaccount, I couldn't reproduce it with either revived or legacy QtWebKit, although I recall similar issue (maybe even the same domain) with legacy QtWebKit from the past.
You can view headers using Inspector, for me it currently shows text/html.
Anyway, such sort of issue would be upstream bug anyway...

**Comment by mytskine** [comment]
@mykurtaccount Your bug ticket is perfectly valid, please excuse me if my
first comment looked like a rebuke (and English is not my native
language, which does not help). I was just pointing the cause of the
problem, to save a bit of Otter developers' time.

As Thomas wrote, the "content-type" is not part of the text displayed, it
is in the HTTP header that comes before the HTTP content. In Firefox, you
can toggle the developer tools with F12, then go to the network tab,
reload the page, and click on the first transfer: it will display the HTTP
request headers (what your browser requested) and the HTTP response
headers (what the server answered). On a valid HTML page, there should be
a line like:   Content-Type: "text/html;charset=UTF-8".

HTTP headers can be seen in Otter too, but you first need to right-click
within the page and select "Inspect element…" to display the developer
tools.
