### ISSUE TITLE
Cannot load any UserJavaScript (addons)

### ISSUE THREAD

**Issue by mytskine** [OtterBrowser/otter-browser#1210]
According to #336, Otter beta11 supports UserJavaScript, yet I could not make any script load. Tested on two Debian systems with Otter beta 11 and the latest Git version.

Here is  a sample script I loaded.
```
// ==UserScript==
// @include https://github.com/*
// @include http://github.com/*
// ==/UserScript==

console.log("github.user.js started");
document.body.setAttribute("style", "background-color: #99FF99;");
```
I added various scripts through the *Addons* page. There is nothing wrong with the JSON file `~/.config/otter/scripts/scripts.json` and the scripts directories.

There is no visible consequence of declaring these scripts. Nothing on the pages that should be affected. Nothing in the global console. Nothing in the developer tools (console, ressources, sources), though I don't know if it's supposed to appear under the (re)sources tabs (in my opinion, it should, or debuging user scripts will be impossible).

**Comment by Emdek** [comment]
@mytskine, have you enabled it after adding?
Works fine here.

**Comment by mytskine** [comment]
I thought it was enabled by default. The config file contained:
```
% cat ~/.config/otter/scripts/scripts.json 
{
    "github.user": {
        "isEnabled": true
    }, …
```

BTW, I thought it was unrelated so I didn't mention it, but after some time Otter looses these scripts. Without any special action, not even restarting the browser, my `scripts.json` becomes `{}`. The *Addon* page becomes empty. The scripts are still there (e.g. `~/.config/otter/scripts/github/github.user.js` still exists), so I get an error if I try to add them again through the *Addon* page.

**Comment by uahim** [comment]
mytskines example script does work here as well as github.js, judging from his https://github.com/OtterBrowser/otter-browser/issues/1211 issue the dot was the problem.

@Emdek is there a way to reload edited/changed scripts other than restaring Otter itself?
I assumed ticking the checkbox in about:addons would do that, but obviously I'm wrong.

**Comment by mytskine** [comment]
@uahim Reloading user scripts seems totally unrelated. This issue is about a single bug that now has a suggested patch.
If you want to open another issure, I read the code yesterday, and IIRC the only way to update a script without restarting Otter is to add another "addon". Then every script will be reloaded (JS files read anew, and status "enabled|disabled" applied). There is no way to remove a script other than modifying the config directory. The easiest fix would be to create a button "Apply changes and reload scripts" on the "Addons" page.

**Comment by Emdek** [comment]
@mytskine, perhaps clearing of that file was caused by this dot issue, since it failed to find that script it got removed from the list.

@uahim, we could add explicit action to reload script or consider use of `QFileSystemWatcher` to detect changes, but the latter would be more complex.

**Comment by uahim** [comment]
@mytskine yes, you are right of course, it's just that it was such a small issue I though I'd mention here rather than open an extra 'issue' for it.

@Emdek excellent, a simple action/button would be sufficient :)
