### ISSUE TITLE
occasional errors while downloading from links containig a tab character

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#1212]
Hi,
I'd like to report a possible cornercase-problem, which causes occasional errors while downloading the linked data in Otter.
The problem arises within a webmail client - with somehow mangled mails with atttachments containing a tab character in the file label.
The webmail page shows a link to the attached file like "somefile.p df" (i.e. with a tab character in the extension p<tab>df )
In the page source, the link attribute "src" doesn't contain an actual file path, just a call with id to be served from the php code.
After clicking on such link, the file type is not recognised, it can't be saved to disk either - the suggested filename is invalid (the extension contains this whitespace), and even after changing it the resulting file on disk is empty and a download error is shown in the download dialog.
I am not sure, whether this could possibly be related to a previously resolved issue with links containing tab:
https://github.com/OtterBrowser/otter-browser/issues/1031

(Using Win 7 64bit, Otter, win64, weekly147)

I realise, that these are non-standard situations, but e.g. opera 12 can handle these links correctly.

Thanks and regards,
                        vbr

**Comment by Chocimier** [comment]
OK, how can we reproduce that bug?

**Comment by vbr** [comment]
Hi,
unfortunately, I am not sure, how to reproduce this outside of the authentised webmail (some sample links I tried on a separate webpage are working ok).
It might be that there are some other problematic data being sent from the server in such cases (possibly some file headers?) but I am not sure, how to simulate it.
In case, nothing can be found (e.g. in the code handling the file paths etc.), this issue can be closed as irrelevant.
          vbr

**Comment by Emdek** [comment]
@vbr, could you perhaps provide us at least list of headers sent by such page (at least *Content-Disposition*)?
Then we could create local test case.

**Comment by vbr** [comment]
Hi,
sorry for the rather deficient information,
the only relevant info in headers, that I can spot, is the presence of tab characters even in these headers,
e.g. (as shown in Opera 44):
Cache-Control:cache
Connection:Keep-Alive
Content-Disposition:inline; filename="SZZ 2017 01 na n%C3%A1st%C4%9Bnku.	xlsx"
Content-Type:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet; name="SZZ 2017 01 na n%C3%A1st%C4%9Bnku.	xlsx"
Date:Tue, 31 Jan 2017 10:33:04 GMT
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Keep-Alive:timeout=5, max=100

The escaped accented characters in the file names don't seem to cause problems, but the tab characters do.
The file extension is in both "Content-Disposition:inline; filename" and "Content-Type: ... name"
.<tab>xlsx

I recognise, that this is a clearly buggy server behaviour (likely in connection with some non-standard Gmail input attachment on the sender-side).
However, other browsers I tried can somehow cope with it - at least save the file and let it rename manually - only Opera 12 can even save or display such attached file directly - while discarding the tab from the file name - the headers in Opera 12 show the <tab> in file extension too, only the diacritics is (mis)encoded differently:
Content-Disposition: attachment; filename="SZZ 2017 01 na nÃ¡stÄnku.	xlsx"
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: application/octet-stream; name="SZZ 2017 01 na nÃ¡stÄnku.	xlsx"

In Otter, I can adapt the filename to be saved, however, the download of such files stalls at 0% and the saved file is empty.

Sorry for an partly off topic follow-up question - can the page headers be displayed in Otter? - I could'nt find it in "page inspection".

thanks and regards
   vbr

**Comment by Emdek** [comment]
@vbr, this issue is now at least partially fixed, I need to run some extra tests to confirm if it is completely fixed.
About headers, we have API for exposing them for main resource for years now, planned to be exposed as part of page information panel.

**Comment by Emdek** [comment]
I've prepared test case based on your data, it seems that we handle it way better than Firefox (it says that's HTML file and shows gibberish for file name)...
http://otter-browser.org/tmp/tests/content-disposition-filename-2/
It works just fine for me, I'm just unsure what to do with that whitespace, preserve or drop it from suggested file name when saving.

**Comment by Emdek** [comment]
I guess that we should keep it as, only clean it up before using fallback check (which is not used by this test case anyway).
