### ISSUE TITLE
Expose actions using jump lists (or similar technologies) 

### ISSUE THREAD

**Issue by pierreporte** [OtterBrowser/otter-browser#1215]
Modern systems provide nice ways to integrate programs and expose features in the desktop interface, and that Otter doesn’t seem to use them. Instead, there is the tray icon, like Opera 12 did. For Opera 12, it was understandable since it already had a 20-year old history when the “original” branch was discontinued. I came up with the idea that it would be a good idea to embrace these modern practices. A great advantage is that the behaviour of the tray icon could be mimic and extended. I’ll now try to expose the idea in detail.

In Windows, since Seven, the icons in the taskbar can have a custom menu when right-clicked:

![](http://logintips.com/hotmail-sign-in/i/add-hotmail-outlook-com-to-windows-taskbar-start-menu.png)

It’s called “jumplistst”. This example is from Outlook but Internet Explorer has it as well, and I believe Firefox uses it too. In this menu, you can expose all features already presented in the tray icon. Plus, if the program is pinned, there is still the menu. With the tray icon, you have to start Otter to have access to it. Good news, Qt 5 is compatible with jumplists: http://doc.qt.io/qt-5/qtwinextras-overview.html.

In Unity and Gnome Shell, there is something similar:

![687474703a2f2f776f726c646f66676e6f6d652e6f72672f75706c6f6164732f323031332f30332f756e697479312e706e67](https://cloud.githubusercontent.com/assets/2029853/20362874/44ab0656-ac3d-11e6-987e-a54025c4732e.png)

![capture d ecran_2016-11-16_20-36-53](https://cloud.githubusercontent.com/assets/2029853/20362780/0f215846-ac3d-11e6-88d0-23a9c7aa1e99.png)

Like in Windows, you have access to the menu even without starting the program.

In Plasma 5, there is also a similar mechanism:

![](http://i.imgur.com/LyiKSRn.png)

For Plasma, [it is made by editing the .desktop file](https://forum.kde.org/viewtopic.php?f=289&t=136615). For Unity and Gnome, it may be the same. The problem is that it doesn’t seem possible to do anything that is not done with commands. I read recently that there is an kind of API for interacting with GUI with commands, but I can’t find it for now.

In OSX, it is called “doc tile menus”:

![](http://cdn.osxdaily.com/wp-content/uploads/2011/04/recent-items-dock-mac.jpg)

For systems that don’t support these features, the systray button could be used as fallback. “Nice” features would be defaults in compatible systems but there would be an option to enable it.

**Comment by bajasoft** [comment]
I'll take care of the Windows part.

**Comment by Emdek** [comment]
I was investigating `QWinJumpList` class in the past already and the main issue was that some actions will require additions to our command line and handling of parameters.
AFAIK the same applies to at least fd.o compatible desktop environments and in case of OS X it's most likely defined in *.plist* file.

Surely we need to skip there action to hide all windows (this makes sense only in case of tray icon) and I'm not sure if it is common to include separate Exit action there (which makes sense only when using multiple main windows) and might be confusing to some users.

I'm not yet sure about where it should be defined, it doesn't make sense to force translators to translate the same actions three times (four including sources) so perhaps it would be best to use only *.desktop* file and parse it in case of Windows (`QSettings` should be enough) and generate *.plist* from it in case of OS X.

**Comment by Emdek** [comment]
Apparently, as usual, it is overcomplicated in case of OS X, static version requires extra nib file and I don't even want to look for details how are they handling translations for these...
At least it seems that there might be useful Qt API for setting custom menu, `QMenu::setAsDockMenu()` (it really should belong to Qt Mac Extras...).

**Comment by Zero3K** [comment]
The items in the jump list shown in Windows 10 aren't working for me (they open a new process instead of using the current one).

**Comment by Emdek** [comment]
@Zero3K, it's #1096 again.
