### ISSUE TITLE
"Create Search" does not add "{searchTerms}" when used on a button

### ISSUE THREAD

**Issue by midluk** [OtterBrowser/otter-browser#1217]
When using "Create Search" on an input field on a web page, a proper search is created.
When doing the same with the corresponding search button on a web page, the search is created, but the "{searchTerms}" are omitted.

**Comment by Emdek** [comment]
@midluk, I guess that in that case we could go for first text field found in that form, perhaps also adding some warning when attempting to save search engine without it.

**Comment by pierreporte** [comment]
@Emdek, in HTML5, there is a special [input element for search field](https://www.w3.org/TR/html-markup/input.search.html), `<input type="search">`. It would be better to take this into account for a better guess.

**Comment by midluk** [comment]
I guess that multiple search buttons for the same text input are more common than multiple text inputs for the same search button.
For example on the top of http://rpmfusion.org/ there are two different search buttons for the same text input. This situation is currently not handled properly at all. Creating a search with a button does not add the search terms and creating a search with the text input field does not add either button.

**Comment by midluk** [comment]
This is not fixed properly.
On http://rpmfusion.org/ it now adds the "{searchTerms}" to some hidden input (that happens to be first in the form) instead of the actual text input field.
