### ISSUE TITLE
Crash with tabs

### ISSUE THREAD

**Issue by VSHY** [OtterBrowser/otter-browser#1218]
STR:
1. Open any site.
2. Click "New Tab" button (sometimes a new tab floats away behind the first tab?!) repeatedly.
3. Close opened tabs.
Repeat the steps 2, 3 - the crash happens:

PROBLEM_EVENT_NAME:	APPCRASH
PROCESS_NAME:	otter-browser.exe
APP_VERSION:	0.9.1.1
APP_TIME_STAMP:	582c3680
FAILURE_IMAGE_NAME:	Qt5Widgets.dll
FAILURE_IMAGE_VERSION:	5.7.0.0
FAILURE_IMAGE_TIME_STAMP:	574747c1
ExceptionCode:	c0000005
ExceptionOffset:	000000000004df5d

Details: [tabs_crash.txt](https://github.com/OtterBrowser/otter-browser/files/613878/tabs_crash.txt)

Environment: Win7 x64, Otter 0.9.12 64-bit weekly 150.

**Comment by Zero3K** [comment]
Please try the latest weekly to see if the issue has been fixed in it.

**Comment by VSHY** [comment]
It is not reproduced now.
