### ISSUE TITLE
Wrapping option for Toolbars

### ISSUE THREAD

**Issue by DI555** [OtterBrowser/otter-browser#1219]
Would be great to be in Otter as in good-old Opera (and a little more)   -   "Wrapping" option for all Toolbars(in "...Bar-Configure"):
No wrapping, Wrap to multiple lines (and number of lines), Show extender menu(movable-sliding).

**Comment by Emdek** [comment]
Simply use two or more toolbars (you can as many of them as you want).
It's way too many work to add feature that can be achieved using existing infrastructure...
