### ISSUE TITLE
All tab disappear after turning off the thumbnails

### ISSUE THREAD

**Issue by pierreporte** [OtterBrowser/otter-browser#1222]
I just compiled version 74231feb2787f73908fa38ec180aa0128ae6c8c7. When I enable the thumbnails in the tabs and them disable them, there is no tab shown in the tab bar:

![s lection_543](https://cloud.githubusercontent.com/assets/2029853/20927846/91596f02-bbc3-11e6-9631-2bc546097df9.png)

It happens with any number of tabs. However, the opened tabs still exist and the display returns to its normal state if you switch tabs (with <kbd>Ctrl</kbd><kbd>T</kbd>) or if you create a new tab by clicking on the button.

**Comment by Emdek** [comment]
I'm unable to reproduce it with current master (but for sure it existed for some time).
