### ISSUE TITLE
[Feature request] Custom user agent string per site or globally

### ISSUE THREAD

**Issue by uahim** [OtterBrowser/otter-browser#1223]
I'm aware this has very low priority as Otter already offers an array of UA to choose from, but it would come very handy if the user could define his very own user agent string either per site - which of course would be the preferred way - or globally (as in Opera up to 12 via `opera:config#UserPrefs|CustomUser-Agent`).

**Comment by Emdek** [comment]
You can add custom User Agents using Preferences -> Advanced -> Network.

**Comment by uahim** [comment]
@Emdek whoops, I swear I didn't see Preferences -> Advanced -> Network for some reason. thank you.
