### ISSUE TITLE
Issues with Fullscreen Mode on Youtube, etc.

### ISSUE THREAD

**Issue by Zero3K** [OtterBrowser/otter-browser#1226]
Its slow on entering and exiting it, shows the title bar for a few seconds, and shows a frame from the current/previously viewed video. Please fix them soon. Thanks in advance.

**Comment by D1mon** [comment]
![1](https://cloud.githubusercontent.com/assets/3872485/21595760/6e8e25fa-d142-11e6-8601-aa9e43ab4ec2.png)
link to: [link](https://support.google.com/youtube/answer/6276924)

**Comment by Zero3K** [comment]
Are you using Beta 12 on Windows?

**Comment by D1mon** [comment]
Arch linux x64 - otter-browser 0.9.12-1

**Comment by VSHY** [comment]
Videos in full screen mode goes very slowly! :(
Win7 x64, Otter x64.

**Comment by Emdek** [comment]
Superseded by #1225.

@D1mon, you need revived QtWebkit to get fullscreen support, AFAIK it entered extras repository as *qtwebkit-ng*.
