### ISSUE TITLE
Cannot build Weekly 156

### ISSUE THREAD

**Issue by pavbaranov** [OtterBrowser/otter-browser#1228]
When I try to build weekly 156 version, I've recived this error: 

Scanning dependencies of target otter-browser
[ 24%] Building CXX object CMakeFiles/otter-browser.dir/qrc_resources.cpp.o
c++: error: weekly: No such file or directory
c++: fatal error: no input files
compilation terminated.
make[2]: *** [CMakeFiles/otter-browser.dir/build.make:441: CMakeFiles/otter-browser.dir/qrc_resources.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/otter-browser.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

Full build log:
[otter-browser-dev-0.9.12.dev156-1-x86_64-build.txt](https://github.com/OtterBrowser/otter-browser/files/678457/otter-browser-dev-0.9.12.dev156-1-x86_64-build.txt)

GIT version is built with success (I've tried yesterday night).

System: up-to-date 64-bit Arch Linux

**Comment by Emdek** [comment]
@pavbaranov, you need to replace line 19. in `CMakeLists.txt`:

``add_definitions(-DOTTER_VERSION_CONTEXT=" weekly 156")``

I'm uploading updated archives right now.
