### ISSUE TITLE
Shift-Arrow link navigation

### ISSUE THREAD

**Issue by gjedeer** [OtterBrowser/otter-browser#1231]
I could not find a setting or an entry in Keyboard Shortcuts to make Shift+arrow keys navigate between links, like classic Opera did. Is it possible to add this feature?

**Comment by mariokamenjak** [comment]
I would love to have it one day as well.

**Comment by ersi-dnd** [comment]
Tab does something like this, but yes, could be better. New Opera and Vivaldi have created a flashy version of links navigation.

**Comment by Emdek** [comment]
Duplicate of #119.
