### ISSUE TITLE
Mouse wheel not working after automatic scroll

### ISSUE THREAD

**Issue by myier** [OtterBrowser/otter-browser#1234]
1. Use middle click to start scrolling, move the mouse up or down
2. Stop the automatic scrolling by clicking on the page, do not move the mouse
3. The wheel does not work unless you move the mouse

(tested on windows, with all versions ever)

**Comment by pierreporte** [comment]
I also have the bug under Archlinux with version 48caf4595134cb7ee1029ad97f634172f7f5278f.
