### ISSUE TITLE
ipfs support?

### ISSUE THREAD

**Issue by mariokamenjak** [OtterBrowser/otter-browser#1237]
IPFS is the new hot and upcoming protocol that hopes to replace the aging http.

https://www.youtube.com/watch?v=cU-n_m-snxQ

https://github.com/ipfs/ipfs

And an experimental browser, that you could use as a reference: 
https://github.com/beakerbrowser/beaker

If it all works out it could be Otters killer feature... But I do understand if you don't want Otter to grow in scope ATM.

**Comment by Emdek** [comment]
We could consider it if it would be more widespread, right now it would way too much work for supporting such curiosity.
