### ISSUE TITLE
Opera 12.15 source code

### ISSUE THREAD

**Issue by DebugReport** [OtterBrowser/otter-browser#1238]
What do you think about this?
https://github.com/prestocore/browser

**Comment by Frenzie** [comment]
My first thought was that it must be fake, but on closer inspection it looks real. Some disgruntled former employee?

**Comment by pierreporte** [comment]
In the eventuality that it is not a fake, would the Presto engine be of any use for us?

**Comment by resetnow** [comment]
Definitely not a fake. Damn, that's pretty much the whole thing! With distribution code and everything.

**Comment by pierreporte** [comment]
The repository was last edited about a year ago, they took their time. The date was available on the user’s page, not on the repository itself.

**Comment by DebugReport** [comment]
Mirror - https://bitbucket.org/prestocore-fan/presto/

**Comment by Frenzie** [comment]
@resetnow "*likely* illegal"? LOL

Yeah, there's nothing here for Otter except maybe some renewed sadness at Opera's new course.

**Comment by Emdek** [comment]
@pierreporte, nah, no use, too outdated.

**Comment by sadjehwty** [comment]
mirror: https://notabug.org/141243/presto

**Comment by Zero3K** [comment]
1. Here's a link to a newer custom made build:

https://u.teknik.io/wLUu9.zip

2. I made a Discord Server for it. You can join it by going to https://discord.gg/WV9s9uw.

**Comment by mrnhmath** [comment]
RIP Opera and Presto.
