### ISSUE TITLE
Feature request: True detach

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#1240]
It's an action to detach a tab from the main window. "True detach" means really just "detach" as distinguished from "new window".

Somewhere around Opera 9.2~5 the drag-tab-to-desktop functionality was changed. Prior to it, the function was Detach. After that, it became indistinguishable from New Window.

In Opera INI terminology, the action was called "Detach page". In Opera's menu.ini on Windows, the menu item was invisible, because there was "Platform Unix-QNX" written in front of the relevant line. Remove that and the function becomes visible. (Applies to Opera version 8-early 9 on Windows.)

THE MAIN IDEA OF THE FEATURE

According to my memory (and recent very limited testing), the action did the same thing as "New window", except:
- No menubar
- No tabbar
- No statusbar
- No panels (sidebar)

Those are the toolbars where you can expect system menus and buttons. So the main idea is that the user sees in a detached window only buttons/menus applicable to that particular window, while the main window has buttons/menus applicable to the entire app. See the illustration.
![detach](https://cloud.githubusercontent.com/assets/6865273/22113528/3d22acd6-de6f-11e6-9521-2eebc6a29068.png)

WHY OPERA CHANGED/REMOVED THE FEATURE?

When "Continue from last time" was ON (which it was by default after a fresh installation), noobs encountered the following problem: 

1. Close the main window
2. Close the detached window(s)
Result: Next launch of Opera opens only the last closed (menu-, tab-, status-, and sidebarless!) detached window. Bummer.

To avoid this, Opera made detached windows have all the main-window toolbars that were formerly missing from detached windows by design. The result was that Detach became the same thing as New Window. An undesired behaviour that followed was this: 

1. Have several windows open
2. Open the panel (sidebar) on one of the windows
Result: The panel opens on all windows.

HOW OPERA SHOULD HAVE SOLVED THE NOOB PROBLEM

To avoid the noob problem, (one of) the right solution(s) would have been for the session algorithm (or   whatever you call it) to give priority to the main window.

1. The session algorithm should comprehend the distinction between main window (with all the toolbars) and detached windows.
2. A main window should always open up at every launch, i.e. even if a single detached window is closed last, next "Continue from last time" launches the (last closed) detached window only after the (last closed) main window has been automatically identified and launched first.

To put it another way:

- If the user selects the action New Window, it means a new main window (with menu-, tab-, status-, and sidebar).
- If the user selects the action Detach, it means a detached window (without menu-, tab-, status-, and sidebar).
- The session algorithm should recognise the difference between the two kinds of windows and always launch a main window when the app is started.

WHY TRUE DETACH WAS A TOTALLY AWESOME KILLER MUST-HAVE FEATURE THAT SHOULD BE REPLICATED IN OTTER

Basically, screen real-estate economy. I personally used a 800x600 screen long into the 21st century and it made quite a difference whether I was browsing with IE (which tended to pop up ad banners as additional windows, messing up the desktop) + composing an e-mail in OE = those two things just didn't fit on the same screen side by side,

or having a webpage open in Opera + an e-mail composer window detached from it = it was possible to type while at the same time checking the webpage. 

Lately browser (and other app) makers have re-discovered the value of having a minimal window running in a corner. For example the [new (Silk Road Gold Brick) Opera has innovated the "video popout"](http://www.opera.com/blogs/desktop/2016/04/opera-beta-update-video-pop/) 

http://www-static-blogs.operacdn.com/multi/wp-content/uploads/sites/3/2016/04/sf-videocast-gif.gif

Looks like a cool economical pleasant item for reference/distraction? Yes, except that Yt app on Android does the same thing, so it's not really an innovation, and old Opera was able to do the same with absolutely any window whatsoever, not just videos - by Detach.

Even these days with FullHD screens (and bigger/denser), I'm sure power users would welcome and appreciate apps that honour screen real-estate economy.

**Comment by ersi-dnd** [comment]
In the illustration, also observe the Windows Panel (sidebar). It displays a nested tree, informing about all open windows:

- With a little triangle in front of it, that's the main window
- Indented under the main window, those are the tabs within the main window
- Aflush with the main window, but no triangle in front of them, those are detached windows.

The session algorithm should use a hierarchy/taxonomy for the items and identify the items in the Windows sidebar based on it.

Also, it would be totally fantastic to have drag-and-drop enabled in the Windows sidebar (Opera had it):

- In the sidebar, drag a detached item under the main window and drop it among tabs = it becomes a tab.
- Drag a tab from under the main window and drop it among detached windows = it becomes detached

Additionally, other main windows should have triangles of their own. This kind of Windows panel would be a great helper for session management and the user could enhance it with a session management button/menu.

**Comment by ersi-dnd** [comment]
An alternate solution to the noob problem referred to in the first post: 

If a detached window (i.e. no menu-, tab-, status-, and sidebar) is closed last, at next launch show the startup dialog regardless of the startup setting of the browser.

**Comment by Emdek** [comment]
@ersi-dnd, maybe, but this one is actually harder to implement.

**Comment by ersi-dnd** [comment]
I'm missing True Detach more and more. Lately it occurred to me that it's cool to keep a chat window open in a separate browser window without any toolbars.

**Comment by Emdek** [comment]
@ersi-dnd, I'm still considering one detail, if we should allow independent toolbar locations per main window too (bot area and order), not just visibility state.
I guess that yes, but it makes it a bit more complex.

**Comment by ersi-dnd** [comment]
Unfortunately I cannot figure out what it means to have toolbar locations per main window and what difference would it make. The relevance that I can think of is the thing that Opera noobs complained about: 

1. When the user had "Continue from last time" turned on and 
2. There was a true-detached window open and 
3. The user closed windows one by one and 
4. The true-detached window was closed last, then 
5. At the next launch only the true-detached (toolbarless) window opened.

So, toolbar locations? Visibility state? Per main window? The answer lies in what difference it makes from the user perspective, such as opening and closing the app with different options.

**Comment by Emdek** [comment]
@ersi-dnd, it means that you could for example have tab bar above page in one main window and under page in another.
Right now locations are synchronized.

**Comment by ersi-dnd** [comment]
Do you mean:
True Detach detaches a tab into a new window without toolbars, but then toolbars can be enabled in that new window

?

This would obviously be a yes. But I am not sure if I am understanding right.

Another thing: When implementing detaching, it's a good idea to think about re-attaching also. Right now I don't see any mechanism to r-eattach a window into another as tab(s). The most convenient user interface for that would be drag-and-drop in Windows Panel.

**Comment by Emdek** [comment]
@ersi-dnd, yes, that requires independent visibility states, separate locations is one step further, but it should be decided now, as it affects data structures.

About reattaching, yeah, that is planned, but until then it would be still doable by showing tab bar and dragging tab to tab bar from another main window.

**Comment by ersi-dnd** [comment]
Well, these technical terms are over my head. I have no idea how "separate locations" and "independent visibility states" relate to anything. I only know that True Detach is a good idea. Also Reattach is a good idea. Also toggling toolbars is a good feature - toggling all toolbars both individually and together in whatever window. 

Moreover, also Links list/manager is a good idea. Old Opera had it. And external editor in textarea is nice, even though old Opera didn't have it. I regret that I am unable to build any of these features myself.

**Comment by Frenzie** [comment]
In lieu of a super useful links panel it should be fairly trivial to use some version of Snap Links as a UserJS.

http://userscripts-mirror.org/scripts/show/77678 (that one has some Opera-specific stuff though)

**Comment by ersi-dnd** [comment]
@Emdek /it means that you could for example have tab bar above page in one main window and under page in another./

Ah, now I get it. So one (main) window would have a tabbar above the webpage and another would have it under the webpage? This raises plenty of questions concerning a possible user case:

-How would the user achieve this configuration with tabbars in different places in different windows? By drag-and-drop?
-Would both windows be main windows or one detached from the other?
-Should the configuration be preservable across restarts? With sessions for example?

If to do this, all these are questions to consider, I assume, so that the user scenario would be sensible and nothing would clash.

Meanwhile, to visualise True Detach, imagine the following. Otter can Tile the tabs. In old Opera, a detached tab looked exactly like those tabs inside the main window, except that it was moved outside the main window. As far as I have been able to verify, the detached window acquired window manager controls like titlebar and borders, but nothing else. Very very old Opera (like versions 5-6) had the downloads manager open outside the main window by default like this, in a true detach manner, and it felt completely natural to me and I got used to detaching other tabs in the similar way. Until some later version destroyed this.
![ekraanipilt_2017-09-06_16-56-08](https://user-images.githubusercontent.com/6865273/30116293-d40f7d3e-9325-11e7-9ee6-1ec543595917.png)

**Comment by Emdek** [comment]
> How would the user achieve this configuration with tabbars in different places in different windows? By drag-and-drop?

Yes, drag and drop, but without applying these changes in other main windows.

> Would both windows be main windows or one detached from the other?

All will be main windows, "true detach" would simply mean hiding all toolbars in such main window.

> Should the configuration be preservable across restarts? With sessions for example?

Yes, this is the point of this discussion, to decide what should be preserved, to design the ideal data structure for sessions. ;-)

Detached tab has to use system window decorations, at least for now, we could consider use of the same drawing as for MDI once we will have support for fake window decorations, but that would make these windows less generic.

Perhaps we should allow to mark toolbar as toggle so we could use it for Address Bar, to make it a bit easier to restore toolbars when session would be restored with just such main window.
Maybe we should show some warning with description what to do when opening such main window too, in fashion similar to what kwin does when going fullscreen or removing decorations using context menu.

I don't like idea of completely hiding of single main windows, it's easy way to lost track of them (already easy to do when hiding them all). ;-)

**Comment by Frenzie** [comment]
Opera had native window decorations on true detach and I liked it. :-P

**Comment by Emdek** [comment]
There is one more aspect, backwards compatibility, so probably it should work like this when restoring:
 1. we take global toolbar settings (normal visibility, location and row);
 2. we take toolbars state preserved in session (if present, existing sessions won't have it);
 3. we apply state stored in session on top of global toolbar settings in a way that doesn't affect toolbars which don't have their state preserved in session.

There is also alternative approach, store information only about visible toolbars and add special flag to indicate if toolbars state information is available.

Perhaps the latter solution is good enough, it also means that we would store less data in session, since hidden toolbars will be simply skipped (but as side effect we will lost information about location of hidden toolbars).

So we might wan to use hybrid approach, store state for all toolbars and have that indicator flag for missing definitions, then we would restore toolbars according to session data and hide these that are not mentioned there.

I hope that it's clear, this idea sort of evolved while I was writing this comment. ;-)

**Comment by Emdek** [comment]
Uhm, there is a tiny but important detail, I'm not yet sure how exactly should it work with our separate visibility states for fullscreen mode and other cases...
I guess that manually toggling visibility using action should set it for current visibility state only, but some might expect forcing it for all modes.

**Comment by Emdek** [comment]
It seems that handling of sidebar toggle already uses similar logic, setting visibility only for current mode.

**Comment by ersi-dnd** [comment]
You mean when the user toggles a toolbar, then the toggling happens only in the currently focused app window? If yes, sure.

The global toggling of a toolbar would be a good option too, but a separate action with a different name, so that those who want it can do it. For example Vivaldi has the cool option to toggle all toolbars off at one go. It's quite useful and if the user has multiple windows open, this is the kind of thing that should happen in all windows. 

In contrast, in old Opera, if there were multiple windows open and you wanted to open/close the sidebar, it only opened in the currently focused window. This made complete sense.

So I guess the best way is to create separate actions so that both use cases are covered.

**Comment by Emdek** [comment]
@ersi-dnd, I'm talking about normal main window state versus fullscreen mode. toolbars have a separate visibility setting for both.

**Comment by ersi-dnd** [comment]
Fullscreen mode for a true-detached window? Toggling toolbar visibility in fullscreen mode? I am not sure how to handle this.

**Comment by Emdek** [comment]
@ersi-dnd, lets say that thanks to this feature all toolbars get hidden in fullscreen mode and address bar is visible when moving mouse cursor to the screen edge.
But these are just defaults that can be freely changed.

**Comment by ersi-dnd** [comment]
How is it possible to switch the jumping addressbar and tabbar off in fullscreen?

**Comment by Emdek** [comment]
@ersi-dnd, just visit their configuration dialogs using context menu and change visibility settings for fullscreen mode.
Note that right now some stuff might be broken due to transition.

**Comment by ersi-dnd** [comment]
@Emdek 
You mean right-click on the address bar > Address Bar > Configure... > Options > Visibility in full screen mode ?

Okay, found it and it works, but that's behind a nested tab and thus hard to find. 

Now I am looking at this place to find all the available actions https://github.com/OtterBrowser/otter-browser/blob/master/src/core/ActionsManager.h (I assume this always contains all the available actions.)

ShowToolBarAction,
ShowMenuBarAction,
ShowTabBarAction,
ShowSidebarAction,

Menubar, Tabbar and Sidebar have their own actions, but Addressbar (or Navigationbar) and Statusbar don't? To make the other toolbars come and go, does the user have to take `ShowToolBarAction` and combine it with other arguments, such as the toolbar name and what to do with it in normal mode and fullscreen mode?

**Comment by Emdek** [comment]
@ersi-dnd, take a look into `ActionsManager.cpp` and look for `IsDeprecatedFlag`, some of these actions shouldn't be used anymore (they are scheduled for removal) and you have to use `ShowToolBarAction` together with `toolBar` parameter that accepts strings like `MenuBar` etc. (values from `ToolBarIdentifier` enumerator from `ToolBarsManager.h` and names of custom toolbars).
Currently they are planned to change visibility just for current mode (for example force them to show in fullscreen mode while you are in fullscreen mode), at least for default actions (these used in Toolbars menu).
But I can later extend it to support `mode` parameter too (including special value to set visibility for all modes).
Also note that there is generic `isChecked` parameter used by actions that are defined as toggles, so when it is present then you can use it to create explicit action to just show or to just hide specified toolbar (and it doesn't work at this time, will be fixed later today).

**Comment by ersi-dnd** [comment]
@Emdek 
> ...you have to use ShowToolBarAction together with toolBar parameter that accepts strings like MenuBar etc.

Is the parameter compulsory? What will happen if the parameter is omitted? Sometimes it makes sense to have a function without parameter too. For example, `ShowToolBarAction` could, without parameters, toggle all the toolbars. Because if the parameter is compulsory and the user wants to toggle all the toolbars at one go, it would require quite a bunch of meticulous writing in the config to achieve this. JSON is not a comfy format at all.

**Comment by Emdek** [comment]
@ersi-dnd, it is, and it won't work without it.
Sometimes such fallbacks are harmful, and in this case I could accept only explicit parameter to enable such behavior.
Don't worry, we will get editor for menus sooner or later as part of #1265, and toolbars most likely end up as ready to use action variants (ready to drag and drop into specified slot).

**Comment by Emdek** [comment]
OK, so it's basically done now, but it might still require some minor fine tuning (I don't like that `noToolBars` parameter name, needs better one, maybe something like "minimumInterface"?).
I've noted possible variants for `ShowToolBarAction` to consider them later (especially mode allowing to toggle them all, maybe also parameter to force global changes too).
There is also one related thing, current panel shown by sidebar, right now it's still global.
Slightly related, we could consider passing of that parameter for `OpenUrl` etc., so you could open new main window directly with minimum interface.

Example definition for `toolBars.json`:
```
{
	"identifier": "DetachTabAction",
	"parameters": {
		"noToolBars": true
	}
},
```
Note that you can also customize text by adding this block next to `parameters`:
```
"options": {
	"text": "Some text"
}
```

**Comment by Emdek** [comment]
@ersi-dnd, another idea, maybe simply allow to specify list of allowed toolbars instead of `noToolBars` parameter?
Also we need to decide what to do when someone attempts to open new tab in such main window (it might be hard to reach it without Tab Bar...) and I'm not sure if forcing these to open in new main windows is a good idea.

**Comment by ersi-dnd** [comment]
Okay. I pulled and built the latest version. By what magic does True Detach work?

- I dragged a tab and dropped it to the desktop: Ordinary new window.
- Right-click on the tabbar > Detach Tab: Ordinary new window.
- I closed Otter and made a brand new toolBars.json with just this content;
```
{
	"identifier": "DetachTabAction",
	"parameters": {
		"noToolBars": true
	}
},
```
- Still the same result both by dragging and by the menu item.

**Comment by ersi-dnd** [comment]
Okay. I pulled and built the latest version. By what magic does True Detach work?

- I dragged a tab and dropped it to the desktop: Ordinary new window.
- Right-click on the tabbar > Detach Tab: Ordinary new window.
- I closed Otter and made a brand new toolBars.json with just this content;
```
{
	"identifier": "DetachTabAction",
	"parameters": {
		"noToolBars": true
	}
},
```
- Still the same result both by dragging and by the menu item.

**Comment by ersi-dnd** [comment]
Okay. I pulled and built the latest version. By what magic does True Detach work?

- I dragged a tab and dropped it to the desktop: Ordinary new window.
- Right-click on the tabbar > Detach Tab: Ordinary new window.
- I closed Otter and made a brand new toolBars.json with just this content;
```
{
	"identifier": "DetachTabAction",
	"parameters": {
		"noToolBars": true
	}
},
```
- Still the same result both by dragging and by the menu item.

**Comment by Emdek** [comment]
@ersi-dnd, you need to use that action from toolbar.
You will be able to modify menu item in context menu soon, there is just one thing preventing me from making it customizable too (proper handling of Customize menu).

Anyway, any ideas what to do with `noToolBars`? I's kind of misleading and ugly name, what about `toolBars` as list of toolbars to be shown?

**Comment by ersi-dnd** [comment]
@Emdek 

| you need to use that action from toolbar for now.

How? Drag and drop is not that. Making the toolbars.json with that content was not that. Do I have to make a custom button or menu item with the same content?

Concerning noToolBars, maybe GUI or Interface : true/false?

**Comment by Emdek** [comment]
@ersi-dnd, well, add it to some toolbar and click it. :-)
It's also possible to use it as shortcut or mouse gesture.

About alternatives, I've proposed some few comments earlier, if we want to keep it simple boolean switch then it could be called `minimumInterface` or `minimalInterface` (perhaps with "use" prefix, I need to review existing parameters and come up with some rules).
Also we can have both simple boolean switch and option to pass list of toolbars, why not.

**Comment by ersi-dnd** [comment]
I give up. I have no clue how to insert the little json code anywhere so that it would give some result.

**Comment by Emdek** [comment]
@ersi-dnd, example with final naming from current master:
```
[
	{
		"identifier": "MenuBar",
		"title": "Menu Bar",
		"iconSize": 20,
		"actions":
		[
 			"MenuBarWidget"
		]
	},
	{
		"identifier": "BookmarksBar",
		"title": "Bookmarks Bar",
		"location": "top",
		"normalVisibility": "hidden",
		"buttonStyle": "textBesideIcon",
		"bookmarksPath": "/"
	},
	{
		"identifier": "TabBar",
		"title": "Tab Bar",
		"location": "top",
		"fullScreenVisibility": "hover",
		"actions":
		[
			"MenuButtonWidget",
			"PrivateWindowIndicatorWidget",
			"TabBarWidget",
			"NewTabAction",
			"spacer",
			"ClosedWindowsMenu"
		]
	},
	{
		"identifier": "AddressBar",
		"title": "Address Bar",
		"actions":
		[
			"GoBackAction",
			"GoForwardAction",
			"ReloadOrStopAction",
			"AddressWidget",
			"SearchWidget",
			{
				"identifier": "DetachTabAction",
				"parameters":
				{
					"minimalInterface": true
				}
			}
		]
	},
	{
		"identifier": "ProgressBar",
		"title": "Progress Bar",
		"fullScreenVisibility": "auto",
		"normalVisibility": "auto",
		"actions":
		[
			"ProgressInformationDocumentProgressWidget",
			"ProgressInformationTotalSizeWidget",
			"ProgressInformationElementsWidget",
			"ProgressInformationSpeedWidget",
			"ProgressInformationElapsedTimeWidget",
			"ProgressInformationMessageWidget"
		]
	},
	{
		"identifier": "SideBar",
		"title": "Sidebar",
		"location": "left",
		"normalVisibility": "hidden",
		"currentPanel": "",
		"panels":
		[
			"bookmarks",
			"history",
			"notes",
			"passwords",
			"transfers"
		]
	},
	{
		"identifier": "StatusBar",
		"title": "Status Bar",
		"iconSize": 20,
		"actions":
		[
			{
				"identifier": "ShowToolBarAction",
				"options":
				{
					"icon": "sidebar-show"
				},
				"parameters":
				{
					"toolBar": "SideBar"
				}
			},
			"StatusMessageWidget",
			"ZoomOutAction",
			"ZoomWidget",
			"ZoomInAction",
			"ContentBlockingInformationWidget"
		]
	},
	{
		"identifier": "ErrorConsoleBar",
		"title": "Error Console",
		"location": "bottom",
		"normalVisibility": "hidden",
		"actions":
		[
			"ErrorConsoleWidget"
		]
	}
]
```

**Comment by ersi-dnd** [comment]
Either JSON is too hard in itself (it certainly is a useless pain compared to INI) or there's something about the piece of code that is not working. 

One thing I have noticed about JSON: You have things like `"identifier": "DetachTabAction",` in some places and things like `"action": "DetachTab",` in other places. This is a pointless complication. The code elements must be consistent, particularly when the code itself is complicated to begin with. Otherwise no regular user will be able to appreciate what can be done with it. I pretty much cannot anymore.

**Comment by Emdek** [comment]
@ersi-dnd, these files are as similar as possible, proper end user documentation will make it way clearer.

**Comment by ersi-dnd** [comment]
I tried to make a keyboard shortcut with ctrl+i. How to do it?

**Comment by Emdek** [comment]
@ersi-dnd, try this:
```
			{
				"action": "DetachTab",
				"parameters": 
				{
					"minimalInterface": true
				},
				"shortcuts": 
				[
					"Ctrl+H"
				]
			},
```

**Comment by ersi-dnd** [comment]
Okay, I tried.

THE GOOD

- After applying your piece manually to my keyboard/custom.json and then going to take a look at it in Preferences > Advanced > Keyboard, the definitions are displayed there as supposed to. When I did the same thing with the earlier code and a bunch of modifications of it, the definitions were simply gone and nothing worked.
- The keyboard shortcut (ctrl+h) does something

THE BAD 

- It's not true detach. It's detach with all the toolbars as usual. The window manager I am running atm is i3 (tiling).


THE UGLY

- I have little clue what is different in your piece of code that made it work and not mine. Maybe some wrong or missing bracket somewhere or some other name? Both? This should not be so difficult, but it is. INI makes so much more sense.

**Comment by Emdek** [comment]
@ersi-dnd, `git pull` and rebuild, it was renamed 32 minutes ago and most likely you are still using older version.

**Comment by ersi-dnd** [comment]
Well, I just added that I applied your piece of code only after I had installed a fresh git version.

**Comment by Emdek** [comment]
@ersi-dnd, no idea, we can try to debug it later on IRC, works fine here...

**Comment by ersi-dnd** [comment]
I pulled it again and it works now, so my earlier pull must have indeed been half an hour ago rather than a few minutes ago. I'm trying the feature now. 

There is a bunch of stuff that must go along with it to make it usable and sensible. I will name them later.

**Comment by ersi-dnd** [comment]
Okay, the worst offender that must be named and fixed as soon as possible.

- First, I opened three-four tabs
- Then I hid the navigation toolbar (address bar)
- Then I detach a tab (by Ctrl+h created by you)
- Result: navigation toolbar appears in the detached tab

There is a logic to True Detach. It's not about making certain specific toolbars vanish upon detach. It's the opposite: Keeping the appearance of the tab as-is upon detach. The modern create-a-new-window-by-dragging-the-tab broke this simple logic.

**Comment by ersi-dnd** [comment]
> There is a logic to True Detach. It's not about making certain specific toolbars vanish upon detach. It's the opposite: Keeping the appearance of the tab as-is upon detach. 

I reiterate what I believe to be the best formulation of the main idea of True Detach: Open multiple tabs. Tile the tabs. A true-detached tab looks exactly like a tiled tab, except that it was moved outside the main window.

**Comment by ersi-dnd** [comment]
No development regarding this ticket last week?

**Comment by Emdek** [comment]
@ersi-dnd, not yet.

**Comment by ersi-dnd** [comment]
Will you notify when it's done?

**Comment by Emdek** [comment]
@ersi-dnd, simply stay subscribed to this ticket. :-P

**Comment by Emdek** [comment]
@ersi-dnd, anything left to be added or fixed (this ticket got pretty long...)?

**Comment by ersi-dnd** [comment]
Now detaching (by the said keybind) seems to work as intended. Except that when a window is detached and then I open the Sidebar by custom keybind, it opens in both windows. I think it should open in the currently focused window only.

After the detachment, the issue is of course how to reattach. The current options seem to be:

- If the address bar was visible in the main window, then it's also visible in the detached window, and you can right-click on the address bar and select Toolbars > Tabbar, then drag the tab back to the main window.
- If the address bar was invisible in the main window, then it's also invisible in the detached window. Basically out of luck then, unless you have (a) a keybind to toggle the tabbar or (b) a keybind to bring up the main menu and navigate there to make the tabbar visible.

There should be more drag-and-drop options to reattach. Awesome options would be:

- Focus the detached window, open one more tab there, then bring up the switch-tabs widget and drag from there to the main window's tabbar. 
- Drag-and-drop in the Windows panel in the sidebar (perhaps too complicated, but it would be extremely useful)

**Comment by ersi-dnd** [comment]
Ah, one more way to reattach:
1. Focus the detached window
2. Copy its URL (can be set to a keybind)
3. Close the detached window (there must be Interface/LastTabClosingAction:closeWindowIfNotLast)
4. Move to the main window - Paste and go.

**Comment by ersi-dnd** [comment]
Looks like the Sidebar toggle is fixed now, i.e. is independent in Detached and Main window. I meanwhile found out how to make a keybind for it too. Is there really no out-of-the-box keybind to toggle for Sidebar?

Now I have another question: Can this `minimalInterface` thing be used as a direct action too? I mean, not as a parameter for another action, but as an action unto itself, so as to toggle the interface on and off in the main window?

**Comment by ersi-dnd** [comment]
Oh, another huge problem, the one I have been warning about since the beginning, so it didn't even occur to me earlier to test it specifically:

1. Have "Show windows and tabs from the last time" as startup behaviour
2. Open many tabs and Detach a tab as True detach
3. Close the main window
4. Close the detached window
5. Open Otter again
Result: a toolbarless window, no way to get toolbars back, unless you have hacked an important toolbar toggle

The toolbar toggles should either be inbuilt or this startup behaviour that puts noobs into a serious predicament must be changed as I suggested in the first post.

**Comment by ersi-dnd** [comment]
It would be great to be able to toggle `"minimalInterface": true` as an independent action, not as a parameter to some other action - i.e. toggle all toolbars on/off at one go. For now, I have discovered that `"minimalInterface": true` can be added as a parameter to NewWindow and NewWindowPrivate actions, which almost does the trick, but `"minimalInterface": true` cannot be added to, for example, ShowToolbar action, which could properly do the trick. I think `"minimalInterface": true` deserves to be its own independent action.
