### ISSUE TITLE
Process keeps running when window is closed

### ISSUE THREAD

**Issue by cfeck** [OtterBrowser/otter-browser#1241]
To reproduce:
- delete ~/.config/otter
- start otter-browser in Konsole
- click window Close button

Actual results:
- window is hidden, but process still runs

Expected result:
- window is close, and process is terminated

Using Menu > Quit works correctly.

otter-browser at 95777dd18a3a17a57211da36e8ba4be29f78b4ef compiled with QtWebKit 5.7.1

**Comment by Emdek** [comment]
I've seen it recently on KDE Plasma 5.8, it is related to ``QSystemTrayIcon`` (when it is disabled there are no issues) and doesn't happen with official Qt binaries, but is reproducible with my system Qt (5.6.2,  the same version from SDK works just fine).

**Comment by cfeck** [comment]
Oh yes, there is an icon hidden in the system tray popup, but clicking it just causes a crash instead of revealing the window.

**Comment by Emdek** [comment]
@cfeck, only after closing last window, until then it works correctly.
Something prevents it from being destroyed when system Qt is in use, maybe some extra Qt patches, some platform integration plugin, no idea.
