### ISSUE TITLE
Tearing when resizing the window

### ISSUE THREAD

**Issue by pierreporte** [OtterBrowser/otter-browser#1243]
When I resize the window, there is a lot of tearing as you can see on this video capture: https://vid.me/ak8K. Black areas appear and widgets does not resize properly during the size change. However, everything is correct when the window keeps its size. It is to note that what you can see on the video linked is a lot better than what I can usually see because the video capture greatly decreases the reactivity of my whole system, due to my 2560×1440 screen, the on the fly down-scaling of the video size to 50 %, and my old GPU.

It is to note that the tearing only affects Otter. Other applications resize perfectly.

**Comment by Emdek** [comment]
Try any other Qt application.
Are you using compositing?
Are you using QtWebEngine? 
It can lead to rendering corruption (at least I've noticed it on some virtual machines).

**Comment by pierreporte** [comment]
Otter is the only Qt application that have apparent tearing. Tearing is present regardless of the backend, but it is far stronger with QtWebengine (the capture was done with it). If by “compositing” you mean 3D acceleration, then I believe I do use it since I am using the standard Gnome 3.22 desktop.

**Comment by Emdek** [comment]
@pierreporte, try resizing this (after loading some URL):
https://github.com/OtterBrowser/test-qtwebkit

Anyway, it's unlikely that we can do anything about that, we are not rendering it ourselves.

**Comment by pierreporte** [comment]
There is tearing with test-qtwebkit, as well as with test-qtwebengine. As with Otter, tearing is less strong with Webkit than with Blink.

**Comment by Emdek** [comment]
@annulen, any idea if we can workaround it somehow (other than drop widgets :-P)?

**Comment by pierreporte** [comment]
Note that I was using legacy QtWebkit, since I don’t want to mess up my system again.

**Comment by annulen** [comment]
What video driver are you using? Is VSync enabled? For instance with nvidia driver there are lots of tunables that can reduce rearing

**Comment by pierreporte** [comment]
My driver is the [ATI open-source one](https://www.archlinux.org/packages/extra/x86_64/xf86-video-ati/) as it is the right choice for my Radeon HD 7770 according to the [Archlinux wiki](https://wiki.archlinux.org/index.php/Xorg#AMD). I don’t know if VSync is enabled and I can’t find a way to check whether it is or not.
