### ISSUE TITLE
Beta 12 AppImage won’t run

### ISSUE THREAD

**Issue by pierreporte** [OtterBrowser/otter-browser#1244]
Even though I already reported something similar in https://github.com/OtterBrowser/otter-browser/issues/1148#issuecomment-269370081, I decided to give it more visibility by opening a dedicated issue. This way, other people could report similar issues in a single place.

Each time that I try to run the AppImage, I get this error message in the terminal:

    QPainter::begin: Paint device returned engine == 0, type: 2
    QPainter::setFont: Painter not active
    QPainter::setPen: Painter not active
    ./otter-browser-0.9.12-beta12-x86_64.AppImage: symbol lookup error: ./otter-browser-0.9.12-beta12-x86_64.AppImage: undefined symbol: _ZN12QWebSettings17pluginSearchPathsEv

I always run an up-to-date Archlinux when trying this.

**Comment by Emdek** [comment]
It appears that somehow it picks up your global Qt installation, perhaps it could be avoided by use of some sort of startup script that would try to preload bundled libraries.

**Comment by probonopd** [comment]
The question is, why is it doing that... inside the AppImage, there should either be a script or binary called `AppRun` that sets `LD_LIBRARY_PATH` to the inside of the AppImage, or the binaries and libraries should have rpath set from running patchelf (which is what linuxdeployqt does).

**Comment by Emdek** [comment]
@probonopd, they are patched.
But yeah, setting `LD_LIBRARY_PATH` is what I would like to try out.

**Comment by Emdek** [comment]
@pierreporte, this one should help:
https://otter-browser.org/tmp/otter-browser-x86_64.AppImage

**Comment by pierreporte** [comment]
@Emdek this one won’t run either:

    execv error: No such file or directory

GDB doesn’t give more details.

**Comment by Emdek** [comment]
@pierreporte, I'm out of  ideas, you can try to follow instructions from here:
http://askubuntu.com/questions/774490/what-is-an-appimage-how-do-i-install-it/836547#836547
Simply mount it somewhere and try running `AppRun` or `otter-browser.sh`.

**Comment by pierreporte** [comment]
I was able to mount your AppImage and the beta 12 AppImage. They run normally as far as I tested. However, there were some ugly output:

# otter-browser-x86_64.AppImage

This one bundles a GTK theme unlike the beta 12.

Your AppRun seems to be wrong. It links to /home/michal/Pobrane/otter/otter-browser/otter-browser.sh and thus doesn’t work. otter-browser.sh works.

```
Qt: Session management error: None of the authentication protocols specified are supported
No language dictionaries for the language: "fr"
qt.network.ssl: QSslSocket: cannot resolve SSLv3_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv3_server_method

(gst-plugin-scanner:27445): GStreamer-WARNING **: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstassrender.so': /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

(gst-plugin-scanner:27445): GStreamer-WARNING **: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstqmlgl.so': ./lib/libQt5Core.so.5: version `Qt_5.7' not found (required by /usr/lib/gstreamer-1.0/libgstqmlgl.so)

(gst-plugin-scanner:27445): GStreamer-WARNING **: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstlibav.so': /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

(gst-plugin-scanner:27445): GStreamer-WARNING **: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstgtksink.so': /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

(gst-plugin-scanner:27445): GStreamer-WARNING **: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstdashdemux.so': ./lib/libxml2.so.2: version `LIBXML2_2.9.0' not found (required by /usr/lib/gstreamer-1.0/libgstdashdemux.so)

(gst-plugin-scanner:27445): GStreamer-WARNING **: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstzbar.so': libzbar.so.0: cannot open shared object file: No such file or directory

(gst-plugin-scanner:27445): GStreamer-WARNING **: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstrsvg.so': /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

(gst-plugin-scanner:27445): GStreamer-WARNING **: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstx265.so': libx265.so.95: cannot open shared object file: No such file or directory

(gst-plugin-scanner:27445): GStreamer-WARNING **: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstclutter.so': /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

(gst-plugin-scanner:27445): GStreamer-WARNING **: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstpango.so': /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

(gst-plugin-scanner:27445): GStreamer-WARNING **: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstpulse.so': /usr/lib/gstreamer-1.0/libgstpulse.so: symbol pa_format_info_is_compatible, version PULSE_0 not defined in file libpulse.so.0 with link time reference

(gst-plugin-scanner:27445): GStreamer-WARNING **: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstfdkaac.so': libfdk-aac.so.1: cannot open shared object file: No such file or directory
```

# Beta 12 AppImage

AppRun links to ./otter-browser

Terminal output:

```
Qt: Session management error: None of the authentication protocols specified are supported
No language dictionaries for the language: "fr"
qt.network.ssl: QSslSocket: cannot resolve SSLv3_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv3_server_method
```

**Comment by Emdek** [comment]
@pierreporte, right, it ended up with absolute symlink. :-/
It seems that you are missing OpenSSL 1.0 and probably some GStreamer 1.x packages too.

**Comment by pierreporte** [comment]
You mean, on my system? I have [OpenSSL 1.0.2](https://www.archlinux.org/packages/core/x86_64/openssl/), [GStreamer 1.10.2](https://www.archlinux.org/packages/extra/x86_64/gstreamer/) (with every plugins), [Phonon GStreamer 4.9.0 for Qt5](https://www.archlinux.org/packages/extra/x86_64/phonon-qt5-gstreamer/), but not [qt-gstreamer](https://www.archlinux.org/packages/extra/x86_64/qt-gstreamer/).

**Comment by Emdek** [comment]
@pierreporte, then I'm out of ideas.
I could bundle GStreamer but it won't be able to play proprietary formats and most likely will end up without sound thanks to Pulse Audio.
OpenSSL issue has own ticket, #1233.

**Comment by pierreporte** [comment]
It wouldn’t be surprising that my system is completely messed up. I installed Archlinux five years ago and didn’t really took care of it. I have been thinking of doing a fresh install but it will wait that I buy a SSD.

**Comment by probonopd** [comment]
> @pierreporte, this one should help:
https://otter-browser.org/tmp/otter-browser-x86_64.AppImage

Runs for me on `ubuntu-16.04-desktop-amd64.iso`. The only message I see on the console is `No language dictionaries for the language: "en"`.

**Comment by pierreporte** [comment]
Weekly 138 AppImage runs fine. The problem seems to have been fixed somehow.
