### ISSUE TITLE
Missing option in Bookmarks list, about:config (and other list-like widgets)

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#1249]
In Opera's bookmarks panel, there was an action (and right-click menu item) to Expand all, not just the selected folder. 

In Otter's bookmarks and about:config, when a folder is collapsed, then Shift+right and Ctrl+right do the same thing: Expand this folder. There is no option to expand all folders. 

And Collapse all is also missing.

**Comment by Emdek** [comment]
Duplicate of #861.
