### ISSUE TITLE
Start page (speed dial)

### ISSUE THREAD

**Issue by szcsaba** [OtterBrowser/otter-browser#125]
Hi Emdek! :-)
I'm glad I've found this project. Many thanks for developing Otter!

Please consider the latter suggestion:
I know that the feedreader, notes have lower priority but at that time, could you add the tile support for them in the speed dial/start page?
I mean, it would be useful to have note tiles, rss-article tiles, mail message tiles or even session tiles. And the folder tile is a good idea from Blink Opera.

**Comment by ersi-dnd** [comment]
In speeddial, will you also set the keybinds CTRL+number for the first nine tiles? If so, I warmly recommend to have an option to unbind them.

**Comment by Emdek** [comment]
Note that it is still possible that we will use QML in future, but this attempt simply failed, and additional dependency caused additional issues like #811.
