### ISSUE TITLE
proxy auto config no longer working

### ISSUE THREAD

**Issue by hunderteins** [OtterBrowser/otter-browser#1253]
Hello,
  I think 093add72ce4fed8eb8a6bae6131676a0cac74cc7 killed proxy auto config (pac).
Can we have that back?
TIA,
hunderteins

**Comment by Emdek** [comment]
I blame `QT_NO_CAST_FROM_ASCII`, I had to comment out a lot of code while testing for missing `QLatin1String` / `QLatin1Char`, somehow I've forgot to uncomment this block and it slipped through diff review...
