### ISSUE TITLE
Segfault in full-screen mode

### ISSUE THREAD

**Issue by pierreporte** [OtterBrowser/otter-browser#1254]
Using cfdbe170bd498ba54702dd9ea030cba65aa5e0f4 under Archlinux.

In full screen mode, regardless of the loaded URL, when the pointer is located at the top of the screen, showing the tab bar, the browser will crash if you continue moving around the screen and hovering the widgets while passing over the tab bar.

Terminal output:

    “otter-browser” terminated by signal SIGSEGV (Address boundary error)

**Comment by Emdek** [comment]
Not reproducible here, needs backtrace.

**Comment by pierreporte** [comment]
There is no backtrace except `“otter-browser” terminated by signal SIGSEGV (Address boundary error)`.

**Comment by Emdek** [comment]
@pierreporte, then get one. ;-)
https://wiki.archlinux.org/index.php/Debug_-_Getting_Traces

**Comment by pierreporte** [comment]
I edited the PKGBUILD to add this line:

    options=(debug !strip)

before compiling and installing again. Then, I ran Otter with GDB:

    $ gdb otter-browser

In the GDB prompt, I entered these commands:

    (gdb) set logging file trace.log
    (gdb) set logging on
    (gdb) thread apply all bt full
    (gdb) run

At this point, I reproduced the bug while GDB was writing the backtrace. When Otter froze (GDB preventing the programme to quit), I stopped the debugging as instructed:

    (gdb) set logging off
    (gdb) quit

Finally, this is the content of trace.log:

```
Starting program: /usr/bin/otter-browser 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffd2e56700 (LWP 18129)]
[New Thread 0x7fffc8bad700 (LWP 18130)]
[New Thread 0x7fffc3fff700 (LWP 18131)]
[New Thread 0x7fffc1d87700 (LWP 18132)]
[New Thread 0x7fffc1381700 (LWP 18133)]
[New Thread 0x7fffc0b80700 (LWP 18134)]
[New Thread 0x7fffb90d1700 (LWP 18135)]
[New Thread 0x7fffb88d0700 (LWP 18136)]
[New Thread 0x7fffb5517700 (LWP 18137)]
[New Thread 0x7fffb4d16700 (LWP 18139)]
[New Thread 0x7fffaffff700 (LWP 18140)]
[New Thread 0x7fffaf7fe700 (LWP 18141)]
[New Thread 0x7fffaeffd700 (LWP 18142)]
[New Thread 0x7fffae7fc700 (LWP 18143)]
[New Thread 0x7fffadffb700 (LWP 18144)]
[New Thread 0x7fffad7fa700 (LWP 18145)]
[New Thread 0x7fffacff9700 (LWP 18146)]
[New Thread 0x7fff8bfff700 (LWP 18147)]
[New Thread 0x7fff8b7fe700 (LWP 18148)]
[New Thread 0x7fff8affd700 (LWP 18149)]
[New Thread 0x7fff8a7fc700 (LWP 18150)]
[New Thread 0x7fff89ffb700 (LWP 18151)]
[New Thread 0x7fff897fa700 (LWP 18152)]
[New Thread 0x7fff88ff9700 (LWP 18153)]
[New Thread 0x7fff5bfff700 (LWP 18154)]
[New Thread 0x7fff1b7fc700 (LWP 18155)]
[New Thread 0x7fff1affb700 (LWP 18156)]
[New Thread 0x7fff1a7fa700 (LWP 18157)]
[New Thread 0x7fff19ff9700 (LWP 18159)]
[New Thread 0x7fff197f8700 (LWP 18160)]
[New Thread 0x7fff18ff7700 (LWP 18161)]
[New Thread 0x7fff03fff700 (LWP 18162)]
[New Thread 0x7fff037fe700 (LWP 18163)]
[New Thread 0x7fff02ffd700 (LWP 18164)]
[New Thread 0x7fff027fc700 (LWP 18165)]
[New Thread 0x7fff01bdd700 (LWP 18166)]

Thread 1 "otter-browser" received signal SIGSEGV, Segmentation fault.
0x00007fffed6022c8 in QObject::installEventFilter(QObject*) ()
   from /usr/lib/libQt5Core.so.5
```

**Comment by Emdek** [comment]
@pierreporte, it looks kind of incomplete, these last three lines were really all it produced (the rest is useless)?

**Comment by pierreporte** [comment]
What do you mean? They were written in the GDB session and in the generated file. I ran one another debugging session with the same result.

Should I install [qt-debug](https://wiki.archlinux.org/index.php/Unofficial_user_repositories#qt-debug) and try all over again?

**Comment by Emdek** [comment]
@pierreporte, it should contain information about context of that call.
Installing debug symbols might help, but I can't guarantee that.
BTW, are you using default toolbars setup?

**Comment by pierreporte** [comment]
I deleted my profile and the bug is still there.

**Comment by Emdek** [comment]
@pierreporte, I've managed to reproduce it with default set, and I've got much more helpful backtrace, it's weird that you were getting just one entry...

**Comment by pierreporte** [comment]
Did you follow the same step as me when you got the full backtrace?

**Comment by Emdek** [comment]
@pierreporte, no, I'm using IDE to do such stuff.
