### ISSUE TITLE
Crash when using "New Window" and Menu bar was never shown

### ISSUE THREAD

**Issue by cfeck** [OtterBrowser/otter-browser#1258]
To reproduce:
- mv .config/otter .config/otter-old
- start otter-browser
- Alt+F11 to hide menu bar
- Alt+Q to Exit
- start otter-browser again
- visit any Url that has a link, e.g. kde.org
- use RMB context menu on a link and select "Open in New Window"

Using 9362e3e40fcd4b03d74ab46444f60521307e4c1f with QtWebKit + Qt 5.8.0.

**Comment by Emdek** [comment]
Note that you don't have to clear profile, you can use *--profile* option to specify some temporary directory (or *--portable* to get cache and profile directories next to main binary).

BTW, I mistyped *kde,org* and WTF, "Kentucky Department of Education" was first result on DuckDuckGo, KDE being second...
