### ISSUE TITLE
Java does not work

### ISSUE THREAD

**Issue by Peter2121** [OtterBrowser/otter-browser#1260]
Otter 0.9.12 beta 12 (from ports) on FreeBSD 10.3 (x64).
Icedtea-web: 1.6.2, openjdk version 1.8.0_112.

Java does not work in Otter browser.
Java works fine in Opera and Firefox.

It seems that Otter tries to start flash plugin when I try to start Java applet:

`*** NSPlugin Viewer  *** ERROR: /usr/local/lib/npapi/linux-f10-flashplugin/libflashplayer.so: can
not open shared object file: No such file or directory`

BTW, #509 is still not fixed, please, reopen it.

**Comment by Emdek** [comment]
Check using this:
https://github.com/OtterBrowser/test-qtwebkit
But that already sounds like upstream issue, probably something wrong in QtWebKit port on FreeBSD or general QtWebKit issue.

**Comment by Peter2121** [comment]
Any hint to build it, please?

**Comment by Emdek** [comment]
@Peter2121, you need *qmake* and Qt base (QtCore, QtNetwork, etc.) and QtWebKit headers, I'm not sure how these are handled on FreeBSD.
It should be enough to run it this way:
```
qmake test-qtwebkit.pro
make
./test-qtwebkit
```
If that won't work for you then any instructions for building Qt projects under FreeBSD should apply.

Java is enabled by default there, so it should simply work, if it works in QtWebKit.

**Comment by Peter2121** [comment]
Still blocked with different issues of building the test-qtwebkit.
`LIBS     = $(SUBLIBS) -L/usr/local/lib -L$(QTDIR)/lib -L/usr/local/lib -lqt-mt -lXext -lX11 -lm`
ld cannot find qt-mt...
Qt5 is installed, the libs are in /usr/local/lib, but there is no libqt-mt.so...

**Comment by Emdek** [comment]
@Peter2121, qt-mt? Never heard about that one.
Check if you are using `qmake` from Qt5, run `qmake -v` and check which Qt version it mentions.
I guess that CMake projects are more user friendly.

**Comment by Peter2121** [comment]
It compiles better with qmake from Qt5 :)
No idea why Qt3 version of qmake was in the path, but not the Qt5 one.
How can I setup the authentication in this test app? 
It goes directly to Error 401, without asking the user/password.

**Comment by Emdek** [comment]
@Peter2121, are you using proxy?
Anyway, I'm pretty sure that it will give the same result, so I'm not sure if it is worth to invest more effort in getting that test application to run.

**Comment by Peter2121** [comment]
Non, it's a direct connection to an Intranet server.
Finally, I open the access to one test file with Java applet inside.
I receive the same error message from the test app, like from Otter Browser:
`*** NSPlugin Viewer  *** ERROR: /usr/local/lib/npapi/linux-f10-flashplugin/libflashplayer.so: cannot open shared object file: No such file or directory`
The code is the following:
`<applet code="com.lixia.rdp.applet.RdpApplet.class" archive="JavaRDP2.0-last.jar" width="1024" height="768" name="ProperJavaRDP" align="center"><param name="code" value="com.lixia.rdp.applet.RdpApplet.class"><param name="archive" value="JavaRDP2.0-last.jar"><param name="name" value="ProperJavaRDP"><param name="geometry" value="1024x768"><param name="server" value="server"><param name="align" value="center"><param name="port" value="3389"><param name="username" value="user"><param name="password" value="pass"><param name="domain" value="LOCALDOMAIN"><param name="bpp" value="16"><param name="keymap" value="fr"><param name="opts" value="NaN"></applet>`

**Comment by Emdek** [comment]
@Peter2121, so it doesn't work there too?
And the same test page works fine in Firefox?

**Comment by Peter2121** [comment]
Yes, like I mentioned in the first message - it works fine in Opera and Firefox, but neither in Otter nor in test-qtwebkit.

**Comment by Emdek** [comment]
@Peter2121, I see...
Then sadly we cannot do anything about that, it needs to be fixed in QtWebKit.
