### ISSUE TITLE
Allow to disable all tooltips in UI

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#1261]
Tooltips are back again on UI buttons, such as on New Tab button and the panel (sidebar) buttons. My preference is to turn tooltips off in about:config, bt they are back again.

**Comment by Emdek** [comment]
This option is meant only for `WebWidget`, these buttons were missing them and simply got them recently.
It seems that there might be possibility to allow to disable them globally, but I don't think that we should reuse that option.

**Comment by Emdek** [comment]
@ersi-dnd, there seems to be no way to simply disable or filter them out,  but there is solution that de facto disables them, by setting their delay to value that should prevent them from being shown for days (I guess that we can assume that user won't leave cursor over widget with tooltip for several weeks ;-)).
