### ISSUE TITLE
Content colors (about:config) don't seem to do anything

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#1263]
There's an ability to set colours in about:config. The colours are meant to be applied to webpages (like FF's Content/Colors and Opera's User mode), but in reality they don't do anything, because the switch to apply them seems to be missing. 

Can you write something like OverrideWebpageColors or ApplyUserStyle ?

Another wish: Is it doable to apply system style to webpages (i.e. author layout preserved, author colors ignored, link colours set by the user) like in Firefox?

**Comment by Emdek** [comment]
@ersi-dnd, works for me, controls are shown after selecting entry and they work, but note that they only set initial values, so stylesheet will usually override them.
For these cases you should use user stylesheet.

Most of this description feels like duplicate or extension of #533.
