### ISSUE TITLE
CSS size unit ex rendered much smaller

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#1267]
Hi,
I recently noticed a kind of cornercase glitch with some elements displayed considerably smaller than expected - most prominently the formulas on wikipedia, e.g.:
https://en.wikipedia.org/wiki/Exponential_function
the rendered (svg) formulas are displayed smaller than other  browsers I tried (which appear quite consistent - opera 12, opera 44, ff, ie ...)
It turns out, that this may be due to the use of a rare size unit ex (i.e. the height of the lowercase x in the respective font setting), cf.:
http://stackoverflow.com/questions/918612/what-is-the-value-of-the-css-ex-unit
It can be seen e.g. on the following sample
```html
<div style="font-size: 100px; font-family:Times New Roman;">div text 100px x|<span style="font-size: 1ex;">|x nested span 1ex</span></div>
```
As I understand it, the vertical bar (spanning the whole character height) of the span-text should have more or less the height of the "x" of the div element. 
In the above sample of the 100px div text, the lowercase x has the height 45 px in my setting, the vertical bar of the span text has only 23 px in Otter (vs. 41 px in the other browsers).
The effect can be seen at:
http://www.w3schools.com/cssref/tryit.asp?filename=trycss_unit_ex

Interestingly, the reduced size also affects the individual svg files without the html markup containing the size attributes, e.g.:
https://wikimedia.org/api/rest_v1/media/math/render/svg/5e96cbfd64b37fd5a800b8ae1b87427683a0da74
such pre-rendered svg graphic is also displayed at about half the size in Otter in comparison to other browsers. (I am actually not sure, whether this belongs to the same issue, but other sorts of svg files I tried are displayed appropriately.)
(using otter beta 9.12 win 64, Win7)
regards,
    vbr

**Comment by annulen** [comment]
This probably depends on used font. Maybe Qt detects xHeight of that font to have different value than font engines of other browsers you've tested
