### ISSUE TITLE
New sidebar issues

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#1271]
![new_sidebar](https://cloud.githubusercontent.com/assets/6757832/22787245/5780c326-eee4-11e6-814d-37964d6ca49d.png)

1. Right-click on the sidebar, **Sidebar** > **Configure...**
2. Click OK
3. A number of "2"s get added to the list of possible entries
4. Every repetition of the process adds more "2"s

**Comment by beastie1** [comment]
A second issue.

1. Click an icon, e.g. Bookmarks; Otter shows the proper sidebar
2. Press **F4** to hide it
3. Restart Otter; the sidebar will still be shown
4. Click the same icon as before to toggle the sidebar off, press F4 and restart, it will not be shown again

**Comment by pierreporte** [comment]
You should add more details. On my installation (a66e916311cbae428a3cc94a1767b8294aa76185, up-to-date Archlinux), the second issue is not present.
