### ISSUE TITLE
Weekly 163 Windows build - Some problems

### ISSUE THREAD

**Issue by ghost** [OtterBrowser/otter-browser#1276]
1) Font settings in general are going to be resetted. Changing font sizes in the options for webpages, restarting browser and fonts are again very tiny also default zoom in options is not stored properly. Only way fonts stay larger is if I change the tab zoom slider which does not result in tiny fonts after browser restart.

3) Old session can't be used anymore, migration option does nothing

System here Windows 8, 64 Bit - using the Otter QTWebkit build

Both are nonexisting issues in beta 12-2 which is also available

**Comment by uahim** [comment]
issues on Win7 x64, all UI/cosmetics in fact

3. UI is all white all of sudden, changing "Style" from Advanced | Appearance does nothing for any of the options but Fusion

4. tab bar height increased by 100%

![clipboard01](https://cloud.githubusercontent.com/assets/6866794/23027100/9c3685a8-f463-11e6-8f6c-df5da4942db0.png)

**Comment by SJ-Diamond** [comment]
Another issue appears in MDI mode - focus is not in the url field when opening a new tab.

**Comment by SJ-Diamond** [comment]
Some more small issues in combination with MDI:

Opening a link from a tab with a middle click to open it as background tab fails as it shoves itself instantly into foreground again. Perhaps that is also related to that tab jumping when i load a session and open tab after tab (suddenly during scrolling with the mouse to activate all tabs of the session the focus from the right now active tab jumps back to a previously activated one)

**Comment by vbr** [comment]
Hi,
I'd like to mention another glitch in weekly 163 - the progress bar now appears in the middle of the screen height, while loading some larger page (instead of the previous placement at the bottom of the page area.
I also confirm the bugs mentioned here or in the parallel issues - strange sidebar toggle or white "theming" in the windows themes. (Otter weekly 163, x64, win 7)
Many thanks for the continued efforts with Otter!
   vbr

**Comment by uahim** [comment]
and another one:
no vertical scroll bar, in this scenario - Otter is being started full screen, a page is loaded: no scrollbar; resized and made full screen again, scroll bar is visible again.

**Comment by grumpygeek** [comment]
When I paste a url (or any text) into the address box, it clears it automatically immediately. (Win 8.1 but doubt OS matters)

Note: otter-browser.org is down (for me) and had problems yesterday too.

**Comment by Emdek** [comment]
@uahim, tab bar size by default depends on icon size set for toolbar, you can set smaller or use *TabBar/MaximumTabHeight*.

**Comment by Emdek** [comment]
Superseded by #1304.
Please report issues that still remain in that ticket.
