### ISSUE TITLE
[Disqus login] Pop-up doesn't close

### ISSUE THREAD

**Issue by lollox** [OtterBrowser/otter-browser#1280]
When I want to login to Disqus (when I'm on an external site that implement it) a pop-up opens to put my credentials. Normally this window autoclose itself when you successfully login, but in Otter it doesn't.

Otter weekly 163, x64 QTWebKit, on Win10 x64

**Comment by Emdek** [comment]
@lollox, please check that using *test-qtwebkit.exe*, but it's most likely QtWebKit bug anyway.

**Comment by annulen** [comment]
Also, check if there are errors in JS console

**Comment by lollox** [comment]
in test-qtwebkit the popup don't open at all 

example: https://www.tomshw.it/hyperion-quando-la-fantascienza-e-grande-letteratura-83449

**Comment by lollox** [comment]
@annulen : http://i.imgur.com/ahSP8Yh.jpg

**Comment by Emdek** [comment]
@lollox, ah, so it's a popup window, not sort of JS dialog layered on top of content?

**Comment by lollox** [comment]
yes, a simple pop-up

**Comment by Emdek** [comment]
@lollox, then it was our issue with missing confirmation dialog when JS wants to close window.
I'm considering making hardcoded or optional (enabled by default) exception to let them close windows opened by scripts in the first place (AFAIR Opera used to behave like that).
