### ISSUE TITLE
Twitter video don't play

### ISSUE THREAD

**Issue by lollox** [OtterBrowser/otter-browser#1281]
Testing and testing, here another weird issue: I play with no problems YouTube videos, but on Twitter they don't play. The player tries to load the content without any result. Obviously no problems in other browsers.

Example: https://twitter.com/SheIsCOLOSSAL

Otter weekly 163 x64 QTWebKit on Win10 x64

**Comment by Emdek** [comment]
There is already one ticket for Media Foundation issues: #1225.
