### ISSUE TITLE
composite file extensions modified when using "open" in file download dialog

### ISSUE THREAD

**Issue by midluk** [OtterBrowser/otter-browser#1288]
When you use "open" in the file download dialog, files are placed in /tmp with some (likely) unique "-xnnnnn" (x is a letter, ne a number) added before the file extension (before the last dot in the file name). When fully downloaded, the selected program is the invoked.
For composite file extensions like tar.gz, tar.bz2, tar.xz this leads to the file extension being altered (e.g. tar-b12345.gz), which then leads to archive viewers not properly opening the tar archive, but just showing a tar-xnnnnn file as content.

I see the following options to fix this:
1. "tar.something" file extensions should be treated specially
2. the uniqueification part should be entered into the file name not after the last, but after the first dot (might look odd in case there are version numbers in the file name, but should cause less problems than the current solution)
3. The uniqueification should be prepended to the file name

**Comment by midluk** [comment]
I tried option 2. Really looks strange.

I also tried option 1, works:
```
diff --git a/src/core/TransfersManager.cpp b/src/core/TransfersManager.cpp
index c166895..c9e749e 100644
--- a/src/core/TransfersManager.cpp
+++ b/src/core/TransfersManager.cpp
@@ -186,6 +186,13 @@ void Transfer::start(QNetworkReply *reply, const QString &target)
        {
                temporaryFileName = QLatin1String("otter-download-XXXXXX.") + m_mimeType.preferredSuffix();
        }
+       else if (temporaryFileName.contains(QLatin1String(".tar.")))
+       {
+               QStringList parts(temporaryFileName.split(QLatin1String(".tar.")));
+               parts[parts.count() - 2].append(QLatin1String("-XXXXXX"));
+
+               temporaryFileName = parts.join(QLatin1String(".tar."));
+       }
        else if (temporaryFileName.contains(QLatin1Char('.')))
        {
                QStringList parts(temporaryFileName.split(QLatin1Char('.')));
```
The down side is that every other composite file extension (I can think of everything ending with .bz2 .gz, .xz, .lzma, .bro, .zst and having more than 1 dot in the file name) would need to be handled separately.

Even though option 3 is most visible to the user, I think that is the cleanest solution.

**Comment by vbr** [comment]
Hi, just an idea, from the user perspective - I think, it is preferable to maintain the original file name in a recognisable form, prepending an "uniformative" unique string could partly harm this.
Could the unique code be possibly just appended *before* the first dot of the filename? - if there is some convention for version numbering between dots, the unique code could possible be separated in some more "aggressive" way, e.g. OriginalFileName__Sj7100__.3.9.17.xml
This way the multiple extensions would be handled generically and both parts of the original filename would be recognisable. A cosmetic downside is the unusual part __. for ordinary filenames without numbering and with just one extension.
regards,
         vbr

**Comment by midluk** [comment]
Your solution is my number 2. Problem here is that the version numbers start before the first dot. You get (for a software version 2.3.5) softwarename_2-xnnnnn.3.5.tar.gz. Definitely better than softwarename_2.3.5.tar-xnnnnn.gz, but not perfect.

**Comment by beastie1** [comment]
Option 2 is not good IMHO. The implementation will be messy and overly complicated.

You've mentioned "file.names.with.version.num.b.er_s", but there's also those "file.names.that.use.dots.instead.of.spaces".

Either appending or prepending should be good though.
