### ISSUE TITLE
Show PDF files with PDF.js 

### ISSUE THREAD

**Issue by chrip** [OtterBrowser/otter-browser#1291]
The otter browser code is very good and the best reference for an example how to use Qt's webengine in the real world. The only thing I missed was a good example how to extend Qt's webengine with a PDF viewer. The easiest way I could find was to use [Mozillas PDF.js](https://github.com/mozilla/pdf.js). It works straight forward in our production system and is very easy to include. I uploaded an example [here](https://github.com/chrip/qt_simplebrowser_pdf). 
I would love to see PDF added to the otter browser!

**Comment by Frenzie** [comment]
A quick search also came up with http://blog.qt.io/blog/2017/01/30/new-qtpdf-qtlabs-module/ (Qt wrapper around PDFium) and of course good old Poppler has Qt bindings as well. NB I'm not really offering an opinion one way or the other. PDF.js is decent enough for most files but can be a touch slow for me on bigger ones.

Btw, for some reason PDF.js looks very blurry in my Otter.

Demo page: https://mozilla.github.io/pdf.js/web/viewer.html

On top is Firefox, nice and sharp. Below is Otter.
![screenshot_2017-02-28_10-24-45-fs8](https://cloud.githubusercontent.com/assets/202757/23399347/37a0e7a0-fda0-11e6-93d8-bf43b722dcf5.png)

**Comment by pierreporte** [comment]
This was already discussed in #60.

**Comment by Frenzie** [comment]
I forgot all about that, but note that the PDFium Qt wrapper I mentioned above is brand new and didn't exist at the time.

**Comment by Emdek** [comment]
I'm still not convinced, *QtPdf* might be interesting in future, so far it can only output images, so no text interaction etc.

Instead it should be a priority to make it easier to add third party modules.

**Comment by Frenzie** [comment]
Oh, I wasn't trying to convince. I'm more than happy opening things in a separate viewer.

**Comment by Emdek** [comment]
@Frenzie, that was just general comment (I would use @ otherwisse). ;-)
