### ISSUE TITLE
Weekly 165 Windows build issues

### ISSUE THREAD

**Issue by uahim** [OtterBrowser/otter-browser#1293]
on Win 7 x64, that is

UI is still white for no reason
(as described in https://github.com/OtterBrowser/otter-browser/issues/1276#issuecomment-280359386 )

inspector is broken, it appears in a tiny box in the upper left corner
![clipboard01](https://cloud.githubusercontent.com/assets/6866794/23470758/888895ca-fea7-11e6-9a2d-bd8ff53a410e.png)

**Comment by Emdek** [comment]
Duplicate of #1276 (nothing new).

**Comment by uahim** [comment]
@Emdek so the second issue is a duplicate too? :)
I noticed the inspector issue doesn't appear with a fresh profile, if that matters.

**Comment by Emdek** [comment]
@uahim, yes, apparently it was introduced in 163 but I cannot reproduce it (already existing profiles).
