### ISSUE TITLE
Updater only works partially

### ISSUE THREAD

**Issue by uahim** [OtterBrowser/otter-browser#1294]
Win 7 x64:
I cannot check within 165 build, but it was still present in 163 (and before) a few minutes ago: when I manually run Help | Check for updates, if a new version is available, the right button is greyed out and there is a message informing me that "a version for my OS may not be available" which is obviously wrong.
it should be noted that I delete the OpenSSL DLLs within the Otter directory because I have it (OpenSSL) installed seperately with the DLLs being in Windows dir. could this be the reason?

**Comment by Emdek** [comment]
It's not related to OpenSSL, there is no metadata which is required by current tool.
We are considering moving away to different solution, see #1175.

**Comment by uahim** [comment]
for what it's worth, in the meantime: my updater (for Otter on Windows) still seems to be working:
http://thewilderness.bplaced.net/otter-updater/
