### ISSUE TITLE
Default useragent in about:config don't work

### ISSUE THREAD

**Issue by c-cesar** [OtterBrowser/otter-browser#1295]
In about:config network > useragent I can change the browser default useragent, but this setting is not apllied and new tabs still using the default "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Otter/0.9.91",

**Comment by Emdek** [comment]
@c-cesar, it doesn't work that way, it expects identifier set in Preferences.
Although there is exception, you can prefix it with `custom;` to emulate feature used when setting UA for tab.

**Comment by c-cesar** [comment]
Well, thanks for pointing me the working way to do this, but if the option is in about:config it should work too in my opinion. This is the expected behavior. 

Setting a custom UA per tab in View menu is working flawlessly. =]

**Comment by Emdek** [comment]
@c-cesar, now it should be more obvious. ;-)
But we should reconsider some sort of hints to make it more obvious where they can be configured.
