### ISSUE TITLE
Tab handle context menu actions only applied to the active tab

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#1298]
Like the title says, all the actions in the tab handle context menu are only applied to the active tab.

For example, if you right-click any tab other than the active one and try to pin it, close it or clone it, instead of running those actions on the right-clicked tab, Otter will run them on the currently-active tab.

**Comment by Emdek** [comment]
@beastie1, it seems that information about target tab is lost, I'm debugging it right now.
