### ISSUE TITLE
Google Drive download and Transfers tab

### ISSUE THREAD

**Issue by finkiki** [OtterBrowser/otter-browser#1300]
While I'm downloading any type of file from Google Drive, the Transfers tab doesn't show the download progress in the progression bar. 
The download directly go from 0% to 100%. Time left is not show, just download Speed.

This wasn't a direct download link, maybe a google drive direct download act differently ? (not tested)
Others sources of download are showed well in progress bar.

Windows 7/ weekly 165 64 bits.

**Comment by Frenzie** [comment]
Servers don't always return the `Content-Length` header, usually because they don't know the size in advance as they're generating it on the fly. Presumably the same thing will happen in all other browsers.

**Comment by finkiki** [comment]
Right, it seems to happen to all unknow size download.
