### ISSUE TITLE
Show when file size is unknown during transfers

### ISSUE THREAD

**Issue by pierreporte** [OtterBrowser/otter-browser#1302]
Related to #1300. Sometimes, servers do not provide the file length of downloaded files. Otter interprets this so that the progress bar goes immediately at 100% which is confusing enough to make at least one person to open an issue about this.

Instead of the current behaviour, the progress bar should be in indeterminate state, that is going back and forth until the transfer is over. It is what Firefox does and it avoid misinterpretation. Moreover, the file size and remaining time should be written as unknown. This way, everything will be clear.

**Comment by Emdek** [comment]
Sadly someone decided that such mode should ignore text. :-|
https://bugreports.qt.io/browse/QTBUG-16260
