### ISSUE TITLE
segfault with qtwebengine

### ISSUE THREAD

**Issue by tjelbert** [OtterBrowser/otter-browser#1303]
QObject: Cannot create children for a parent that is in a different thread.
(Parent is Otter::ContentBlockingManager(0xeb1d70), parent's thread is QThread(0xb5e910), current thread is 
QThread(0x7fff8809bfd0)

Thread 15 "Chrome_IOThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff9e7fc700 (LWP 24252)]
Otter::ContentBlockingProfile::evaluateRulesInNode (this=this@entry=0x7fff880a11e0, node=node@entry=0x0, currentRule=...,
    resourceType=resourceType@entry=Otter::NetworkManager::MainFrameType)
    at /var/git/qt5/qt5-apps/otter/src/core/ContentBlockingProfile.cpp:834
834             for (int i = 0; i < node->rules.count(); ++i)

# after disabling content blocking:
#
# Fatal error in /usr/src/qtwebengine-opensource-src-5.8.0/src/3rdparty/chromium/v8/src/runtime/runtime-numbers.cc, line 124
# Check failed: radix == 0 || (2 <= radix && radix <= 36).
#

**Comment by Emdek** [comment]
Fixed for next release.
