### ISSUE TITLE
HTTP content on HTTPS pages

### ISSUE THREAD

**Issue by lollox** [OtterBrowser/otter-browser#1305]
For what I can understand, when you're on a HTTPS page that loads content from HTTP source, that source is not loaded.

This is particularly tedious when I'm on InoReader and all articles I try to read have images from non HTTPS source

In all other browsers instead they simply give you an alert (generally a badge in the address bar for mixed content)

Is it intended? Or how should otter handle this kind of situations?

**Comment by Emdek** [comment]
@lollox, I need some test case, so far I've only seen Firefox sometimes letting to load some insecure content when HTTPS is in use.
You can also try to set *Security/AllowMixedContent*, but that might work or not, since behavior of revived QtWebKit changed to match others and option to restore old behavior was added after TP5.

**Comment by lollox** [comment]
My experience is quite limited since I use for the most only InoReader and Gmail and the issue is present only in the first one (Gmail doesn't load external content by default for what I know)

However I tested several browsers (Opera 12.1, Opera_chromium, Vivaldi, Firefox, QupZilla)  and all load the insecure content without any problem (sometimes a badge and/or an alert appears in the addressbar, but I didn't understand when this happens and when it doesn't)

**Comment by Emdek** [comment]
@lollox, I need some specific URL for testing, since behavior may depend on additional factors.

**Comment by Frenzie** [comment]
I believe old Opera is from an era when this wasn't yet considered as big of an issue.

Chromium-based browsers can be started with `--allow-running-insecure-content` but I don't know if that works in combination with [Strict Transport Security](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security).

I think the default behavior in lieu of HSTS is that Firefox loads with a warning, whereas Chromium & co. display a warning where you can click "load anyway".

Test page: https://www.bennish.net/mixed-content.html

**Comment by Emdek** [comment]
@Frenzie, yeah, classic Opera shouldn't be even considered in this case.
*Security/AllowMixedContent* is supposed to work in similar way to that Chromium option but right now we cannot implement it in QtWebKit backend yet.

BTW, HSTS support for QtWebKit is coming soon, it was added in Qt 5.9.

**Comment by lollox** [comment]
For what I can see, the issue I described in InoReader soesn't act as the test page posted by @Frenzie  (where I get all the alerts and the insecure content is blocked, using all browsers as Opera, Vivaldi or Firefox)

But in InoReader (HTTPS) instead Opera, Vivaldi or Firefox load external images though HTTP without alerts, while Otter simply don't load these images

Probably is a different kind of problem?

**Comment by Emdek** [comment]
@lollox, to get old (insecure) behavior you can toggle *Security/AllowMixedContent*, right now it is available only for legacy QtWebKit, enabling it for revived QtWebKit will be possible once we will be able to depend on next release after TP5.
