### ISSUE TITLE
Report a Site Problem button

### ISSUE THREAD

**Issue by paradogz** [OtterBrowser/otter-browser#1309]
Feature request: add a button (menu item) for reporting site problems via [Webcompat.com](https://webcompat.com/issues/new), since some websites work incorrectly in Otter.

**Comment by Emdek** [comment]
I've never heard about that, does any browser add such action?
This sounds more like a task for some extension anyway.

**Comment by pierreporte** [comment]
Firefox has this action, called [Firefox Input](https://qsurvey.mozilla.com/s3/FirefoxInput/) available in the main menu. I don’t know if it’s still supported, the system behind it has changed for sure but I couldn’t find any relevant information during my quick search.

I don’t think this is a task for an extension, and in fact I believe it would be an essential feature. However, it shouldn’t be by using the Webcompat service but with our own infrastructure. The feature would send all data that identifies the browser version, operating system, backend, etc. plus some text that the user would like to enter. All this would be stored in a specific system like the crash reporter.

**Comment by Emdek** [comment]
@pierreporte, but what would be the point of filling disks with that data?
We are not developing rendering engine here so it is close to useless for us.

**Comment by beastie1** [comment]
@Emdek, please check the Help menu in classic Opera. ;)

But I agree this is out of the scope of the Otter project. Unlike classic Opera and Firefox which are the main developers and users of Presto and Gecko, the Otter project is not tied to a particular backend the same way these are.

**Comment by Emdek** [comment]
@beastie1, right, forgot about that one.

Anyway, for now I don't see how it could help us, with few exceptions such stuff could be only interesting to WebKit developers.

**Comment by paradogz** [comment]
> does any browser add such action?
Webcompat seems to be used in Firefox Nightly: https://miketaylr.com/posts/2017/01/report-site-issue-button-in-firefox-nightly.html

**Comment by Emdek** [comment]
@paradogz, well, it's more justified there since in these versions they actually can break rendering from time to time. ;-)

BTW, nowadays rendering engines development sort of stagnated, even Microsoft doesn't have extremely large gap to fill...
New technologies are either not really that useful or show up at a rate that others can catch up easily.
