### ISSUE TITLE
Improved Tab Closing Action

### ISSUE THREAD

**Issue by thecreamedcorn** [OtterBrowser/otter-browser#1314]
I always really liked the way that Internet Explorer closed tabs. When a tab was closed all the other tabs would instantly resize so that the user would not have to move the mouse in order to close the next tab. As soon as the mouse moved off the tab bar then all the tabs would go back to normal size.

Here are pictures of the tabs resizing as they are closed (the pictures are a little out of alignment only because of cropping)
![cap1](https://cloud.githubusercontent.com/assets/25673290/24228167/f4e63d92-0f48-11e7-98e9-215c621b5d96.png)
![cap2](https://cloud.githubusercontent.com/assets/25673290/24228171/fb662f7e-0f48-11e7-9055-9627693692a6.png)
![cap3](https://cloud.githubusercontent.com/assets/25673290/24228172/fd98a9fc-0f48-11e7-815d-04060c05d973.png)

I'm thinking that it could be an option in the tab bar edit entry (I don't think one exists currently). I'm also not sure if this would be worth considering as a goal in #190 or kept seperate.

**Comment by Emdek** [comment]
@thecreamedcorn, uhm it's kind of an opposite of what we do, in our implementation you are supposed to do the same by starting with the leftmost tab, they won't resize until leaving tab bar so next one the the right will end up in the same place.

**Comment by Frenzie** [comment]
But so does Otter? (And Opera, and Firefox, and…)
