### ISSUE TITLE
crashes on some (ad-heavy) sites

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#1315]
Hi,
I am experiencing rather regular crashes of Otter while browsing some sites, most often these are ad-heavy news sites like
http://technet.idnes.cz/planeta-saturn-sonda-cassini-mesic-pan-dh7-/veda.aspx?c=A170313_160926_veda_mla

Most regularly a crash occurs after clicking on some link in such page, like a discussion page below the article: "Vstoupit do diskuse..."
http://technet.idnes.cz/diskuse.aspx?iddiskuse=A170313_160926_veda_mla

This crashes don't appear, if the linked pages are opened in new tabs (via mousewheel clik) or, yet more reliably, in private tabs or windows via context menu.

(I am wondering, whether this can be connected with the issues of QNetworkAccessManager like
https://github.com/OtterBrowser/otter-browser/issues/1308 
There is an analogy in "fresh" tab instances not having such problems; however, these crashes also appear on stable network connection (while the other mentioned problem in issue 1308 probably only matters on  wifi network failures).)

I recently don't send the automatic crash reports in such cases, as they appear to be rather uniform, hence  creating noise in the debug data. If the reports are desirable, please let me know. Is there maybe something more to check for (like some designated settings)?

Using Otter win64-weekly168 on Win7, tested both, with and without the adblock.

Thanks and regards,
    vbr

**Comment by ondrej-zary** [comment]
I have the same problem on Linux. It's probably a webkit bug because Midori likes to crash the same way. Looks like some race because it's more likely to happen with slower CPUs.

**Comment by Emdek** [comment]
@ondrej-zary, any backtraces? Which version of QtWebKit (legacy might be not worth checking)?

**Comment by franco27** [comment]
I can not assert the problem with an earlier version. I recently discovered Otter.
On my second computer with Windows 10 x32bits and version OtterBrowser:
- installer for Windows 7 or later, 32 bit (29 MiB) + Weekly report #195 (25-09-2017).

Crash repetitive
example for this url:
https://secure.internetdownloadmanager.com/buy_idm.html

**Comment by riBoon** [comment]
Maybe I have the same problem, maybe its another one.
This URL:
https://www.heise.de/newsticker/meldung/Amazon-Marketplace-Haendler-erhielten-kein-Geld-3881243.html
and clicking on link "Verkäuferforen" (in the middle of the page)
(its german at all but the text doesn't matter)
After clicking Link otter browser crashes with "memory access denied"
As franco27 said open it with right click and "new tab" all is fine.


Done a strace starting otter browser, opening the url above and click on the link. If you need more debug things please tell us what you need.
Have the latest rc2 build "Otter 0.9.92 weekly 200" with "Qt version 5.10.0"

[otterbrowser-strace.txt](https://github.com/OtterBrowser/otter-browser/files/1449583/otterbrowser-strace.txt)

**Comment by riBoon** [comment]
Someone is working on it in a newer Issue #1453

**Comment by riBoon** [comment]
@vbr My problem is fixed with solving #1453. Could you please check if the newest weekly also fixed your one?

**Comment by franco27** [comment]
Problem solved
https://secure.internetdownloadmanager.com/buy_idm.html

**Comment by vbr** [comment]
Hi, thanks for the notice, it indeed seems, the originally mentioned problems are probably solved; I don't see these crashes on Otter 64bit, RC3. vbr

**Comment by riBoon** [comment]
Ok, then someone should close it. Can't do that or don't know how :D
