### ISSUE TITLE
Entire page content scrolls to the right if sidebar is open

### ISSUE THREAD

**Issue by uahim** [OtterBrowser/otter-browser#1316]
as of the last several builds, on some pages, when the mouse cursor moves over certain elements of the page - e.g. the ad bar ("Anzeigen") in between the matches on https://www.ebay-kleinanzeigen.de/s-freizeit-nachbarschaft/berlin/c185l3331 - the entire page including the scroll bar (1) content moves out of visible range to the right. OS is Win7 x64.
( (1) may be somehow related to https://github.com/OtterBrowser/otter-browser/issues/1276#issuecomment-280934501 which is actually fixed, so I'm not sure )

as the inspector is still unusable ( https://github.com/OtterBrowser/otter-browser/issues/1276#issue-211142668 ) I can not pinpoint the html element responsible for this.

update 1
managed to track it down to toolBars.json - which ironically is the second most important settings file (after otter.conf) to me, and it's rather time consuming to rebuild it from scratch to satisfy my needs.
[toolBars.json.txt](https://github.com/OtterBrowser/otter-browser/files/865611/toolBars.json.txt)

update 2
got it! it's caused by the sidebar.
if it's open, it causes the behavior described above, if it's closed, everything is fine.

**Comment by uahim** [comment]
even though nobody seems to care, this appears to be fixed in weekly 170

**Comment by uahim** [comment]
whoops, it isn't. sorry.

**Comment by Emdek** [comment]
@uahim, sorry, but some stuff gets higher priority, and more obvious stuff goes first. ;-)
And this one sounded like some sort of page issue.
I'll investigate it later this week.

**Comment by uahim** [comment]
@Emdek I'm aware his ma ynot be high priority, but it has been quite a while and I see that this is neither assigned to anyone nor has it a "bug" tag; is it even a bug or just me?
the same can be said for the still unsable inspector (which doesn't seem to have its own ticket? or so it seems)

**Comment by beastie1** [comment]
I don't really understand what's the problem here. Are you trying any of this using a brand new profile?

Here's what it looks like for me with the sidebar open, along with the element inspector:
![screenshot-otter_06072017-220326](https://user-images.githubusercontent.com/6757832/27928376-a00d8e4a-6297-11e7-9e9e-30be0a1ab990.jpg)

**Comment by beastie1** [comment]
Or is this a WebEngine-only issue?

**Comment by uahim** [comment]
@beastie1 WebKit, but you are correct about the profile: none of this happens with a new one.

**Comment by uahim** [comment]
apologies - the inspector issue doesnt even appear in latest build(s), and the other one seems to be only affecting me with my 'old' profile (as usual, I keep rebuilding profiles once per quartal) so I'm closing this.

**Comment by Emdek** [comment]
@uahim, I'm pretty sure that this issue was sort of relevant, but perhaps it got indeed fully fixed in the meantime.

**Comment by uahim** [comment]
for what it's worth, I have finally pinpointed this -  it happens if I create a new toolbar (on top) and add a "status field" to that.
