### ISSUE TITLE
Tabs placed below addressbar

### ISSUE THREAD

**Issue by pafri** [OtterBrowser/otter-browser#1319]
The tip, how to fulfil the wish of one user (read in some discussion about the new (prepared) appearance of Firefox), who wants to have the tab bar under control - the option to set/have placed the tabs this way:

(as the old times...**?**) **search field above a below it the tabs** (but now allegedly just Firefox browser (and its clones) can do it, and **only thanks to some extensions** - and probably only for short time).

Can/could Otter Browser set the tabs this way?

**Comment by Emdek** [comment]
Yes.

Go to View -> Toolbars and create new toolbar and setup it to look like address bar (using context menu action to trigger configuration dialog) and then hide already existing toolbar in the same menu.
Then use drag and drop to rearrange them (there is small drag and drop handle on the left edge of toolbar when they aren't locked), you can place them in any order on any edge.
