### ISSUE TITLE
unable to enter numeric values in login or password file with qtwebengine

### ISSUE THREAD

**Issue by tjelbert** [OtterBrowser/otter-browser#1320]
any numeric key causes jumping to any other tab or crash

eg

try to connect to
http://webmail.scarlet.be
and use a name containg some numeric or specail char for user or password

This only happens with qtwebengine

**Comment by BenTalagan** [comment]
I have a slight different problem which may be related : with QtWebengine, using the <kbd>Backspace</kbd> key in a textfield will trigger a 'Back in History' action instead of deleting one char. Some other keys are working correctly (e.g. letters, numbers). 

It does not happen with QtWebkit.

**Comment by Emdek** [comment]
Cannot reproduce with current master, QtWebEngine from Qt 5.9, but yeah, that used to happen for sure.
