### ISSUE TITLE
notify me when rss reader done

### ISSUE THREAD

**Issue by kloun** [OtterBrowser/otter-browser#1323]
subj

**Comment by m4sk1n** [comment]
hi, it's already in TODO list. Unfortunately, Otter Browser don't have feature that can notify you about adding RSS reader...
btw, what do you expect from feed reader

**Comment by Chocimier** [comment]
> Otter Browser don't have feature that can notify you
we could create a feed at otter-browser.org

**Comment by pierreporte** [comment]
There wasn’t an issue about the RSS reader. Now that there is one, we could use it to discuss about it. When it will be implemented, this issue will be closed and you will be notified. That being said, you should rename the title to something like “RSS reader”.

**Comment by Emdek** [comment]
Nah, this ticket is invalid, I'll prepare new one later from scratch.

**Comment by zakius** [comment]
> btw, what do you expect from feed reader

look at newsfox
improve minor annoyances like having to click it to scroll
Smart RSS for example lacks one core feature: being able to middle-click on the title on the list to open in new tab, I'd be glad to take part in early tests if possible

**Comment by Emdek** [comment]
Finally a proper ticket: #1415.
