### ISSUE TITLE
Small issue with appimage AppRun

### ISSUE THREAD

**Issue by disarmer** [OtterBrowser/otter-browser#1324]
Now otter-browser.sh script is used to run browser in appimage. But /bin/sh process stays alive, all time while browser running. You can check it with "ps fax":
 \_ -zsh                          (where i running appimage)
   \_ /bin/sh /tmp/.mount_B5td4G/AppRun
      \_ ./otter-browser

You can save a bit of memory(~3MB) by adding "exec" before calling binary:
exec ./otter-browser ${1+"$@"}
By the way, why you are using ${1+"$@"}? "$@" should be enought, isn't it?

And one another optimization: cd `dirname $0` => cd $APPDIR (APPDIR is mounted path exported by appimage itself)

**Comment by Emdek** [comment]
@disarmer, AFAIR it was based on some existing example or something like that.

**Comment by Emdek** [comment]
I've tried this and I don't see any issues:
```shell
#!/bin/sh

export LD_LIBRARY_PATH=./lib
cd $APPDIR
exec ./otter-browser $@
```

**Comment by disarmer** [comment]
Great, but better to leave double quotes around $@, without them /bin/sh will do word splitting if arguments contain spaces:

```
$ func(){ printf "%s\n" "$@"; }; func firstargument "second argument"
firstargument
second argument
$ func(){ printf "%s\n" $@; }; func firstargument "second argument"
firstargument
second
argument
```

**Comment by Frenzie** [comment]
Same for $APPDIR I imagine, seeing how directory names can have spaces. Also see http://www.shellcheck.net/ for shell code quality issues.

**Comment by Emdek** [comment]
@disarmer, @Frenzie, is this fine?
```shell
#!/bin/sh

export LD_LIBRARY_PATH=./lib
cd "$APPDIR"
exec ./otter-browser "$@"
```

**Comment by Frenzie** [comment]
Looks fine to me!

**Comment by Emdek** [comment]
@Frenzie, OK, I'll use it in next version.
