### ISSUE TITLE
Error 301

### ISSUE THREAD

**Issue by ovas10** [OtterBrowser/otter-browser#1325]
When authorizing on many sites, the error is 301.
otter-browser v169 Win64x32xXP

**Comment by Emdek** [comment]
It seems that I've managed to find URL that reproduces this issue in consistent way (clicking last link in *Spis treści*):
http://pclab.pl/art73744.html

**Comment by ovas10** [comment]
What does it mean?

**Comment by Emdek** [comment]
@ovas10, it means that I should be able to finally fix it, since I finally can reliably reproduce it.

**Comment by Emdek** [comment]
And now I know why does it happen, so there is a big chance that I'll be able to fix it for this weekly.
