### ISSUE TITLE
Tab area completely blank

### ISSUE THREAD

**Issue by midluk** [OtterBrowser/otter-browser#1326]
Since revision 34b39c4892080c9640afe9ccdce1be3ba6608940 otter is completely broken. When I start otter, the tab area is completely blank (no content, no address bar). The tab bar also does not display properly, the first tab has its "close" button misplaced and all further tabs are just completely blank.
This is on Fedora Linux 25 x86_64.

**Comment by Emdek** [comment]
@midluk, is that new session or restored?
Any difference with empty profile (run with *--portable*)?

No issues here (both fresh and with restored session)...

**Comment by midluk** [comment]
That is an empty (just start page) default session.
It seems to work with a clean profile, but I would prefer to not have to setup everything again.

**Comment by midluk** [comment]
It seems to be the 
```
[TabBar]
OpenNextToActive=false
```
entry I have in my otter.conf. If I delete that, it works.

**Comment by Emdek** [comment]
@midluk, good catch, now I can reproduce it.
