### ISSUE TITLE
Feature : Add widget/way to reset the zoom level to 100%

### ISSUE THREAD

**Issue by BenTalagan** [OtterBrowser/otter-browser#1328]
Hi, currently that behaviour does not exist (double click on the zoom widget to reset the zoom level to 100%). 

It'd be a small, nice add :)

**Comment by Emdek** [comment]
@BenTalagan, uhm, does anyone do something like this?
I don't see it in classic Opera, and in our case it will have the same issues, it will first jump to value corresponding to clicked point.
Isn't it easier to simply customize that toolbar to contain such action?

**Comment by BenTalagan** [comment]
You're right! I was pretty sure about it, but it's done with a small menu on the left side of the slider. Also, in Vivaldi, they do it with a reset button at the left of the slider.

One way to achieve this could also be double-clicking on the handle of the slider, not the rail of the slider. That way you could make the difference between a click on the rail of the slider (to change the zoom level), a click on the handle (to start the drag and drop to change the zoom level), and a double click on the handle (to reset).

**Comment by Frenzie** [comment]
I think a reset button of some sort sounds like the better option.

**Comment by BenTalagan** [comment]
@Frenzie, I agree. And if we have customisable toolbars in the future, it can exist either in a simple button form, or in a more complex dropdown menu with more options (like in Opera 12).

**Comment by Emdek** [comment]
@BenTalagan, future is already here, just right click on Status Bar and select Configure. ;-)

Anyway, I'm against adding new default buttons there, they look bad, since Status Bar is so small by default (and should stay that way), I'm even considering removal of Zoom In and Zoom Out actions.

**Comment by BenTalagan** [comment]
> @BenTalagan, future is already here, just right click on Status Bar and select Configure. ;-)

Arrrrgh yes ! Absolutely fantastic. Maybe you could remove the Zoom In and Zoom Out actions by default, and put the Zoom Original action on the left of the bar instead? It's the default layout of Opera 12.

**Comment by Frenzie** [comment]
Btw, in other browsers <kbd>Ctrl</kbd> + <kbd>0</kbd> resets the zoom level and <kbd>Ctrl</kbd> + <kbd>=</kbd> is equivalent to <kbd>Ctrl</kbd> + <kbd>+</kbd>, although I don't know what they do in other keyboard layouts like AZERTY where that might make less sense.

**Comment by Emdek** [comment]
@Frenzie, I've updated default keyboard shortcuts (<kbd>Ctrl</kbd> + <kbd>0</kbd> and <kbd>Ctrl</kbd> + <kbd>=</kbd>).

Uhm, when you talk about "Zoom Original action on the left" do you mean that one in popup or something else?

**Comment by beastie1** [comment]
@Emdek, perhaps you could do as classic Opera did and implement a second option in the form of a combo box (editable, of course) with presets (including 100%).

**Comment by Emdek** [comment]
@beastie1, uhm, such combobox would require the same amount of clicks like popup with actions, and custom widget, so it doesn't sound like a good idea to me.

**Comment by Frenzie** [comment]
@Emdek Cool! :-)

Actually I misremembered the old Opera defaults (which I didn't use), presumably because of Vivaldi.

# Opera 12.16
![screenshot_2017-04-04_20-44-03](https://cloud.githubusercontent.com/assets/202757/24673121/74660f9c-1977-11e7-8b1b-00cb96c1f89d.png)

# Vivaldi 1.8
![screenshot_2017-04-04_20-44-52](https://cloud.githubusercontent.com/assets/202757/24673159/95d70262-1977-11e7-992c-5e336d4ae592.png)

**Comment by Emdek** [comment]
@Frenzie, I would say that they put too many icons there in Vivaldi.

**Comment by beastie1** [comment]
@Emdek, agreed. That's probably why they didn't have it as default. I think it was default at some point a long while ago but was dropped in the last few major releases.
Personally I'm good with Otter's current setup. I'm just brainstorming here ;)
Another option you could consider is adding a button in the address bar like Chrome/ium does.
![images](https://cloud.githubusercontent.com/assets/6757832/24673595/8e7dc776-1981-11e7-82df-6371f7483caa.jpg)

**Comment by BenTalagan** [comment]
The main reason I asked for that feature is because it's quite painful to go back to Zoom Original when you've changed the zoom level (especially when otter's slider proposes either 99% or 101% but not 100% ;) ;) ;) ) . OpenOffice, for example, has snapping and it works but I don't like it because you cannot fine tune the zoom level.

Thus, my current and preferred config is the following :

![capture d ecran 2017-04-04 a 21 10 18](https://cloud.githubusercontent.com/assets/427791/24674297/3e758b0c-197b-11e7-894b-7d70e6a9ae62.png)

That's what I meant by "Zoom Original action on the left" :) (@Emdek)

**Comment by Frenzie** [comment]
Enjoy this screenshot of my real Opera configuration full of mysterious toggles. :-P

Actually they're just indicators. I switched those things (JS, UserJS, CSS, fit to width, etc.) through keyboard shortcuts.

But yeah, that should all be kept to the user (like in Opera). The default image toggle on the taskbar in Vivaldi is a relic from another era, and I don't think the tile or screenshot button belong down there at all. But their idea of sticking reset zoom left of the slider seems pretty decent.

![screenshot_2017-04-04_21-04-33-fs8](https://cloud.githubusercontent.com/assets/202757/24674050/6cef683c-197a-11e7-8e9b-a9789dfaf54b.png)

**Comment by Emdek** [comment]
@beastie1, polluting address field is bad idea, it doesn't look bad in Chrome, but it's really bad in Firefox...

@BenTalagan, it's calculated using `QStyle::sliderValueFromPosition()`, I don't see a good way to workaround that. :-/

@Frenzie, my configuration from ~10 years ago had so many icons that I had to use special toolbar that could be toggled by action, but since it broke with every major upgrade I've gradually simplified it, and right now my setup is almost the same as defaults, just missing like two actions and showing menu bar instead of menu button.

**Comment by Frenzie** [comment]
@Emdek Same here. Otter is good enough to the point that i don't customize the GUI at all. My Firefox is also basically vanilla with menubar, statusbar, Tab Tree and proper Ctrl+Tab switching order from Tab Mix Plus. (Plus some non-GUI stuff except a little icon like NoScript, GreaseMonkey, and Stylish.)

**Comment by Frenzie** [comment]
Btw, because I never really use reset zoom I just noticed that the "Zoom Original" action goes to 100% rather than my default zoom of 200%. :-)

**Comment by Emdek** [comment]
@Frenzie, well, 100% is original. :-D
Also in classic Opera it goes to 100% instead of default value.
It seems logical that there should be separate action or parameter allowing to simply reset zoom instead.

**Comment by Frenzie** [comment]
Right, I've been talking about reset zoom to default this entire time (Ctrl + 0, reset button), not 100%.

**Comment by Emdek** [comment]
@Frenzie, well, for me Ctrl + 0 always gives 100% in classic Opera. ;-)

**Comment by Frenzie** [comment]
I used 100% default zoom in those days so I never noticed the big. :-p
