### ISSUE TITLE
HTML form selects look a bit ugly

### ISSUE THREAD

**Issue by BenTalagan** [OtterBrowser/otter-browser#1329]
Hi, this has been tested under MacOs only but maybe it is also the case under windows. It's a minor issue.

HTML selects (and maybe other html components) look a bit ugly under otter when compiled with webkit, compared to e.g. Safari or Firefox. The font is a bit too big, padding and margin are really big compared to other brothers, and padding cannot be set to 0 with CSS (whereas it is possible with Safari so it's a bit strange between webkit based browsers). See this example where you can compare the rendering of a form select between browsers :

https://www.w3schools.com/code/tryit.asp?filename=FEB8VRINMMYW

When compiled with QtWebEngine it looks far better.

**Comment by Emdek** [comment]
@BenTalagan, it's controlled by QtWebKit, we could try to manipulate it with custom `QStyle` but I doubt that we would be able to eliminate these issues, just improve look a bit.
AFAIK QtWebKit contains some code that could be used as universal style for controls.

**Comment by annulen** [comment]
Could you post screenshot please ~~just to laugh on~~? Works fine on Linux with fusion style.

@BenTalagan Try running with -style fusion argument

Emdek: you indeed might want to use other QStyle on Mac for your webview, QMacStyle is the worst offender of all Qt styles, e.g. there was https://github.com/annulen/webkit/issues/269 and there might be other bugs on both sides

**Comment by Emdek** [comment]
@annulen, yeah, that `QStyle` is bogus, I've noticed that it simply ignores hints like `QRect` (similar to that issue with misplaced check box).
Although I would prefer to have some sort of option to force universal style for all web views without creating multiple instances of `QStyle`...

**Comment by annulen** [comment]
setStyle takes QStyle*, so you don't need multiple objects

That said I'll try to fix QMacStyle-related bugs if there are minimal test cases for them

**Comment by Emdek** [comment]
@annulen, indeed, "The ownership of the style object is not transferred.".

**Comment by BenTalagan** [comment]
@annulen, yes sure.

With QtWebEngine (very close to chromium/firefox/safari) under MacOs :

![capture d ecran 2017-04-04 a 21 31 24](https://cloud.githubusercontent.com/assets/427791/24675238/b3422f1e-197e-11e7-8c41-4c2e455bf93b.png)

With QtWebkit under MacOs : 

![capture d ecran 2017-04-04 a 21 32 15](https://cloud.githubusercontent.com/assets/427791/24675257/c42008b0-197e-11e7-8f3d-5815c1bf8dec.png)

With QtWebkit under MacOs with Fusion style :

![capture d ecran 2017-04-04 a 21 33 02](https://cloud.githubusercontent.com/assets/427791/24675289/d71f4278-197e-11e7-9d14-675951b4c157.png)

**Comment by annulen** [comment]
Could anyone try  if this patch helps?
```diff
diff --git a/Source/WebKit/qt/WidgetSupport/QStyleFacadeImp.cpp b/Source/WebKit/qt/WidgetSupport/QStyleFacadeImp.cpp
index b35545674b3..09e427272dd 100644
--- a/Source/WebKit/qt/WidgetSupport/QStyleFacadeImp.cpp
+++ b/Source/WebKit/qt/WidgetSupport/QStyleFacadeImp.cpp
@@ -225,7 +225,7 @@ void QStyleFacadeImp::getButtonMetrics(QString *buttonFontFamily, int *buttonFon
     *buttonFontFamily = defaultButtonFont.family();
     *buttonFontPixelSize = 0;
 #ifdef Q_OS_MAC
-    button.setAttribute(Qt::WA_MacSmallSize);
+    button.setAttribute(Qt::WA_MacVariableSize);
     QFontInfo fontInfo(defaultButtonFont);
     *buttonFontPixelSize = fontInfo.pixelSize();
 #endif
```
