### ISSUE TITLE
Selected tab shows black on MacOs + QtWebengine

### ISSUE THREAD

**Issue by BenTalagan** [OtterBrowser/otter-browser#1330]
Hi, (and sorry for the bug report pace, but I'm more and more fond of otter!)

Under MacOs, the tabs appearance differ between QtWebkit :

![capture d ecran 2017-04-05 a 17 41 36](https://cloud.githubusercontent.com/assets/427791/24714078/b80262e0-1a27-11e7-9c74-ba88ac0670ae.png)

and QtWebengine :

![capture d ecran 2017-04-05 a 17 42 42](https://cloud.githubusercontent.com/assets/427791/24714086/bb1e4958-1a27-11e7-8ee2-4e4743565f0f.png)

In both cases, the aspect of tabs is not exceptionally beautiful but as I understand a relooking is planned before 1.0. The black color of selected tabs is a bit handicapping though.

**Comment by m4sk1n** [comment]
have you tried changing qstyle?

**Comment by BenTalagan** [comment]
Ok, I've just tested. The 'black' bug does not appear with fusion or windows style. 

I've also noticed that when launching otter without any open tab, the tab appearance is OK, I can open empty tabs without triggering the bug. It only happens as soon as a real web page is loaded. After that, the selected tab will always be black.

Relaunching otter will clear the bug - except in the case where it automatically reloads an open web page on startup (that triggers the bug again because of the re-load).

**Comment by Emdek** [comment]
@BenTalagan, it seems to be Qt bug, I've prepared minimal test case, could you give it a try too?

test.pro:
```pro
QT       = core gui widgets webenginewidgets
TARGET   = qtwebengine_macos_unifiedtitleandtoolbar
TEMPLATE = app
SOURCES  += main.cpp
```

main.cpp:
```cpp
#include <QtWidgets/QApplication>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QTabBar>
#include <QtWidgets/QToolBar>
#include <QtWebEngineWidgets/QWebEngineView>

class MainWindow : public QMainWindow
{
public:
	MainWindow() : QMainWindow()
{
	QTabBar *tabBar(new QTabBar(this));
	tabBar->setDocumentMode(true);
	tabBar->addTab("Tab 1");
	tabBar->addTab("Tab 2");
	tabBar->addTab("Tab 3");

	QToolBar *toolBar1(new QToolBar("Toolbar 1", this));
	toolBar1->setMovable(true);
	toolBar1->addAction("Action 1");
	toolBar1->addSeparator();
	toolBar1->addAction("Action 2");

	QToolBar *toolBar2(new QToolBar("Toolbar 2", this));
	toolBar2->addWidget(tabBar);

	addToolBar(Qt::TopToolBarArea, toolBar1);
	addToolBarBreak(Qt::TopToolBarArea);
	addToolBar(Qt::TopToolBarArea, toolBar2);
	setUnifiedTitleAndToolBarOnMac(true);
	setCentralWidget(new QWebEngineView(this));
}

};

int main(int argc, char *argv[])
{
	QApplication application(argc, argv);
	MainWindow window;
	window.show();

	return application.exec();
}
```

**Comment by BenTalagan** [comment]
@Emdek, great, thanks for your quickness! 

This is what I get :

![capture d ecran 2017-04-06 a 15 54 03](https://cloud.githubusercontent.com/assets/427791/24758073/76b6cf0a-1ae1-11e7-9634-9d4eeab65963.png)

Does it confirm your suspicion of a bug in Qt ?

**Comment by Emdek** [comment]
@BenTalagan, yes, thanks.
Upstream report:
https://bugreports.qt.io/browse/QTBUG-59980
