### ISSUE TITLE
Feature : Dev Tools and inspector with QtWebengine

### ISSUE THREAD

**Issue by BenTalagan** [OtterBrowser/otter-browser#1331]
That one is probably already on the TODO list, but having the dev tools with the inspector for Otter with QtWebengine would be awesome!

**Comment by m4sk1n** [comment]
https://github.com/OtterBrowser/otter-browser/wiki/QtWebEngine-Wishlist
Unfortunately, QtWebEngine currently does not support it… That's why its support in Otter Browser is called 'experimental'
Why can't you just use QtWebKit?

**Comment by BenTalagan** [comment]
> Unfortunately, QtWebEngine currently does not support it… That's why its support in Otter Browser is called 'experimental'

Well it did not seem to me very clear to me if it was supported or not when I posted my issue. See for example :

https://doc.qt.io/qt-5/qtwebengine-debugging.html or
http://stackoverflow.com/questions/28681141/qtwebengine-debugging

So probably, someone more instructed on that subject could explain the reality of this ?

> Why can't you just use QtWebKit?

QtWebKit is quite cool but there are small things here and there that I've seen for a few days which are dissatisfying visually to me under MacOs (form components not rendering very well, web fonts that do not render while they should whereas they do work in Safari for example...) so I've been hesitating between the two of them. I like the idea that otter proposes both backends, this is great, impressive and almost unique. People cannot complain about ideological choices (just like they would do with search engines too), Otter offers that kind of freedom. Awesome!

**Comment by Emdek** [comment]
@BenTalagan, upstream is currently working on proper support for dev tools without need to open any ports.

**Comment by BenTalagan** [comment]
Great news! Thanks for the update.

**Comment by Emdek** [comment]
@BenTalagan, bad news is that's planned for 5.11...

**Comment by Emdek** [comment]
Tested QtWebEngine version doesn't like usage of `QWebEnginePage::InspectElement` so it will crash when using "Inspect Element" action until it will be fixed upstream, use of "Inspect Page" doesn't cause issues.
