### ISSUE TITLE
mediasource extensions with qtwebkit fork

### ISSUE THREAD

**Issue by gothmog123** [OtterBrowser/otter-browser#1332]
They are not really working - audio disappears, video freezes, etc. 

Is it a qt bug?

**Comment by Emdek** [comment]
Nope, that's QtWebKit issue, see:
https://github.com/annulen/webkit/issues/334

I'm assuming that you have enabled them in the first place, using *about:config* (**QtWebKitBackend/EnableMediaSource**).
It's disabled since it's not bug free even with GStreamer backend.

**Comment by gothmog123** [comment]
Thanks, yes I have.

When are they planning to fix this? Full screen isn't working either.

They should be given a medal for reviving a non-spying browser engine (as opposed to webengine), but they need to fix these basic video issues quickly if they expect people to migrate over.

**Comment by Emdek** [comment]
@gothmog123, I think that it's in better shape (at least GStreamer support) in newer branch of WebKit, so it should be in better shape after merge, but that has to wait until current branch will be stabilized.

Fullscreen is not working? Are you using QtWebKit  TP5 or newer?

**Comment by gothmog123** [comment]
Yeah, up-to-date arch with tp5, lxqt.

**Comment by Emdek** [comment]
@gothmog123, do you see some message when trying to use it on pages like YouTube etc.?
I f you are using TP5 or newer then there are at least two possibilities, somehow you ended up with fullscreen disabled while configuring build or you are linking against older QtWebKit version (check reported QtWebKit version in About Otter in Help menu, it should show 602.1 or similar).

**Comment by gothmog123** [comment]
Thanks, webkit shows up as 602.1.

There's no message, what happens is the whole screen starts flickering and little pieces of the window are jumping around the screen.

**Comment by Emdek** [comment]
@gothmog123, it seems to be some weird regression unrelated to backend, I'm investigating it now.

**Comment by Emdek** [comment]
And it should be fixed now.

**Comment by gothmog123** [comment]
Cool, great work!
