### ISSUE TITLE
border between title bar and tab bar

### ISSUE THREAD

**Issue by gothmog123** [OtterBrowser/otter-browser#1333]
Sorry to open 2 issues in a row.

There's a border visible between the window title bar and the tab bar - when the menubar is disabled - and I think otter would look better without it - like FF, chrome, etc.  Just a suggestion.

**Comment by Emdek** [comment]
@gothmog123, it depends on Qt style, Firefox and Chrome ignore it.
Which one are you using? Some screenshot could help too.

**Comment by gothmog123** [comment]
Using the standard fusion theme set to a dark color scheme using qt5ct.
![a](https://cloud.githubusercontent.com/assets/5462340/24770119/21938252-1b09-11e7-8a8c-c5df173516e3.jpg)

**Comment by Emdek** [comment]
@gothmog123, I've tested it locally and it seems to be some sort of standard decoration for toolbars, but color is quite unfortunate for dark palettes, maybe even hardcoded.
You can try some other style, you can set it in Preferences -> Advanced -> Appearance.

**Comment by gothmog123** [comment]
ok, thanks.

**Comment by cofi89** [comment]
Similar here, though with these diferences:
- [qt5gtk2](https://bitbucket.org/trialuser02/qt5gtk2) is the style used
- border is visible on the navigation bar
<a href="http://www.zimagez.com/zimage/screenshot2017-04-0621-28-22.php">
  <img src="http://www.zimagez.com/miniature/screenshot2017-04-0621-28-22.php" />
</a>

**Comment by Emdek** [comment]
@cofi89, that one is something else, related to #1310.
It needs extra check to skip drawing it on last toolbar of belonging to main window when subwindow (tab) is maximized.
