### ISSUE TITLE
Switching tabs closes the web inspector

### ISSUE THREAD

**Issue by BenTalagan** [OtterBrowser/otter-browser#1334]
All is in the title :) That behaviour is probably not expected, right?

**Comment by Frenzie** [comment]
This only seems to happen on the updated WebKit backend (602.1 from weekly 170), not on the legacy backend (538.1, also weekly 170).

**Comment by BenTalagan** [comment]
Thanks for pointing this out, I'm under MacOs but building from source, and thus using 602.3 .

**Comment by Emdek** [comment]
@BenTalagan, @Frenzie, yeah, it's weird regression in revived QtWebKit, I've prepared minimal test case that works just fine with legacy but reproduces this issue with fresh *qtwebkit-stable* branch.

**Comment by BenTalagan** [comment]
Thanks, @Emdek !

**Comment by Emdek** [comment]
Here is upstream ticket:
https://github.com/annulen/webkit/issues/446

**Comment by Emdek** [comment]
@BenTalagan, I've found source of that issue and proposed fix, so hopefully it will be fixed in next snapshot (probably TP6 or alpha).

**Comment by BenTalagan** [comment]
@Emdek , awesome! Thanks a lot!
