### ISSUE TITLE
XDA Developers website is displayed incorrectly

### ISSUE THREAD

**Issue by fturco** [OtterBrowser/otter-browser#1340]
The following website is displayed incorrectly by Otter: https://forum.xda-developers.com/

![xda-developers](https://cloud.githubusercontent.com/assets/5459866/24877841/0a55077a-1e31-11e7-90e4-48d64cd49701.png)

No problems with XDA Developers under Firefox. No problems with any other website under Otter.

I'm using Otter 0.9.12 beta 12 on a Gentoo Linux system.

**Comment by Emdek** [comment]
@fturco, are you using content blocking or legacy QtWebKit (version older than 602)?

**Comment by Emdek** [comment]
Judging from screenshot styles could get blocked by content blocking (since it works fine even with legacy QtWebKit), try disabling it.

**Comment by fturco** [comment]
You're right. I had content blocking enabled (Easylist). Thank you!
