### ISSUE TITLE
Week 171: HomePage button without effect?

### ISSUE THREAD

**Issue by BorutAtGit** [OtterBrowser/otter-browser#1342]
No matter how I define the home page, at my place it seems that clicking on the home page button has no effect. (Tested with portable WinXP 32 bit legacy QtWebKit version on Windows 7.) If it is defined that Otter should start with a home page, that works so on start. But explicit click on home page button seems not to work.

**Comment by Emdek** [comment]
@BorutAtGit, is that button next to address field?

**Comment by BorutAtGit** [comment]
Oh, sorry, maybe my configuration is not a standard one. In my configuration it is not in the nav bar, but in the **tab bar**. Its definition at my place: Back, Forward, Reload or Stop, **Go to Home Page**, Tab Bar, -spacer-, List of Closed Tabs and Windows. But I guess we are basically having the same button in mind and only its position is different.
