### ISSUE TITLE
HTML5 video not playing (YouTube)

### ISSUE THREAD

**Issue by uzerus** [OtterBrowser/otter-browser#1345]
When i open youtube, select an video to load... It looks like it want play something (says me the lenght of media, the ads where it should be (in timeline) and.... it sucks. it tells something about try again later, there is an error. 

In YT it's player_error1 (something's wrong) i thing it's linked with [#1225](https://github.com/OtterBrowser/otter-browser/issues/1225)

OS: Linux
Distro: ArchLinux x64
Build: [AUR](https://aur.archlinux.org/packages/otter-browser/)
Version: 0.9.12 - official package from github

**Comment by Emdek** [comment]
@uzerus, it's one of these:
1. you are using legacy QtWebKit (WebKit version lower than 6xx, can be checked in Help menu), then you should use *qt5-webkit-ng* package (replacing old one should be enough);
2. you are using revived QtWebKit but codecs are missing, then you have to install relevant codecs for GStreamer 1.x.

You can also go for our AppImage instead, it also requires codecs for GStreamer 1.x but it needs OpenSSL 1.0 in the system too.

**Comment by PistachioGuy** [comment]
qt5-webkit-ng doesn't seem to exist anymore, what would I use now?
