### ISSUE TITLE
Regression: Full Screen mode not working

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#1349]
Full Screen mode doesn't seem to work anymore. The last time it worked for me was on April 13.

Now when I press F11 it hides all toolbars but doesn't switch to Full Screen. It only switches if I press F11 a second time.

And once it's in Full Screen it can't get out. When pressing F11 the screen just flickers and Otter stays in Full Screen.

**Comment by Emdek** [comment]
@beastie1, what WM are you using?
Is that fresh master?
Any difference when using context menu (it is available in default one)?
I would ask if  the same happens when entering or leaving fullscreen videos but it's not the case in legacy QtWebKit...

**Comment by beastie1** [comment]
I'm using Fvwm 2.6.7.

Yes, the very latest MASTER. Yesterday's build was the same. The one from April 13 worked fine. So it must be some change on the 14th or 15th.

The same thing happens using the keyboard shortcut, context menu and View menu.

**Comment by Emdek** [comment]
@beastie1, I see, as I thought, I've got a bit similar report for i3, where apparently WM fails to properly restore state after exiting fullscreen.

**Comment by midluk** [comment]
I can confirm that since revision f485847fdc959f6f68657a58555d2ac1741a46ad full screen does no longer work (legacy QTWebkit backend).
On KDE Plasma 5/Kwin the screen flickers shortly when I press F11 (or use the context menu) but nothing else happens. If the window is not maximized, the flickering is visible in the top left corner of the screen with the size of the window.

**Comment by Emdek** [comment]
@midluk, are you using current master?
It works fine here, same DE and WM.

**Comment by midluk** [comment]
@Emdek, yes, current master.
This is on Fedora 25 with plasma 5.8.6, kf5 5.33.0 and qt 5.7.1.

**Comment by BorutAtGit** [comment]
Actually I can confirm that it is also not working under WinXP with Weekly 172 with legacy WebKit (in portable mode). It flikers for a moment (so not forever, as was the case earlier) and then returns to normal.

**Comment by Emdek** [comment]
@beastie1, any difference with current master?

**Comment by midluk** [comment]
For me it seems to work again with current master.

**Comment by beastie1** [comment]
Indeed, it works fine now. Great job!
