### ISSUE TITLE
Regression: right-click/left-click confusion on toolbar icons

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#1350]
Right-clicking any icon on the Tab Bar or Navigation Bar (e.g. New Tab, Reload, Go, etc.) results in a left click action.

Note this doesn't happen for example with icons that have their own menus, such as the Back and Forward icons, which have the Clear/Purge menu.

**Comment by Emdek** [comment]
@beastie1, indeed.

BTW, are you using IRC maybe?
I'm considering restricting bug reports only to official releases (including weeklies) starting with May or June, so that would be the best channel for reporting such regressions then.

**Comment by beastie1** [comment]
I haven't use IRC in the past 15 years or so hehe. But if you find GitHub issues are being crammed with too many of these reports, then sure no problem.

**Comment by Emdek** [comment]
@beastie1, well, IRC is the fastest way to report them, in case of smaller issues you might get fix quickly, or I can ask about important details of bigger issues without waiting for reply (which usually means that fix will arrive sooner) etc. :-)
