### ISSUE TITLE
standalone "close tab" menu item always disabled

### ISSUE THREAD

**Issue by midluk** [OtterBrowser/otter-browser#1353]
The standalone "close tab" menu item (can be added to any menu bar) is always grayed out and can not be clicked. I'm pretty sure it worked at some point in the past.
Using the "close tab" icon in the individual tabs in the tab bar or the ctrl+w shortcut works.

**Comment by Emdek** [comment]
@midluk, I don't think that it ever worked that way, except for special (hardcoded) cases. But it should.

**Comment by midluk** [comment]
It broke with revision dd031a3fa1566a0a7bfdd04a1a5a9aa5a954fd9a.
Previously the button was always enabled and worked like clicking on the "close tab" icon in the currently active tab.

**Comment by Emdek** [comment]
@midluk, uhm, perhaps it lost "always enabled" state then.
I really need to finally finish that actions redo...
