### ISSUE TITLE
"Open in New Window" creates two tabs in new window

### ISSUE THREAD

**Issue by cfeck** [OtterBrowser/otter-browser#1354]
To reproduce:
- start otter-browser with default configuration
- go to any web page with links
- right-click on link and select "Open in New Window" from context menu

Actual results:
- the new window has two tabs, the first tab is the "Start Page" tab, the second (active) is the new tab

Expected results:
- the new window only has one tab

**Comment by BorutAtGit** [comment]
I can confirm this under WinXP in portable mode. 

Maybe also of interest in this context: If one opens a new Window **via Ctrl-N**, then the new window **does not receive focus**. (It receives focus when opened from menu: File > New Window.)

**Comment by Emdek** [comment]
@cfeck, cannot reproduce with current master, which version are you using?

@BorutAtGit, interesting, it's the same codepath, just different way of triggering it.
@bajasoft, any idea if Windows could mess it up when using keyboard shortcut?

**Comment by cfeck** [comment]
I just re-tried with 5fc22c719163a71fc95ad3dec1e132acd9330695 and the same issue happens. Using Qt 5.8.0 with QtWebKit 5.8.0.

**Comment by Emdek** [comment]
@cfeck, right, I've misread and tried another action (without link), confirmed.

**Comment by Emdek** [comment]
It's not a perfect way to deal with it but I don't have better idea right now...

**Comment by cfeck** [comment]
Merci, no problem :)
