### ISSUE TITLE
[site specific] arte.tv/guide/de lets Otter use up all available RAM

### ISSUE THREAD

**Issue by uahim** [OtterBrowser/otter-browser#1356]
latest weekly (173) on Win7 64

can anyone else confirm this?

**Comment by Frenzie** [comment]
Did you mean when you click to play a video? Just loading the URL you mentioned doesn't seem to do anything out of the ordinary for me on the 173 AppImage on Linux x64, but loading a video freezes the browser (albeit without a RAM increase).

**Comment by uahim** [comment]
@Frenzie simply loading the page, video plays fine in fact

**Comment by Emdek** [comment]
@uahim, is it reproducible with *test-qtwebkit.exe*?

**Comment by uahim** [comment]
yes, after a few seconds it does. and additionally, it uses 12-25% CPU time.

**Comment by Emdek** [comment]
@uahim, then it's some sort of issue with QtWebKit backend, could you please retry reproducing it after disabling *QtWebKitBackend/EnableMedia* in **about:config**?

**Comment by uahim** [comment]
@Emdek no change

**Comment by Emdek** [comment]
@uahim, uhm, what about plugins?
Try disabling them completely.

**Comment by uahim** [comment]
@Emdek they were disabled all along. maybe I should have mentioned that, though as far as I can tell there are video tags or plugins used on the page that could be causing this.

**Comment by Emdek** [comment]
@uahim, any change after disabling JS?

**Comment by uahim** [comment]
@Emdek yes, that was it!

**Comment by annulen** [comment]
@uahim Does it help if you keep JS enabled but run with environment variable `JSC_useJIT=0`?

**Comment by uahim** [comment]
@annulen I assume I am to put that in otter.conf, but which section? also, is it JSC_useJIT=0 or =false ?
thanks

**Comment by beastie1** [comment]
@uahim 

Press the "Windows key + R", type "cmd" and press "Enter"
Type "set JSC_useJIT=0" and press "Enter"
Type "otter.exe" (or whatever the name is in Windows) and press "Enter"

I think that should work.

**Comment by uahim** [comment]
@beastie1 ah I see, it's a system enviroment variable then, not an Otter setting.
however, that doesn't fix the memory issue.

**Comment by Emdek** [comment]
Closing since it's upstream issue.

@annulen, feel free to continue debugging here or in new ticket in your repository.
