### ISSUE TITLE
Opening a new windows with ctrl-n opens always in the background

### ISSUE THREAD

**Issue by hunderteins** [OtterBrowser/otter-browser#1362]
Hello,
this drives me mad. Since March 5th, otter-browser opens a new windows on ctrl-n always in the background. Checked that with an uptodate windows build. Same thing happend there. Does not happen with ctrl-alt-n nor 'New Window' in the menu, only on keystroke.

I digged around an found src/core/Application.cpp. When I replace 
createWindow();
with
createWindow({{QLatin1String("hints"), SessionsManager::NewWindowOpen}});
around line 528
this goes away.

regards
hunderteins

**Comment by Emdek** [comment]
@hunderteins, any difference in current weekly?
There was related issue caused by incompatible runtime change in newer Qt versions which caused various weird stuff.

**Comment by hunderteins** [comment]
still the same. Without the above change a new windows opens in the back.

**Comment by CyberC123** [comment]
Here the same, the new Window is always in the background, minimized and narrowed.
Version:
	Main Number         0.9.91
	Weekly Number       183

**Comment by Emdek** [comment]
OK, now I see how it can fail, there is no fallback value, but it still doesn't fully explain it.
