### ISSUE TITLE
Source viewer related bugs

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#1363]
1. The source viewer has no icons for its **Back** and **Forward** buttons. Personally I don't see how useful these button are in this case, but if we want to keep toolbars standard everywhere at least they should always have icons. ;-)

2. The source viewer should be disabled for blank tabs and the start page, just like it is for special pages. For the start page, the source viewer is empty. For new tabs it is also empty (which makes sense), but it also creates a second new tab with "Blank Page" as a title instead of the usual "(Untitled)".

**Comment by Emdek** [comment]
@beastie1, first point is not related to Source Viewer, all special pages are affected, it's side effected of unfinished actions rework.

**Comment by beastie1** [comment]
Great! Thanks for the commit. So do we close the issue?

**Comment by Emdek** [comment]
@beastie1, no, it's still a bug after all.

**Comment by beastie1** [comment]
And now it's fixed. Thanks!
