### ISSUE TITLE
windows xp - ssl

### ISSUE THREAD

**Issue by otterxp** [OtterBrowser/otter-browser#1364]
on windows xp sp3 we are having too much ssl issue.
always give error "connection is insecure". we should click advanced button to avoid problems.
(date-time is correct)

is it possible ignoresslerrors parameters will work with "true" parameter. and automaticly will pass this errors.

thanks

**Comment by m4sk1n** [comment]
Hi. What version of Otter Browser do you use?

**Comment by otterxp1** [comment]
#175 one.
actually i am having 2 issues on xp.
one is ssl and other one is mp3, webm files are not playing. (youtube, html5 videos etc)

**Comment by otterxp1** [comment]
btw in the office we have 300pcs with winxp and installed already. (call center in asia pacific)

for ssl issue i downloaded certificates and instaled manual (global sign, digicert...) but still a lot ssl certificates are there and cant do it manually :)

for html5 videos i have no solution yet. still looking.

**Comment by Emdek** [comment]
This change will land in next weekly, together with long awaited update to Qt 5.6 and revived QtWebKit.
It allows us to bundle Mozilla certificates which solves issues under XP and allows to add new certificates by simply adding new files to *certificates* directory next to otter-browser.exe or in profile directory.
