### ISSUE TITLE
No JavaScript in github pages with legacy qtwebkit

### ISSUE THREAD

**Issue by midluk** [OtterBrowser/otter-browser#1365]
Since a few weeks ago java script stopped working on github pages (sorting issues, network graph, issue preview). Neither reverting to an old version of Otter helped, nor should there have been any change to qtwebkit on my system in the last months. So I guess this is caused by some change in the github code itself. 
This is with current otter master with legacy qtwebkit, qt 5.7.1 on Fedora 25 x86_64 on two computers.
Firefox and the qtwebengine backend in otter do not show this problem.

In the developer console of otter I can find:
ReferenceError: Can't find variable: Promise
in the file https://assets-cdn.github.com/assets/frameworks-12370566edc60b404ac458967a7f2fa0d6696da99f37edf7deb1196f1aff5f0a.js

**Comment by midluk** [comment]
I finally managed to build the new qtwebkit and use it in otter. Github works now.
So this likely is a bug in legacy qtwebkit.

**Comment by Emdek** [comment]
@midluk, yeah, it seems that github devs don't care much about users, as such error is likely to hit users of many IE versions too, etc.
