### ISSUE TITLE
Less strings to translate by reusing common strings

### ISSUE THREAD

**Issue by scootergrisen** [OtterBrowser/otter-browser#1367]
The numbers of strings to translate could be improved much.
If for example common strings like "Delete" and "Remove" and "Open in New Tab" etc. would not have to be translated 5-10-20 times exactly the same way.
So just translated the string one time and then reuse the string in the software multiple places.

**Comment by Chocimier** [comment]
They are separate for a reason: same English string "Delete" may need to be translated differently depending of e.g. grammatical gender of what is deleted.
That problem should be rather handled by translation tool you use. Qt Linguist is able sort strings, so it is easy to spot same already translated source string and to propose reusing its translation.
