### ISSUE TITLE
Support for Ubuntu Touch

### ISSUE THREAD

**Issue by nfsprodriver** [OtterBrowser/otter-browser#1369]
Hi there! Is there a possibility to build this for Ubuntu Touch? If yes, will there be a mainfest, apparmor and the instructions be added? Thanks for yours answers!

**Comment by Emdek** [comment]
@nfsprodriver, Ubuntu Touch is sort of dead, and AFAIK nobody in the team has access to such devices, so no, there will be no such support, sorry.
