### ISSUE TITLE
{searchTerms} cannot contain '@' character

### ISSUE THREAD

**Issue by cfeck** [OtterBrowser/otter-browser#1373]
To reproduce:
- create websearch shortcut to search KDE bug reports by reporter:
        keyword: reporter
        URL: https://bugs.kde.org/buglist.cgi?email1={searchTerms}&emailreporter1=1&emailtype1=substring
- Visit "reporter test@test.org"
- Visit "reporter test%40test.org"

Actual results:
- https://www.kde.org/
- https://bugs.kde.org/buglist.cgi?email1=test%2540kde.org&emailreporter1=1&emailtype1=substring

Expected results:
- https://bugs.kde.org/buglist.cgi?email1=test%40kde.org&emailreporter1=1&emailtype1=substring

**Comment by cfeck** [comment]
Cannot edit the comment, but replace 'test.org' with 'kde.org' (or whatever :)

**Comment by Emdek** [comment]
@cfeck, cannot reproduce using current master, which version are you using?

**Comment by cfeck** [comment]
I am at 89ccd9608ae07c06eacf2bb99f53a73e3606cbd9 but let me check todays' master.

**Comment by cfeck** [comment]
Today's commits fixed it, merci :)
