### ISSUE TITLE
Click on Website Preferences... otter core dumps

### ISSUE THREAD

**Issue by hunderteins** [OtterBrowser/otter-browser#1375]
Click in the context-menu on "Website Preferences..." and otter core-dumps.

I think f4d705f93a882460fecb5564db78e9a8eaa0009a introduced this,  I don't get where

items[1]->setFlags(items[1]->flags() | Qt::ItemNeverHasChildren);

in src/core/NetworkManagerFactory.cpp 

is comming from. Before all was about item[0], so I commented it out, otter works again.

regards,
hunderteins

**Comment by beastie1** [comment]
Same here.
