### ISSUE TITLE
Official forum has no https support

### ISSUE THREAD

**Issue by kotoko** [OtterBrowser/otter-browser#1377]
[Official forum](http://thedndsanctuary.eu/index.php?board=9.0) has no http**s** support, which means every connection to the server is unencrypted. It's critical security flaw. While I'm not using it, keep in mind that all users of this forum should treat their passwords as compromised.

Why https matters?
If you don't believe me, believe [Google](https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https).

What next?
1. Create certificates and setup them to production.
2. Inform users about this situation (+ force them to change passwords).

**Comment by Frenzie** [comment]
It's cheap shared hosting. I suppose I should send off an e-mail inquiring if they intend to offer automated Let's Encrypt for customers. The US-based Dreamhost, for example, [does so](https://www.dreamhost.com/hosting/ssl-tls-certificates/). The situation is suboptimal, but as long as you use a VPN on insecure wireless connections I'd say "critical" is a rather strong word to use.

Incidentally, unless someone has bothered targeting Elkarte specifically, the password is actually sent mildly encrypted: https://github.com/elkarte/Elkarte/blob/f35fd546fa008f27e2137b80a3e6eb4d1a0e9ac4/themes/default/scripts/script.js#L649 Obviously it's not secure, but it's not exactly [Strawberrynet](https://www.troyhunt.com/strawberrynet-privacy-insanity/) either.

(quoting Google)
> HTTPS helps prevent intruders from tampering with the communications between your websites and your users’ browsers. Intruders include intentionally malicious attackers, and legitimate but intrusive companies, such as ISPs or hotels that inject ads into pages.

HTTPS does pretty much nothing for that. Certificates do. (Hey, they're the ones talking about dispelling myths…)

**Comment by kotoko** [comment]
Whenever I see a website with ability to login and no https I immediately quit. I like otter project and shared my concern. 

Keep in mind that firefox and chrome added new feature that shows warnings on sites with http and logging in ability. So if you don't want to frighten potential users this should be fixed.

Feel free to close this issue, if you'd like - I won't be using this forum anyway.

**Comment by kotoko** [comment]
Quoting first sentence from Google:

> You should always protect all of your websites with HTTPS, even if they don’t handle sensitive communications.

**Comment by Frenzie** [comment]
Obviously I don't disagree with that, although I find Google's supporting arguments there to be on the weaker side. That doesn't change the fact that I consider an extra €30/year a giant waste of money. I also wouldn't switch to something else just for TLS (yet).

The [Mozilla scare page](https://support.mozilla.org/en-US/kb/insecure-password-warning-firefox) is much better written, but it does contain this doozy:

> You can also continue to log in to the website even if the connection is insecure, but do so at your own risk. If you do go this route, try to use a unique password or a password that you don’t also use for other important sites.

If you're not using unique passwords regardless, you're doing it wrong.

**Comment by Emdek** [comment]
@kotoko, it's not perfect but it's not that bad either.
Anyway, forum is running on separate server and existed even before this project went public.

@Frenzie, BTW, are there any estimates how much traffic is consumed by forum per month?
I think that I have plenty of unused disk space and traffic on my VPS...

**Comment by Frenzie** [comment]
@Emdek 
I have a cheap VPS for private use too, but the only part of security that's easy in that case is the HTTPS veneer. I suppose it should be okay since server OSes like Debian have sensible defaults, but still. With shared hosting from a half-competent provider you don't have to worry about that at the cost of some mild potential inconvenience.

**Comment by Frenzie** [comment]
@kotoko The forum is now TLS-enabled and verified by a Symantic Basic certificate.
