### ISSUE TITLE
Cannot play flash or html5 videos

### ISSUE THREAD

**Issue by rohshall** [OtterBrowser/otter-browser#1379]
For me, flash videos never worked for me on otter. When I try to play any video on youtube, for some strange reason, the ad plays, but the video gives this error:

> "an error occurred. Please try again later" 

I used your test-qtwebengine project, and any video on youtube plays great there.

This is the console log for otter, whenever I try to play something:
`
ATTENTION: default value of option force_s3tc_enable overridden by environment.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
`

Information about my system:

> I am on Arch Linux.
> I built the latest code from otter. (otter version 0.0.91-dev)
> My Qt webengine version 5.9.1

**Comment by Emdek** [comment]
@rohshall, sounds like something wrong with your build of QtWebEngine or system.
I would suggest to switch to preferred backend, you can get newest QtWebKit using this package:
https://www.archlinux.org/packages/extra/x86_64/qt5-webkit/

**Comment by rohshall** [comment]
If there was something wrong with my QtWebengine, the test-webengine project wouldn't work, right? The test project works. Also, I am using qupzilla, which uses the same QtWebengine.

**Comment by Emdek** [comment]
@rohshall, then it has to work everywhere.
QtWebEngine doesn't even have enough runtime options to mess it up. ;-)

Are you 100% sure that you are using that backend (check in Help -> About Otter…)? 
If you have legacy QtWebKit (outdated versions tend to have issues with multimedia and PPAPI is supported only by Google) around then it will be picked up as default and you have to either disable it at build time or switch it in *about:config*.

**Comment by rohshall** [comment]
@Emdek you were right. Now, I am using only qt5-webengine, and this problem was because otter used my qt5-webkit.
