### ISSUE TITLE
page loading spinner never stops

### ISSUE THREAD

**Issue by rohshall** [OtterBrowser/otter-browser#1380]
When I navigate to many sites like gmail, the page loading spinner keeps spinning forever - indicating that page load is not complete, even though it is complete, and I can interact with the page.

The relevant console log could be:

`
QCoreApplication::postEvent: Unexpected null receiver
`

System information:
`
I am on Arch Linux.
I built the latest code from otter. (otter version 0.0.91-dev)
My Qt webengine version 5.9.1
`

**Comment by Emdek** [comment]
@rohshall, any specific page? Cannot reproduce here using 5.9.1 from official Qt SDK.

**Comment by rohshall** [comment]
For me, gmail.com and a couple of other websites like https://app.pomodoneapp.com

**Comment by Emdek** [comment]
@rohshall, does it happen when doing nothing (simply waiting for page to finish loading) or after clicking some internal links that use anchors (#)?

**Comment by m4sk1n** [comment]
@rohshall, have you tried using Google Chrome user agent?

**Comment by rohshall** [comment]
@Emdek it was when I opened the gmail. But, after I removed qt5-webkit, and made qupzilla link only with qt5-webengine, this problem doesn't happen. Since qt5-webkit is deprecated anyway, I will close this issue.

**Comment by Emdek** [comment]
@rohshall, it's not really deprecated anymore, but you had legacy version installed, see here:
https://github.com/annulen/webkit/wiki/Comparison-with-QtWebKit-5.6
Here is up to date package:
https://www.archlinux.org/packages/extra/x86_64/qt5-webkit/

Note that QtWebEngine backend means less features (just like in case of QupZilla which lost many of them while switching to it).
