### ISSUE TITLE
Otter hangs on Transifex site

### ISSUE THREAD

**Issue by smarquespt** [OtterBrowser/otter-browser#1381]
How to reproduce:

Access https://www.otter-browser.org/
Click 'Translations repository'

Observed:
Otter keeps loading on transifex site but never completed loading

System - Windows 10
Otter Version - Weekly 182

**Comment by Emdek** [comment]
@smarquespt, cannot reproduce using both legacy or revived QtWebKit.
Which version are you using, which platform?
Perhaps you are using content blocking?

**Comment by smarquespt** [comment]
@Emdek 

My system is Windows 10 and Otter is the portable release 32 bits. The otter version is 0.9.91weekly 182 and webkit is 602.1

**Comment by Emdek** [comment]
@smarquespt, confirmed using both 32 bit and 64 bit versions, it's some sort of issue with JS in QtWebKit, since it's reproducible using plain *test-qtwebkit.exe*.
We will have to wait for upstream fix.

**Comment by smarquespt** [comment]
@Emdek 

It's fixed in latest RC

**Comment by BorutAtGit** [comment]
At my place, under Win7 32bit, using RC3 from otter-browser-win32-0.9.93-rc3.7z in portable mode, the page becomes partly visible and then Otter hangs with a quite high CPU load, while apparently trying to complete it.
