### ISSUE TITLE
HTTP_ACCEPT Headers

### ISSUE THREAD

**Issue by fox7000** [OtterBrowser/otter-browser#1385]
Hello,
please can you add an option to set the "HTTP_ACCEPT Headers" ?
I see an option to change the "User Agent" but nothing else.

Every browser set the "HTTP_ACCEPT Headers" and the "User Agent" to different values, so if we change one but not the other the fingerprint become unique.

For more info on fingerprint, disable javascript and, go here:
https://panopticlick.eff.org/

An example with firefox my "User agent" is:
Mozilla/5.0 (X11; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0

and my "HTTP_ACCEPT Headers" is:
text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 gzip, deflate, br en-US,en;q=0.5

Observe that there is a comma (,) after the word deflate.
With Otter is actually impossible to simulate this result.

Regards.

**Comment by Emdek** [comment]
@fox7000, that sounds a lot like #27.
Another possibility to allow to do something about would be #42.
