### ISSUE TITLE
Latest Git Master keeps crashing

### ISSUE THREAD

**Issue by Vistaus** [OtterBrowser/otter-browser#1389]
OS: Solus
DE: Budgie (latest)
Qt: 5.9.1
Web backend: qt5-webkit 5.9.1

This is the output:

```
[13:54:01] vistaus@vistaus-solus /media/MicroSD/Apps/otter-browser (1) 
> otter-browser 

(otter-browser:20159): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(otter-browser:20159): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplayManager'

(otter-browser:20159): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(otter-browser:20159): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
fish: “otter-browser” terminated by signal SIGSEGV (Address boundary error)
[13:54:21] vistaus@vistaus-solus /media/MicroSD/Apps/otter-browser (139) 
> 
```

How to solve this?

**Comment by m4sk1n** [comment]
@Vistaus, change Otter theme (or default Qt theme) from gtk2 to for example Fusion

**Comment by Vistaus** [comment]
@m4sk1n But I want the GTK2 theme. Anyway, I did change it now to Fusion and I've also tried Motif but Otter still crashes.

**Comment by Emdek** [comment]
@Vistaus, try to get backtrace:
https://wiki.archlinux.org/index.php/Debug_-_Getting_Traces#Getting_the_trace

**Comment by Vistaus** [comment]
@Emdek Thanks. Here's the output of gdb run:

```
[19:24:35] vistaus@vistaus-solus /media/MicroSD/Apps (0) 
> gdb /usr/bin/otter-browser 
GNU gdb (GDB) 7.12.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-solus-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/otter-browser...run
done.
(gdb) run
Starting program: /usr/bin/otter-browser 
warning: File "/usr/lib64/libstdc++.so.6.0.22-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /usr/lib64/libstdc++.so.6.0.22-gdb.py
line to your configuration file "/home/vistaus/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/vistaus/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
warning: File "/usr/lib64/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
[New LWP 24171]
[New LWP 24172]
[New LWP 24174]
[New LWP 24175]
[New LWP 24176]
[New LWP 24177]
[New LWP 24178]
[New LWP 24187]
[New LWP 24188]
[New LWP 24189]
[New LWP 24190]
[New LWP 24191]

(otter-browser:24167): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplayManager'

(otter-browser:24167): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(otter-browser:24167): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

Thread 1 "otter-browser" received signal SIGSEGV, Segmentation fault.
0x00007fc958ce5431 in gdk_display_manager_get_default_display () from /usr/lib/libgdk-3.so.0
(gdb) 
```

And here's the actual backtrace: https://pastebin.com/e08FF3gE

**Comment by Emdek** [comment]
@Vistaus, thanks, looks like some QtWebKit issue, or in some other layer, could you try to reproduce it using this?
https://github.com/OtterBrowser/test-qtwebkit
It would be nice to try to generate backtrace after installing debug symbols for QtWebKit too.

**Comment by annulen** [comment]
@Vistaus By chance, are you using GTK3 theme for Qt? If so, run Otter with `-style fusion` argument

**Comment by Vistaus** [comment]
@Emdek In that case it seems easier to switch to QtWebEngine, no? QtWebKit is dead anyway (I only chose it because QtWebEngine was very buggy in QupZilla, but maybe it's improved now).

@annulen No, also look at my earlier response where I tried other styles which resulted in the same crashes.

**Comment by Emdek** [comment]
@Vistaus, it's not dead, just versions older than 5.212 are outdated.
Anyway, you should try using parameter, unless you have tried that way already too (using option in Preferences might be not enough in this case).

**Comment by Vistaus** [comment]
Same crash when using that parameter.

**Comment by annulen** [comment]
Please paste output of `info sharedlibrary` gdb command

**Comment by annulen** [comment]
With Qt style different from gtk, please

**Comment by annulen** [comment]
BTW, does AppImage version crash?

**Comment by Emdek** [comment]
@Vistaus, one more thing, could you please check if your system is using `libproxy`?
It used to cause a lot of crashes due to mixing incompatible plugins.

**Comment by Vistaus** [comment]
@annulen 
Here's the output of info sharedlibrary with Qt style Fusion: https://pastebin.com/KPSJXRsp

I'm not gonna try the AppImage version.

@Emdek I'm not sure if it's being used, but Solus Software Center says it's installed.

**Comment by annulen** [comment]
Are you running Wayland?

**Comment by Vistaus** [comment]
@annulen Nope. Budgie isn't ported to Wayland yet, so I'm using Xorg.

**Comment by annulen** [comment]
Could you uninstall `/usr/lib64/mozilla/plugins/libevbrowserplugin.so` and retry?

**Comment by Vistaus** [comment]
@annulen Hmm, so far, so good. Seems like removing /usr/lib64/mozilla/plugins/libevbrowserplugin.so did the trick. Thanks! :)
