### ISSUE TITLE
Feature request "closeWindowsIfNotLastElseOpenTab"

### ISSUE THREAD

**Issue by CyberC123** [OtterBrowser/otter-browser#1391]
hey,

can you please add the value "closeWindowsIfNotLastElseOpenTab" in the LastTabClosingAction?
The function is: The window is closed like "closeWindowsIfNotLast" but when the last windows is reached then a new Tab is open.

Thanks

**Comment by Emdek** [comment]
@CyberC123, that is a bit too complicated, looks more like a task for scripting part of #42.
