### ISSUE TITLE
CRASH: The browser v0.9.91 crashed on the SF.net download page

### ISSUE THREAD

**Issue by lit-uriy** [OtterBrowser/otter-browser#1393]
If I click on a link to download a ZIP archive from SF.net ( https://sourceforge.net/projects/otter-browser/files/otter-browser-weekly184/otter-browser-win32-weekly184-xp.zip/download ), then browser crashes.

browser: 0.9.91 weekly 184
OS: Win XP SP3

**Comment by Emdek** [comment]
@lit-uriy, it seems to be some JS related issue that affects only this build, I'll try to debug it together with @annulen.

**Comment by Emdek** [comment]
And now there is patch for that issue, it should be included in next release.
