### ISSUE TITLE
Blocking whole websites?

### ISSUE THREAD

**Issue by CyberC123** [OtterBrowser/otter-browser#1394]
Hey,
I have tested with the AdBlock filter options to block facebook (||facebook.com) but I can still go to facebook.com.
In Opera's urlfilter I have block facebook completely with "*://*facebook.*".
Is there a option to block a whole website?

Thanks.

**Comment by Emdek** [comment]
@CyberC123, currently there is exception for such content when it is viewed directly, I guess that we could make it optional.
