### ISSUE TITLE
Mac build does not work

### ISSUE THREAD

**Issue by tienhv** [OtterBrowser/otter-browser#1395]
Hello,
Could you build the application for OS X 10.11 also? I cannot run it there.

Bests,

**Comment by tienhv** [comment]
Here is the error message
![image](https://user-images.githubusercontent.com/9072983/28774018-f506a8f0-7615-11e7-90fc-f54e0371e760.png)
Thanks

**Comment by Emdek** [comment]
@tienhv, do you have similar issues with previous weekly?
There was only one change that deals with macOS APIs and that one was supposed to be compatible with 10.10 and newer according to Apple docs.

**Comment by tienhv** [comment]
Yes, it is already a long time  (might be more than half year) I got this error and cannot use the software.  I know in Xcode there is an option to set compatibility operating system target for application (like >=10.10 ). Maybe the problem is similar here.

**Comment by Emdek** [comment]
@tienhv, I see, so it's something different then.
I'm not using XCode directly but there seems to be a solution here:
https://stackoverflow.com/questions/10165335/can-cmake-specify-the-base-sdk-on-mac-os-x
I can build experimental version(s) using these tips and we will find out then.

**Comment by Emdek** [comment]
@tienhv, I've updated package for weekly 184 on sf.net, could you give it a try?

**Comment by tienhv** [comment]
Thanks @Emdek, confirmed that it works perfectly!

**Comment by Emdek** [comment]
@tienhv, thanks for testing. :-)
