### ISSUE TITLE
Tab context menu broken/deserted

### ISSUE THREAD

**Issue by uahim** [OtterBrowser/otter-browser#1401]
daily 189, Win 7x 64, even with a fresh profile, most actions are greyed out:
![clipboard01](https://user-images.githubusercontent.com/6866794/29425963-60132aa2-8385-11e7-985b-bf28f1e91492.png)

**Comment by Emdek** [comment]
Already fixed in 59adc45dbfa2fd582eebdb58b54230b1630cdf14.
