### ISSUE TITLE
Images not displaying properly in pages loaded in background tab

### ISSUE THREAD

**Issue by midluk** [OtterBrowser/otter-browser#1402]
On some news sites or blogs (e.g. petapixel.com) images are displayed very small or extremely blurry when I open a link/article in a new background tab.
Opening the link by normal left click in the same tab or in a new non-background tab works properly. The images are also displayed normally after the affected page is reloaded.

This also happens with a new otter config with disabled content blocking.

I'm seeing this with current otter master (but exists for some time already) on Linux with qt 5.7.1 and qtwebkit 5.212.0 alpha2.

**Comment by Emdek** [comment]
@midluk, it seems to be some sort of issue with initial viewport size.

**Comment by Emdek** [comment]
There is still one case left, restoring session without delayed loading.
