### ISSUE TITLE
CloseTabOnMiddleClick no longer working/gone from settings?

### ISSUE THREAD

**Issue by uahim** [OtterBrowser/otter-browser#1405]
latest weekly/Win x64

I can't seem to find anything in the settings (except for "PasteAndGoOnMiddleClick")

**Comment by Emdek** [comment]
@uahim, see Known Issues for weekly 191, under Windows it's missing default profiles for keyboard shortcuts and mouse gestures (middle click to close tab counts as mouse gesture).
