### ISSUE TITLE
Move HTML bookmarks parsing to background thread

### ISSUE THREAD

**Issue by franco27** [OtterBrowser/otter-browser#1408]
I tried to import my bookmarks from Vivaldi in the browser Otter. Since Vivaldi, I have exported my bookmarks in an .html file. This file is voluminous (many bookmarks). (Windows10 x64)

Since Otter, when I try to import this file. Otter freezes immediately (when I open the task manager, I see Otter: "the software is no longer responding")
I waited 10 minutes but the situation does not improve (still frozen)

**Comment by Emdek** [comment]
@franco27, any hint how much is that in KB?
The problem is that parsing is done in the same process, we need to delegate it to at least a separate thread and in case of HTML bookmarks it might require completely different approach (new parser).

**Comment by franco27** [comment]
750 ko is its size.

That I export in .html from Opera or Vivaldi. I have the same problem. Thank you for your reply.
Good continuation.

**Comment by Emdek** [comment]
@franco27, that's a lot indeed, I guess that we should generate similar file for testing purposes.

**Comment by franco27** [comment]
I have nothing to hide. if you wish, I send it to you. Give me an email address or contact me
out of curiosity, you are the developer.

**Comment by Emdek** [comment]
@franco27, OK, that works for me too. ;-)
You can find my email address on top of *main.cpp* file in *src* folder of the Code tab of this github project.

**Comment by franco27** [comment]
I have sent you the files: (.HTML export)
- one exported with Vivaldi and -the other exported with Opera
I can import in both web browser.

**Comment by Emdek** [comment]
@franco27, yep, thanks.
Now I see that we have two main issues here, current way of fetching entries is inefficient and we need to tell bookmarks bar to stop reloading while importing too.

**Comment by franco27** [comment]
OK, you've found the way to solve this problem.

**Comment by Emdek** [comment]
@franco27, well, more like sources of that problem. ;-)

BTW, I've managed to import one of them, I've sent it back to you.

**Comment by Emdek** [comment]
These changes (and some others, not referenced here) allowed to reduce import time from 86 seconds (not counting eliminating complete freeze before being able to measure it) to 200 milliseconds, that's pretty big change. ;-)

**Comment by franco27** [comment]
OK , thank you for keeping me informed

**Comment by Emdek** [comment]
@franco27, well, this is how bug tracker works, everybody gets informed as long as they are subscribed to ticket or mentioned in explicit way. ;-)

**Comment by franco27** [comment]
in the roadmap of the software, are you planning  to add for the input areas of passwords, to activate its visibility.

**Comment by Emdek** [comment]
@franco27, lesson number two, do not blend-in unrelated issues when there is already separate ticket. :-P
If you are referring to that other ticket then I'll take care of it when more important stuff will be done, right now it's not classified yet (has no labels yet).

**Comment by franco27** [comment]
OK, it was just a question, not to create a topic if there is already one. Thank you for your reply. and sorry

**Comment by franco27** [comment]
I confirm the resolution of the problem. I can import.

**Comment by Emdek** [comment]
It turns out that current solution is good enough, separate thread is unlikely to increase performance and most likely there would be extra overhead caused by communication with it.
