### ISSUE TITLE
video playback problem

### ISSUE THREAD

**Issue by franco27** [OtterBrowser/otter-browser#1409]
on this page, at the bottom of the page, or the second video
https://www.scrivener.fr/scrivener-maitriser-scrivener-facilement/

the video starts playing correctly but its display is incorrect (the video display during playback, there is a part of the video hidden).

I refreshed the page and started reading several times but this problem is still present.
![capture](https://user-images.githubusercontent.com/31793920/30239317-3a14029a-955a-11e7-8c63-91327dba204a.png)

**Comment by franco27** [comment]
in other internet browsers, there is not this problem during playback

**Comment by Emdek** [comment]
@franco27, cannot reproduce (Windows 10 and Linux), are you using content blocking or anything non standard?
Video is slightly misplaced comparing to Firefox but nothing gets hidden, it just hides part of that fake shadow under it.

Also, take a look at dedicated ticket for Media Foundation (default multimedia backend under Windows): #1225.

**Comment by franco27** [comment]
I will see #1225. Otter default setting.

I am under Windows10 x64Bits.

**Comment by franco27** [comment]
You see everything as me the screenshot, I am not inventing . Thank you for your response.

**Comment by Emdek** [comment]
@franco27, I believe you, anomalies can happen (espescially when using content blocking, user stylesheets or User Scripts), but are very rare, this is what I'm seeing:
https://otter-browser.org/tmp/wmf-video.png

You can also try reproducing that using "xp" build (full compatible, but using different compiler and different multimedia backend), but it seems to be falling back to flash based replacement, so you will most likely see placeholders unless you will enable plugins for that page (using action from address field or enabling them for that page in Website Preferences, from context menu).

**Comment by franco27** [comment]
ok Thank you for your reply.

You are talking about this version: "ZIP package for Windows XP or later, 32 bit (66.5 MiB);"
This problem will be solved.

I discovered this problem and I wanted to tell you. I went on this website by hazard.

Another topic: I use a download manager. I can not install a Firefox or Chrome extension in Otter.
It would be a good idea to include a button to copy the URL because on the download page, the download address is not always visible or accessible.   In this window, see the screenshot.
![copyurl_otter browser](https://user-images.githubusercontent.com/31793920/30276210-6591fdc2-9704-11e7-8c91-1e6a89702e26.png)

**Comment by Emdek** [comment]
@franco27, no issues with that one? That would confirm that it is MF specific issue.

Yeah, such button was already suggested years ago, but the main issue is where to put it, this dialog is already pretty complex...

**Comment by franco27** [comment]
by right-clicking on "From" (on the address)  (De: version french)

**Comment by annulen** [comment]
@franco27 With WebInspector you can get video url right from `<video>` element

**Comment by franco27** [comment]
I have no more displaying problems for the video. I confirm that this issue is resolved

I tried again with the version: Weekly report #196 (02-10-2017) (Pre) RC 1 release
installer for Windows 7 or later, 64 bit
