### ISSUE TITLE
How to edit keyboard shortcuts?

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#1411]
Some major things don't match right now. For me, editing anything under Preferences/Advanced/Keyboard, then OK/Save/Apply and restart the browser has no effect. After restart, everything is the same old. That place should be the user interface to change things, but it must actually save things. 

In my user directory under .config/otter-browser/keyboard/ I have a file from old, currently named keyboard.json. This name or file does not show up under Preferences/Advanced/Keyboard. 

When messing with that section, I deleted everything in Preferences/Advanced/Keyboard - things are not being preserved, so why keep anything there? But this deletion *did* get saved and now my Otter is completely without keybinds. 

As said, I have a keyboard.json file in my .config/otter-browser/keyboard/ directory with plenty of configurations in it in json format. However, it does not show up in Preferences/Advanced/Keyboard and it does not help me to get keybinds back.

When the user edits Preferences/Advanced/Keyboard, the editing should be directly linked to a file in .config/otter-browser/keyboard/ and that file should be overwritten and applied by OK/Save/Apply. Shouldn't it?

**Comment by Emdek** [comment]
@ersi-dnd, it seems that there is stupid bug involving empty profile identifier (at least in case of new profiles), apparently file ended up named... *.json*.
You can try renaming that file manually (to name present in Browser/KeyboardShortcutsProfilesOrder, or anything else if not present there) and then using Readd menu from Add button.

I'm not sure about issues with existing profiles (including these created by migration), so far I haven't noticed any.

**Comment by Emdek** [comment]
It seems that it applied to any edited profile too.

**Comment by ersi-dnd** [comment]
@Emdek 
> You can try renaming that file manually (to name present in Browser/KeyboardShortcutsProfilesOrder, or anything else if not present there) and then using Readd menu from Add button.

I can see an "Add again" menu item under Add button, but it's inactive for me in every situation. 

So the keyboard.json file should be named without the .json part? Here's what did the trick:

1. Restore defaults in about:config Browser/KeyboardShortcutsProfilesOrder. "default" appears.
2. Close Otter and go to .config/otter/keyboard directory
3. Rename the file there to `default` (without .json)
4. Open Otter and go to Preferences > Advanced > Keyboard. There's a working "Default" keyboard profile there (assuming that the contents of the file in the home directory is alright)

Thanks.

**Comment by Emdek** [comment]
@ersi-dnd, it should be *keyboard.json*, otherwise you are changing from missing basename to missing extension. :-D

**Comment by BorutAtGit** [comment]
I think that something is still flawed here, at least under Windows. I am running it under Windows 7 32bit, in a portable mode.

What regards keyboard, I tried to simulate the initial condition: I deleted the profile\keyboard directory.

On Windows, the **Ctrl+Ins for the Copy command seems not to be working, although the appropriate definition is visible in the default definition.**

Also, if I try to make a clone of the default definition, it does not contain all the shortcut definitions for Copy, just the Ctrl+Alt+C for the plainText copy. I expected that the clone would be completely same as the original (in that case the default).

Am I doing or expecting something wrong?

**Comment by Emdek** [comment]
@BorutAtGit, I'm not re about that Ctrl+Ins (needs debugging) but cloning might ignore them since standard editing actions don't use our shortcuts system and have to be ignored when creating them.
And it seems to affect cloning too.

**Comment by Emdek** [comment]
Ctrl+Ins seems to work when used for other actions, weird.

**Comment by BorutAtGit** [comment]
Maybe these hints could help (everything under Win32 32bit in portable mode, default keyboard (i.e. no keyboard directory in the profile) and only the "default" value in about:config/Browser/KeyboardShortcutsProfilesOrder) - just retested these three versions: 

Previous versions:
W190: Ctrl+Ins works OK
W191: Did not use, do not know
W192: Ctrl+Ins does not work
W193: Ctrl+Ins does not work

Ctrl+C seems to work always - even if one defines a clone and then deletes **all** entries for the Copy command.

Regarding cloning: All entries seem to still be there **immediately after cloning**. It is after the save (be it only the name of the clone was changed) that all but one entry for the Copy command are lost.

**Comment by Emdek** [comment]
@BorutAtGit, OK.
Anyway, it seems that elimination of conflicts with native editing shortcuts cannot be a reason for them to be not cloned, since it is still done by `MainWindow` while setting them up...

**Comment by Emdek** [comment]
But cloning can drop other information, single key shortcuts.

**Comment by ersi-dnd** [comment]
I can't find Ctrl+Tab among editable keybinds under Preferences/Keyboard. This shortcut brings up the tabswitcher thingie. Can it be edited?

**Comment by Emdek** [comment]
@ersi-dnd, nope, it's not a simple shortcut.
But you can add shortcut that brings that dialog but without selecting next / previous tab.

**Comment by ersi-dnd** [comment]
The reason I asked is because I would like click+scroll to do the same thing as ctrl+tab. Right now click+scroll switches tabs, but without the thingie. Is it doable?
