### ISSUE TITLE
The popup progress bar stays on indefinitely

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#1412]
The popup progress bar used to vanish once the webpage was loaded. Now it stays on forever
![ekraanipilt 2017-09-12 13-01-50](https://user-images.githubusercontent.com/6865273/30320736-3ed7ad22-97bc-11e7-94f2-68196d1022c8.png)

**Comment by Emdek** [comment]
@ersi-dnd, make backup of *toolBars.json* and reset toolbar settings (or simply rename that file and restart) and try again, it sounds like messed up configuration file.

**Comment by ersi-dnd** [comment]
Yes, renaming `toolBars.json` worked as advertised :)

**Comment by Emdek** [comment]
@ersi-dnd, you can still try fixing it, you just need to remove or replace some parts, compare with defaults from *resources/other/toolBars.json*.
