### ISSUE TITLE
Enabling the "Close other tabs"-button

### ISSUE THREAD

**Issue by BorutAtGit** [OtterBrowser/otter-browser#1414]
This is probably an easy bug:

If, in a session, there is only one foreground tab and many many background tabs (opened for instance via links in the foreground tab), the button "Close other tabs" stays grayed. This is so in the several weeklies already.

It might seem as an "incredibly rare situation" and a nonproblem, but in fact - due to some usual task I have to do - it happens to me at least two times a day.

**Comment by Emdek** [comment]
@BorutAtGit, where is that action located in your case?
I can't reproduce it with various locations.

**Comment by BorutAtGit** [comment]
Sorry nr.1: I was off-line since Thursday evening. Sorry nr.2: Did not mention it: I have positioned the "Close Other Tabs"-button in the tabs bar. (It has a folder icon with a small red x on it.)

Hope that this helps.

**Comment by Emdek** [comment]
@BorutAtGit, I've anticipated such setup and tried it, without success in reproducing it...
Any other details? Your wording might suggest use of MDI, but that shouldn't matter.
Is that a continued session with several tabs?
Does your main window start without tabs or with just a single tab opened?
Action should update state as soon as amount of tabs changes, no matter where it is placed (that was the point of that big rewrite which introduced ActionExecutor), so it sounds a bit odd.
Also, could you please share your *toolBars.json* file (you can find profile path in Diagnostic Report for Help menu)?

**Comment by BorutAtGit** [comment]
My main window starts with just one tab, which shows the home page. If one now clicks on links contained in this page using Ctrl+Shift (i.e. opens all resulting pages in new background tabs) the button stays grayed.

The button becomes usable only after one clicks to (i.e. switches to) at least one of these background tabs (in that way bringing it to foreground).

Now, at the first moment this sounds logical - why would one open background tabs and then want to close them all without ever looking at them. However, in my case, they are just a kind of confirmation pages with no real usable contents, so I am never interested in them.


[toolBars_json.txt](https://github.com/OtterBrowser/otter-browser/files/1310507/toolBars_json.txt)

**Comment by Emdek** [comment]
@BorutAtGit, thanks, single tab main window restored from the session is the key.
