### ISSUE TITLE
Feeds reader module

### ISSUE THREAD

**Issue by Emdek** [OtterBrowser/otter-browser#1415]
We need at least basic feeds reader.

The most important stuff:
- [x] OPML parser;
- [x] Atom parser;
- [x] RSS parser;
- [x] `about:feeds` module;
- [x] `view-feed:` protocol;
- [x] feeds storage;
- [ ] auto update.

Other tasks:
- [ ] use `view-feed:` protocol when accessing URLs with matching MIME types;
- [ ] move handling of `view-feed` protocol to `HandlersManager`;
- [ ] add OPML importer;
- [ ] parse feeds in background thread.

**Comment by Emdek** [comment]
Related ticket: #457.

**Comment by Emdek** [comment]
And a bit: #1272.

**Comment by ersi-dnd** [comment]
And first of all you will add a stylesheet for RSS pages, right? Like this 
![2017-09-22-164717-rss](https://user-images.githubusercontent.com/6865273/30747609-76896290-9fb6-11e7-85e2-f1b14d44c65b.png)
In Opera, this function has its own file called webfeeds.html so users can alter it at will.

**Comment by ersi-dnd** [comment]
This simple style is the most useful thing: You don't have to subscribe to and download every feed, just bookmark the link and visit to read the updates. Some feeds are good to download (because the content is useful and the feed contains complete articles), others are only good for bookmarking like this.

**Comment by ersi-dnd** [comment]
The location of webfeeds.html can be found (and changed) at `opera:config#UserPrefs|WebfeedsHTMLTemplateFile`

**Comment by Emdek** [comment]
@ersi-dnd, it has separate ticket, and right now it's set to be a XSLT stylesheet, but surely that would make it harder to edit by users...

**Comment by zakius** [comment]
http://nullprogram.com/blog/2013/09/23/ everything wrong about RSS and what to be careful about

**Comment by Frenzie** [comment]
@zakius Quite true. I came to the same conclusion with Atom 0.3. :-)

There is (or was?) one tiny annoyance with Atom though. Empty content (serving merely as an update notification) was technically considered an invalid feed.

That GUID stuff is also very annoying for us in FreshRSS. See, for instance, https://github.com/FreshRSS/FreshRSS/pull/1558

But as far as Otter goes, surely there is some library (like SimplePie for FreshRSS) that does a half-sensible job abstracting RSS away. And even if there isn't, QuiteRSS (GPLv3) has stuff like [this](https://github.com/QuiteRSS/quiterss/blob/2f3871cee0d2aa9036fd1311326cb60f2b726fdc/src/parseobject.cpp).

**Comment by Emdek** [comment]
@Frenzie, QuiteRSS is useless, as noted earlier on IRC they even mix in SQL in that file...
I was considering using this:
https://github.com/akrennmair/newsbeuter/tree/master/rss
But now I'm considering custom parser, starting with Atom and RSS 2.0.

**Comment by Frenzie** [comment]
@Emdek I didn't really mean QuiteRSS, just something *like* QuiteRSS. Sorry about being unclear. :-P (I just happen to like QuiteRSS from a user's POV.)

Anyway, I also see the SQL mixed in there on a closer look (weird) but perhaps basic parsing logic like [this](https://github.com/QuiteRSS/quiterss/blob/2f3871cee0d2aa9036fd1311326cb60f2b726fdc/src/parseobject.cpp#L261-L293) could still be helpful to show some pitfalls they've already tackled. Well, for RSS anyway. The Atom stuff is pretty straightforward.

**Comment by sjehuda** [comment]
@ersi-dnd what do you think of "table of contents" instead of table/tiles?

![image](https://user-images.githubusercontent.com/19249089/167294904-a5aab167-cdfa-4455-98ef-35765ea0c43e.png)

**Comment by ersi-dnd** [comment]
@sjehuda My first preference would be to have it visually similar to the way Opera 11 displays it. But probably an even better idea is to take it a step further and provide options, so the user can choose whether to see only the headings or also the content somehow.

**Comment by sjehuda** [comment]
I think options is good.

I'm intending to apply several styles (one of which is the style of the
Otter homepage), but the one of Opera 11 that you refer to, requires
someone more skillful at CSS than myself.

My attempts weren't perfect. See https://openuserjs.org/scripts/sjehuda/Newspaper/issues/Improve_CSS#comment-180985d9b61

If you know or find someone who can help, please do let me know.

**Comment by sjehuda** [comment]
Here is an example of a design that is adaptable for wide and small
display. See https://poolp.org/

When display is wide, items are shown like in Opera 11 and when display
is narrow, items are displayed one below the other.

@ersi-dnd, do you know how to code in CSS?

**Comment by ersi-dnd** [comment]
Unfortunately I am not available for coding. But I think a way to start is to take a look at Opera 11 feed.css found under /usr/share/[opera]/styles on my computer. The file feed.css should be in some similar folder on your computer too, if you have old Opera installed. The way I'd develop Otter would be to take a look at the way Opera was developed every step of the way.

**Comment by sjehuda** [comment]
Just a note.

Once we have it implemented, I am sure that the CSS be modifiable, so, I think, that the design is not crucual at the moment.
