### ISSUE TITLE
Startup Tabs - Restore Last Session Not Working 

### ISSUE THREAD

**Issue by erdosnew** [OtterBrowser/otter-browser#1416]
otter ver 0.9.91, the restore previous session isn't working, browser starts with a new window everytime

**Comment by Emdek** [comment]
@erdosnew, please attach Environment and Settings sections from Diagnostic Report in Help menu.
Also please check if you profile directory is writable.

**Comment by erdosnew** [comment]
here're the settings, i checked the profile directory, i believe it's writable.

Otter Browser diagnostic report created on 2017-09-21T03:18:55Z

Version:
	Main Number         0.9.91
	Weekly Number       169
	Context              weekly 169
	Web Backend         WebKit Backend (legacy) 538.1

Environment:
	System Name                   Windows XP
	Build ABI                     i386-little_endian-ilp32
	Build CPU Architecture        i386
	Current CPU Architecture      i386
	Build Qt Version              5.5.1
	Current Qt Version            5.5.1
	Locale                        en_US

Paths:
	Profile             C:\Documents and Settings\User\Local Settings\Application Data\Otter\otter
	Configuration       C:\Documents and Settings\User\Local Settings\Application Data\Otter\otter/otter.conf
	Session             C:\Documents and Settings\User\Local Settings\Application Data\Otter\otter\sessions\default.json
	Overrides           C:\Documents and Settings\User\Local Settings\Application Data\Otter\otter/override.ini
	Bookmarks           C:\Documents and Settings\User\Local Settings\Application Data\Otter\otter\bookmarks.xbel
	Notes               C:\Documents and Settings\User\Local Settings\Application Data\Otter\otter\notes.xbel
	History             C:\Documents and Settings\User\Local Settings\Application Data\Otter\otter\browsingHistory.json
	Cache               C:\Documents and Settings\User\Local Settings\Application Data\Otter\cache

Settings:
	AddressField/CompletionDisplayMode                compact             default             no overrides
	AddressField/CompletionMode                       inlineAndPopup      default             no overrides
	AddressField/DropAction                           replace             default             no overrides
	AddressField/HostLookupTimeout                    200                 default             no overrides
	AddressField/Layout                                                   default             no overrides
	AddressField/PasteAndGoOnMiddleClick              true                default             no overrides
	AddressField/SelectAllOnFocus                     true                default             no overrides
	AddressField/ShowCompletionCategories             true                default             no overrides
	AddressField/SuggestBookmarks                     true                default             no overrides
	AddressField/SuggestHistory                       true                default             no overrides
	AddressField/SuggestLocalPaths                    true                default             no overrides
	AddressField/SuggestSearch                        true                default             no overrides
	AddressField/SuggestSpecialPages                  true                default             no overrides
	Backends/Passwords                                file                default             no overrides
	Backends/Web                                      qtwebkit            default             no overrides
	Browser/AlwaysAskWhereToSaveDownload              true                default             no overrides
	Browser/DelayRestoringOfBackgroundTabs            true                default             no overrides
	Browser/EnableMouseGestures                       true                default             no overrides
	Browser/EnableSingleKeyShortcuts                  true                default             no overrides
	Browser/EnableSpellCheck                          true                default             no overrides
	Browser/EnableTrayIcon                            true                default             no overrides
	Browser/HomePage                                  -                   default             no overrides
	Browser/InactiveTabTimeUntilSuspend               -1                  default             no overrides
	Browser/KeyboardShortcutsProfilesOrder                                default             no overrides
	Browser/Locale                                    -                   default             no overrides
	Browser/Migrations                                                    non default         no overrides
	Browser/MouseProfilesOrder                        default             default             no overrides
	Browser/OfflineStorageLimit                       10240               default             no overrides
	Browser/OfflineWebApplicationCacheLimit           10240               default             no overrides
	Browser/OpenLinksInNewTab                         true                default             no overrides
	Browser/PrintElementBackgrounds                   true                default             no overrides
	Browser/PrivateMode                               false               default             no overrides
	Browser/RememberPasswords                         false               default             no overrides
	Browser/ReuseCurrentTab                           false               default             no overrides
	Browser/ShowSelectionContextMenuOnDoubleClick     false               default             no overrides
	Browser/SpellCheckDictionary                      -                   default             no overrides
	Browser/StartupBehavior                           continuePrevious    default             no overrides
	Browser/TabCrashingAction                         ask                 default             no overrides
	Browser/ToolTipsMode                              extended            default             no overrides
	Browser/TransferStartingAction                    openTab             default             no overrides
	Browser/ValidatorsOrder                                               default             no overrides
	Cache/DiskCacheLimit                              51200               default             no overrides
	Cache/PagesInMemoryLimit                          5                   default             no overrides
	Choices/WarnFormResend                            true                non default         no overrides
	Choices/WarnLowDiskSpace                          warn                default             no overrides
	Choices/WarnOpenBookmarkFolder                    true                default             no overrides
	Choices/WarnOpenMultipleDroppedUrls               true                default             no overrides
	Choices/WarnQuit                                  noWarn              default             no overrides
	Choices/WarnQuitTransfers                         true                default             no overrides
	Content/BackgroundColor                           #FFFFFF             default             no overrides
	Content/CursiveFont                               Impact              default             no overrides
	Content/DefaultCharacterEncoding                  -                   default             no overrides
	Content/DefaultFixedFontSize                      16                  non default         no overrides
	Content/DefaultFontSize                           16                  non default         no overrides
	Content/DefaultZoom                               100                 default             no overrides
	Content/FantasyFont                               Comic Sans MS       default             no overrides
	Content/FixedFont                                 DejaVu Sans Mono    default             no overrides
	Content/LinkColor                                 #0000EE             default             no overrides
	Content/MinimumFontSize                           -1                  non default         no overrides
	Content/PageReloadTime                            -1                  default             no overrides
	Content/SansSerifFont                             DejaVu Sans         default             no overrides
	Content/SerifFont                                 DejaVu Serif        default             no overrides
	Content/StandardFont                              DejaVu Serif        default             no overrides
	Content/TextColor                                 #000000             default             no overrides
	Content/UserStyleSheet                            -                   default             no overrides
	Content/VisitedLinkColor                          #551A8B             default             no overrides
	Content/ZoomTextOnly                              false               default             no overrides
	ContentBlocking/CosmeticFiltersMode               all                 default             no overrides
	ContentBlocking/EnableContentBlocking             true                default             no overrides
	ContentBlocking/EnableWildcards                   true                default             no overrides
	ContentBlocking/Profiles                                              default             no overrides
	History/BrowsingLimitAmountGlobal                 1000                default             no overrides
	History/BrowsingLimitAmountWindow                 50                  default             no overrides
	History/BrowsingLimitPeriod                       30                  default             no overrides
	History/ClearOnClose                                                  default             no overrides
	History/DownloadsLimitPeriod                      7                   default             no overrides
	History/ExpandBranches                            first               default             no overrides
	History/ManualClearOptions                                            default             no overrides
	History/ManualClearPeriod                         1                   default             no overrides
	History/RememberBrowsing                          true                default             no overrides
	History/RememberClosedPrivateTabs                 false               default             no overrides
	History/RememberDownloads                         true                default             no overrides
	History/StoreFavicons                             true                default             no overrides
	Interface/DateTimeFormat                          -                   default             no overrides
	Interface/EnableSmoothScrolling                   false               default             no overrides
	Interface/IconThemePath                           -                   default             no overrides
	Interface/LastTabClosingAction                    openTab             default             no overrides
	Interface/LockToolBars                            false               default             no overrides
	Interface/NewTabOpeningAction                     maximizeTab         default             no overrides
	Interface/NotificationVisibilityDuration          5                   default             no overrides
	Interface/ShowScrollBars                          true                default             no overrides
	Interface/ShowSizeGrip                            true                default             no overrides
	Interface/StyleSheet                              -                   default             no overrides
	Interface/UseNativeNotifications                  true                default             no overrides
	Interface/UseSystemIconTheme                      false               default             no overrides
	Interface/WidgetStyle                             -                   default             no overrides
	Network/AcceptLanguage                            -                   default             no overrides
	Network/CookiesKeepMode                           keepUntilExpires    default             no overrides
	Network/CookiesPolicy                             acceptAll           default             no overrides
	Network/DoNotTrackPolicy                          skip                default             no overrides
	Network/EnableReferrer                            true                default             no overrides
	Network/Proxy                                     system              default             no overrides
	Network/ThirdPartyCookiesAcceptedHosts                                default             no overrides
	Network/ThirdPartyCookiesPolicy                   acceptAll           default             no overrides
	Network/ThirdPartyCookiesRejectedHosts                                default             no overrides
	Network/UserAgent                                 default             default             no overrides
	Network/WorkOffline                               false               default             no overrides
	Paths/Downloads                                   -                   default             no overrides
	Paths/OpenFile                                    -                   default             no overrides
	Paths/SaveFile                                    -                   non default         no overrides
	Permissions/EnableFullScreen                      ask                 default             no overrides
	Permissions/EnableGeolocation                     ask                 default             no overrides
	Permissions/EnableImages                          enabled             default             no overrides
	Permissions/EnableJavaScript                      true                default             no overrides
	Permissions/EnableLocalStorage                    true                default             no overrides
	Permissions/EnableMediaCaptureAudio               ask                 default             no overrides
	Permissions/EnableMediaCaptureVideo               ask                 default             no overrides
	Permissions/EnableMediaPlaybackAudio              ask                 default             no overrides
	Permissions/EnableNotifications                   ask                 default             no overrides
	Permissions/EnableOfflineStorageDatabase          false               default             no overrides
	Permissions/EnableOfflineWebApplicationCache      false               default             no overrides
	Permissions/EnablePlugins                         onDemand            default             no overrides
	Permissions/EnablePointerLock                     ask                 default             no overrides
	Permissions/EnableWebgl                           true                default             no overrides
	Permissions/ScriptsCanAccessClipboard             false               default             no overrides
	Permissions/ScriptsCanChangeWindowGeometry        true                default             no overrides
	Permissions/ScriptsCanCloseSelfOpenedWindows      true                default             no overrides
	Permissions/ScriptsCanCloseWindows                ask                 default             no overrides
	Permissions/ScriptsCanOpenWindows                 ask                 default             1 override(s)
	Permissions/ScriptsCanReceiveRightClicks          true                default             no overrides
	Permissions/ScriptsCanShowStatusMessages          false               default             no overrides
	QtWebKitBackend/EnableMedia                       true                default             no overrides
	QtWebKitBackend/EnableMediaSource                 false               default             no overrides
	Search/DefaultQuickSearchEngine                   duckduckgo          default             no overrides
	Search/DefaultSearchEngine                        duckduckgo          default             no overrides
	Search/EnableFindInPageAsYouType                  true                default             no overrides
	Search/ReuseLastQuickFindQuery                    false               default             no overrides
	Search/SearchEnginesOrder                                             default             no overrides
	Search/SearchEnginesSuggestions                   false               default             no overrides
	Security/AllowMixedContent                        false               default             no overrides
	Security/Ciphers                                  default             default             no overrides
	Security/IgnoreSslErrors                                              default             no overrides
	Sessions/OpenInExistingWindow                     false               default             no overrides
	Sessions/OptionsExludedFromInheriting             Content/PageReloadTimedefault             no overrides
	Sessions/OptionsExludedFromSaving                                     default             no overrides
	SourceViewer/ShowLineNumbers                      true                default             no overrides
	SourceViewer/WrapLines                            false               default             no overrides
	StartPage/BackgroundColor                                             default             no overrides
	StartPage/BackgroundMode                          standard            default             no overrides
	StartPage/BackgroundPath                          -                   default             no overrides
	StartPage/BookmarksFolder                         -                   default             no overrides
	StartPage/EnableStartPage                         true                default             no overrides
	StartPage/ShowAddTile                             true                default             no overrides
	StartPage/ShowSearchField                         true                default             no overrides
	StartPage/TileBackgroundMode                      thumbnail           default             no overrides
	StartPage/TileHeight                              190                 default             no overrides
	StartPage/TileWidth                               270                 default             no overrides
	StartPage/TilesPerRow                             0                   default             no overrides
	StartPage/ZoomLevel                               100                 default             no overrides
	TabBar/EnablePreviews                             true                default             no overrides
	TabBar/EnableThumbnails                           false               default             no overrides
	TabBar/MaximumTabHeight                           -1                  default             no overrides
	TabBar/MaximumTabWidth                            250                 default             no overrides
	TabBar/MinimumTabHeight                           -1                  default             no overrides
	TabBar/MinimumTabWidth                            -1                  default             no overrides
	TabBar/OpenNextToActive                           true                default             no overrides
	TabBar/PreviewsAnimationDuration                  250                 default             no overrides
	TabBar/RequireModifierToSwitchTabOnScroll         true                default             no overrides
	TabBar/ShowCloseButton                            true                default             no overrides
	TabBar/ShowUrlIcon                                true                default             no overrides
	Updates/ActiveChannels                                                default             no overrides
	Updates/AutomaticInstall                          false               default             no overrides
	Updates/CheckInterval                             7                   default             no overrides
	Updates/LastCheck                                 -                   non default         no overrides
	Updates/ServerUrl                                 -                   default             no overrides

**Comment by Emdek** [comment]
@erdosnew, first of all, update to newer weekly, 169 is ancient (6 months old), in the meantime there was the long awaited QtWebKit upgrade (XP variant uses the same version as other Windows builds now) which brings fixes for SSL issues (bundled certificates from Mozilla), enables support for some multimedia formats (using GStreamer backend with bundled codecs) etc.
I don't see any unusual overrides in settings, so lets try that way first.

**Comment by erdosnew** [comment]
thank you, update solves the problem!

it's great that otter still supports XP!  Great Job!  thanks!

**Comment by Emdek** [comment]
@erdosnew, it will be supported as long as it doesn't require too big effort, so I guess that it should get at least two more years of support.
