### ISSUE TITLE
Failing to run built application on macOS

### ISSUE THREAD

**Issue by xaek** [OtterBrowser/otter-browser#1417]
I have successfully built Otter Browser on macOS, however whenever I try to run built application I receive following error:

$ open ./Otter\ Browser.app/
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Otter Browser.app.

Compilation Platform:

- Mac OS X 10.12.6  
- XCODE9  
- clang-900.0.37 
- cmake version 3.9.3
-  Qt 5.9.1 from official binary
- compiled QtWebKit from https://github.com/annulen/webkit
-  hunspell 1.6.2 (homebrew)

Please let me know if you need additional debug information.

**Comment by Emdek** [comment]
@xaek, obviously I do. :-)
Some sort of backtrace would be useful.

**Comment by xaek** [comment]
Ok, I'll try to make backtrace.
Also .app package is only 15.2 MB. Is it right size?
It seems smaller than official packages, could the error be due to that something was omitted during build?

**Comment by Emdek** [comment]
@xaek, you should deploy it using `macdeployqt`.

**Comment by xaek** [comment]
@Emdek Thanks, used macdeployqt and .app package is 178.8 MB now.
Still receiving the same error as in first comment.

**Comment by Emdek** [comment]
@xaek, it seems to be some generic error message and there are many results around, but this one is quite interesting:
https://www.oxygenxml.com/forum/topic13639.html

**Comment by xaek** [comment]
@Emdek Could this be the reason? Some missing library.

dyld: Library not loaded: @rpath/QtWebKitWidgets.framework/Versions/5/QtWebKitWidgets
  Referenced from: /Applications/Otter Browser.app/Contents/MacOS/./Otter Browser
  Reason: image not found
Abort trap: 6

**Comment by Emdek** [comment]
@xaek, yes.
Also why not simply using these binaries?
https://github.com/annulen/webkit/releases/tag/qtwebkit-5.212.0-alpha2

**Comment by xaek** [comment]
@Emdek Do you know how to fix it?
I have QtWebKitWidgets in /usr/local/lib

**Comment by Emdek** [comment]
@xaek, I'm using official Qt SDK binaries combined with _qtwebkit-5.212.0_alpha2-qt59-darwin-x64.tar.xz_ from that link, just unpacking them to proper directories in SDK using mc (since Finder is too stupid to merge directories...) and then building using QtCreator.

**Comment by xaek** [comment]
@Emdek Thank you very much for your help! Followed your instructions from last comment and Otter Browser is now running fine.
