### ISSUE TITLE
incorrect display "downloads" tab (very narrow column)

### ISSUE THREAD

**Issue by franco27** [OtterBrowser/otter-browser#1418]
on my 2 computers under Windows 10, with the version of OtterBrowser 0.9.91 weekly193.
![2017-09-24 17_42_43-telechargements - otter browser](https://user-images.githubusercontent.com/31793920/30784363-1d62a6f0-a154-11e7-829e-0daca3649aa1.png)

I can not definitely apply the column width of the "Downloads" tab.
Each time I open the "Downloads" tab, the filename column is always very narrow (too narrow to read the name).

**Comment by franco27** [comment]
Each time I change the size of the column "file name" but when I open the "downloads" tab again.
The width settings always return as shown in the screenshot.

**Comment by Emdek** [comment]
@franco27, it's related to #1035 which got fixed earlier this week.
There were also some other changes that improve sizing of that column especially c8ff5c19fdb7fd872684de685168f7cf85093ee5. 
it should be always at least 500 pixels plus extra space if avilable (bce063468a44ba4d2ad5fc0252207b1940023bee).

**Comment by franco27** [comment]
Ok thank you. I'm waiting for the update

**Comment by franco27** [comment]
I confirm that this issue is resolved
