### ISSUE TITLE
otter fails to launch error on freebsd 11 

### ISSUE THREAD

**Issue by erdosnew** [OtterBrowser/otter-browser#1419]
ver.   otter-browser-0.9.12_2     
error occurred during launch,   core dumped, otter failed to lanuch.

"otter-browserqt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set1_groups"

this is for freebsd 11 installation of otter.

**Comment by Emdek** [comment]
@erdosnew, it's a bug in QtNetwork package (part of QtBase), please report it to maintainers of Qt packages in FreeBSD.
Perhaps Qt was updated but patches for adding LibreSSL weren't updated or something like that.
