### ISSUE TITLE
French translation incorrect

### ISSUE THREAD

**Issue by franco27** [OtterBrowser/otter-browser#1420]
In the parameters of OtterBrowser, in General/At startup
For the French language, there is a mistake
![2017-09-27 13_07_13-preferences - otter browser](https://user-images.githubusercontent.com/31793920/30910646-e8c15f66-a385-11e7-8dbd-f8ada3063f9a.png)

"Afficher la page vide" is an incorrect translation
When I select this setting, when starting OtterBrowser, it is the Speed dial that is displayed.

It would be necessary to replace "Afficher la page vide" by "Afficher la Speed dial"

on the other hand, the title of the tab is inappropriate, this causes confusion for the Speed ​​dial.
for tab "Page de démarrage" to replace by "Speed dial"

![2017-09-27 13_30_40-page de demarrage - otter browser](https://user-images.githubusercontent.com/31793920/30911424-d72fbbfa-a388-11e7-9451-11b934a28e04.png)

**Comment by aurhat** [comment]
https://www.transifex.com/otter-browser/otter-browser/dashboard/ - you can register on Transifex and join to French team, to fix the translation. :)

**Comment by Emdek** [comment]
@franco27, yeah, translations are handled outside github and not all translators watch tickets here, so such stuff has to be reported on Transifex (granted, their UI is not optimized for reporting such issues by people from outside translation teams...).

**Comment by franco27** [comment]
Ok, thank you for your answers.
but I have a big problem to go to the page:
https://www.transifex.com/otter-browser/otter-browser/dashboard/

with OtterBrowser, every time I want to go to this URL. OtterBrowser freezes and when I try to click a menu or button, a Windows error message "the application does not respond".
To close Otter, I have to use the task manager.

With Opera or Vivaldi, there's no problem.

I'm with the version Otter:
installer for Windows 7 or later, 64 bit (36.4 MiB); Weekly report #195 (25-09-2017)

**Comment by Emdek** [comment]
@franco27, it seems to be some generic JS issue on Windows 7 64 bit (maybe 32 bit one too).
Try this:
https://github.com/annulen/webkit/wiki/Debugging-issues-with-JavaScript-execution

**Comment by franco27** [comment]
I am under Windows 10  64bits.
I have installed both versions of JAVA 32bits ant 64bits.

I am not familiar with computer programming.

**Comment by Emdek** [comment]
@franco27, Java != JavaScript.

**Comment by franco27** [comment]
Thank you for your response. I understood for Java and Javascript. After reading this URL, I didn't know what to do.

**Comment by franco27** [comment]
With the Otter version : Weekly report #196 (02-10-2017) and (Pre) RC 1 release , installer for Windows 7 or later, 64 bit:
when I go directly to this URL: Otter no longer responds (problem always present)
https://www.transifex.com/otter-browser/otter-browser/dashboard/

but when I go to https://www.transifex.com/ and I access the OtterBrowser project
by this method, I no longer have this problem

**Comment by franco27** [comment]
I made the modification for the French language
