### ISSUE TITLE
AppImage fails to run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [OtterBrowser/otter-browser#1424]
otter-browser-0.9.91-rc1v2-x86_64.AppImage fails to run on Ubuntu 14.04:

```
./otter-browser: symbol lookup error: /run/firejail/appimage/.appimage-7142/lib/libQt5WebKit.so.5: undefined symbol: _gst_tag_list_type
```

What system was this built on?

Reference:
https://travis-ci.org/AppImage/appimage.github.io/builds/282251292#L693

**Comment by Emdek** [comment]
@probonopd, it was built by Qt CI (official binaries), and to have all features enabled it requires GStreamer 1.4 or newer (and bundling it is not an option thanks to stuff like PulseAudio etc.).
I'm not sure if it's worth to wasting time on supporting that outdated Ubuntu variant (which seems to not even have 1.x preinstalled, so it will fail anyway), it forces me to risk stability of my fragile build VM, highly patched CentOS6, if it breaks it might mean no AppImages at all (I don't have another entire three days to setup it from scratch... well, this time it would be closer to one full day, I guess).
I've also tried to do minimal rebuild (rebuilding entire QtWebKit is pain, especially when messing with one of dependencies at the same time) without code path that uses single feature from 1.0.4 but it fails with the same error (my VM has 1.10).

**Comment by Emdek** [comment]
@probonopd, I've managed to get it running with help from @annulen, some renaming in incompatible GStreamer headers allowed to build compatible library without need for full rebuild.

**Comment by probonopd** [comment]
Thanks, that error went away. However I see that you are bundling `libnsl.so.1`. This is known to be problematic, as this library (as the following ones) is part of glibc, and one should not attempt to mix and match different parts of glibc from different versions.

* ld-linux.so.2
* ld-linux-x86-64.so.2
* libanl.so.1
* libBrokenLocale.so.1
* libcidn.so.1
* libcrypt.so.1
* libc.so.6
* libdl.so.2
* libm.so.6
* libmvec.so.1
* libnsl.so.1
* libnss_compat.so.2
* libnss_db.so.2
* libnss_dns.so.2
* libnss_files.so.2
* libnss_hesiod.so.2
* libnss_nisplus.so.2
* libnss_nis.so.2
* libpthread.so.0
* libresolv.so.2
* librt.so.1
* libthread_db.so.1
* libutil.so.1

**Comment by Emdek** [comment]
@probonopd, dunno, for me it works with and without that library under 14.04 (from osboxes.org), but note that it requires patched QtWebKit to lower required GStreamer version and I'm not sure anymore if latest AppImage was using it (I'm testing using unpackaged files).
I'm not sure why it was included, AFAIR there were just libraries picked up by `linuxdeployqt` from last year, but it was almost one year ago so I'm not 100% sure.
Anyway, perhaps it will make slight size difference too, it was pretty big library. ;-)
