### ISSUE TITLE
Otter startup error "BAD IMAGE"

### ISSUE THREAD

**Issue by sotel** [OtterBrowser/otter-browser#1427]
During startup of Otter I get always an error: "Bad image. C:\Windows\system32\wpdshext.dll is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator" (see screenshot, German version).
I never saw this error here before and I did a system check: no results, all ok.

Here runs: 
-Windows 7 pro 64bit
-Otter (Pre) RC 1 release (01-10-2017) from its setup file: otter-browser-win64-0.9.91-rc1v2-setup.exe

Screenshot:
![bildschirmfoto_001_2017-10-06_21-37-15](https://user-images.githubusercontent.com/107782/31303246-79a3fb48-ab0a-11e7-91e9-d2fc3c05fe87.png)

**Comment by Emdek** [comment]
@sotel, that sounds like some sort of Windows issue, it's a system library:
http://www.win7dll.info/wpdshext_dll.html
Apparently Inno Setup somehow triggers it.
