### ISSUE TITLE
XP support roadmap

### ISSUE THREAD

**Issue by tumagonx** [OtterBrowser/otter-browser#1430]
Hi I just tried Otter on Windows XP, and I think this is the best Webkit browser since Apple drop safari on Windows.
As I once tinkering on webkitgtk I believe it also face the same cloudy upstream issue. So my question
Will XP version survive colossal version 1.0 and on? I hope it won't be like Vivaldi :(

Note that current XP build seems affected by glib regression https://bugzilla.gnome.org/show_bug.cgi?id=739835 so gstreamer unable to find plugins unless pointed by say GST_PLUGIN_PATH envvar

**Comment by m4sk1n** [comment]
It would be so stupid to stop releasing Otter for Windows XP, Emdek really cares of this version. It's not only best WebKit browser for Windows, it's probably the best supported browser for XP… ;)

**Comment by beastie1** [comment]
Sure that [may be true](https://github.com/OtterBrowser/otter-browser/issues/1416#issuecomment-331361917) ...

But perhaps you forget there are (mainly) two things the Otter Browser project has low - if not zero - control over: WebKit and Qt. While everyone in these projects remains cooperative everything's good, but that can't be guaranteed to last forever.

**Comment by tumagonx** [comment]
That's why I want to know the roadmap, at least please don't be abrupt like vivaldi (the last version for XP is neither rock stable nor feature polished).
Personally I don't really care html5 compliance as I still use Opera 12 which presto may on par with webkit in that regard.

**Comment by Emdek** [comment]
@tumagonx, as long as QtWebKit will continue to work with Qt 5.6.x (the last LTS release that has XP support - it's doable with newer versions but requires patching) it's not a problem.
BTW, I haven't seen that issue, but instead these environment variables never worked for me, just relative paths.
