### ISSUE TITLE
password manager greyed out in settings

### ISSUE THREAD

**Issue by riBoon** [OtterBrowser/otter-browser#1431]
Maybe related to issue #1343 but I think not.
I test the weekly build. I can't enable the password manager, its just greyed out.

Is it a issue just with linux? I have ubunutu 14.04 and use the ppa
https://launchpad.net/~otter-browser

![otter-browser-about_version jpg](https://user-images.githubusercontent.com/8161689/31428404-e3eec254-ae6a-11e7-8f65-6519c5a0ea08.png)
![otter-browser-password_manager_greyed_out jpg](https://user-images.githubusercontent.com/8161689/31428406-e49af948-ae6a-11e7-833d-d8906eb246c3.png)

**Comment by Emdek** [comment]
@riBoon, it's not the newest, it's the last one that can be built on that outdated version of Ubuntu (although it fails for no good reason, since hunspell is not mandatory).
Just use AppImage instead, note that it requires GStreamer 1.0 (0.10 is incompatible) to be installed.
