### ISSUE TITLE
Wrong color for tab text

### ISSUE THREAD

**Issue by tsujan** [OtterBrowser/otter-browser#1433]
Apparently, otter-browser consults the Qt style engine for `CE_TabBarTabShape` (in `QStyle::drawControl`) to draw the tab background -- which is good -- but doesn't consult `CE_TabBarTabLabel` to draw the tab label. That can result in an unreadable text when the (active) tab background has a high contrast with the window background. The following screenshot shows the issue with otter-browser styled by a Kvantum theme (under Linux):

![tabs](https://user-images.githubusercontent.com/981076/31575353-b49fb93e-b0f1-11e7-81db-2c9b4e1df707.png)

The correct rendering would be like this (the following screenshot is taken with another Qt5 browser):

![correct](https://user-images.githubusercontent.com/981076/31575356-f1b447cc-b0f1-11e7-925b-ab7d8dc7418a.png)

IMHO, if the the text of a widget is drawn by the app code, its background (panel) should be so too, and conversely. Generally, it's more desirable to leave all drawings to the active Qt style engine -- at least under Linux --  for a consistent look and feel.

**Comment by Emdek** [comment]
@tsujan, yeah, I knew that it will pop up sooner or later, the main issue is that I didn't have any proper style to test such variant, thanks.

**Comment by tsujan** [comment]
Glad to know that you knew about it! Actually, this issue is not important. Themes like the above one are very rare and, as far as I know, only Kvantum supports them.

**Comment by Emdek** [comment]
@tsujan, BTW, which theme is that? I can't find it in *kvantummanager*.

**Comment by tsujan** [comment]
It's "KvSimplicityTurquoise" -- yes, a very long name ;) -- and is installed with Kvantum.

After I took a look at your commits for Otter, I realized that pay attention to minute details. Hence this report; otherwise -- as I said above -- it isn't important, IMO.

**Comment by Emdek** [comment]
@tsujan, thanks, now I can test it properly.

**Comment by Emdek** [comment]
I've prepared some initial patch (marking as active window can be improved):

```diff
diff --git a/src/ui/TabBarWidget.cpp b/src/ui/TabBarWidget.cpp
index 9cece3d4..7351beb2 100644
--- a/src/ui/TabBarWidget.cpp
+++ b/src/ui/TabBarWidget.cpp
@@ -63,6 +63,7 @@ TabHandleWidget::TabHandleWidget(Window *window, TabBarWidget *parent) : QWidget
 	m_window(window),
 	m_tabBarWidget(parent),
 	m_dragTimer(0),
+	m_isActiveWindow(false),
 	m_isCloseButtonUnderMouse(false),
 	m_wasCloseButtonPressed(false)
 {
@@ -70,7 +71,6 @@ TabHandleWidget::TabHandleWidget(Window *window, TabBarWidget *parent) : QWidget
 	setAcceptDrops(true);
 	setMouseTracking(true);
 
-	connect(window, &Window::activated, this, &TabHandleWidget::markAsActive);
 	connect(window, &Window::needsAttention, this, &TabHandleWidget::markAsNeedingAttention);
 	connect(window, &Window::titleChanged, this, static_cast<void(TabHandleWidget::*)()>(&TabHandleWidget::update));
 	connect(window, &Window::iconChanged, this, static_cast<void(TabHandleWidget::*)()>(&TabHandleWidget::update));
@@ -186,15 +186,26 @@ void TabHandleWidget::paintEvent(QPaintEvent *event)
 
 	if (m_titleRectangle.isValid())
 	{
-		QColor color(palette().color(QPalette::Text));
+		QStyleOptionTab option;
+		option.initFrom(this);
+		option.rect = m_titleRectangle;
+		option.text = m_window->getTitle();
+
+		if (m_isActiveWindow)
+		{
+			option.state |= QStyle::State_Selected;
+		}
+
+		painter.save();
 
 		if (m_window->getLoadingState() == WebWidget::DeferredLoadingState)
 		{
-			color.setAlpha(150);
+			painter.setOpacity(0.75);
 		}
 
-		painter.setPen(color);
-		painter.drawText(m_titleRectangle, ((isRightToLeft() ? Qt::AlignRight : Qt::AlignLeft) | Qt::AlignVCenter), fontMetrics().elidedText(m_window->getTitle(), Qt::ElideRight, m_titleRectangle.width()));
+		style()->drawControl(QStyle::CE_TabBarTabLabel, &option, &painter);
+
+		painter.restore();
 	}
 }
 
@@ -284,14 +295,9 @@ void TabHandleWidget::dragEnterEvent(QDragEnterEvent *event)
 	}
 }
 
-void TabHandleWidget::markAsActive()
-{
-	setFont(parentWidget()->font());
-}
-
 void TabHandleWidget::markAsNeedingAttention()
 {
-	if (m_tabBarWidget->getWindow(m_tabBarWidget->currentIndex()) != m_window)
+	if (!m_isActiveWindow)
 	{
 		QFont font(parentWidget()->font());
 		font.setBold(true);
@@ -504,6 +510,21 @@ void TabHandleWidget::updateGeometries()
 	update();
 }
 
+void TabHandleWidget::setIsActiveWindow(bool isActive)
+{
+	if (isActive != m_isActiveWindow)
+	{
+		m_isActiveWindow = isActive;
+
+		if (isActive)
+		{
+			setFont(parentWidget()->font());
+		}
+
+		update();
+	}
+}
+
 Window* TabHandleWidget::getWindow() const
 {
 	return m_window;
@@ -1132,6 +1153,11 @@ void TabBarWidget::addTab(int index, Window *window)
 	{
 		updatePinnedTabsAmount();
 	}
+
+	if (count() == 1)
+	{
+		handleCurrentChanged(0);
+	}
 }
 
 void TabBarWidget::removeTab(int index)
@@ -1410,6 +1436,16 @@ void TabBarWidget::handleCurrentChanged(int index)
 	{
 		showPreview(tabAt(mapFromGlobal(QCursor::pos())));
 	}
+
+	for (int i = 0; i < count(); ++i)
+	{
+		TabHandleWidget *tabHandleWidget(qobject_cast<TabHandleWidget*>(tabButton(i, QTabBar::LeftSide)));
+
+		if (tabHandleWidget)
+		{
+			tabHandleWidget->setIsActiveWindow(i == index);
+		}
+	}
 }
 
 void TabBarWidget::updatePinnedTabsAmount()
diff --git a/src/ui/TabBarWidget.h b/src/ui/TabBarWidget.h
index 7e7225d9..908c43aa 100644
--- a/src/ui/TabBarWidget.h
+++ b/src/ui/TabBarWidget.h
@@ -40,6 +40,7 @@ class TabHandleWidget final : public QWidget
 public:
 	explicit TabHandleWidget(Window *window, TabBarWidget *parent);
 
+	void setIsActiveWindow(bool isActive);
 	Window* getWindow() const;
 
 protected:
@@ -54,7 +55,6 @@ protected:
 	void dragEnterEvent(QDragEnterEvent *event) override;
 
 protected slots:
-	void markAsActive();
 	void markAsNeedingAttention();
 	void handleLoadingStateChanged(WebWidget::LoadingState state);
 	void updateGeometries();
@@ -67,6 +67,7 @@ private:
 	QRect m_thumbnailRectangle;
 	QRect m_titleRectangle;
 	int m_dragTimer;
+	bool m_isActiveWindow;
 	bool m_isCloseButtonUnderMouse;
 	bool m_wasCloseButtonPressed;
 
```
While it works fine with Kvantum there are new issues with Fusion, it fails to elide text and simply clips it.
It seems that at least some styles expect elided text when using `QStyleOptionTab`.
Also we will need to align rectangle to force text alignment (I find it odd that there is no style hint or setter to force it, such mechanism exists for some other widgets and `QTabBar` has slightly related option already, ability to force elide mode).

**Comment by tsujan** [comment]
Yes, I'd guessed that you wanted elided text with fusion.

I'll look into it and will make a PR if a solution comes out.

**Comment by Emdek** [comment]
@tsujan, no worries, I can take care of it myself.
I already have an idea how to align it and cache results (adjusted rectangle and elided text) to make it cheaper to repaint.
But since I have a rare opportunity to consult such changes with someone who deals with QStyles I've decided to split it to increase chances of getting some valuable feedback. ;-)

**Comment by tsujan** [comment]
> no worries, I can take care of it myself.

I know, of course. It's just that delving into the code of this nice browser seems exciting :) Looking forward to your solution.

**Comment by tsujan** [comment]
Your above-mentioned solution worked fine with all styles as soon as I replaced `option.text = m_window->getTitle();` with:
```cpp
option.text = fontMetrics().elidedText(m_window->getTitle(),
                                       Qt::ElideRight,
                                       style()->subElementRect(QStyle::SE_TabBarTabText, &option).width());
```
This is with Fusion:

![fusion](https://user-images.githubusercontent.com/981076/31866028-a4aad7f8-b785-11e7-9661-e39d2e586d32.png)

And this with Kvantum:

![kvantum](https://user-images.githubusercontent.com/981076/31866034-ae1898f2-b785-11e7-9e88-d6459977633f.png)

**Comment by tsujan** [comment]
It just seems that paddings are too big.

**Comment by Emdek** [comment]
@tsujan, there was some extra padding as leftover from previous approach, you can find it in branch:
https://github.com/OtterBrowser/otter-browser/tree/tabBarTextColor

But it's still too big, but it seems to be constant for all, perhaps it is safe to assume that we can make rectangle slightly wider without consequences.
I'm going to test it under Windows 10 and macOS (this one might require extra overrides in our platform style, since it has to use customized tab bar, since Qt provides outdated look, completely different from Finder or Safari...) later today.

**Comment by tsujan** [comment]
I'll test it tonight.

As for Windows and Mac, I totally forgot about them ;) Maybe some changes need to be OS specific. I can test only on Linux.

**Comment by Emdek** [comment]
@tsujan, I can provide screenshots, no problem.
If results will be satisfactory then I would go for pushing it today, to have a chance to gather more feedback from users, so it could be improved (if needed) in time for RC2.

**Comment by tsujan** [comment]
I had a little time to test, downloaded https://github.com/OtterBrowser/otter-browser/tree/tabBarTextColor, and used these under paintEvent → `if (m_titleRectangle.isValid())`:
```cpp
if (m_titleRectangle.isValid())
{
	QStyleOptionTab option;
	option.initFrom(this);
	option.rect = m_titleRectangle | m_urlIconRectangle | m_closeButtonRectangle;
	option.text = option.text = fontMetrics().elidedText(m_window->getTitle(),
	                                                     Qt::ElideRight,
	                                                     m_titleRectangle.width());
...
```
The reason was that the option rect should be *the total rect* while the text should be elided inside the title rect. I think this is what you want:

Fusion:

![fusion](https://user-images.githubusercontent.com/981076/31881883-d8d82046-b7f1-11e7-8c28-2c4c7d1882b4.png)

Kvantum:

![kvantum1](https://user-images.githubusercontent.com/981076/31881892-e230bc8e-b7f1-11e7-970b-37334a7c1e45.png)

![kvantum2](https://user-images.githubusercontent.com/981076/31881898-e85cafdc-b7f1-11e7-87f9-36240bdc6e1b.png)

A 2-3px padding could be added to the left if it looks too tight (will play with that tonight).

**Comment by Emdek** [comment]
@tsujan, yeah, but it might cause issues with forced horizontal alignment (and it's important for me).
I'll play a bit with it, I know that experimenting with button sizes in `QStyleOptionTab` could be a good idea too, but some styles ignore these values (and we force our own sizes), especially macOS style was nasty...

**Comment by tsujan** [comment]
I'm almost sure that the above calculation is correct -- except for the text-icon spacing, that should be added. To test more, I set max tab width to 400px and the result was the same:

![400px](https://user-images.githubusercontent.com/981076/31883397-abb54544-b7f6-11e7-8a23-618ec844e505.png)

However, no one knows your code better than you. I admit that I didn't consider all aspects of the above change.

**Comment by Emdek** [comment]
@tsujan, I guess that I'll have to override this value in our proxy style to make it right:
http://code.qt.io/cgit/qt/qtbase.git/tree/src/widgets/widgets/qtabbar.cpp#n233

**Comment by Emdek** [comment]
@tsujan, I've updated branch (note that commit that removed padding was forcefully reverted), now I'm forcing that rectangle (reusing `documentMode` hack, so it doesn't affect other widgets) and it seems to work as before, but using proper color supplied by the style.
It still needs custom horizontal alignment but it's trivial with this override.

**Comment by Emdek** [comment]
@tsujan, done, but now I have a problem with Kvantum, it doesn't like forced align, there is still some extra padding and text ends up elided even when not needed.
There is some extra debug, including drawing rectangles for both available label space and space computed for title.

Perhaps I should move that part (aligning) to `Style` or expose some extra hint to let it continue to adjust alignment on supported themes.

Diff for *tabBarTextColor*:

```diff
diff --git a/src/ui/TabBarWidget.cpp b/src/ui/TabBarWidget.cpp
index 2e914c46..073e99be 100644
--- a/src/ui/TabBarWidget.cpp
+++ b/src/ui/TabBarWidget.cpp
@@ -184,11 +184,13 @@ void TabHandleWidget::paintEvent(QPaintEvent *event)
 		}
 	}
 
-	if (m_titleRectangle.isValid())
+	if (!m_title.isEmpty())
 	{
 		QStyleOptionTab option;
 		option.initFrom(this);
 		option.documentMode = true;
+		option.leftButtonSize = {0, 0};
+		option.rightButtonSize = {0, 0};
 		option.rect = m_titleRectangle;
 		option.text = m_title;
 
@@ -204,6 +206,9 @@ void TabHandleWidget::paintEvent(QPaintEvent *event)
 			painter.setOpacity(0.75);
 		}
 
+		painter.fillRect(m_labelRectangle, Qt::green);
+		painter.fillRect(m_titleRectangle, Qt::red);
+
 		style()->drawControl(QStyle::CE_TabBarTabLabel, &option, &painter);
 
 		painter.restore();
@@ -361,10 +366,11 @@ void TabHandleWidget::updateGeometries()
 
 	QRect controlsRectangle(style()->subElementRect(QStyle::SE_TabBarTabLeftButton, &option, m_tabBarWidget));
 
-	m_closeButtonRectangle = QRect();
-	m_urlIconRectangle = QRect();
-	m_thumbnailRectangle = QRect();
-	m_titleRectangle = QRect();
+	m_closeButtonRectangle = {};
+	m_urlIconRectangle = {};
+	m_thumbnailRectangle = {};
+	m_labelRectangle = {};
+	m_titleRectangle = {};
 
 	if (TabBarWidget::areThumbnailsEnabled())
 	{
@@ -444,7 +450,7 @@ void TabHandleWidget::updateGeometries()
 	}
 	else
 	{
-		m_titleRectangle = controlsRectangle;
+		m_labelRectangle = controlsRectangle;
 
 		if (isUrlIconEnabled)
 		{
@@ -454,19 +460,19 @@ void TabHandleWidget::updateGeometries()
 			{
 				m_urlIconRectangle.setLeft(controlsRectangle.right() - 16);
 
-				m_titleRectangle.setRight(controlsRectangle.right() - 20);
+				m_labelRectangle.setRight(controlsRectangle.right() - 20);
 			}
 			else
 			{
 				m_urlIconRectangle.setWidth(16);
 
-				m_titleRectangle.setLeft(m_urlIconRectangle.right() + 4);
+				m_labelRectangle.setLeft(m_urlIconRectangle.right() + 4);
 			}
 		}
 
 		if (isCloseButtonEnabled && (isActive || controlsWidth >= 70))
 		{
-			m_closeButtonRectangle = m_titleRectangle;
+			m_closeButtonRectangle = m_labelRectangle;
 
 			if (TabBarWidget::isLayoutReversed())
 			{
@@ -474,22 +480,22 @@ void TabHandleWidget::updateGeometries()
 			}
 			else
 			{
-				m_closeButtonRectangle.setLeft(m_titleRectangle.right() - 16);
+				m_closeButtonRectangle.setLeft(m_labelRectangle.right() - 16);
 			}
 
 			if (controlsWidth <= 40)
 			{
-				m_titleRectangle = QRect();
+				m_labelRectangle = {};
 			}
 			else
 			{
 				if (TabBarWidget::isLayoutReversed())
 				{
-					m_titleRectangle.setLeft(m_titleRectangle.left() + 20);
+					m_labelRectangle.setLeft(m_labelRectangle.left() + 20);
 				}
 				else
 				{
-					m_titleRectangle.setRight(m_closeButtonRectangle.left() - 4);
+					m_labelRectangle.setRight(m_closeButtonRectangle.left() - 4);
 				}
 			}
 		}
@@ -516,13 +522,35 @@ void TabHandleWidget::updateTitle()
 {
 	QString title(m_window->getTitle());
 
-	if (!m_titleRectangle.isValid() || m_titleRectangle.width() < 5)
+	if (!m_labelRectangle.isValid() || m_labelRectangle.width() < 5)
 	{
 		title.clear();
 	}
-	else if (fontMetrics().width(title) > m_titleRectangle.width())
+	else
 	{
-		title = fontMetrics().elidedText(title, Qt::ElideRight, m_titleRectangle.width());
+		int length(fontMetrics().width(title));
+
+		if (length > m_labelRectangle.width())
+		{
+			title = fontMetrics().elidedText(title, Qt::ElideRight, m_labelRectangle.width());
+			length = fontMetrics().width(title);
+		}
+
+		m_titleRectangle = m_labelRectangle;
+qDebug() << length << m_labelRectangle.width() << (length - m_labelRectangle.width());
+		if (length < m_labelRectangle.width())
+		{
+			const int difference(length - m_labelRectangle.width());
+
+			if (isLeftToRight())
+			{
+				m_titleRectangle.adjust(0, 0, difference, 0);
+			}
+			else
+			{
+				m_titleRectangle.adjust(difference, 0, 0, 0);
+			}
+		}
 	}
 
 	if (title != m_title)
diff --git a/src/ui/TabBarWidget.h b/src/ui/TabBarWidget.h
index 1a9aa56d..999e9ced 100644
--- a/src/ui/TabBarWidget.h
+++ b/src/ui/TabBarWidget.h
@@ -67,6 +67,7 @@ private:
 	QRect m_closeButtonRectangle;
 	QRect m_urlIconRectangle;
 	QRect m_thumbnailRectangle;
+	QRect m_labelRectangle;
 	QRect m_titleRectangle;
 	int m_dragTimer;
 	bool m_isActiveWindow;
```

**Comment by tsujan** [comment]
I'll join you tomorrow; today, I'm busy with some life problems...

**Comment by Emdek** [comment]
@tsujan, no worries, I've managed to take care of it, now I only need to check GTK style and macOS.
I went for extra hints in `Style`, by default enabling forced text alignment for Fusion, Breeze and Oxygen and letting platform style to override it.
It seems that I'll be able to merge it today, but we can always improve it afterwards if needed.

**Comment by tsujan** [comment]
Glad to hear that! And yes, improvements could be made afterward if needed. I like this app so much that I might bother you again and again ;)

**Comment by Emdek** [comment]
@tsujan, merged. :-)

I'm not sure what to do with macOS, Safari and Finder center text, I guess that we should follow it there, since they are strict about such details.

**Comment by tsujan** [comment]
> I'm not sure what to do with macOS, Safari and Finder center text

Interesting! I also center the text in `CE_TabBarTabLabel` (in Kvantum); from the start, it felt more natural.

**Comment by Emdek** [comment]
@tsujan, well, not in the browsers (except of Safari apparently, but this one is very special case...). ;-)
