### ISSUE TITLE
Runtime backend switching

### ISSUE THREAD

**Issue by Oblomov** [OtterBrowser/otter-browser#1434]
It would be nice to be able to switch backend at runtime, without having to edit `otter.conf`, possibly from the webview right-click menu, in a place similar to the one Opera used to allow opening a webpage in a different browser.

**Comment by aurhat** [comment]
You can change backend in about:config -> Backends/Web

**Comment by Oblomov** [comment]
Oh, nice, I didn't know that about:config had been implemented.

Backend switching still requires a restart though.

**Comment by aurhat** [comment]
New backend will affect the **new** tabs without restarting the browser.

**Comment by Oblomov** [comment]
I hadn't noticed that.

@Emdek also tells me on IRC that it's possible to add actions (e.g. toolbar actions) which open tabs with specific backends.

All in all it would seem that this is solved (in the sense that the possibilities are there), so it's more of a documentation/discoverability issue.

**Comment by Emdek** [comment]
@Oblomov, I guess that I can only mark it as Invalid, I was considering "needs documentation" label but it's a bit weird...
Anyway, there is related ticket: #1181.
