### ISSUE TITLE
The tabbar cannot be hidden in fullscreen mode

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#1440]
The option "Visibility in full screen mode" under Customize > Tabbar > Configure > Options has ceased working. No matter what the options are there, the Tabbar is fully visible in fullscreen mode. It begins shaking and vanishes only when "Visible only when cursor is close to screen edge" is selected and then in fullscreen you jerk the mouse at screen edge. But I want it always vanish and stay away securely in fullscreen mode.

**Comment by ersi-dnd** [comment]
Tried resetting the toolbar settings and then changing the settings again, also in clean profile, still cannot be hidden in fullscreen mode.

**Comment by ersi-dnd** [comment]
Have you tested this well? Tabbar still remains visible for me in fullscreen.

**Comment by Emdek** [comment]
@ersi-dnd, first make sure that your clone is up to date:
```
git reset --hard && git pull
```
And then rebuild and install if needed.
