### ISSUE TITLE
Feature request: Search in the coding terms in Keyboard Edit list

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#1441]
When you add a keybind in the Keyboard Edit dialog, the list can be searched (the slot at the bottom). This is very good, but it searches only in the current language of the app. 

When the user makes a search for an action, he may know the name of the action as it is coded, for example ShowToolbar, not whatever it is translated to. This is why it would be useful to have the search show results also in the coding terms.

In Cinnamon DE menus, the search turns up results both in the selected language of the environment and in the original coding language. I think this makes sense and the same should be implemented in that search in Otter. 

Also a cosmetic improvement - the list should collapse as the search narrows down.

**Comment by Emdek** [comment]
@ersi-dnd, what do you mean by collapsing? Some sort of animation?

**Comment by ersi-dnd** [comment]
By collapse I mean there's lots of empty space when filtering. It's prettier when there's no such empty space.
![collapse](https://user-images.githubusercontent.com/6865273/31860479-56c0f3ae-b723-11e7-91e9-7a0580fb14ed.png)

**Comment by ersi-dnd** [comment]
And no, I don't like animations at all. I prefer instant response everywhere.

**Comment by Emdek** [comment]
@ersi-dnd, ah, this filtering, I've misread this request. :-D
I can give it a try, but it might be risky, since that filtering is a hack by itself.

**Comment by ersi-dnd** [comment]
If there are similar searches/filters for commands elsewhere in Otter, the same request would of course apply to them too.

**Comment by Emdek** [comment]
@ersi-dnd, yeah, that's the point, I've applied it to these instead. :-D
There are at least two more places, `ActionComboBoxWidget` and `ToolBarDialog`.

**Comment by ersi-dnd** [comment]
![ekraanipilt 2017-10-22 14-58-27](https://user-images.githubusercontent.com/6865273/31861659-df3d050e-b739-11e7-9659-2952c98b00ef.png)
Here's my custom file in the Keyboard Edit dialog. What if this dialog showed ALL actions, even those not currently present, and permitted editing them? This way the Add popup would be unnecessary.

**Comment by Emdek** [comment]
@ersi-dnd, but there is no such thing as complete list of all possible actions once parameters arrived, so we would still need such solution for adding actions with custom parameters (yes, currently they are not editable there but that will be changed later).

**Comment by ersi-dnd** [comment]
Well, in Opera it worked something like this in the same (kind of) dialog:
1. Press Add - a new empty line appears
2. Begin typing in that line, suggestions appear as approriate (somewhat like in address field)

Wouldn't this work?

**Comment by Emdek** [comment]
@ersi-dnd, well, it's kind of the same concept, just reversing location of the field...
But simply making it editable makes it more complex and requiring to manually select entry from the list with tooltips showing identifier in textual form (yes, there is extra information there :-P) helps to ensure that user selects correct action.
I can rethink it later, for now it makes more sense to simply improve it.

**Comment by Emdek** [comment]
Upstream report for sizing issue: https://bugreports.qt.io/browse/QTBUG-63956.
