### ISSUE TITLE
new link

### ISSUE THREAD

**Issue by sofeboz** [OtterBrowser/otter-browser#1444]
i use otter browser winxp more th an 200 PC.
up to today i was using #188 without problem. finally today i upgraded system to #200.

but the browser always crash different times. (idk the reason)
and i found another error. when i click the link with _blank target that browser crash. there was no problem with #188.

sample:
https://www.w3schools.com/tags/att_a_target.asp

thanks

**Comment by Emdek** [comment]
@sofeboz, cannot reproduce using (not that much different) package for RC 2.
Please retry when it will go public.

**Comment by alexs-rnd** [comment]
Had the very same problem on _blank target with 200 on Windows 7 x64. The problem is gone with RC2.

**Comment by Emdek** [comment]
@alexs-rnd, thanks for confirmation.
