### ISSUE TITLE
Browser's elements are too big

### ISSUE THREAD

**Issue by dimqua** [OtterBrowser/otter-browser#1447]
I just installed Otter from AUR for ArchLinux, everything is fine, but it has enormous UI on my system.
I don't have such problem with Qupzilla, which is QtWebEngine-based, or any other Qt5 app.

![](https://i.imgur.com/pACUmwU.png)

<img src="https://i.imgur.com/jykpBLk.png" width="360"></img>

**Comment by Frenzie** [comment]
Adding cross-ref to #1428.

**Comment by dimqua** [comment]
@Frenzie running with QT_AUTO_SCREEN_SCALE_FACTOR=0 helps in my case.

![](https://i.imgur.com/OrtzELG.png)

**Comment by Frenzie** [comment]
@dimqua I don't think that's a reason to close the issue. A closed issue or PR is harder to find. I just didn't want to be the one to open it.
