### ISSUE TITLE
Blink backend does not recognise user.css

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#1451]
Here's the user.css that I use http://userstyles.org/styles/2187 

The user.css is applied in Content/UserStyleSheet

I switched to the Blink engine in Backends/Web, then restart. And the user.css has no effect anymore.

Is this a Blink problem or something that can be fixed in Otter?

**Comment by Emdek** [comment]
@ersi-dnd, it's one of many things not supported there.
There is no way to have proper support for them in QtWebEngine (AFAIR due to some sort of Blink limitations).
