### ISSUE TITLE
Feature request: handl all cookies from given domain

### ISSUE THREAD

**Issue by V-Z** [OtterBrowser/otter-browser#1457]
If I set acceptance of cookies to "always" and keeping until "ask every time", Otter asks for acceptance of every single cookie. It would be very helpful to have some option to remember that choice for whole domain. E.g. I go to some domain, it offers cookies, and I'd like to set accept or decline for whole domain.

I have Otter 0.9.92 on openSUSE Tumbleweed.

**Comment by Emdek** [comment]
@V-Z, you can setup policy per domain in Website Preferences (<kbd>Alt</kbd> + <kbd>F12</kbd>).
