### ISSUE TITLE
Blocking of advertisement doesn't work

### ISSUE THREAD

**Issue by V-Z** [OtterBrowser/otter-browser#1458]
If I allow content blocking (that tiny menu in bottom-right corner), I select some filters, I go to some site and see the content is not blocked and all filters are turned off. The filters keep turning off every time I go to any page or even reload the page.

I have Otter 0.9.92 on openSUSE Tumbleweed.

**Comment by Emdek** [comment]
@V-Z, you should use action from Tools menu instead to setup it globally, that menu sets it just for current tab.
Due to issue fixed in c673ecba it was cleared when using address field to open new URL.
