### ISSUE TITLE
Closing a window on macOS disables the About and Preference dialogs

### ISSUE THREAD

**Issue by jd284** [OtterBrowser/otter-browser#1460]
Version: 0.9.92-rc2 on macOS 10.13.1

Steps to reproduce:
- start Otter, have first window open
- open a second window (from menu or Command-N)
- close that second window (but not the first one!)
- About and Preference dialogs are now disabled despite still having the first window open, and the entries in the Otter menu are grayed out
- open a new window again
- About and Preference dialogs are now enabled again, until this window is closed too

This happens even if three or four windows are open, whenever one of them is closed these dialogs are disabled until a new window is opened again.

**Comment by Emdek** [comment]
@jd284, it seems to be some obscure Qt bug, I've tried renaming some of these actions and disabling their their menu roles and then they weren't affected.
See documentation for [QAction::MenuRole](http://doc.qt.io/qt-5/qaction.html#MenuRole-enum).
