### ISSUE TITLE
Bookmarks Bar folders show entire bookmarks content

### ISSUE THREAD

**Issue by resbro** [OtterBrowser/otter-browser#1462]
Each folder in bookmarks bar shows the whole bookmarks content

Win 10
Otter Rc3 x 64

**Comment by Emdek** [comment]
@resbro, that's normal, it operates on given bookmarks folder (just like Start Page), you can set custom folder in its configuration dialog.

**Comment by resbro** [comment]
no matter what i do weather its a new bookmarks bar or trading the folders configuration, EVERY folder when clicked shows the entire bookmarks folder contents.

**Comment by Emdek** [comment]
@resbro, oops, sorry, I misunderstood your report.

**Comment by resbro** [comment]
Okay! thanks.
