### ISSUE TITLE
Find (and Find next) partly do not work as expected... 

### ISSUE THREAD

**Issue by BorutAtGit** [OtterBrowser/otter-browser#1463]
...under some special hard circumstances.

When page content is contained in large multicolumn tables, it seems that repositioning the page over the first/next find does not work. On the other hand, marking the found strings seems to work OK.

**To reproduce:**

Open this page (be patient, it contains a large table):
https://wiki.openstreetmap.org/wiki/Template:PastEvents
Then Edit/Find... (or Ctrl+F), using the following search string: Leoben (it can be found at four places, "quarterly").

Finds seem to be marked as expected, but the page is not repositioned, neither to the first one, nor to next ones.

Admittedly, this is probably very hard to achieve. **Tested under Win7 32bit, using RC3 in a portable mode.** Note also, that in source of that page I see some strange (for my very moderate and not particularly current experience) css style tags of a div surrounding the table, for instance:

-moz-column-width:34em; 
-webkit-column-width:34em;
column-width:34em;
-moz-column-gap:1em;
-webkit-column-gap:1em;
column-gap:1em;

**Comment by Emdek** [comment]
@BorutAtGit, cannot reproduce under Linux or Windows 10.
Do you have access to some other environment where you could try to reproduce it?

**Comment by BorutAtGit** [comment]
@Emdek OK, I think I have nailed it: It apparently depends neither on OS, nor on UserAgent.

**Try this: Ctrl+F12; Content; Default zoom: 120%**

Then create a new tab and go to that page (simple reload does not seem to take into account the change in the zoom factor). Then try find.

I hope it will so be reproduced at your place too.

(Old eyes here, therefore default of 120%.)

**Comment by Emdek** [comment]
@BorutAtGit, indeed, it's related to zoom.
I was able to reproduce it using QtTestBrowser (test browser provided by QtWebkit), all you need to do is increase zoom and try to find text.
I'll create upstream ticket if needed.

**Comment by Emdek** [comment]
@BorutAtGit, it was confirmed that it's generic WebKit bug, so most likely we will have to wait for QtWebKit release based on new branch to get fix.

**Comment by annulen** [comment]
https://bugs.webkit.org/show_bug.cgi?id=180576

**Comment by annulen** [comment]
Bug doesn't reproduce on Mac port, that's why it is still here. Reproduces on GTK port

**Comment by BorutAtGit** [comment]
Might be connected, but am not sure (maybe it is the page, although this does not happen in other browsers):

1. Set zoom to >100%
2. Go to https://maps.metager.de/map/15.094738269406925,47.380100144986784,18
3. Note that the copyright information is not visible (bottom right map corner)
4. Zoom back to <=100
5. Note that the copyright information is now visible
