### ISSUE TITLE
Build failed with following errors.

### ISSUE THREAD

**Issue by Diablopc** [OtterBrowser/otter-browser#1466]
What wrong?
https://pastebin.com/W2b5vQyD
Tell me what extrainfo needed?

**Comment by mariokamenjak** [comment]
I am not sure. May be that some QT dependency is missing on your system. Wait for other people to comment as well.

**Comment by Diablopc** [comment]
Hmm, this shit happens with gcc-4.8, but everything  fine with gcc-7.
It seems need to add gcc-7 as a build dependency...

**Comment by Frenzie** [comment]
> It seems need to add gcc-7 in README as a build dependency...

Unless something changed within the last couple of weeks, it definitely builds on gcc 6.3.

But you left out all the other info, like the Qt version (and distro+version for context).

**Comment by Diablopc** [comment]
@Frenzie I had jump directly from 4.8  to 7.xx and didn't have the possibility to make any tests on 5.x or 6.x gcc releases.
But with 7.x all ok =)
System: openSUSE Leap 42.3
Qt: 5.10.0

**Comment by Emdek** [comment]
@Diablopc, apparently 4.8 is too old, 5.4.0 here.
You can also try clang.
