### ISSUE TITLE
Packages for Mageia 6.

### ISSUE THREAD

**Issue by Diablopc** [OtterBrowser/otter-browser#1469]
Due to uncertainty with MRC repos, fresh RPMs will be available in [YD folder](https://yadi.sk/d/ChjhBlZ_3QgQFW).
Also in plans reborn of Mageia Russian Repository (or maybe  as custom user repo) since New Year

**Comment by Emdek** [comment]
@Diablopc, unofficial packages should be tracked here:
https://github.com/OtterBrowser/otter-browser/wiki/Packages
