### ISSUE TITLE
Speeddial hot keys

### ISSUE THREAD

**Issue by ghost** [OtterBrowser/otter-browser#1472]
Legacy opera had func to immediate switch between first 9 speeddial tiles by pressing Ctrl[1-9]. What about to realize this in otter?

**Comment by Emdek** [comment]
@Diablopc, sure, it's planned.
I was close to finish it recently but it needs some more work on proper naming etc. (so we won't have to break and migrate it later).

**Comment by fnkkio** [comment]
@Emdek I think this can be closed.
