### ISSUE TITLE
Cmake Error

### ISSUE THREAD

**Issue by wuyougongzi** [OtterBrowser/otter-browser#1473]
I use ubuntu16.04  qt5.6.3

https://github.com/OtterBrowser/otter-browser/blob/5afdb84ebc7141f502e2cdacc6b649fa85dd339d/CMakeLists.txt#L84

Cmake Eorr at CmakeList.txt 84 (find_package)
By not providing FindQt5.Cmake in CMAKE_MODULE_PATH this project has asked CMake to find a package configureation file provied by 'Qt5'(request version 5.4.0) with any of the following names:

Qt5Config.CMake
qt5-config.cmake

....

I Add a line before line84 like this and slove the problem.

set(CMAKE_PREFIX_PATH $ENV{HOME})/Qt5.6.3 /5.6.3/gcc_64

I think this question because of  my qt environment. Does someone other have the same problem?

Do I need to add the code and push to the master branch?

**Comment by Diablopc** [comment]
@wuyougongzi it seems like you have Qt installed in non system path, and no another trouble =)

**Comment by Emdek** [comment]
@wuyougongzi, if you don't want to use system Qt or have to specify path then you simply have to set CMake variables in generic way, you can find instructions on the net, just make sure that you are using instructions for Qt5 and not for Qt4.
