### ISSUE TITLE
QWE backend would do better to check for QWE instead of Qt version?

### ISSUE THREAD

**Issue by RJVB** [OtterBrowser/otter-browser#1476]
I think that the QWE backend code would do better to check for the QWE version it builds against rather than the Qt version. 

QWE isn't very tightly coupled to a specific Qt version and has been maturing faster than Qt itself. Speaking just for myself, I have already been using QWE 5.7 with Qt 5.6LTS in the past, and now have a system that runs QWE 5.8.0 with Qt 5.9.3LTS .

The change is trivial of course:
[QWE_VERSION_CHECK.diff.txt](https://github.com/OtterBrowser/otter-browser/files/1589644/QWE_VERSION_CHECK.diff.txt)

**Comment by Emdek** [comment]
@RJVB, maybe, anyway, soon (2 - 3 months) we will bump requirements for QtWebEngine and most of (or all) existing checks will be dropped anyway (Qt 5.9 will be required for that backend, 5.6 for the rest).
