### ISSUE TITLE
Closing the last tab opens an empty page instead of the Speed Dial

### ISSUE THREAD

**Issue by lynqa** [OtterBrowser/otter-browser#1478]
As I described in the title – when I close the last tab, a new one is opened (according to the LastTabClosingAction setting in about:config), but instead of the Speed Dial (as it was in RC3 and before), all I see is an empty page titled "(untitled)".

**Comment by Diablopc** [comment]
@lynqa build with latest commit not causes this ( https://youtu.be/xX0iq3k5-ow )
and i cant remember similar earlier.
Try load default settings (by deletting user settings folder e.g. ~/.config/otter )
btw, dont forget to backup it =)

**Comment by lynqa** [comment]
You're right, sorry, the latest commit doesn't contain this bug. Please remove this issue report.

**Comment by Diablopc** [comment]
@lynqa U can close this issue by pressing "Close Issue" button which located under comment field.
