### ISSUE TITLE
How to install a Otter Browser on Ubuntu 17.04?

### ISSUE THREAD

**Issue by Cybermaxrus** [OtterBrowser/otter-browser#1489]
Hello! I would like to install a Otter Browser on Ubuntu 17.04 x64, please give a step-by-step instruction on how to compile it from the source code or give a binary installation package. Thank you.

**Comment by Frenzie** [comment]
If you want to create your own installable package, I wrote down some instructions here that may still be valid: https://thedndsanctuary.eu/index.php?topic=507.msg27803#msg27803

But there's also the PPAs, which are generally the simplest on Ubuntu:

* release (generally a good bet) https://launchpad.net/~otter-browser/+archive/ubuntu/release
* weekly (slightly outdated) https://launchpad.net/~otter-browser/+archive/ubuntu/weekly
* daily (slightly risky but up to date) https://launchpad.net/~otter-browser/+archive/ubuntu/daily

```bash
# replace release with weekly or daily if desired
sudo add-apt-repository ppa:otter-browser/release
sudo apt update
sudo apt install otter-browser
```

**Comment by Cybermaxrus** [comment]
I installed from the release. When I go to youtube the browser crash. when I open the facebook browser crash.

**Comment by Emdek** [comment]
@Cybermaxrus, it's because Ubuntu has extremely outdated dependencies, they will finally update them in 18.04.
