### ISSUE TITLE
ftp.videolan.org redirection issue

### ISSUE THREAD

**Issue by bugreport0** [OtterBrowser/otter-browser#1490]
1. Open http://www.videolan.org/developers/x264.html
2. Click Download x264 button
Expected result:
Download starts for ftp://ftp.videolan.org/pub/x264/snapshots/last_x264.tar.bz2
Actual result:
ftp://ftp.videolan.org/pub/x264/snapshots/last_x264.tar.bz2 is open as a folder, it contains ftp://ftp.videolan.org/pub/x264/snapshots/last_x264.tar.bz2//pub/x264/snapshots/last_x264.tar.bz2 link which is wrong

Using Otter 0.9.94

**Comment by Emdek** [comment]
@bugreport0, it seems to be missing handling of symlinks.
