### ISSUE TITLE
Jumbled appearance at pages such as www.reddit.com/r/waterfox/#siteTable 

### ISSUE THREAD

**Issue by grahamperrin** [OtterBrowser/otter-browser#1495]
https://photos.app.goo.gl/CPzy3Mnrqbq6Ni6A2 includes two shots of Otter on FreeBSD-CURRENT: 

- https://www.reddit.com/r/waterfox/ appears OK
- https://www.reddit.com/r/waterfox/#siteTable appears jumbled after the pointer is moved across it.

![2018-02-18 17_20_11 otter 02](https://user-images.githubusercontent.com/192271/36355910-74a435d0-14e2-11e8-803a-8c5dadb2a787.png)

Also reproducible at: 

- https://www.reddit.com/r/firefox/#siteTable
- https://www.reddit.com/r/freebsd/#siteTable

Please, is this reproducible on other platforms?

**Comment by grahamperrin** [comment]
[diagnostic.txt](https://github.com/OtterBrowser/otter-browser/files/1735031/diagnostic.txt)

**Comment by resbro** [comment]
Not reproducible for me on Win 10
Otter rc5 x64

**Comment by annulen** [comment]
What window manager are you using? Are you using some compositing manager, or enable compositing in WM? What graphics card are you using with what drivers?

**Comment by grahamperrin** [comment]
AMD 'Thames' Radeon HD 7570M in an HP EliteBook 8570p. 

XRender, compositing enabled. Today I temporarily disabled compositing and switched to OpenGL 2.0, the issue persisted. 

```text
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% pkg info plasma5-kwin
plasma5-kwin-5.12.1
Name           : plasma5-kwin
Version        : 5.12.1
Installed on   : Thu Feb 22 16:19:53 2018 GMT
Origin         : x11-wm/plasma5-kwin
Architecture   : FreeBSD:12:amd64
Prefix         : /usr/local
Categories     : kde-plasma kde x11-wm
Licenses       : GPLv2
Maintainer     : kde@FreeBSD.org
WWW            : https://projects.kde.org/projects/kde/workspace/kwin
Comment        : Plasma5 window manager
Shared Libs required:
        libKF5Package.so.5
        libKF5Codecs.so.5
        libkdecorations2private.so.5
        libKF5TextWidgets.so.5
        libKF5Attica.so.5
        libxcb-xfixes.so.0
        libfreetype.so.6
        libKF5NewStuff.so.5
        libKF5QuickAddons.so.5
        libKF5JobWidgets.so.5
        libKF5CoreAddons.so.5
        libepoxy.so.0
        libQt5Concurrent.so.5
        libX11-xcb.so.1
        libQt5Quick.so.5
        libSM.so.6
        libdrm.so.2
        libKF5Auth.so.5
        libxcb-cursor.so.0
        libkdecorations2.so.5
        libwayland-cursor.so.0
        libKF5KIOWidgets.so.5
        libxcb-composite.so.0
        libgbm.so.1
        libxcb-damage.so.0
        libQt5X11Extras.so.5
        libKF5WaylandClient.so.5
        libKF5IdleTime.so.5
        libKF5KCMUtils.so.5
        libKF5GlobalAccel.so.5
        libinput.so.10
        libQt5DBus.so.5
        libKF5WaylandServer.so.5
        libKF5NewStuffCore.so.5
        libKF5Completion.so.5
        libQt5Network.so.5
        libKF5Activities.so.5
        libxcb-glx.so.0
        libxcb-sync.so.1
        libKF5IconThemes.so.5
        libXi.so.6
        libKF5ConfigCore.so.5
        libQt5Gui.so.5
        libXext.so.6
        libQt5Sensors.so.5
        libxcb-shape.so.0
        libKF5WidgetsAddons.so.5
        libxcb-image.so.0
        libKF5ConfigGui.so.5
        libQt5Qml.so.5
        libxcb-shm.so.0
        libQt5Widgets.so.5
        libICE.so.6
        libxkbcommon.so.0
        libKF5XmlGui.so.5
        libKF5ConfigWidgets.so.5
        libxcb.so.1
        libxcb-render.so.0
        libKF5WindowSystem.so.5
        libKF5SonnetUi.so.5
        libX11.so.6
        libKF5Notifications.so.5
        libQt5QuickWidgets.so.5
        libKF5I18n.so.5
        libQt5Core.so.5
        libudev.so.0
        libQt5Xml.so.5
        libKScreenLocker.so.5
        libKF5Service.so.5
        libKF5KIOCore.so.5
        libfontconfig.so.1
        libxcb-icccm.so.4
        libQt5Script.so.5
        libxcb-randr.so.0
        libKF5Plasma.so.5
        libKF5Declarative.so.5
        libxcb-keysyms.so.1
        libKF5GlobalAccelPrivate.so.5
        libKF5Crash.so.5
Shared Libs provided:
        libkwineffects.so.11
        libkwin4_effect_builtins.so.1
        libdecorationplugin.so
        libkdecorationprivatedeclarative.so
        libplastikplugin.so
        libkwinglutils.so.11
        libkwin.so.5
        libkwinxrenderutils.so.11
        libkdeinit5_kwin_rules_dialog.so
        libkdeinit5_kwin_x11.so
Annotations    :
        FreeBSD_version: 1200037
        cpe            : cpe:2.3:a:kwin:kwin:5.12.1:::::freebsd12:x64
        repo_type      : binary
        repository     : poudriere
Flat size      : 22.0MiB
Description    :
Plasma5 KWin Window manager

WWW: https://projects.kde.org/projects/kde/workspace/kwin
```

[Xorg.0.log.old.txt](https://github.com/OtterBrowser/otter-browser/files/1778703/Xorg.0.log.old.txt)

Maybe relevant: 

- my FreeBSD-CURRENT is quite outdated
- the KDE Plamsa 5 is from Area 51, https://community.kde.org/FreeBSD/Setup/Area51

– although I haven't seen anything like what's in Otter, in any other app.

**Comment by grahamperrin** [comment]
Reddit now defaults to a different appearance, I can reproduce the issue at 

https://old.reddit.com/r/waterfox/#siteTable

Maybe not specific to Reddit. This, for example: 

![2018-09-22 02 25 15 waterfox](https://user-images.githubusercontent.com/192271/45911743-2b987a00-be0f-11e8-820e-8d249e123466.png)

KDE Plasma 5 is now release quality (no longer limited to Area 51) for FreeBSD. 

	$ date ; uname -v
	Sat 22 Sep 2018 02:28:54 BST
	FreeBSD 12.0-ALPHA5 #4 r338602: Wed Sep 12 06:34:09 BST 2018     root@momh167-gjp4-hpelitebook8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG 
	$ pkg info falkon 
	falkon-3.0.0_1
	Name           : falkon
	Version        : 3.0.0_1
	Installed on   : Mon Jul  2 20:40:58 2018 BST
	Origin         : www/falkon
	Architecture   : FreeBSD:12:amd64
	Prefix         : /usr/local
	Categories     : www
	Licenses       : GPLv3
	Maintainer     : kde@FreeBSD.org
	WWW            : https://userbase.kde.org/Falkon
	Comment        : Web browser based on WebKit engine and Qt Framework
	Options        :
	        GNOMEKEYRING   : off
	Shared Libs required:
	        libQt5QuickWidgets.so.5
	        libQt5X11Extras.so.5
	        libQt5Gui.so.5
	        libQt5Positioning.so.5
	        libQt5Core.so.5
	        libQt5PrintSupport.so.5
	        libQt5WebEngineCore.so.5
	        libQt5WebEngineWidgets.so.5
	        libKF5Wallet.so.5
	        libQt5Qml.so.5
	        libQt5Widgets.so.5
	        libQt5Sql.so.5
	        libQt5Quick.so.5
	        libQt5DBus.so.5
	        libQt5Network.so.5
	        libQt5WebChannel.so.5
	        libxcb.so.1
	Shared Libs provided:
	        libFalkonPrivate.so.3
	Annotations    :
	        FreeBSD_version: 1200069
	        repo_type      : binary
	        repository     : FreeBSD
	        …

**Comment by grahamperrin** [comment]
No longer reproducible at <https://old.reddit.com/r/waterfox/#siteTable> with Otter 1.0.01 

![image](https://user-images.githubusercontent.com/192271/54076557-f7bded80-42a4-11e9-94af-61927f00acd8.png)

https://www.freshports.org/www/otter-browser/
