### ISSUE TITLE
Seeing some videos obtruse the interface

### ISSUE THREAD

**Issue by srgloureiro** [OtterBrowser/otter-browser#150]
Seeing some youtube videos in the 'maximize to frame' format, like this
http://www.youtube.com/v/chsbGUEooKA

cause the video element to expand to the full otter window, making it impossible to access anything else.

The problem is even worse because even after restarting the browser it persists.

**Comment by Zero3K** [comment]
Is there any work that can be done on this issue?

**Comment by Emdek** [comment]
@Zero3K, several:
* trying *QtWebEngine* backend (Pepper flash plugin);
* disabling plugins;
* changing operating system (it is Windows specific). ;-)

This issue was already tackled upstream, but seems to return from time to time.
