### ISSUE TITLE
Windows issue - constant crash when closing the browser with the x symbol

### ISSUE THREAD

**Issue by Sa-Ja-Di** [OtterBrowser/otter-browser#1500]
As the title already says... when closing that way it crashes. Latest version available also affected.

Menu -Exit does not lead to a crash. Fault comes from the with Otter delivered ucrtbase.DLL file.

Windows 8, Otter 64 Bit in use.

Name of the failed application: otter-browser.exe, version: 0.9.9.5, timestamp: 0x5a9c1e19
Name of the failed module: ucrtbase.DLL, version: 10.0.10240.16384, timestamp: 0x559f3851
Exception code: 0xc0000409
Error offset: 0x0000000000065a4e
ID of the failed process: 0x76c
Start time of the failed application: 0x01d3b408ab2573e7
Path of the failed application: C: \ Users \ SapphireJD \ Desktop \ xxx \ Otter \ otter-browser.exe
Path of the failed module: C: \ Users \ SapphireJD \ Desktop \ xxx \ Otter \ ucrtbase.DLL
Report identifier: edc27952-1ffb-11e8-885f-a311a85a6832
Full name of the failed package:
Application ID that is relative to the failed package:

**Comment by aurhat** [comment]
Isn't it already fixed?
