### ISSUE TITLE
Using an external/installed/up-to-date KF5 Sonnet library?

### ISSUE THREAD

**Issue by RJVB** [OtterBrowser/otter-browser#1505]
I'm using a patch that builds Otter-Browser against the installed KF5 Sonnet library. Would you consider such a patch for upstreaming, and would it need to be controlled by a cmake option?

**Comment by Emdek** [comment]
@RJVB, nope, upstream Sonnet is missing one crucial feature, ability to specify custom search paths for dictionaries, which is must have, especially outside of Linux.
When I've checked last time they were still using deprecated Hunspell APIs, so it's not really newer, just some minor changes...

**Comment by RJVB** [comment]
> @RJVB, nope, upstream Sonnet is missing one crucial feature, ability to specify custom search paths for dictionaries, which is must have, especially outside of Linux.

Why is that crucial?


If your embedded version has improvements, why not propose them upstream?

**Comment by Emdek** [comment]
> Why is that crucial?

Because spell checker without dictionaries is pointless. :-P
System wide dictionaries are available only under Linux, BSD and maybe Solaris, I've expected that macOS will have them too, but they do not ship any (at least by default).

> If your embedded version has improvements, why not propose them upstream?

These are just hacks, Sonnet APIs need redesign, better yet, Qt should finally invest into proper addon module for spell checking.

**Comment by RJVB** [comment]
> Because spell checker without dictionaries is pointless. :-P

Well, doh ... but that doesn't explain why it's crucial to have custom dictionary install locations.

> System wide dictionaries are available only under Linux, BSD and maybe Solaris, I've expected that macOS will have them too, but they do not ship any (at least by default).

AFAIK, Sonnet is an interface to hunspell (and other optional spell checker engines). So where and when dictionaries are installed should depend on the underlying engine (hunspell, aspell, etc). On Mac I install hunspell via MacPorts, including the dictionaries that concern me. KF5 Sonnet uses that, and it just seems to work. FWIW, linking to "upstream" Sonnet means I no longer need to link to hunspell explicitly.

I would expect that Mac OS and MSWin have their own spell checkers with system APIs to use them from user code. If so, Sonnet should support those too.

> These are just hacks, Sonnet APIs need redesign, better yet, Qt should finally invest into proper addon module for spell checking.

Well, somebody needs to start, don't they, and even proposing a hacked improvement might set off such a process.

Qt have to make choices, if they start investing in every kind of addon modules they'll end up becoming a full-blown OS...

**Comment by Emdek** [comment]
@RJVB, I've analysed that for long time, this is the only feasible way to achieve all of our goals, which includes UI to manage dictionaries that allows to download missing ones in cross platform way.

> Well, somebody needs to start, don't they, and even proposing a hacked improvement might set off such a process.

Someone would have to find time to maintain it afterwards.

> Qt have to make choices, if they start investing in every kind of addon modules they'll end up becoming a full-blown OS...

Something like this?
https://en.wikipedia.org/wiki/Qt_Extended

**Comment by RJVB** [comment]
>@RJVB, I've analysed that for long time, this is the only feasible way to achieve all of our goals, which includes UI to manage dictionaries that allows to download missing ones in cross platform way.

If that's part of the requirements, then yes. I still don't really see why that would require custom installation locations, doesn't hunspell support user-installed dictionaries?

I just don't like the idea that each and every application installs its own copy of all kinds of things that could be shared.

>Someone would have to find time to maintain it afterwards.

The usual pretext not to implement change O:-)

>Something like this?
>https://en.wikipedia.org/wiki/Qt_Extended

Or worse. And discontinued, 9y ago already.

**Comment by lanodan** [comment]
> Someone would have to find time to maintain it afterwards.

You still have to manage your browser, I don’t think having to maintain (you should, if not you should seriously remove it) yet another stuff by copying it in your software repository is good practice.

And I’m pretty sure the Qt Community as quite an army of maintainers, specially compared to OtterBrowser.

> > Something like this?
> > https://en.wikipedia.org/wiki/Qt_Extended

> Or worse. And discontinued, 9y ago already.

There is SailfishOS / Mer Project if your what stuff that is still alive btw.

**Comment by RJVB** [comment]
>And I’m pretty sure the Qt Community as quite an army of maintainers, specially compared to OtterBrowser.

Yes they have, even the KDE community is sizeable in proportion. Sonnet being a core library ("KF5 Framework") used in lots of applications you can be certain that any changes will be vetted for maintainability as well as functional merit.

About that possibility to install additional dictionaries - where do I find that? Is it purely contained (and exposed from) within the 3rdparty/sonnet code, IOW is it to be expected I see no trace of it when using the upstream Sonnet library? Or is it still to be implemented?

>There is SailfishOS / Mer Project if your what stuff that is still alive btw.

I wasn't looking for a Qt OS, I merely mentioned that as something the Qt devs are probably not aiming for.

**Comment by RJVB** [comment]
>When I've checked last time they were still using deprecated Hunspell APIs, so it's not really newer, just some minor changes...

Interesting argument when you're using the same APIs ;)

Keep an eye out on upstream though. I've submitted a few patches for review, a migration to the modern Hunspell API and one that reenables the possibility to use whatever available backend supports a requested language if the default doesn't. 

I've already pushed a series of improvements to the NSSpellChecker backend that should now be a real alternative on Mac.

We could also think of proposing an interface to specify an app-specific additional dict repository, (app-specific implying runtime, not saved in the "global" sonnet config file).

R.

**Comment by Emdek** [comment]
>  I still don't really see why that would require custom installation locations, doesn't hunspell support user-installed dictionaries?

It needs to know where to look for them.
Plus thanks to Google and their proprietary dictionary format (AFAIR it was fork of hunspell) it gets even more complex when taking into account QtWebEngine backend.

> I just don't like the idea that each and every application installs its own copy of all kinds of things that could be shared

Me too, but there is no Qt friendly library around that provides all required features.

> The usual pretext not to implement change O:-)

Yes, good one, AFAIK Qt won't accept module without maintainer. :-P
And existing modules sooner or later become deprecated after losing maintainers...

> You still have to manage your browser, I don’t think having to maintain (you should, if not you should seriously remove it) yet another stuff by copying it in your software repository is good practice.

It's really small piece of code, and I'm checking upstream for useful changes from time to time.

> About that possibility to install additional dictionaries - where do I find that? Is it purely contained (and exposed from) within the 3rdparty/sonnet code, IOW is it to be expected I see no trace of it when using the upstream Sonnet library? Or is it still to be implemented?

The main blocker is a remote repository containing dictionaries ready for download, preferably existing one, AFAIK there was at least one used by OpenOffiie.org.

> Interesting argument when you're using the same APIs ;)

When I was deciding what should I use for spell checking "old" APIs weren't deprecated yet, I'm not sure if new APIs even existed back then.
Writing own code to support them would mean ditching Sonnet, writing custom `QSyntaxHighlighter` is not that hard after all.

> Keep an eye out on upstream though. I've submitted a few patches for review, a migration to the modern Hunspell API and one that reenables the possibility to use whatever available backend supports a requested language if the default doesn't.

That sounds interesting.

> We could also think of proposing an interface to specify an app-specific additional dict repository, (app-specific implying runtime, not saved in the "global" sonnet config file).

Personally I think that Sonnet needs new public API, simpler workflow.

**Comment by RJVB** [comment]
> The main blocker is a remote repository containing dictionaries ready for download, preferably existing one, AFAIK there was at least one used by OpenOffiie.org.

FWIW, the parts where the hunspell plugin looked for OOo dicts was stripped recently.

> Writing own code to support them would mean ditching Sonnet, writing custom `QSyntaxHighlighter` is not that hard after all.

There are exactly 2 calls in Sonnet that use deprecated hunspell functions. It's possible that there's a more modern API too, I haven't checked (I don't think I saw any trace of it in the headerfile where the deprecated functions are declared).

For syntax highlighting there is KSyntaxHighlighting, which is not entirely the same thing as syntax checking ;)
