### ISSUE TITLE
problems in gmail - weekly 219

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#1509]
Hi,
I just noticed problems in gmail after updating to weekly 219 (otter win64 weekly219 (webkit), on Win 7, just overwriting the previous install with the content of the current 7-zip file).
Either the webmail is not even loaded and displayed after logging in, or the list of e-mails is shown, but individual messages aren't shown after clicking them.
Sometimes, Gmail internal messages are shown, approx. (translated from my local setting)
"... System encountered an error (#007). - New attempt in …
Retry."
Or
"Some functions of Gmail cannot be loaded. If the problem persists, try reloading the page or using Basic HTML display."

In error console, some security related errors are listed, like
The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored.
Blocked a frame with origin "https://apis.google.com" from accessing a frame with origin "https://mail.google.com". Protocols, domains, and ports must match.

If I just replace the file otter-browser.exe with the previous version (RC 6), the problem disappears and Gmail works normally
some errors are written to the error console too, like the mentioned:
"The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored."
but the webmail works.

Using test-qtwebkit, Gmail doesn't work either, but the error messages are different, mostly:
Failed to load resource: HEADERS on invalid stream ...

I believe I already encountered something like this in some previous versions of Otter too, but I can't be sure, there were no other problems (like cache, cookies, content-blocking, user agent or similar); in any case it somehow got fixed with new updates.
If there are other things or settings to adjust or check, please let me know.

regards,
   vbr

**Comment by Emdek** [comment]
@vbr, yeah, it's HTTP2 issue in Qt which was supposed to be already fixed, but it's either not fixed or there still exist some cases that are not handled correctly.
It was working previously because I was applying extra patch to disable it, now I've pushed it to master and I'll keep it until testing will prove that it was finally fixed upstream.
