### ISSUE TITLE
userStyleSheetFilePath requires full path

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#1511]
Right now, user CSS file path requires full path in Linux, like /home/user/and-so-on/

This makes migration and sharing of profiles difficult. It would be better, if Otter would recognise both the full path and path with `~` (with quotes, if necessary). 

Same goes for Downloads path, and probably also other paths.

**Comment by Frenzie** [comment]
Does $HOME work?

**Comment by ersi-dnd** [comment]
Tried with the stylesheet. Does not work.

**Comment by Emdek** [comment]
@ersi-dnd, we can more or less support it using `Utils::normalizePath()` which is already used by address field for suggesting local file paths.
However there is on one limitation, right now it will work only with native path separators (Windows vs the rest of the world), but perhaps that one can be solved too.
