### ISSUE TITLE
WebGL?

### ISSUE THREAD

**Issue by probonopd** [OtterBrowser/otter-browser#1512]
What is the status of WebGL? Is it supposed to be working? THis is the 0.9.93 RC3 AppImage:

![webgl](https://user-images.githubusercontent.com/2480569/38204884-2590b79c-3694-11e8-82ab-3cc10ac38b99.png)

[TinkerCAD](https://tinkercad.com) does not run without it.

**Comment by Frenzie** [comment]
I can confirm that it doesn't work for me in the AppImage for weekly 221. That's practically equivalent to rc7, but rc3 is a touch older. ;-)

This is without the AppImage using legacy QtWebKit:
![screenshot_2018-04-02_19-03-45](https://user-images.githubusercontent.com/202757/38205889-99f3bf58-36a8-11e8-8600-8e2f39907560.png)

**Comment by Emdek** [comment]
@probonopd, it turns out that we were missing *plugins/xcbglintegrations/* (credit for determining cause of this issue goes to @annulen), it seems that it wasn't deployed or got somehow lost afterwards.
Fix will be available as part of next weekly.
