### ISSUE TITLE
freebsd - core dump when closing browser within [X] button

### ISSUE THREAD

**Issue by mpastor** [OtterBrowser/otter-browser#1514]
I have the same problem as #1500, but on FreeBSD. Closing via "File->Exit" or Ctrl+q is OK.

The previous version of browser (I don't remember which one):

```Mar 21 14:41:06 atlantis kernel: pid 38410 (otter-browser), uid 1001: exited on signal 11 (core dumped)```

After disabling coredump and upgrading browser:

```Apr 11 22:29:32 atlantis kernel: pid 38466 (otter-browser), uid 1001: exited on signal 11```

FreeBSD 11.1
otter 0.9.98-dev
WebKit Backend 602.1
qt 5.7.1

**Comment by aurhat** [comment]
Isn't it already fixed?

**Comment by mpastor** [comment]
Hi,

upgraded system to 11.2-RELEASE-p2 and it seems to be ok now, thanks.

FreeBSD 11.2-RELEASE-p2
Otter 1.0.81-dev
WebKit Backend 602.1
Qt version 5.10.1
