### ISSUE TITLE
Appimage crashes under Arch

### ISSUE THREAD

**Issue by Ilya87** [OtterBrowser/otter-browser#1521]
QT_DEBUG_PLUGINS=1 /home/ilya/otter-browser-0.9.99-weekly230-x86_64.AppImageQFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_51m6ce/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() looking at "/tmp/.mount_51m6ce/plugins/platforms/libqxcb.so"
Found metadata in lib /tmp/.mount_51m6ce/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 330240
}

Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/tmp/.mount_51m6ce/platforms" ...
Cannot load library /tmp/.mount_51m6ce/plugins/platforms/libqxcb.so: (/usr/lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var)
QLibraryPrivate::loadPlugin failed on "/tmp/.mount_51m6ce/plugins/platforms/libqxcb.so" : "Cannot load library /tmp/.mount_51m6ce/plugins/platforms/libqxcb.so: (/usr/lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var)"
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
@emdek
Solution:

https://github.com/probonopd/linuxdeployqt/issues/261#issuecomment-378583536
Just confirming that the proposed fix of excluding libharfbuzz.so.0 and libfreetype.so.6 from the AppImage works for me as well to get my own AppImage of Peek run again on Arch.

**Comment by Emdek** [comment]
@Ilya87, we had `libfreetype.so.6` only, it seems that it still works here after removing it (different distribution than our AppImage builder).
It will be available as part of next binaries, hopefully tomorrow.
