### ISSUE TITLE
Feed reader connections aren't aware of sessions/cookies

### ISSUE THREAD

**Issue by c-cesar** [OtterBrowser/otter-browser#1523]
Tumblr have non standard authentication and uses client session instead of URL credentials to private feeds.
I can access the content of the feed by URL, but get a error if I try to subscribe.

**Comment by Emdek** [comment]
@c-cesar, odd, it should make use of main store, unless you are using QtWebEngine backend which has limited integration...
Are there any errors in the Console (in View -> Toolbars or <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>O</kbd> - letter, not number)?

**Comment by c-cesar** [comment]
Using QtWebKit 602.1, and the console show the error: "Failed to parse feed".
A very NSFW example: http://daddy-calls-me-puddles.tumblr.com/rss

**Comment by Emdek** [comment]
@c-cesar, if that is RSS 2.0 feed and you are using RC then it is fixed, there was parsing error related to weird feature of RSS 2.0 comparing to sanity of Atom...
Please take a look using upcoming weekly (hopefully packages will be available today).

**Comment by c-cesar** [comment]
Using lastest git compiled some hours ago.
As public feeds from Tumblr works fine, I don't think is a format problem.

**Comment by Emdek** [comment]
@c-cesar, I see, are there are any extra details in Error Console? Yo may need to expand entry.

**Comment by c-cesar** [comment]
Sadly not. the "Failed to parse" is already the detailed info.

**Comment by Emdek** [comment]
@c-cesar, ok, then I'll need to simply try it out then, with some extra debug output.

**Comment by c-cesar** [comment]
Confirmed as closed.
Thanks,
