### ISSUE TITLE
Phantom toolbars

### ISSUE THREAD

**Issue by uahim** [OtterBrowser/otter-browser#1524]
I just created a fresh profile and moved all files except for toolBars.json because of https://github.com/OtterBrowser/otter-browser/issues/1316 and now I'm seeing a couple of phantom toolbars. they are not accessible via the context menu, nor are they listed in the new, bare toolBars.json.
losing my precious toolbars was hard enough, so is there a counter somewhere (I don't see one in otter.conf) that can be set to zero to get rid of this without creating a profile from scratch?
thanks

![phantom](https://user-images.githubusercontent.com/6866794/41161489-5a6134c8-6b33-11e8-9969-2f8561c30c9e.png)

**Comment by beastie1** [comment]
What happens if you rename toolBars.json?

**Comment by uahim** [comment]
@beastie1 actually, nothing. but everytime I add the old toolBars.json and restart, it adds exactly two of those phantom toolbars even after I rename the json again. hilarious:
![phantom2](https://user-images.githubusercontent.com/6866794/41177276-be32bc3a-6b63-11e8-8c0a-8ea98e0d7e8f.png)

**Comment by Emdek** [comment]
@uahim, I've seen something similar in the past, AFAIR it was single extra toolbar, that could be removed by editing configuration file, but AFAIR it was also accessible through menus.
Could you please send me your current `toolBars.json`?

**Comment by uahim** [comment]
@Emdek json as txt (really, Github? no json "support" in 2018?)
[toolBars.json.txt](https://github.com/OtterBrowser/otter-browser/files/2094023/toolBars.json.txt)

**Comment by Emdek** [comment]
@uahim, thanks, at first glance I don't see anything unusual, do you use multiple main windows or some other less usual stuff?
BTW, since MS is going to take over GitHub we can expect many weird things (yes, I have contingency plan already). ;-)

**Comment by uahim** [comment]
@Emdek nope, nothing like that. 

ended up in creating a new profile after all.

is there any way I can place the standard staus bar on top instead? manually adding _"location": "top",_ doesn't work and/or messes up the gui completely (I had the standard staus bar twice at on point, on top and at the bottom ;-) )

apologies if the following have been reported before, it's all just gui stuff:
- "icon only" doesn't work for the menu item on a toolbar in a fresh profile. it always shows the "menu" label.
- on very long uris, the zoom icon on the standard starus bar shrinks horizontally by a few pixels.
- on the standard tab bar, there is no option (anymore?) to get rid of the favicon and "close" icon.

**Comment by beastie1** [comment]
@uahim
> is there any way I can place the standard status bar on top instead? manually adding "location": "top", doesn't work and/or messes up the gui completely (at one point I had the standard staus bar twice, on top and at the bottom ;-) )

Of course you can. As long as by "top" you don't mean over the menu bar itself. The GUI toolbar editor will happily do what you want. Simply add a new toolba, add a `Status Message Field` entry to it and move the toolbar wherever you wish using the small grip widget (where the mouse pointer becomes a cross).

And that's what it will generate:
```
	{
		"actions": [
			"StatusMessageWidget"
		],
		"buttonStyle": "iconOnly",
		"fullScreenVisibility": "hidden",
		"identifier": "CustomBar",
		"location": "top",
		"normalVisibility": "visible",
		"row": 2,
		"title": "MyCustomToolbar"
	}
```
