### ISSUE TITLE
YouTube account tab

### ISSUE THREAD

**Issue by johnny-mac** [OtterBrowser/otter-browser#1525]
Hello, I found this browser just the other day and I like it! But there's one thing I'm having trouble with, and that's the youtube account tab in the top right corner of youtube, I don't know why it would do this, perhaps youtube thinks this is an older browser? This is the one thing I need to get working & then I can make this browser my primary browser.

I would really like to get YouTube into the dark theme in the otter-browser, if anyone knows of another way of activating the dark theme that'd be great.

It should look like this:
https://imgur.com/a/fNuE5Tu

But for some reason, it looks like this:
https://imgur.com/a/DfXzOEk

**Comment by lanodan** [comment]
Have you tried putting a false user-agent (like firefox) ?
(I don’t have a google account, can’t test…)

**Comment by Emdek** [comment]
@johnny-mac, I'm assuming that you are using QtWebKit backend, in case of Google services it's a better idea to use QtWebEngine backend (right now binaries with that backend are available only for Windows).
