### ISSUE TITLE
Can DragonFly be used with Otter?

### ISSUE THREAD

**Issue by TCH68k** [OtterBrowser/otter-browser#1533]
Is it possible to use Opera 12's DragonFly debugger with Otter?

**Comment by Emdek** [comment]
@TCH68k, no, probably it would be easier to modify Web Inspector than port DragonFly to new architecture.

**Comment by osilkin98** [comment]
What exactly is the issue between Otter's Architecture and Dragonfly's that makes it difficult to port?
