### ISSUE TITLE
No web backends available!

### ISSUE THREAD

**Issue by dcalixto** [OtterBrowser/otter-browser#1547]
After try to install in the end of compilation as you can see in the screenshot below show this
![install](https://user-images.githubusercontent.com/1009077/46970490-9e53e880-d08f-11e8-9652-f9861f51449e.png)

> No web backends available!

 What this mean?

**Comment by Emdek** [comment]
@dcalixto, you have the answer just above that message. ;-)
CMake can't find bot QtWebKit and QtWebEngine, perhaps you are missing some development packages or something like that, it's hard to tell since you haven't provided details about your platform.

**Comment by dcalixto** [comment]
@Emdek thank you but says optional. anyway, o gonna install the left packages.

**Comment by Emdek** [comment]
@dcalixto, yeah, optional, but more like a choice, one or another (or both).
Most of that output is standard CMake stuff, I don;t think that I can let it know that at least one must be present in better way.

**Comment by dcalixto** [comment]
@Emdek ok, well the browser is installed, and is very good. thank you!
but on youtube is not showing the video images, just the sound. the screenshot below to confirm

is another thing that i'm missing?

**Comment by Emdek** [comment]
@dcalixto, most likely you are missing some GStreamer (1.x) codecs.

**Comment by FredMontteiro** [comment]
> @Emdek ok, well the browser is installed, and is very good. thank you!
> but on youtube is not showing the video images, just the sound. the screenshot below to confirm
> ![video](https://user-images.githubusercontent.com/1009077/47039018-44b7f080-d159-11e8-9bb6-a55482d654c0.png)
> 
> is another thing that i'm missing?
> 
> by the way i'm on lubuntu 18.04

Hi friend, I know it's been a while since you posted here, but if you can help me I would be very grateful.

I'm trying to install the Otter Browser on Lubuntu 18.04 LTS.

I am facing a problem very similar to yours.

I will attach a screenshot.
![2020-05-11-222825_1360x768_scrot](https://user-images.githubusercontent.com/36718807/81628755-e22be280-93d7-11ea-86e3-7b37312b1350.png)

How did you solve the problem?
