### ISSUE TITLE
insert note via context menu

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#1549]
Hi,
I'd like to ask, whether the context menu for editable text elements on websites (or even in the browser itself) could be enhanced by adding a menu (group) "insert from note", with the individual menu items populated with the currently saved notes.
I believe, something like that might have been available some time ago, but currently there is only an option to "copy to note" (like for other text content), and not the other way round.

Or is something like this maybe already possible via menu customisation? Is there some documentation of the available actions?

Thanks and regards,
 vbr

**Comment by Emdek** [comment]
@vbr, uhm, are you using custom `webWidget.json` file?
This menu is available for at least form elements.

**Comment by vbr** [comment]
Ah, you are right - thanks for the hint and sorry for the noise - in an the Otter instance without webWidget.json the notes via context menu are working correctly.
What is the expected action name for this function?
Currently, I have the respective (faulty) portion of the webWidget.json code in the form:
            "type": "include",
            "includeIn": "edit",
            "actions":
            [
                "PasteNote",
                "separator",
                ...
Is another name appropriate, or perhaps another format of this setting?
Thanks and regards,
   vbr

**Comment by Emdek** [comment]
@vbr, try this:
```
{
	"type": "menu",
	"identifier": "NotesMenu",
	"excludeFrom": "source"
},
```
`"excludeFrom": "source"` is optional, used to hide it in the Source Viewer.

**Comment by vbr** [comment]
Thank You very much for the quick answer; this works as expected.
vbr
