### ISSUE TITLE
Otter 1.0.01 does not display Twitch.tv correctly

### ISSUE THREAD

**Issue by Otteruser** [OtterBrowser/otter-browser#1562]
Step One: Install Otter 1.0.01 
Step Two: Navigate to https://www.twitch.tv
Step Three: Notice that the site does not display as it does in Chrome, Firefox, and Opera.

**Comment by beastie1** [comment]
I suspect it's a browser engine issue.
Is this on Windows? Alas **1.0.01** has no package for the **WebEngine** version yet (the default you're using is **WebKit**). You may want to try an [older version](https://sourceforge.net/projects/otter-browser/files/otter-browser-rc12/experimental/) instead.
If you're using *nix, then try building Otter yourself and switch between engines (**Backends/Web** in **about:config**).
