### ISSUE TITLE
Mac Otter has bad text display

### ISSUE THREAD

**Issue by paradise-404** [OtterBrowser/otter-browser#1563]
Hello,

I have MacOS Sierra and Otter often doesn't display text or it's jumbled as a previous poster noted.

I changed encoding to default to utf-8 and it helped some but not all.

Sometimes, the text on a website will appear but when I scroll down and come back up, it's disappeared.

Any ideas? I can try to fix the issue in the source code on my end if anyone has an idea if it's some lines in some classes that is making it buggy.

![screenshot 2019-01-13 14 48 54](https://user-images.githubusercontent.com/20283663/51093960-92eb8880-1776-11e9-9fc0-cf53e4c14bc0.png)

![screenshot 2019-01-13 14 49 14](https://user-images.githubusercontent.com/20283663/51093962-967f0f80-1776-11e9-91b5-be4d04494a28.png)

Thanks!

**Comment by WreckWren** [comment]
This is STILL the case in mid-2020. Guess this browser just isn't updated at all.

**Comment by Emdek** [comment]
@WreckWren, macOS build surely isn't up to date right now, since we have no access to a build machine right now (whatever you have tried is super outdated right now)…
Also, this kind of issues are backend bugs, not the browser itself.
