### ISSUE TITLE
Cmake Error

### ISSUE THREAD

**Issue by MahdiyarTH** [OtterBrowser/otter-browser#1565]
I have cloned and installed your browser, but after running cmake ../ command, i got this error:
`-- Could NOT find HUNSPELL (missing: HUNSPELL_LIBRARIES HUNSPELL_INCLUDE_DIR) 
-- The following OPTIONAL packages have been found:

 * Qt5MacExtras (required version >= 5.6.0)

-- The following REQUIRED packages have been found:

 * Qt5Core
 * Qt5Gui
 * Qt5Multimedia
 * Qt5Network
 * Qt5PrintSupport
 * Qt5Qml
 * Qt5Svg
 * Qt5Widgets
 * Qt5XmlPatterns
 * Qt5 (required version >= 5.6.0)

-- The following OPTIONAL packages have not been found:

 * Qt5WebEngineWidgets (required version >= 5.12.0), QtWebEngine based backend (widgets), <https://www.qt.io/>
 * Qt5WebKitWidgets (required version >= 5.212.0), QtWebKit based backend (widgets), <https://www.qt.io/>
 * Hunspell (required version >= 1.5.0), Generic spell checking support, <https://hunspell.github.io/>

CMake Error at CMakeLists.txt:597 (message):
  No web backends available!

-- Configuring incomplete, errors occurred!
See also "/Users/mahdiyartaheri/Qt5.7.0/Projects/otter-browser/build/CMakeFiles/CMakeOutput.log".`

I'm using MacOS Mojave and Qt 5.7

**Comment by Emdek** [comment]
@MahdiyarTH, you need to either install QtWebEngine module or get QtWebKit here (it needs to be unpacked to matching directories of your Qt installation):
http://download.qt.io/snapshots/ci/qtwebkit/5.212/latest/qtwebkit/
Also note that 5.7 is very old, you should consider updating to 5.12.1.
