### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by tezeug** [OtterBrowser/otter-browser#1574]
![Screenshot_2019-03-27_19-50-58](https://user-images.githubusercontent.com/48736723/55103951-65e61b00-50c1-11e9-99cc-4e07fcaf6a39.png)

**Comment by Frenzie** [comment]
If you're on a Debubuntu-type system, do you have `build-essential` packages installed? (Or perhaps more to the point, g++.)

**Comment by tezeug** [comment]
I do not think.

**Comment by tezeug** [comment]
I’ll try to install it.
