### ISSUE TITLE
Build in Windows 10 

### ISSUE THREAD

**Issue by IProudNoob** [OtterBrowser/otter-browser#1579]
I have a problem with the build:

```
E:\otter-browser\build>cmake.exe ..
-- Building for: Visual Studio 16 2019
-- The C compiler identification is MSVC 19.20.27508.1
-- The CXX compiler identification is MSVC 19.20.27508.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:83 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" (requested
  version 5.6.0) with any of the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "E:/otter-browser/build/CMakeFiles/CMakeOutput.log".
```

**Comment by Frenzie** [comment]
I don't think that looks like you're using Qt Creator?

**Comment by IProudNoob** [comment]
I'm sorry, I did not understand.
I not  using Qt Creator.

**Comment by Frenzie** [comment]
What I mean is that you can either figure out how to set up Qt stuff in Windows the hard way (for bragging rights?) or you can just use Qt Creator.

**Comment by IProudNoob** [comment]
Ok)))
But hove use in Qt Creator? In this project not have .pro files. 
Help me pleas.

**Comment by Frenzie** [comment]
Like @Emdek said [here](https://github.com/OtterBrowser/otter-browser/issues/1577#issuecomment-485540181), you have to open CMakeLists.txt instead.

**Comment by IProudNoob** [comment]
I open CMakeLists.txt file
But hove this

Running "C:\Program Files\CMake\bin\cmake.exe -E server "--pipe=\\.\pipe\{ab0e4f2d-41e8-4ba1-8602-9c9eba95e9e9}" --experimental" in E:\build-otter-browser-Desktop_Qt_5_7_1_MSVC2015_64bit-Default.
Starting to parse CMake project.
The C compiler identification is MSVC 19.0.24215.1
The CXX compiler identification is MSVC 19.0.24215.1
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/BIN/x86_amd64/cl.exe
CMake Error: Generator: execution of make failed. Make command was: jom /nologo cmTC_5b33a\fast 
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/BIN/x86_amd64/cl.exe -- broken
CMake Error at C:/Program Files/CMake/share/cmake-3.14/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/BIN/x86_amd64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: E:/build-otter-browser-Desktop_Qt_5_7_1_MSVC2015_64bit-Default/CMakeFiles/CMakeTmp
    
    Run Build Command(s):jom /nologo cmTC_5b33a\fast 
    The system cannot find the file specified
    Generator: execution of make failed. Make command was: jom /nologo cmTC_5b33a\fast 
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:11 (project)


Configuring incomplete, errors occurred!
See also "E:/build-otter-browser-Desktop_Qt_5_7_1_MSVC2015_64bit-Default/CMakeFiles/CMakeOutput.log".
See also "E:/build-otter-browser-Desktop_Qt_5_7_1_MSVC2015_64bit-Default/CMakeFiles/CMakeError.log".
CMake Project parsing failed

**Comment by IProudNoob** [comment]
I am begin study Qt. 
Maybe I'm doing something wrong?

**Comment by Emdek** [comment]
@IProudNoob, I'm not sure if Qt already supports VS 2019, especially for such old version like 5.7.
You can retry with 5.12 or 5.13 (these might have compatible builds), or go for mingw.
