### ISSUE TITLE
Does not build on Antix

### ISSUE THREAD

**Issue by AntixUser** [OtterBrowser/otter-browser#1584]
Hi folks,

I used the recent version to build it on Antix Linux (Debian Stretch based). I installed every needed dependency but get this:

root@host:/usr/src/otter-browser/otter-browser/build# cmake ../
--
-- The following OPTIONAL packages have been found:

 * Hunspell (required version >= 1.5.0) , Generic spell checking support , <https://hunspell.github.io/>
 * Qt5DBus (required version >= 5.6.0)

-- The following REQUIRED packages have been found:

 * Qt5Core
 * Qt5Gui
 * Qt5Multimedia
 * Qt5Network
 * Qt5PrintSupport
 * Qt5Qml
 * Qt5Svg
 * Qt5Widgets
 * Qt5 (required version >= 5.6.0)

-- The following OPTIONAL packages have not been found:

 * Qt5WebEngineWidgets (required version >= 5.12.0) , QtWebEngine based backend (widgets) , <https://www.qt.io/>
 * Qt5WebKitWidgets (required version >= 5.212.0) , QtWebKit based backend (widgets) , <https://www.qt.io/>

CMake Error at CMakeLists.txt:601 (message):
  No web backends available!

-- Configuring incomplete, errors occurred!
See also "/usr/src/otter-browser/otter-browser/build/CMakeFiles/CMakeOutput.log".

**Comment by Emdek** [comment]
@AntixUser, Debian Stretch? That sounds old.
I'm guessing that your Qt is older that 5.12 (which eliminates QtWebEngine backend) and Debian stable haven't updated to QtWebKit 5.212 yet.
You need to use official [Qt SDK](https://www.qt.io/download-qt-installer) or build from source (building QtWebKit or QtWebEngine takes a lot of time, especially the latter).
If you want to use QtWebKit (recommended) then you can find the latest build [here](http://download.qt.io/snapshots/ci/qtwebkit/5.212/1559865835/qtwebkit/) (you need to unpack contents on top of Qt SDK installation, so `bin/` contents go to `bin/` etc.), right now you should go for Qt 5.12.x.
Another alternative is to wait for new AppImage (blocked by OpenSSL ABI issues).
Also please note that you should use stable branch for now, master has some MDI related issues.
