### ISSUE TITLE
Massive memory leak

### ISSUE THREAD

**Issue by RickOrchard** [OtterBrowser/otter-browser#1585]
I ran the [Dromaeo](http://dromaeo.com/?all) browser-benchmark today, was just curious. Didn't expect it to take 11GB of my memory to comlete the test though.
After the test finished it kept all of it.
After closing the culprit-tab the Otter-browser still occupied 7.7GB of memory (only left one tab open with maps.google.com freshly loaded).

Comparing with other browsers i was running the test with its not doing very good, they use way less memory during the test (even Falkon, which uses the QtWebEngine as well) uses only 1.5GB max during the test, and they clean up when they are done.

------------------
System specs:
 Manjaro Linux
 Packages: 1373 (pacman), 3 (flatpak) 
 Shell: bash 5.0.7 
 Resolution: 1680x1050, 1920x1080 
 DE: KDE 
 WM: KWin 
 WM Theme: SteampunK 
 Theme: Breeze Dark [KDE], Adwaita [GTK2], Bre 
 Icons: SteamPunk-kde44-scalable-blackysgate.d 
 CPU: Intel Xeon E31270 (8) @ 3.800GHz 
 GPU: NVIDIA Quadro 2000 
 Memory: 551MiB / 15997MiB 

 Qt version 5.12.4
 Otter v1.0.01

**Comment by Emdek** [comment]
@RickOrchard, which web backend was that?
You can check that using Help -> About Otter.

**Comment by RickOrchard** [comment]
I see it's using WebKit not QtWebEngine btw. 

It does show the same quircks when using other JS intensive sites like
Google Maps, compared to for example Opera (yes i like using
underdog-browsers). You don't notice it while using it though, Google
Maps feels very snappy: 

Also it's not loading the JetStream benchmark
(https://browserbench.org/JetStream/), maybe also due to the WebKit
engine? 

Cheers for keeping FOSS alive! 
Kind regards, 

Richard 

---

-------------------------

Michał schreef op 2019-07-08 14:58:

> @RickOrchard [1], which web backend was that?
> You can check that using Help -> About Otter. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/RickOrchard
[2]
https://github.com/OtterBrowser/otter-browser/issues/1585?email_source=notifications&amp;email_token=AE77LACXEDE2YSXEJWJFLZDP6M2XBA5CNFSM4H6T5R3KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZM77HQ#issuecomment-509214622
[3]

**Comment by Emdek** [comment]
@RickOrchard, could you please try to reproduce it using this minimal test case?
https://github.com/OtterBrowser/test-qtwebkit
BTW, right now there is ongoing work on updating QtWebKit to new upstream branch so we can expect fixes for newer benchmarks and stuff.

**Comment by RickOrchard** [comment]
Same issue (see screenshots).
Obviously it's a WebKit issue then...


![qtwebkit-memleak1-running](https://user-images.githubusercontent.com/20968832/60881586-4cb74380-a246-11e9-98b6-3b9e69a74513.png)

![qtwebkit-memleak2-finished](https://user-images.githubusercontent.com/20968832/60881585-4cb74380-a246-11e9-909c-ef48b85090b1.png)

**Comment by RickOrchard** [comment]
Hi @Emdek,

I took the source from your v1.0.01 release, installed Qt 5.12.4 and compiled it with the Qt5WebEngine (Qt5WebKit is no longer available in modern Qt versions).

The problem no longer occured. It maxed out at around 2GB of memory. So this mystery is solved i guess.

Bummer: the Dromaeo score was way lower using the WebEngine (3551.65) compared to WebKit (4441.43).

**Comment by Emdek** [comment]
@RickOrchard, it's the legacy branch that is no longer maintained, you can find new releases here:
https://github.com/qtwebkit/qtwebkit/releases/tag/qtwebkit-5.212.0-alpha3
This issue seems to be affecting the GTK port from the same branch too.
Currently there is work in progress on new branch for QtWebKit, so hopefully it won't be reproducible there anymore (there is no release date set yet).
