### ISSUE TITLE
Webkit backend doesn't play all webcams

### ISSUE THREAD

**Issue by bcoolumbo1** [OtterBrowser/otter-browser#1590]
Please try playing the video at https://www.skylinewebcams.com/en/webcam/espana/cataluna/barcelona/playa-barceloneta.html or any other webcam at this website.
Debugger says it can't find variable $
Webengine works well, but with webengine many other things don't.
May I suggest a ui button to switch the backend, or a setting per url in the config files.
Setting configs from within the sidebar doesn't work because there is no save button.
Arch Linux otter devel.

**Comment by Emdek** [comment]
Reported upstream.
Currently there is ongoing work on updating QtWebKit to newest WebKit, so hopefully we will see more fixes later this year:
https://github.com/qtwebkit/qtwebkit/commits/qtwebkit-dev
