### ISSUE TITLE
Otter automatically loads videos even though autoplay is disabled

### ISSUE THREAD

**Issue by bcoolumbo1** [OtterBrowser/otter-browser#1591]
I can see it in my conky transfer gauge: 
Megabytes over megabites are downloaded even though I do not plan to watch the video.

**Comment by Emdek** [comment]
@bcoolumbo1, which backend? Do they actually play?
This might be caused by preloading.

**Comment by bcoolumbo1** [comment]
Only webkit backend.
The videos play.
Here an example:
https://www.20min.ch/schweiz/bern/story/So-ruhig-und-romantisch-waren-hierzulande-die-50er-11571114

**Comment by Emdek** [comment]
@bcoolumbo1, it seems that it could be easily fixable, so hopefully fix will land in next release of QtWebKit 5.212.
