### ISSUE TITLE
Hosts file not read

### ISSUE THREAD

**Issue by Kirikmelet** [OtterBrowser/otter-browser#1595]
It seems like the QTwebengine could not read my hosts file properly, since when I tried to open censored websites (Indonesian Censor) like reddit.com, it would not open, but when I opened vimeo.com, it worked.

**Comment by aurhat** [comment]
Could you explain, how to reproduce it step by step? How is your local host file related to "Indonesian Censor"?

**Comment by Kirikmelet** [comment]
No, but to overcome Indonesian censorship, I had to edit my hosts file. Unfortunately, the browser did not read it. And furthermore, I already switched to Linux so I don't know if I could recreate it again.

**Comment by Kirikmelet** [comment]
Should I close this?

**Comment by Kirikmelet** [comment]
Nevermind, it worked on Linux.
![Screenshot from 2019-10-24 20-19-13](https://user-images.githubusercontent.com/52523838/67489349-a0398a00-f69b-11e9-93a2-4f507465be94.png)
