### ISSUE TITLE
otter-browser open about:blank#blocked page instead "home screen" 

### ISSUE THREAD

**Issue by AngryPenguinPL** [OtterBrowser/otter-browser#1596]
We recently discovered that Otter-browser after opening instead of showing the so-called "home screen", opens an empty tab - about:blank#blocked. 

If we take a good look, the "home screen" appears after the start literally for half a second, and then about:blank#blocked appears. The same behavior appears when you open a new tab.
Just like in gif below:

![Peek 2019-10-10 16-06](https://user-images.githubusercontent.com/3121142/67010637-532f4400-f0ee-11e9-97d8-9b762c94ddc3.gif)

(here is a backup if above gif dont load https://imgur.com/eUVxbZu)

Is there any logical explanation or is it a bug, maybe a packing issue? Can we fix it somehow?
Here is ours spec: https://github.com/OpenMandrivaAssociation/otter-browser

**Comment by aurhat** [comment]
Could you check in the current master branch? https://github.com/OtterBrowser/otter-browser/commit/36478f2 - this commit fixes the problem (likely).

**Comment by AngryPenguinPL** [comment]
Yes, in version build from master branch this issue is fixed. So I thnk I can create patch from this commit to current stable.

Thanks.

**Comment by Emdek** [comment]
@AngryPenguinPL, I've added it to the list of commits to backport, I'm planning to push 1.0.02 soonish.

**Comment by Emdek** [comment]
It was broken by QtWebEngine update, I don;t remember which one was it exactly, perhaps 5.12 or 5.13.
