### ISSUE TITLE
Browser icon

### ISSUE THREAD

**Issue by fastrizwaan** [OtterBrowser/otter-browser#16]
Do we have application icon for otter browser? I'd like to make fedora rpm, but needs icon.

**Comment by DoctorJellyface** [comment]
Celebrating the first anniversary! Woo!

On a more serious note, I'm looking into this now.

**Comment by DoctorJellyface** [comment]
OK, what about this? The otter does look more like a lion than an otter, didn't dix that yet, but got rid of the bloat, except the eyes, which I haven't figured out yet either.

**Comment by Emdek** [comment]
@DoctorJellyface, there is also new slightly updated version of icon, still work in progress:
http://thedndsanctuary.eu/index.php?topic=681.0

**Comment by DoctorJellyface** [comment]
Didn't see any icon there. Could you give me a direct link?

Also, I made #963, which is a tiny tweak to the icon, but making it much nicer.

**Comment by asimonv** [comment]
@Frenzie i really loved this icon, can i use it? 
https://github.com/OtterBrowser/otter-browser/issues/16#issuecomment-31575726

**Comment by Frenzie** [comment]
Probably. What do you have in mind?

**Comment by asimonv** [comment]
Just a personal project for an iOS app. I need to modify it too, like adding a background color, etc.

**Comment by Frenzie** [comment]
Is that commercial or non-commercial? I was thinking something like CC
BY-SA 4.0 or CC BY-NC-SA 4.0 would probably work for me.
