### ISSUE TITLE
Segmentation fault after clearing 'All' browsing history and entering string in address bar

### ISSUE THREAD

**Issue by fnkkio** [OtterBrowser/otter-browser#1600]
Steps to reproduce:
1. Visit any website
2. Clear 'All' browsing history
3. Type any string in address bar

Results:
Segmentation Fault

Attached stacktrace.
[stacktrace.txt](https://github.com/OtterBrowser/otter-browser/files/3829051/stacktrace.txt)

**Comment by Emdek** [comment]
Fixed in bfbf960fed20235ba4dc189534f2a4047c1d36e3.
