### ISSUE TITLE
Javascript problems with WebKit backend

### ISSUE THREAD

**Issue by SuperRoboWizard** [OtterBrowser/otter-browser#1633]
Examples:

https://mastodon.social/public throws two "TypeError: undefined is not a function" in the console. Both of these trace back to "console.error(something);" in the source. While I'm not surprised to see an error here, the error given is nonsense.

https://duckduckgo.com, searching "test", then clicking on the images tab throws two "Unrecognized Content-Security-Policy directive 'frame-ancestors'." errors, and a "Failed to load resource" due to a 403 forbidden.

https://google.com, searching "test", then clicking on the images tab loads the basic HTML version of the page without JS.

I cannot replicate any of these issues using the Blink backend, nor Falkon. The only messages in the terminal are many instances of "No language dictionaries for the language: "en_US"".

I'm running Otter 1.0.01 and WebKit backend 602.1 natively installed on Arch Linux. This issue also occurs using Otter 10.0.81 weekly 300 (same WebKit version) running in portable mode from the build folder.

**Comment by Emdek** [comment]
@SuperRoboWizard, the only thing that we can do about that is to wait for the first release from current WIP branch of QtWebKit (based on current upstream WebKit).
It might take few more months, so we need to be patient.
