### ISSUE TITLE
Freeze on https://www.reflex.cz/ page

### ISSUE THREAD

**Issue by tmysik** [OtterBrowser/otter-browser#1644]
Try to open https://www.reflex.cz/kategorie/7220/prostor-x and then any "sub" page with any interview (e.g. [this one](https://www.reflex.cz/clanek/prostor-x/100995/ivan-bartos-babis-nas-pomlouva-a-jede-linku-nenavisti-vlada-zneuziva-nouzovy-stav.html)) - the browser will freeze completely.

Manjaro Linux (all up-to-date)
Otter 1.0.01 
WebKit 602.1.
OpenSSL 1.1.1g 21 Apr 2020.

Thanks.

**Comment by micwoj92** [comment]
Its upsteam qtwebkit issue, with qtwebengine it should work fine

**Comment by tmysik** [comment]
@micwoj92 

I followed instructions to [change it](https://wiki.archlinux.org/index.php/Otter_Browser) but no change. the tab freezes and after a while, the whole browser crashed.

**Comment by micwoj92** [comment]
Hmm, have you tried with otter-browser-git? for me changing backend solves almost all loading issues

**Comment by tmysik** [comment]
@micwoj92 OK, I can confirm that `otter-browser-git` works. Hopefully, the new stable version will be available soon :)

Thanks!

**Comment by tmysik** [comment]
Unfortunately, I have to say that Otter browser is **very** slow on these pages (see the subject of the issue). Using e.g. Falkon is much much better (faster).
