### ISSUE TITLE
Rendering error on Antutu's HTML5 test

### ISSUE THREAD

**Issue by RJVB** [OtterBrowser/otter-browser#1654]
There's Webkit/Otter specific rendering issue on https://www.antutu.com/html5/ : the benchmark that shows the floating periodic table of elements doesn't behave as it does in other browsers, including the MiniBrowser from QtWebKit. It does behave fine with the QtWebEngine backend.

The flock benchmark also misbehaves but this appears to be a QtWebKit issue.

**Comment by Emdek** [comment]
@RJVB, please report such issues directly upstream. ;-)
BTW, we have `test-qtwebkit` tool which is probably the most minimal test case around.

https://github.com/qtwebkit/qtwebkit/issues/1002

**Comment by RJVB** [comment]
On Thursday June 25 2020 12:46:09 Michał wrote:
>@RJVB, please report such issues directly upstream. ;-)
..
>https://github.com/qtwebkit/qtwebkit/issues/1002

That one is for the flock issue, which I could have NOT mentioned here to avoid confusion.

This ticket is about the periodic elements table issue, which exists only in Otter Browser. Is there another animal living upstream I'm not aware of that's responsible for this glitch? :)
