### ISSUE TITLE
Doesn't Support Some Website

### ISSUE THREAD

**Issue by criticalsoft** [OtterBrowser/otter-browser#1659]
For Example YouTube Studio
With Custom User Agent String Set

**Comment by Emdek** [comment]
@criticalsoft, try QtWebEngine backend, QtWebKit is lagging behind upstream WebKit…

**Comment by criticalsoft** [comment]
> 
> 
> @criticalsoft, try QtWebEngine backend, QtWebKit is lagging behind upstream WebKit…

Thank You.
