### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by travankor** [OtterBrowser/otter-browser#1661]
Can there be a new release tag made that adds full support for QT webengine?

**Comment by Emdek** [comment]
@travankor, what exactly do you mean by "full support"?
That "Experimental" status of the backend? It's called that way since it's subpar compared to QtWebKit in terms of integration level…
Sadly right now you can only choose between better integration and better standards support. :-/

**Comment by travankor** [comment]
Interesting, so the problem is with QTWebengine? I prefer QTWebkit myself, but webengine has more security updates at this point and is maintained by a large team. QTWebkit is still using insecure webkit from 2016 :/

GTKWebkit is okay, but I don't really like the GTK browsers so much.

**Comment by DI555** [comment]
btw, qtWebEngine isn't passed security checks for blobs and telemetry spyware injections ..., as it is a chromium core.

**Comment by DI555** [comment]
and qtWebKit is qite up to date, the last one is from 2020 spring..
