### ISSUE TITLE
support for IntersectionObserver

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#1662]
Hi,
I'd like about the possibility to support IntersectionObserver in Otter;
I recently noticed some pages where rather basic navigation means were missing (possibly after some code update);
the error message suggest, this might be the cause (or one of them...)
ReferenceError: Can't find variable: IntersectionObserver
It might be a rather modern addition
https://webkit.org/blog/8582/intersectionobserver-in-webkit/
but I am not sure, how/whether it applies for the webkit engine in Otter

Otter Browser diagnostic report created on 2020-09-15T10:30:44Z

Otter 1.0.81 (64bit), 	Weekly 333; WebKit 602.1; Win 10

Thanks for considering this,
       regards,
            vbr

**Comment by Emdek** [comment]
@vbr, sorry, that is one of these things that has to wait for new major release of QtWebkit…

**Comment by vbr** [comment]
Thanks for the prompt answer;
I'm ok with that, I could imagine, this is a rather complex task.
Regards,  vbr

**Comment by Emdek** [comment]
@vbr, in general it is better to focus on trying to get new release sooner than redirecting resources for such cherry picking (unless it is something trivial or important from security point of view), since it will bring a lot of new features etc.
