### ISSUE TITLE
missing vcruntime140_1.dll

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#1668]
Hi,
many thanks for the new windows build of Otter (weekly 360)! 
After updating a portable installation - overwritting the program folder with the content of the archive otter-browser-win64-weekly360.7z - the program cannot start - the error message states, a dll: vcruntime140_1.dll is missing.
(After supplying this file to the otter folder from another program the browser runs correctly, however, this is likely not the supposed  fix - i'm not sure about possbile version mismatch  or other problems.)
Could this dll file maybe be included in the archive files for the current build, or are there other fixes?  (vcruntime140.dll is already there in the z-archive.)
Thanks in advance,
             vbr

**Comment by Emdek** [comment]
Microsoft is working hard on making development of native applications a pain on every step.
So far I'm unable to locate proper files for deployment since it was installed system wide and only for one architecture.

**Comment by Emdek** [comment]
After some more research it seems to be a 64 bit specific dependency, since it seems to be present only in *VC_redist.x64.exe* but not in *VC_redist.x86.exe*.

**Comment by Emdek** [comment]
@vbr, this DLL will be included in packages for 1.0.02 release (should be available tomorrow), please let me know if it won't help (clean up to date Windows 10 doesn't seem to complain about it).

**Comment by vbr** [comment]
Hi, thank You for the quick fix as well as for the current release! I can confirm, that otter-browser-win64-1.0.02 works ok for me, without the above mentioned dependency error (a clean new install of that version is ok too) - on Win 7 pro, 64 bit.

Merry Christmas,
   and best wishes for 2021!
          regards,
              vbr
