### ISSUE TITLE
Cancelling tab dragging via mouse with Esc drops the page to a new window

### ISSUE THREAD

**Issue by twse** [OtterBrowser/otter-browser#1669]
**Steps to reproduce**
* Open a new tab or switch to an existing tab
* Click the tab to drag
* Press Esc to cancel the tab dragging

**Expected result**
Tab dragging should be cancelled

**Actual result**
The page is dropped to a new window

**Comment by Emdek** [comment]
@twse, it seems to be an upstream limitation, there seems to be no way (unless involving window manager maybe) to detect that key press and `QDrag` is missing cancellation signal…
