### ISSUE TITLE
Otter Browser not access to OneDrive

### ISSUE THREAD

**Issue by enricodimenna** [OtterBrowser/otter-browser#1672]
Otter Browser do not permit the access to Onedrive. 
After to have digit the account do not appear the display where to digit the password ... how I can do?
Using MyPal or other browsers the access is normal. 
I am using Windows XP Professional SP3.
Thanks and regards. Enrico DI MENNA.

**Comment by locness3** [comment]
> I am using Windows XP Professional SP3.

~~I mean...~~

**Comment by Vistaus** [comment]
Working fine for me in Otter on Linux, so it must be related to your old Windows version.

**Comment by Emdek** [comment]
@enricodimenna, I doubt that it will work with QtWebKit backend, you would have to use QtWebEngine (and packages for that one are not always available).
