### ISSUE TITLE
"libicuuc.so.69" not found

### ISSUE THREAD

**Issue by Jeongheegenius** [OtterBrowser/otter-browser#1692]
Hello! Developers, I recently got to know otter_browser through the Android app termux. But I come to a big problem.
It's an error right away. Haha...

The error contents are as follows.

```
CANNOT LINK EXECUTABLE "otter-browser": library "libicuuc.so.69" not found: needed by /data/data/com.termux/files/usr/lib/libQt5WebKit.so in namespace (default)
```

Is there a way to solve this? Let me know if you have any! I hope you have a great day today.

P.S. This article has been translated through Naver Papago Translator, so there may be awkward parts. I ask for your understand!

**Comment by Emdek** [comment]
@Jeongheegenius, I haven't tried building for Android (it's a bad idea, since UI is not touch optimized), but it looks like missing ICU dependency.

**Comment by Jeongheegenius** [comment]
oh thank you i didn't see the issue because i was busy i will close the issue now that this is fixed
