### ISSUE TITLE
No web backends available! 

### ISSUE THREAD

**Issue by liuxing860** [OtterBrowser/otter-browser#1693]
Hello, can you help me see what is the cause of this compilation error? Thank you

“CMake Error at CMakeLists.txt : 611 (message):
No web backends available! "

**Comment by Emdek** [comment]
@liuxing860, it means that CMake cannot find C++ headers for any of the backends, so you might be missing QtWebKit or QtWebEngine module or their development files (_dev_ packages in case of Linux).

**Comment by liuxing860** [comment]
Thank you, I try to recompile
