### ISSUE TITLE
Video-Converter.com is no longer working

### ISSUE THREAD

**Issue by LeoNeeson** [OtterBrowser/otter-browser#1695]
Hi! I would like to report that https://video-converter.com/ is no longer working when using the latest Otter Browser (I've tested it using: Weekly report #400 (2021-08-30), Web Backend: WebKit 602.1, under Windows XP, and the same when dual booting and using Windows 7). This is not your fault, but a website's owner decision of using modern JavaScript. This website was working perfectly fine until a few days ago, but due to recent changes on a JavaScript file (shared-v3.js), rendered this website useless (some elements are broken). I've contacted the website owner, but it seems he is not willing to use backwards compatible code. I've asked him to do a 'graceful degradation' to maintain compatibility, but had no response from him (I guess he won't fix it). If you have the time, you can compare and review the recent of changes of the file 'shared-v3.js'. You can find the old and new version of that file, on this forum post, here: https://thedndsanctuary.eu/?topic=3954.0
Perhaps it's an easy fix for you (but there is no hurry).
Any comments will be appreciated.
Cheers,
Leo.-

**Comment by Emdek** [comment]
@LeoNeeson, sorry, can't do anything about that other than suggesting to use QtWebEngine backend for now (which won't work under Windows XP anyway).

**Comment by LeoNeeson** [comment]
Instead of opening a new issue, I would like to report another website that 'suddenly' stop working overnight: https://www.coinpayu.com/ (I've already wrote to their support email, and after giving a sincere explanation and detailed explanation, all I've got was this 'Sorry, we can not help you over this').

I understand that you can't magically fix every website that stop working, so, don't take this as a request (if you have some spare time and it's easy to fix, that's would be great, but if it's hard to solve don't worry, at least save the URL to make some tests in the future).

This is not your fault, so, don't take as an issue of your browser (it's the other way around). It's web developers fault, that change his websites code, without doing a proper 'graceful degradation', breaking the internet for the end-users and forcing browser upgrades, with this mindset: 'either you update or you can no longer use a certain website'. It's a disgrace what most web developers nowadays, since this happens all the time, constantly, and I don't see anyone complaining or exposing these bad practices, when the web should be accessible and compatible for everyone.

**Comment by LeoNeeson** [comment]
Instead of opening a new issue, I would like to report another website that 'suddenly' stop working overnight: https://www.coinpayu.com/ (I've already wrote to their support email, and after giving a sincere and detailed explanation, all I've got was this 'Sorry, we can not help you over this').

I understand that you can't magically fix every website that stop working, so, don't take this as a request. If you have some spare time and it's easy to fix, that would be great, but if it's hard to solve don't worry (at least save the URL to make some tests in the future).

This is not your fault, so, don't take as an issue of your browser (it's the other way around). It's web developers fault, that change his website's code, without doing a proper 'graceful degradation', breaking the internet for the end-users and forcing browser upgrades, with this mindset: 'either you update or you can no longer use a certain website'. It's a disgrace what most web developers nowadays do, since this happens all the time, constantly, and I don't see anyone complaining or exposing these bad practices, when the web should be 'accessible and compatible for everyone'.
