### ISSUE TITLE
(Haiku) Segment violation & hard crash when hovering over "File" menu

### ISSUE THREAD

**Issue by LianBg** [OtterBrowser/otter-browser#1696]
Hey there,

I personally cannot reproduce this again, but hey, it happened.
I am on the Haiku operating system, installed on an Acer Aspire 7738G.

The steps I took prior to this crash:
1. Registered an account on a website
2. Went into my mail client to confirm the mail
3. Confirmation site opened in a different browser due to defaults
4. Returned to Otter browser to continue on
5. Reloaded the site
6. Accidentally hovered over the "File" menu in the top bar, which opened it briefly.

Then, the application terminated within a fraction of a second.

I have attached the crash report to this issue.

**Comment by LianBg** [comment]
For some reason, the crash log did not attach and I can't attach it here on Github either (using Otter Browser, ironically), so here it is linked on the Haiku issue tracker that I also reported this to:

https://dev.haiku-os.org/attachment/ticket/17420/Otter-Browser-15166-debug-24-11-2021-12-55-28.report

**Comment by Emdek** [comment]
@LianBg, sadly that report file is not really useful, but there is a possible clue, it mentions system tray icon - try disabling it.
Any chance for a more detailed backtrace?

**Comment by LianBg** [comment]
@emdek

Well, I can't reproduce it, but I could put a current diagnostics report here if that helps.
https://pastebin.com/raw/0wmyDFuk

Also, the issue with the rectange seems to be unrelated, because for me it happens every single time I use the top menu bar and go into submenus; their outlines just stay there, as if the buffer wouldn't update.

I took a screenshot this time:

https://i.ibb.co/HXGY3Mr/screenshot1.png

**Comment by Emdek** [comment]
@LianBg, we use menus drawn by Qt.
Does the same happen on for example about:config?
Does changing window size force redraw?
Any difference when using menu bar?

**Comment by LianBg** [comment]
It seems to be an issue with several programs using Qt and QtWebKit. The same issue also happens in the Falkon browser.

1) about:config is not affected.
2) Changing window size does not force a redraw
3) It only happens in the menu bar.

And 4) I noticed that after this bug happens, the window is stuck in the background permanently. It is still interactive and can be resized and moved, but other windows are always above it even if it is focused.

**Comment by Emdek** [comment]
@LianBg, apparently it is some sort of issue (or issues) in Qt port for Haiku, you should report it to the maintainer.
Also, Falkon is not using QtWebKit anymore (unless it is a port of very old version), so it might be not specific to QtWebKit.
