### ISSUE TITLE
Otter uses absurd font for various text fields

### ISSUE THREAD

**Issue by LianBg** [OtterBrowser/otter-browser#1697]
Heya,

I have installed the linja pona font (https://github.com/janSame/linja-pona) in OTF format, which is a logographic font for the Toki Pona language. Now, the problem is, for some reason, various text instances within Otter Browser are using this font. Namely, in the screenshot below, it's a selection widget on ImgBB.

https://user-images.githubusercontent.com/92891614/142853312-08124c72-56b4-40e0-869b-8733543b29f2.png
This screenshot proves I have not set the linja pona font as any kind of system font.

https://i.ibb.co/mF7Np5L/linjaponaotter.png
This screenshot is a screenshot of the issue.

https://github.com/haikuports/haikuports/issues/6426
This issue for another Haiku program is probably related, but Haiku as a system only provides fonts and does not select them for programs; hence why this is most likely an Otter issue itself. It might be a Qt problem or an individual problem that developers have to watch out for when developing for Haiku.

**Comment by Emdek** [comment]
@LianBg, you mean UI or webpages?
We don't mess with fonts in the UI yet.
Please provide a screenshot showing Fonts section of Preferences -> Content.

**Comment by LianBg** [comment]
> @LianBg, you mean UI or webpages?
We don't mess with fonts in the UI yet.
Please provide a screenshot showing Fonts section of Preferences -> Content.

The UI, specifically.
I narrowed it down to being a bug in Qt, somehow.
Qt seems to think that font is a good fit for various font types. Which font types it applies it to seems to be relatively random.

The same thing happens in the Qt-based mail client Trojitá, and the new Falkon browser that's in the repos today.

This is the default, right out of the box font selection screen for the Falkon browser, for example:
![falkon-font](https://user-images.githubusercontent.com/92891614/143677933-8cb5c8c7-8b14-4be3-9a5a-6ef1ace09754.png)
You can see it thinks the linja pona font was a good fit for sans serif, fantasy and cursive.

It seems to be a bug for everything using Qt as a framework.
This is the Preferences dialogue you asked for:
![otter-font](https://user-images.githubusercontent.com/92891614/143677988-7104306f-c0f1-4425-b676-045cfd46755c.png)
Apparently, fixed width font is the issue in Otter.

**Comment by Emdek** [comment]
@LianBg, UI fonts are handled by Qt, so it's something wrong in Qt itself or perhaps platform integration code for Haiku.
Fixed font defaults to *DejaVu Sans Mono* and apparently font database returns a pretty bad match for it, I'm not sure if we can do something about that one.
