### ISSUE TITLE
Content blocking: filters won't enable

### ISSUE THREAD

**Issue by Vistaus** [OtterBrowser/otter-browser#1700]
When I go to Tools --> Content Blocking, select some filters and click ‘Save’, the filters don't actually get enabled. And when I close Content Blocking and reopen it, the filters aren't selected anymore.

Am I missing something?

**Comment by Emdek** [comment]
@Vistaus, which version are you using?

**Comment by Vistaus** [comment]
Sorry, forgot to specify that. I'm using the latest git master.

**Comment by Emdek** [comment]
@Vistaus, indeed, there seems to be some sort of issue with collecting selected entries.

**Comment by Vistaus** [comment]
I can confirm that it's fixed now. Thank you! 🙂
