### ISSUE TITLE
cloudflare redirect issue on 1.0.0.2 win64

### ISSUE THREAD

**Issue by firezblade** [OtterBrowser/otter-browser#1706]
Hello,

1. Stuck at cloudflare redirect page. Anybody has a workaround?

2. Help files for addon/userscript. Is there a forum or list of commonly used/compatible userscripts? I vaguely recall that I need to download the userscripts, put them in a folder and enable them from within otter browser options but i cannot find the website to download and folder to store the userscripts.

Thanks!

**Comment by Emdek** [comment]
@firezblade, do you have some test URL that could be used for debugging purposes?
This sounds like QtNetwork or QtWebKit issue, perhaps it was already fixed upstream (1.0.03 packages will be based on a newer Qt version).

About user scripts, you can add them using about:addons (as files), but that feature still needs more work to be fully reliable.

**Comment by firezblade** [comment]
The cloudflare checking browser/redirection loop issue went away on its own after a few days. No idea what happened and i can't replicate it now.

Thanks for your attention.

**Comment by GunGunGun** [comment]
Tested on https://alternativeto.net

Result: The above page showed a captcha page, possibly it's TLS Fingerprint JA3 by CF https://github.com/cloudflare/mitmengine
