### ISSUE TITLE
Otter Browser 1.0.02 won't run on Windows XP SP3

### ISSUE THREAD

**Issue by EgorKuzevanov** [OtterBrowser/otter-browser#1707]
There is an error about missing the d3d11.dll library (DirectX 11).
But on Windows XP SP3, only a maximum of DirectX 9.0c is supported.
Otter Browser 1.0.01, although it supports Windows XP SP3, but the OpenSSL libraries there are very outdated and do not support the new TLS 1.3 encryption protocol and the ChaCha20_Poly1305 cipher suites for TLS 1.2.
Link to the problematic version: https://sourceforge.net/projects/otter-browser/files/otter-browser-1.0.02/otter-browser-win32-1.0.02.7z/download

**Comment by Emdek** [comment]
@EgorKuzevanov, Windows XP is only supported by the *-xp* builds, and these won't get TLS 1.3 since they are stuck with Qt 5.6.
