### ISSUE TITLE
"All settings" tab

### ISSUE THREAD

**Issue by babut85** [OtterBrowser/otter-browser#1710]
when several windows are open, and the "All settings" tab is open in one of them, then when you click the "All settings" button in another window, the new "All settings" tab does not open, and the old one is not activated. if this happens in a situation where you have 8 windows and ~500 tabs, then finding the only tab already open "All settings" is a non-trivial task

**Comment by Emdek** [comment]
@babut85, allowing to open it only once in the session is by design, but it sounds like there is some sort of a issue with activating that already opened tab, right?

**Comment by babut85** [comment]
right. as i said, if a previously opened tab with settings was not closed, if there are a lot of windows and tabs, then it is difficult to find it, because when you try to open it again, it does not become active. it would not be a problem if another tab with settings opened(when you have about 500 tabs, then one more, one less- it is not that important ;))

**Comment by Emdek** [comment]
Just checked how it was solved in Firefox, and it works as it is supposed to work in Otter Browser - it activates already opened preferences tab (activating its window if needed).
It seems that we have a regression that makes them unique only on the window level (it allows to open another about:config in new window).

**Comment by Emdek** [comment]
It required a slight behavior change, to make it work properly it needs to close the dialog first.
