### ISSUE TITLE
Accents do not work on compiled otter (armbian)

### ISSUE THREAD

**Issue by robert-winkler** [OtterBrowser/otter-browser#1712]
Hi, I compiled Otter on armbian. It seems to run fast and stable. 
Unfortunately, language-specific symbols and accents such as é, ó, ü, ß etc do not work.
For me, that is a problem, because I write webmails in Spanish and German.
Is there a way to enable UTF8 letters?
Best, Robert

**Comment by Emdek** [comment]
@robert-winkler, you have that issue with webapges, UI or both? 
Either way it sounds like some issue with Qt or web backend (are you using QtWebKit or QtWebEngine?).
Could you please provide some screenshot?

**Comment by robert-winkler** [comment]
Sure. attached the screenshot.

I'm using QtWebKit. The display of symbol works, but the input troubles.

**Comment by Emdek** [comment]
@robert-winkler, so it's some sort of input issue then.
Does the same happen when you input text in UI controls (for example search field)?

**Comment by robert-winkler** [comment]
Yes, I just typed 'é' in the duckduckgo search field, and it displays
'00e9'.

I have the same input problems with other Qt browsers, i.e. Konqueror and Falkon.

Thus, I tend to blame Qt.

**Comment by Emdek** [comment]
@robert-winkler, OK, then it is indeed some sort of Qt issue, it should be reported upstream.
