### ISSUE TITLE
The "api-ms-win-core" DLL files are apparently missing, help!

### ISSUE THREAD

**Issue by Dylanmc6** [OtterBrowser/otter-browser#1715]
A little while, ago I tried installing Otter Browser. Suddenly, some error messages on the installer appeared saying that the "api-ms-win-core" DLL files are missing, and that I have to abruptly stop installation. Does anyone here know how to fix this problem?

**Comment by Dylanmc6** [comment]
I'm waiting for an answer.

**Comment by Emdek** [comment]
@Dylanmc6, patience is a virtue. ;-)
Which exact installer was that?
Which Windows version?
Set of these DLLs is shipped by both 32 and 64 bit builds for Windows.
