### ISSUE TITLE
Otter crashes upon invoking built-in Feed Reader

### ISSUE THREAD

**Issue by sjehuda** [OtterBrowser/otter-browser#1718]
Clicking on RSS button causes a crash
```
$ otter-browser 
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::at: __n (which is 112) >= this->size() (which is 112)
Aborted (core dumped)
```

Entering view-feed:ADRESS (which is not in Otter Feed Reader) causes a crash too.
```
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 551, resource id: 8537044, major code: 40 (TranslateCoords), minor code: 0
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::at: __n (which is 112) >= this->size() (which is 112)
Aborted (core dumped)
```

Using Otter 1.0.03 on Archlinux

**Comment by sjehuda** [comment]
Entering view-feed:ADRESS (which is not in Otter Feed Reader) causes a crash too.

```
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 551, resource id: 8537044, major code: 40 (TranslateCoords), minor code: 0
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::at: __n (which is 112) >= this->size() (which is 112)
Aborted (core dumped)
```

**Comment by Frenzie** [comment]
On a specific website or all that you come across?

**Comment by sjehuda** [comment]
All that I come across

**Comment by sjehuda** [comment]
Testing when I'm already subscribed to https://otter-browser.org/feed/ (both cases below)

**Button:**
All that I come across, unless it's an address which I'm already subscribed to (unless I'm subscribing when the XML is the web-document opened)

Visit: https://otter-browser.org/
Clicking on RSS icon on URL bar will open Otter Feed Reader.

Visit: https://otter-browser.org/feed/
Clicking on RSS icon on URL bar will crash Otter.
When I'm inside the feed (seeing plain text page) Otter will always crash when clicking on that button.

**view-feed:**
All that I come across, unless it's an address which I'm already subscribed to.
If I'm not subscribed, then Otter crashes.

Entering view-feed:https://otter-browser.org/feed/ will lead user to Otter Feed Reader.

**Comment by Emdek** [comment]
@sjehuda, cannot reproduce, could you please try to create a backtrace?
Which backend are you using?

**Comment by sjehuda** [comment]
> @sjehuda, cannot reproduce, could you please try to create a backtrace?

Please guide me.

> Which backend are you using?

Otter 1.0.03 
Web browser controlled by the user, not vice-versa.
https://www.otter-browser.org/

Web backend: **WebKit Backend 602.1**.

SSL library version: OpenSSL 1.1.1n 15 Mar 2022.

**Comment by sjehuda** [comment]
What do you mean by platform, if not Archlinux?

This is the package I'm using at the moment.
[otter-browser 1.0.03-1](https://archlinux.org/packages/community/x86_64/otter-browser/)

Proprties | Details
-- | --
Architecture   | x86_64
Repository     | Community
Description    | Web browser aiming to recreate the best aspects of the classic Opera (12.x) UI using Qt5
Upstream URL   | https://otter-browser.org/
License(s)     | GPL3
Replaces       | otter-browser-nowebengine
Maintainers    | Balló György
Package Size   | 2.8 MB
Installed Size | 12.7 MB
Last Packager  | Antonio Rojas
Build Date     | 2022-03-13 18:33 UTC
Signed By      | Antonio Rojas
Signature Date | 2022-03-13 18:34 UTC
Last Updated   | 2022-03-13 18:36 UTC

**Comment by Emdek** [comment]
@sjehuda, any chance to create a backtrace?
https://wiki.archlinux.org/title/Debugging/Getting_traces

**Comment by sjehuda** [comment]
Yes. I'll setup a time for that this week, I hope.
Apparently, I need to rebuild the package with certain modifications:
```
# gdb /usr/bin/otter-browser
GNU gdb (GDB) 11.2
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/otter-browser...
(No debugging symbols found in /usr/bin/otter-browser)
(gdb)
```

**Comment by sjehuda** [comment]
I think it's going to be delayed.  I'm closing this ticket and I'll open it when I'm readdy.

**Comment by sjehuda** [comment]
I am glad to inform that Otter Browser operates smoothly on Arch Linux.
