### ISSUE TITLE
feed: Unsupported address type

### ISSUE THREAD

**Issue by sjehuda** [OtterBrowser/otter-browser#1720]
`feed:` should invoke `xdg-open`.
`feed:` is a pseudo protocol, like `magnet:` of BitTorrent, so I consider it as a handler.

The URI scheme `feed:` is utilized to make an easier association and automation with Feed Readers.  See #1719
On my system `$ xdg-open feed:https://otter-browser.org/feed/` will be opened by Liferea as `https://otter-browser.org/feed/`.

**Comment by Emdek** [comment]
@sjehuda, it seems that only Chrome attempts to open these URLs, not even the classic Opera, but it's easy to either redirect them or simply open in our viewer.

**Comment by Emdek** [comment]
Moreover, perhaps it would be a good idea to rename our `view-feed` to just `feed`.
