### ISSUE TITLE
Date of build in about Otter

### ISSUE THREAD

**Issue by Ygarr** [OtterBrowser/otter-browser#1722]
Please add string in "Help">"About Otter" with specified date of build of otter to control bugs, features  and other experience.
e.g. cannot figure out with versions: 1.0.81 weekly360 or 1.0.03 of 22 feb.

**Comment by Frenzie** [comment]
Date of tag/commit and possibly date of build, rather, I would say. :-)

**Comment by Emdek** [comment]
Yeah, I've investigated it in the past, the issue is how to accomplish it with CMake in the easiest way, if someone has seen some ready to use code (with compatible license) then we can go for it.
