### ISSUE TITLE
github page in otter browser

### ISSUE THREAD

**Issue by Ygarr** [OtterBrowser/otter-browser#1723]
There is smth. like incompatibleness with github portal, cause cannot get information after login looks like in attachments:
![image](https://user-images.githubusercontent.com/14309871/162080841-d1d963c8-d657-4ddd-8a34-a4efcf2d1898.png)

Otter 1.0.81 weekly 360 version

**Comment by Emdek** [comment]
@Ygarr, switch to QtWebEngine backend, QtWebKit is again lagging behind…
