### ISSUE TITLE
JavaScript | Not supported

### ISSUE THREAD

**Issue by Ricky-Tigg** [OtterBrowser/otter-browser#1726]
reference:
```
$ LANG=C otter-browser --report | awk 'NF' | sed -n '2,14p'
Version:
	Main Number         1.0.03
	Weekly Number       -
	Context
	Web Backend         WebKit Backend 602.1
Environment:
	System Name                   Fedora Linux 36 (Workstation Edition)
	Build ABI                     x86_64-little_endian-lp64
	Build CPU Architecture        x86_64
	Current CPU Architecture      x86_64
	Build Qt Version              5.15.2
	Current Qt Version            5.15.3
	Locale                        C
```
**Windows system:** X11; Would be unstable under Wayland. Browser left with its **default settings**.

Hello. Visiting that [page](https://html5test.com/) leads to produce what follows:

![Otter_v 1 0 03_javascript_prompt](https://user-images.githubusercontent.com/26058215/166457745-279ca5d1-2a01-484c-a323-3205d0057d72.png)

Therefore the on-line test served by the site cannot be conducted.

**Comment by Emdek** [comment]
@Ricky-Tigg, it's an issue with unsupported feature of QtWebKit backend, you can try QtWebEngine instead,

**Comment by Ricky-Tigg** [comment]
All right! May the suggested component be tied to a setting within Otter, or requiring a methodology to be build. I lack knowledge but certainly i am willing to observe relevant instructions if any, somewhere. Do you have in mind any source in this regard?
