### ISSUE TITLE
Unknown counterpart for Otter.of Opera 12's own internal protocol, 'opera:'

### ISSUE THREAD

**Issue by Ricky-Tigg** [OtterBrowser/otter-browser#1727]
**otter-browser v.:** 1.0.03

Hello. At the time the web browser Opera was in **version 12**, it has its own internal protocol, _opera:_, implemented, which operated within the **URL field**. Illustration:

![opera_v _12 18_URL_details](https://user-images.githubusercontent.com/26058215/166514216-a488d0cf-9624-4695-b950-cfe84a71b26d.png)

**note:** mention _Windows 8_ is wrong; correct would be _Windows 11_. That is most likely due to the obsolescence of components in that very browser.

Unknown is in the project made public, the counterpart for Otter of Opera 12's own internal protocol, _opera:_. Does it even exist?

**Comment by Frenzie** [comment]
If you type `about:` then the autocomplete will suggest a list of such internal pages.

**Comment by Ricky-Tigg** [comment]
That a news for me It would be worth a mention in documentation, unless i was the only one not to know yet or lacked of intuition.

![otter_about-protocol_URLs](https://user-images.githubusercontent.com/26058215/166640928-fe2ad5f2-a04e-4bd3-8d32-b90c2227b8ba.png)

**Comment by Frenzie** [comment]
It probably wouldn't hurt, but it's not like you're missing out on anything other than some trivia. Sometimes it might be slightly faster, probably mainly if it requires Tools → Preferences → some tab → some button. These pages are simply what's opened when you activate the relevant button/menu item/shortcut.

**Comment by Ricky-Tigg** [comment]
So It can be closed unless you have an objection.

**Comment by Frenzie** [comment]
Alright, closing then. ^_^

**Comment by Emdek** [comment]
@Ricky-Tigg, yeah, we need user documentation, but someone would have to write it…
