### ISSUE TITLE
Add support of scalability with pages whose display are governed by the 'about:' protocol

### ISSUE THREAD

**Issue by Ricky-Tigg** [OtterBrowser/otter-browser#1731]
**reference:**
```
$ otter-browser --report | awk 'NF' | sed -n '2,8p;12,13p'
Version:
	Main Number         1.0.03
	Weekly Number       -
	Context
	Web Backend         WebKit Backend 602.1
Environment:
	System Name                   Fedora Linux 36 (Workstation Edition)
	Build Qt Version              5.15.2
	Current Qt Version            5.15.3
```
Hello.  In the **version 12** of Opera, the window's **display view scaling** is operational with Opera's own internal protocol, _opera:_, which operates inside the URL field, as well with classic URLs, those non-internal. None of the content of that view is manually scalable. Resizing enough the browser window to smaller, has no effect on the elements or characters part of it, at the exception of the **graphical element** aiming to add a site, which has the **+** in it, by scaling it accordingly.

![opera_v 12 18_window_display_view_scaling](https://user-images.githubusercontent.com/26058215/166679155-1333c7a1-a992-4ea5-9d82-b7ee418154a9.png)

 In **this product**, the window's **display view scaling** is **not** operational with its own internal protocol, _about:_,which operates inside the URL field, while it is with classic URLs. Characters and elements part of the following view are **not scalable**, neither manually nor by resizing enough the browser window to smaller,

![otter_v 1 0 03_display_scaling](https://user-images.githubusercontent.com/26058215/166673655-1f7d308e-3074-4725-8355-c0c2cba92e44.png)

The support of scalability with pages whose display are governed by the _about:_ protocol, would be welcome. as it would still serve its purpose when characters and elements within the view cannot be read due to a case too small for the reader.

**Comment by Emdek** [comment]
@Ricky-Tigg, the issue is that these pages are actual widgets, not just some HTML, which makes that a bit complicated.
But I can experiment with base font scaling, perhaps it will just work, at least in most cases.

**Comment by Ricky-Tigg** [comment]
My suggestion must not affect the capacity of developers to keep the focus on issues that they may estimate of higher priority in regard to fixing. The present one could even be already closed if human resources do not allow any fix in a close future.
