### ISSUE TITLE
Can I use Qt5WebEngine with OpenSSL

### ISSUE THREAD

**Issue by samwell-ho** [OtterBrowser/otter-browser#1734]
As far as I know, Chromium (in Qt5WebEngine) uses NSS for most of its cryptographic operations, especially for HTTPS/TLS.

If I compile Qt5 using OpenSSL, will it be used for HTTPS or not?

Can someone show me how to compile Qt5 with Qt5WebEngine and OpenSSL so that Otter uses OpenSSL for HTTPS. 

Thanks, I'm new to Otter so I don't know how to compile it properly.

**Comment by Emdek** [comment]
@samwell-ho, Chromium uses [BoringSSL](https://en.wikipedia.org/wiki/OpenSSL#BoringSSL), it doesn't use SSL provided by Qt at all, but that one is still used for operations not involving QtWebEngine (for example direct downloads, updating feeds etc.).
AFAIK there is no way to replace it.
