### ISSUE TITLE
Scroll position not saved

### ISSUE THREAD

**Issue by Katarn** [OtterBrowser/otter-browser#183]
Steps to reproduce:
1. Open two tabs with different urls
2. In the active tab (1), scroll to the middle of the page
3. In inactive tab (2) scroll should be at the any
4. When the tab (1) is active close browser
5. Start the browser again
6. !!! Scrolling in tab (1) is at the top
7. Ok, scroll tab (1) to the middle again
8. Open tab (2)
9. !!! Returns to tab (1) - scroll is at top again

By the way, I use delay loading, perhaps the problem is related to this.

**Comment by beastie1** [comment]
This old issue seems to have reappeared in the latest build(s). It occurs randomly.

I'm still using the default WebKit engine if that matters.

**Comment by beastie1** [comment]
Just to be clear, I'm talking about the issue of the scroll position not being saved when switching from one tab to another in a live session.

**Comment by Emdek** [comment]
@beastie1, any chance for some kind of screencast showing this issue?
As it seems to be something a bit different than in the past.

**Comment by beastie1** [comment]
1. Search with **Ctrl+F** (e.g. the word **middle** which is only found at the top of the page); the page scrolls to the first result
2. Scroll to the bottom of the page
3. Switch to anoher tab
4. Switch back to this tab; the page has scrolled back to the search result position at the top

**Comment by Emdek** [comment]
@beastie1, it's separate issue in `SearchBarWidget`.
