### ISSUE TITLE
Content blocking

### ISSUE THREAD

**Issue by manushanga** [OtterBrowser/otter-browser#206]
The browser is lacking ad block support, if included will add massive value to the browser since it's lean and featureful.

**Comment by fguzm** [comment]
For (southpark) videos to watch, I have to disable EasyList globally.
The context menu disbles it globally.
Why not per-site content blocking selection?

**Comment by Emdek** [comment]
@fguzm, it's already available, but no exposed in UI yet.
You need to add custom entry to *override.ini* in profile directory, something like this:

```
[southpark.cc.com]
Content\BlockingProfiles=list,of,profiles
```

Just copy value from *otter.conf* and remove *easylist*.

**Comment by Yodzeity** [comment]
What's the state of this?

**Comment by Emdek** [comment]
@Yodzeity, done, but still missing support for few more complex rules, see #1221.
