### ISSUE TITLE
Back/Forward history

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#210]
Two nice additions I'd like to see in the back and forward toolbar icons:
* right-clicking should do the same as left-clicking and holding: it should display the list, but instantaneously instead of having to wait for 1 sec or so.
* a "Clear" menu item, like the one in the "Closed Tabs" menu, to clear the tab's history.

What do you think?

Thank you!

**Comment by Emdek** [comment]
Adding custom button per menu item appears to be a bit too complicated (unless we don't care for MacOS X...), so I guess that I'll try with Delete key (remove entry) and Shift+Delete (purge entry - remove also global entry, if possible).
Maybe also some context menu (yeah, menus can have context menus, an we even already use that for bookmarks ;-)).
