### ISSUE TITLE
Source viewer

### ISSUE THREAD

**Issue by Emdek** [OtterBrowser/otter-browser#23]
Plans for this feature are as follow:
1.  as module derived from **ContentsWidget**;
2.  using API shared with save feature (not ready yet), getting source of webpage by asking WindowsManager by URL, which will query opened windows for contents for given URL (possibly preferring cache, since WebKit tends to modify it a bit, like reformatting of some tags) and downloading it if needed (like it is done in Firefox, but always preferring local content);
3.  standard syntax highlighting feature (starting with HTML, then adding CSS and JavaScript);
4.  line numbering (optional, defaulting to on);
5  ability to save contents to disk (I'm unsure if sending it back to original tab is good idea, Inspector is more up to that task);
6.  implementing undo stack (it should be enough to simply expose that or **QPlainTextEdit**).

Currently main issue is how URLs passed to it should look like, prepend **source+** to original URL (for example: source+http://otter-browser.org) or maybe better use standard **about:source/encoded URL** scheme (allowing "malformed" URLs, created by typing request through address field without encoding it first). 
Original URL should be anyway always displayed on top of page (using **TextLabelWidget**).

If someone would like to start working on this now then you should first check out **ContentsWidget** API and ask me to add required API (the one supposed to be shared with save action).

I've already have implementation of text editing widget with syntax highlighting and line numbering (plus some other stuff), from my thesis project which could be used as a base implementation, after some cleanup.

**Comment by vbr** [comment]
Hi, I would like to ask about the possibility to include an interface for setting an external editor for source viewing. Would it be feasible at least till the planned built in viewer is ready? Or are there some barriers for this functionality which must be solved for both built in or external source viewer?
Additionally an old opera option to reload the page from cache would be ideal, but probably not trivial ...

Thanks for the continued effort 
   and regards
        vbr

**Comment by Emdek** [comment]
@vbr, there is one important issue, there is no clean way to get original HTML code, QtWebKit only allows to fetch snapshot of DOM, already modified by WebKit, or even by JS.
The best way seems to be to try to ask cache using DOM snapshot as fallback.

Reloading from cache might be doable, at least in case of QtWebKit.

**Comment by vbr** [comment]
Thanks for the clarification, I didn't expect such a restriction of QtWebKit, howaver, the cache access seems reasonable; reloading would really be an extra bonus, if it is doable.
regards,
    vbr

**Comment by Katarn** [comment]
I think for this feature may need to do a layer of downloading files bypassing WebKit. It may also be necessary to download images only from the cache, blocking all other requests to images.

**Comment by Katarn** [comment]
It can also be used to index the files for save the page to disk.
