### ISSUE TITLE
Transfers Manager - Clear Finished Transfers bug

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#231]
Good day!

There's a bug in the **Transfers Manager**. When you click **Clear Finished Transfers**, not all transfers are cleared (even if all transfers are complete).
You have to repeat **Clear Finished Transfers**, several times before the entire list is emptied.

**Comment by beastie1** [comment]
This bug is back.

**Comment by Emdek** [comment]
@beastie1, and now it is back where it belongs. ;-)
