### ISSUE TITLE
URL completion / history dropdown widget

### ISSUE THREAD

**Issue by xyz32** [OtterBrowser/otter-browser#250]
After selecting the Suggest bookmarks check box in the options menue and adding a couple of bookmarks, no hint shows up when starting to type a new address.
OS: Linux
Otter Version: Latest From GIT

**Comment by Frenzie** [comment]
Congratulations, great work! :-)

**Comment by Frenzie** [comment]
You've probably noticed this already, but I now can't type anything in the address bar anymore without the browser searching for it. I'm a bit undecided about what's the most user-friendly with regard to hostnames, but e.g. example.com and http://example.com even more so shouldn't result in any searches being performed.

**Comment by Emdek** [comment]
@Frenzie, no, there is no search performed (unless you mean accidental one after hitting Enter, I'm going to fix that one).
For now you can disable that first entry by setting ``AddressField/SuggestSearch`` to ``false``.

**Comment by Frenzie** [comment]
> no, there is no search performed (unless you mean accidental one after hitting Enter, I'm going to fix that one).

Yes, that's what I meant. Sorry for the confusion.

**Comment by beastie1** [comment]
**Paste and Go** (or paste followed by Enter) in the address bar causes Otter to output this on the console:
```
Warning: QObject::connect: No such slot Otter::AddressWidget::deleteText() ((null):0, (null))
Warning: QObject::connect: No such slot Otter::AddressWidget::copyToNote() ((null):0, (null))
```

**Comment by Emdek** [comment]
@beastie1, odd, these could be only generated by triggering context menu.

**Comment by beastie1** [comment]
Haha yes, you're right. I thought it was right-clicking and **Paste and Go**, but just right-clicking is enough. Sorry.
