### ISSUE TITLE
Stop the download/upload of data right away on pressing Esc or the X button plus suggestions

### ISSUE THREAD

**Issue by Felipefpl** [OtterBrowser/otter-browser#270]
The reason for this request is that no browser has this behavior and it sucks having to wait for the transfer of data to stop, i'm on dial-up on win7 x64 (the same happened on xp) which explains why i'm asking for this, i cant pay for broadband, i know this is something small but this is important to me.

Suggestions:

1 - allow to put a bookmark star just like in Opera like it's displayed in the image

![bookmark star](https://cloud.githubusercontent.com/assets/5569804/2811830/69267230-ce33-11e3-878f-17c9a224183f.gif)

2 - ensure all parts of the GUI can resize themselves automatically to give room for the translations, the word "speed" in the progress bar is translated to "velocidade" in portuguese, on Opera the word "velocidade" isnt fully displayed due to the GUI not resizing itself.

3 - why the file size is 36,9 MB when Opera 12.17 is 9,80 MB? a explanation for this is a good thing to add in the FAQ section. ;)

4 - i know the 64 bit programs use more memory but i dont understand why Opera x64 sometimes spent a lot of memory (500 MB RAM) after some time where i loaded some webpages and then after i closed them (keeping only 3 IRC windows opened) the memory consumption remained on 500 MB, this doesnt happen with 32 bit version. I hope you'll keep an eye on this. ;)

5 - i know this is your creation so i'll understand if you dont wanna change this but one of the things i didnt like on Opera was the addition of programs that only 0.01% of users used (usually web devs) this kind of programs are better as extensions, they only serve to make the browser bigger, i remember around Opera 7.0 when the installer was around 5 MB and it got bigger and bigger due the addition of these programs, just a suggestion, these things are really better as extensions. ;)

That's all, thank you very much for your creation/work on this program, thanks to the others who helped too and thank you for your attention.

**Comment by Emdek** [comment]
Stopping current page load by pressing Esc was added long time ago already.

**Comment by Felipefpl** [comment]
indeed, numbers 1 and 3 are out but i hope the 2, 4 and 5 are still on yor mind. ;)

**Comment by Emdek** [comment]
@Felipefpl, 2. should get fixed at least partially when progress bar will become customizable, then these fields could be limited by attribute to set maximum item size.
4. is not a something that we can control much, except ensuring that 32 bit binaries don't break. ;-)
5. is something that can be only partially done, both *QtWebKit* and *QtWebEngine* are simply large (and the latter tries to have everything built-in, for example this is a reason why Debian maintainers don't like *QtWebEngine* and want to skip it :-D). 
We won't ship any external applications, we are only considering if it would be possible to ship video codecs for Windows as currently these must be installed separately...
About extensions, usually compiled code takes less space and resources than JS, so must have features will be done in C++ (as long as it is possible, ``QtWebEnine`` and Blink itself forces to do a lot of stuff using JS calls :-/).

**Comment by Felipefpl** [comment]
i see, thanks for the explanations.

**Comment by lollox** [comment]
MPC-HC is an external application... a codec built-in (or loaded from system) is a whole different thing...

**Comment by Felipefpl** [comment]
i know, what i meant was why make otter download this stuff when can you have a full program with codecs? Just my opinion.

**Comment by lollox** [comment]
however... doesn't QTWebEngine include all the stuff itself?

**Comment by Emdek** [comment]
@lollox, codecs?
Yes, but h264 requires compile flags and licence...
QtWebKit can use anything available system-wide through QtMultimedia.

**Comment by lollox** [comment]
Since QTWebkit is a living-dead module, shouldn't we focus more on QTWebEngine ?

**Comment by Emdek** [comment]
@lollox, world doesn't end on KHTML-derived layout engines. ;-)
QtWebEngine is as usable as possible with current state of that module, we can try to do something more as soon as there will be Qt 5.5 beta, which should be soon.
And QtWebkit is far from being dead. ;-)
