### ISSUE TITLE
Option to disable images

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#317]
Hello.

Like the title says, I think a global option to disable the display of images would be great to have.
This would be similar to the global option to disable plugins, Javascript, etc.

Of course in the future, when "page specific preferences" are implemented, such options could be added to override global preferences (whether these be "on" or "off"). But for now, a global option would be good enough.

Thanks!

**Comment by Emdek** [comment]
Accidentally (I was sure that there was such ticket already but couldn't find it) superseded by #1146.
