### ISSUE TITLE
Add UserJavaScript support

### ISSUE THREAD

**Issue by uahim** [OtterBrowser/otter-browser#336]
I'm aware this has very low priority, but it would be excellent if it could be added in later versions as UserJS lets the user define how a site works in many cases - not vice versa ;-)

**Comment by Zero3K** [comment]
What's the status on implementing this?

**Comment by Emdek** [comment]
@Zero3K, basic support (loading selected / all scripts every time) isn't a big task, but providing compatibility with existing solutions is harder.
Perhaps I should split this ticket into two, keeping this for basic implementation (well, it will be enough in most cases anyway, I guess) and another one for more advanced stuff (possibly QtWebKit specific).

**Comment by uahim** [comment]
@Emdek so if possible, add basic support for the time being and let users enable it via basic_userjs true (with default being false) in about:config? :) Otter is better than Vivaldi already, but adding this would make it win the race for now

**Comment by Emdek** [comment]
@uahim, I don't think that we really need an option for that, for now it should be enough to check if that directory exists.
Perhaps I'll find some time to create basic manager too.

**Comment by Emdek** [comment]
Here is ticket for tracking work on improved support for GM scripts: #1091.

**Comment by pierreporte** [comment]
I wrote a comment https://github.com/OtterBrowser/otter-browser/issues/832#issuecomment-246751035 in response of @zoidbergthepopularone about a potential user-JS password manager. He said that he disables JS since it is a “huge security hole” and it leads me to an interrogation: could remote JS be disabled while user JS be still enabled? That way, users could still use their userscripts while avoiding JS provided by websites.

**Comment by zoidbergthepopularone** [comment]
@pierreporte: 1) From what I have seen, I very much doubt that modern browser engines (at least Chromium, Blink, WebKit and Gecko) support differentiation of the source of a particular script. As an evidence I would like to point out that, to the best of my knowledge, no browser based on the mentioned engines allows a creation of extension which would be able to interact with a webpage AND not require javascript turned on for that webpage. AFAIK, the extension's code gets injected into the webpage and then treated as the webpage's native script. The same is true for e.g. Opera 12's UserJS implementation.

2) Microsoft did very much the same thing in Internet Explorer 4 with the introduction of different security zones. A great number of critical vulnerabilities of IE comes from the fact that a webpage managed to break from the Internet zone to the My Computer zone. I would take that as indication that properly separating sources of scripts would be a difficult challenge.

**Comment by The-Compiler** [comment]
QtWebEngine allows running JS via runJavaScript with the page having disabled just fine, QtWebKit allows it with a workaround which works fine in all scenarios I could test, but apparently doesn't for some users - see [this file](https://github.com/The-Compiler/qutebrowser/blob/master/tests/unit/browser/webkit/test_qt_javascript.py#L26-L62) for some related tests I've written to verify that.

I'm also pretty sure Chromium extensions run just fine when the JS is disabled for the page.

**Comment by ccd0** [comment]
> I'm also pretty sure Chromium extensions run just fine when the JS is disabled for the page.

They do for the most part, although event handlers registered by the extension don't work.  Event handlers from Greasemonkey scripts in Firefox work without JS enabled, though.
