### ISSUE TITLE
Open page in other browser(s) - cross-platform library to list applications associated with MIME type

### ISSUE THREAD

**Issue by uahim** [OtterBrowser/otter-browser#337]
via context menu or some other way - that'd come handy if pages do not work as they should in webkit, possibly with user defined paths for those browsers

**Comment by uahim** [comment]
I'm aware this isn't closed, just wanted to say that the 'problem' re-appeared in the last couple of builds, including beta 4

**Comment by Emdek** [comment]
@uahim, we don't have such action yet (to insert it as menu) but it is already used by Transfers Manager, so it can get some testing before ending up in context menu.

**Comment by Frenzie** [comment]
Awesome work, thanks!
