### ISSUE TITLE
Rewind/Fast Forward

### ISSUE THREAD

**Issue by lollox** [OtterBrowser/otter-browser#343]
I don't see it in the ToDo list so here is: will these two historic Opera features be supported in Otter? (in default configuration only as shortcuts, no buttons in GUI)

**Comment by ersi-dnd** [comment]
I am beginning to miss a proper Fast Forward. As far as I am able to determine in Opera, Fast Forward

- looks up and follows links in webpages labelled Next and "->" and everything else defined in fastforward.ini http://www.fredfred.net/download/Opera/fastforward.ini
-  looks up and follows the HTML header element link rel="next"
- detects images and orders them into slideshow that can be cycled with Fast Forward button or keybind or mouse gesture

In addition to the ordinary Fast Forward button or keybind or mouse gesture, Opera also triggers Fast Forward action by spacebar, like this: Usually spacebar scrolls the page down, but when the page bottom is reached, spacebar triggers Fast Forward.

**Comment by piktaszuikis** [comment]
Good new everyone!
I've implemented a prototype fast-forward function for otter witch hopefully will get merged into the mainstream.
It would be awesome if any of you would check it's performance. You can find a fork over there: https://github.com/piktaszuikis/otter-browser/tree/fast-forward

**Comment by pierreporte** [comment]
@piktaszuikis you should make a pull-request.

**Comment by Emdek** [comment]
@pierreporte, too early for that, we are not done yet with review phase.
