### ISSUE TITLE
Cursor indicator issues

### ISSUE THREAD

**Issue by lollox** [OtterBrowser/otter-browser#344]
http://i.imgur.com/jfdQIPz.jpg

As you can see in the above image, when I use arrows to move through text fields I've that strange artifacts or, sometimes, the cursor simply disappears (and there's no action able to make it visible again untill I leave the text field)

**Comment by The-Compiler** [comment]
@lollox do you still see this happening? I haven't seen it recently, but I'm also using Windows less recently :tada:

**Comment by lollox** [comment]
@The-Compiler no, I just tested it and it seems it doesn't happen anymore
