### ISSUE TITLE
Tab preview apperance options.

### ISSUE THREAD

**Issue by DoctorJellyface** [OtterBrowser/otter-browser#351]
I'm on a issue spree today :)

For me, the tab preview appears way too quickly and is too transparent for my taste. Could this be configurable?

As always, thanks for the great work.

On Otter Beta 1.

**Comment by Emdek** [comment]
It seems that stuff like opacity should be already customizable using application stylesheet (available in Preferences -> Advanced -> Appearance):
> **QToolTip**
> Supports the box model. The opacity property controls the opacity of the tooltip.
> See Customizing QFrame for an example (a QToolTip is a QFrame).
