### ISSUE TITLE
Add option for html5 <video> tag to disable auto play

### ISSUE THREAD

**Issue by uahim** [OtterBrowser/otter-browser#353]
afaik there is no standard for his, so it would be very convenient if an option to disable this via about:config could be implemented - in similar fashion to the click to play/ODP/content blocking functionality

**Comment by Emdek** [comment]
This could be considered task for user scripts, #336.

**Comment by Frenzie** [comment]
This was promised to us by the browser makers when they added the `autoplay` attribute to HTML5. I'm still waiting…

**Comment by Emdek** [comment]
@Frenzie, well, at least it's easy to overcome assuming that there is support for user scripts.
Personally I would like to see separate option to disable media, just like plugins.
