### ISSUE TITLE
Bottom bar combined with bookmarks bar (read this it's awesome)

### ISSUE THREAD

**Issue by DoctorJellyface** [OtterBrowser/otter-browser#356]
Damnit, just had an awesome idea.

Look at your bottom bar. Now imagine your bookmarks on the white space. And when you hover on a link on a webpage, the bookmarks would be replaced with the url, and when you unhover the link (go away from it), it would switch back to the bookmarks bar.

Just the controls on the right wouldn't change.

Don't tell me this wouldn't be awesome.

**Comment by midluk** [comment]
In the original Opera you could just drag tabs anywhere and it added a bookmark item at that place.
I never used the actual bookmarks but had everything as little icons in the status bar. At some point they made it more difficult to do so (had to press shift to drag), but it still worked.
Would love to be able to do so again.

**Comment by xploSEoF** [comment]
Personally, I never saw why the links URL had to come up in the bottom left - why not in the address bar as a `current.url/shown/as?this=cropped&at... => new.url/shown/here?maybe=just&relative=url`

**Comment by Emdek** [comment]
@DoctorJellyface, it seems that your original idea didn't sell...
Anyway, it should be still possible to achieve that using custom widgets once they will land (#42), as mentioned earlier, widget could occupy entire toolbar (which is already possible) and simply decide what to display depending on user actions.
