### ISSUE TITLE
Add option  "show start bar"

### ISSUE THREAD

**Issue by vnu007dl** [OtterBrowser/otter-browser#363]
In Opera browser i like so much "start bar". This bar is appear when you click in address bar. This is place where  I have shourts to hompage, top ten sites and favourites.
![startbar](https://cloud.githubusercontent.com/assets/655156/3299838/da43e634-f618-11e3-8b31-32d51c8eb688.JPG)

Startbar can be enable in opera menu - appearance (shift+ F12) - toolbars
![startbar2](https://cloud.githubusercontent.com/assets/655156/3299864/4100bf78-f619-11e3-8a3d-f34588d24438.JPG)
Can we imagine that this feature will appear in Otter browser?
PS. Sory forr my english

**Comment by Emdek** [comment]
Apparently nobody else is interested in adding it here.
