### ISSUE TITLE
KeePassX auto-type doesn't work in Otter.

### ISSUE THREAD

**Issue by DoctorJellyface** [OtterBrowser/otter-browser#365]
It's damn annoying.
I am sure it's not a problem with KeePassX, it works everywhere else.

Otter 0.9.02-dev
KeePassX 0.4.3

**Comment by Chocimier** [comment]
It is an upstream issue. Otter compiled with qt5.5 works well.

**Comment by The-Compiler** [comment]
It's actually some mixture between otter and KeePassX bugs - it's also fixed in the alpha version of KeePassX: https://www.keepassx.org/dev/issues/236
