### ISSUE TITLE
Paste & Go on new tab?

### ISSUE THREAD

**Issue by jurf** [OtterBrowser/otter-browser#407]
So that you don't have to press Ctrl+Tab before Ctrl+Shift+V.

**Comment by ersi-dnd** [comment]
I tried this kind of contents in the macro.ini:

[OOOO]
title="new-paste-go"
actions=NewTab,PasteAndGo
shortcuts=Ctrl+H

[OOO1]
title="address-paste"
actions=GoToPage,Paste
shortcuts=F2

(Of course I hid F2 shortcut from the ordinary keyboard.ini)

The second one is not working properly. The idea was to open up the secondary address field and paste into it whatever happens to be in the clipboard. It opens up the address field, but does not paste anything. A focus problem?

**Comment by Emdek** [comment]
@ersi-dnd, these actions do not affect dialogs and I'm not sure if it would make sense (and definitively would complicate current code which finally works as it should be).
This is a task for scripting mentioned in another ticket.
