### ISSUE TITLE
New keyboard shortcuts

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#436]
Good day.

A few additional keyboard shortcuts that would be great to have:
- Esc: unselect any selected text when the "Webkit area" is focused (BTW how is that area called?)
- Always open anything in a new tab if Shift is pressed. Otter currently has Shift+click on a link; Opera also has this for the address bar (Shift+Enter) and Shift+click on bookmarks does the same as Open in New Tab even if the browser is set to reuse tabs

Thanks!

**Comment by beastie1** [comment]
Hah! So when did you add text deselection using the Esc key **without** JavaScript? I've only discovered it now hehe. Thanks!

**Comment by Emdek** [comment]
@beastie1, dunno, recently there was change that should allow to run our JS even when it is disabled, thanks to hint provided by @The-Compiler.
But this could be something different too.

**Comment by beastie1** [comment]
@Emdek, interesting. So what are the rules that override the settings when JavaScript is disabled?

**Comment by Emdek** [comment]
@beastie1, running it using ``QWebElement`` API, on document.
