### ISSUE TITLE
Page inspector resets after tab switching

### ISSUE THREAD

**Issue by Katarn** [OtterBrowser/otter-browser#438]
Steps to reproduce:

1. Open two tabs with some urls.
2. On first tab open Page inspector. Select random DOM-node in Elements tab. Or open Console tab, enter `alert('test')`, press Enter. Close alert window.
2. Switch to other tab.
3. Switch to first tab. Page inspector is in reset state.

**Comment by Emdek** [comment]
@Katarn, this is definitely some kind of upstream issue, for some unknown reason it appears to work better if MDI is enabled although it seems to also work better in standard mode now (Qt 5.5), as the worst case I've seen was switching to another tab if it was switched in another instance (for example opening one instance and then another in different tab and switching it to console, both ended up switched to console) but selected DOM element was kept intact.
