### ISSUE TITLE
QtConcurrent module is used

### ISSUE THREAD

**Issue by SchaichAlonso** [OtterBrowser/otter-browser#461]
Hello,

The QtConcurrent module is referenced at least in ${otter-root}/src/core/ContentBlockingList.cpp, however this module is not tracked by the (cmake/qmake) project files.

**Comment by rakuco** [comment]
Could you please elaborate on how adding the explicit dependency could potentially break the installation? I don't see how the way Qt is packaged would have an influence on this problem, as regardless of whether there's just one qt-base package (like in ArchLinux) or several packages (Fedora, FreeBSD etc) `libQt5Concurrent.so` is still a separate library whose symbols are being used (and whose headers are pulled separately from Qt5Core).

**Comment by Emdek** [comment]
@rakuco, I don't remember exact details but adding that broke installation in some cases.

**Comment by rakuco** [comment]
OK, you did mention that, my question was whether you have more information about that. Given how QtConcurrent is a separate shared library, it is really not clear to me how one thing could be related to the other, so it is hard to try to come up with a fix proposal for example.
