### ISSUE TITLE
Add advanced settings for cookies

### ISSUE THREAD

**Issue by ghost** [OtterBrowser/otter-browser#463]
And in the cookies manager I can find such nice friends as doubleclick.net or statcounter.com

**Comment by VSHY** [comment]
The people very nervous about black/white-lists for cookies: http://forum.ru-board.com/topic.cgi?forum=5&topic=46573&start=140#17 :)
Similar proposals are often found in other forums.

**Comment by Emdek** [comment]
@VSHY, there are no white and black lists, you can set all three policies (general, third-party and if cookies should be kept or not after ending session) for each host separately, using Website Preferences or manually in *override.ini* (you can override most of options that way).
We could get UI that does that like if there would be such lists, but there are more important tasks right now.

**Comment by VSHY** [comment]
@Emdek
That's right. Thanks for your answer.

**Comment by Emdek** [comment]
@VSHY, I've analyzed that again and there is one thing that is missing after all, exceptions for third party cookies.
I'll create new ticket for that task.

**Comment by ersi-dnd** [comment]
For me cookies in Otter misbehave in a major way. For example Github declares at login "Your browser did something unexpected". Transifex declares 

400 Bad Request
Request Header Or Cookie Too Large

I have global cookies set off and I enable cookies individually for domains in website preferences. This works in Opera and Seamonkey (always has), but not in Otter. 

To be fair, some sites work in Otter this way, but Github and Transifex are important to Otter project and I should be able to visit those sites in Otter. This issue doesn't let Otter become my home browser.

**Comment by Emdek** [comment]
@ersi-dnd, I've posted patch for debugging that issue on forums earlier, could you please check what it outputs for these websites?
Let me know if it needs updating.

**Comment by ersi-dnd** [comment]
Yes, I remember the patch and I think I compiled it successfully into Otter for a while, but unfortunately I don't know how to read its output. Where does it put out anything?

**Comment by Emdek** [comment]
@ersi-dnd, just run it from terminal, it will output debug information there.
