### ISSUE TITLE
Keyboard shortcut profiles and menus

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#467]
IMO there are serious issues with the status of keyboard shortcuts configuration. I have these problems:
1. Some shortcuts that work (i.e. Ctrl+T for New Tab or Ctrl+W for Close Tab) are not in the files under Tools -> Preferences -> Advanced -> Keyboard. The problem: I cannot configure these shortcuts, but I need to configure them.
2. There are some very strange unconfigurable files called Default and Platform under Tools -> Preferences -> Advanced -> Keyboard. This is the place for configuration of things, so why can they not be edited? 
3. The strange files can be deleted though. The deletion of those files results in the deletion of keyboard shortcuts. This means those files contain the keyboard shortcuts, such as Ctrl+T for New Tab or Ctrl+W for Close Tab or 1 and 2 for Switch Tab. Which brings up the question: Why cannot they be edited?
4. It's possible to make copies of the strange unconfigurable files. The copies can be edited, but I don't see that they contain actions for New Tab or Close Tab. Such actions cannot be added either. Yet these actions, New Tab and Close Tab, somehow work at first by means of Ctrl+T and Ctrl+W.  Where are they so I could configure them? I don't want to simply delete them. I want to configure them.
5. In the copied shortcut file, those shortcuts that can be deleted are not deleted in reality. For example when I delete 1 and 2 for Switch Tab, 1 and 2 still continue to switch tabs. 
6. Reordering files under Tools -> Preferences -> Advanced -> Keyboard has no discernible effect. I cannot choose to switch on the file I want and I cannot choose to switch off the file I do not need. In Opera there was always one file (called keyboard setup) selected and that one file worked. Other files were there to switch from one setup to another. Very cool and perfectly intuitive. The corresponding text files were in the profile directory and could be edited by hand. How is it planned in Otter? 
7. Can I combine actions in those files in the future? For example do Copy+New Tab+Focus Address Bar+Paste with a single shortcut? Evidently not, because actions cannot be added.
8. When I search in the file under Tools -> Preferences -> Advanced -> Keyboard, it searches only the actions. It doesn't search the shortcuts in the file. In Opera's GUI dialogue, it searches for both.
9. When I assign a shortcut to an action, it doesn't warn me that this shortcut is already taken for another action. This results in conflicts, but I don't see any error messages. I simply see shortcuts not working. How will the user know about the conflicts? Is there an order of priority according to which the shortcuts work even in case of conflicts?
10. What are Action Macros? What are the differences/similarities compared to keyboard shortcuts?
11. Menu configuration GUI dialogue seems completely missing. Is it planned? Opera didn't have the ability to change the menus in GUI dialogue, but it had the ability to switch from one menu setup to another. How will it be in Otter?

In these threads I see several requests for specific shortcuts. I personally don't care what the shortcuts are. It is immensely more important to configure whatever the shortcuts are, but for this I have to be able to find the shortcut entries and configure them, change them to whatever I need. Same for menus. It works this way in Opera.

**Comment by Emdek** [comment]
I'm pretty sure that listed issues related to keyboard profiles were already fixed (for example recent addition of Status column with warnings for shortcuts) or are simply gone (Platform profile).
Multiple profiles are here to stay, but at least now Default one can be transparently overriden by custom file.
