### ISSUE TITLE
Tab settings inheritance

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#511]
Hello!

The fact that the options in the **F12** menu overwrite global settings for the current tab only is a major improvement over Opera which changed settings for all tabs.

I only wish tabs could inherit these settings. For example, if I enable JavaScript in some tab and clone that tab, both the tab and its clone have JavaScript enabled. Same with a tab that is created by middle-clicking a link. The **New Tab** should also have JavaScript enabled.

**Comment by Zero3K** [comment]
I would like to have the ability to choose if links on a page with certain settings applied had those settings applied to them when opened as new tabs.

**Comment by beastie1** [comment]
Is there any work planned concerning the [Nov 16, 2014 post](https://github.com/OtterBrowser/otter-browser/issues/511#issuecomment-63233156)? Especially the part about storing tab settings in the session file, similar to the **Images** and **JavaScript** settings in the **F12** menu.

I'm asking this because I've noticed something very annoying during a crash while searching through Google images.

Global settings are set to **No images**, so when I wanted to open an image I changed the settings for that tab to **All Images** and clicked the link. For some reason Otter crashed. When I ran it again, I had a **Network error 301** page instead and no way to get the image back.

This is just one example. But I guess the same would apply to other situations like a page you don't trust enough to have JavaScript enabled by default or one that you trust and breaks down when having JavaScript disabled by default.

This can actually have important consequences on both usability and security.

**Comment by Emdek** [comment]
@beastie1, I've prepared patch to save sessions to JSON already in October... 2015.
But it was dealing only with saving and restoring it, the main issue is, what to do with existing session files? 
Mass converting them and deleting old versions will prevent from returning to older version.

**Comment by beastie1** [comment]
You mean it will not be backward compatible? That's one major pitfall of beta phase. ;)

IMHO backward-compatibility is not reason enough to delay such a great upgrade.

**Comment by Emdek** [comment]
Now we have class to migrate configuration files, it's time to finally solve part involving preservation of settings in session file. :-)
I guess that it would be best to allow to configure it using option containing list of allowed options (defaulting to *all*) and we could add similar option for configuring what to apply to cloned tab or opened from link in existing tab.

Another topic is, what to do with idea of separate variant of <kbd>F12</kbd> menu for global settings, do we really need it? 
If yes, should it be default menu for <kbd>F12</kbd> or alternative, using something like <kbd>Shift</kbd> <kbd>F12</kbd>?

**Comment by ersi-dnd** [comment]
I like the Qutebrowser way. In Qutebrowser, any setting can be set as temporary (`-t` flag = applies for this tab/window until it closes). Is it doable? 

Opera applied F12 settings to every tab and new window that was opened from that point onwards. I have no opinion whether it should be like this. It could make sense that F12 options only apply to the tab where F12 is opened, and to its cloned tabs. 

Best: Users can configure their own F12 menu and set all options there as temporary.

**Comment by Emdek** [comment]
@ersi-dnd, per tab settings (F12 menu and actions) are currently temporary (with few exceptions), but they are going to be preserved as part of session by default.

Sure, I would like to even allow to define menus from scratch, but such stuff is blocked by extensions, as I don't want to duplicate features in incompatible way.

**Comment by beastie1** [comment]
Well, two years later, I'm still of the opinion that having **F12** change current tab settings instead of global settings is a great improvement over Opera.
Not being able to change current tab settings *easily* is very bad for usability since you may have dozens of open tabs and need different settings on each one.

IMO you don't need to change global settings every day, even less so every few hours, so I don't think it's really necessary to have easily-accessible global settings. It's easy enough to change them the classic way through **Tools > Preferences** or **about:config**.

What may be useful here is to be able to add **about:config** settings as custom buttons on the toolbar like it was possible in Opera with **opera:/button/Set preference...**. But a complete clone of the **F12** menu for global settings, I'm not so sure about that ...

> I guess that it would be best to allow to configure it using option containing list of allowed options (defaulting to *all*) and we could add similar option for configuring what to apply to cloned tab or opened from link in existing tab.

Personally I'd be satisfied with Otter just storing **all** the relevant settings, meaning pretty much everything that's in the **F12** menu.
Why making this configurable to begin with? Is there any advantage other than having slightly smaller session files? I don't know if implementing this is worth the hassle!

All the above is just my own opinion of course ...

**Comment by Emdek** [comment]
@beastie1, I guess that for now we have three votes to keep <kbd>F12</kbd> menu as is, without adding other variants.

@Chocimier was working on widgets allowing to expose any configuration option on toolbars but they need some UI polishing (to not look too random comparing to buttons).

Making list of preserved settings configurable has two reasons:
 1. we are changing previous behavior, it allows to restore it;
 2. we are going to have similar setting for tabs opened using links, so code path will already exist anyway.

*Relevant settings* is too relative, so it seems that the best option seems to be to preserve all by default but allow to fine tune it when needed.

**Comment by Emdek** [comment]
About preserving settings, perhaps it would be better to have list of **excluded** instead of **allowed** settings, since it is easier to entry single option name to exclude than compile list of all options and remove one selected (plus it will break once new options will be added). ;-)

**Comment by beastie1** [comment]
Some commit between 28 January and 3 February reversed this issue back to what it was. Now cloning a tab or opening a new tab through a hyperlink creates a new tab with all the default settings.

**Comment by Emdek** [comment]
@beastie1, all default?
Note that yesterday a lot of options got renamed and there is no migration path yet since process wasn't completed yet.

**Comment by beastie1** [comment]
Yes, with an empty profile that's only there to be filled with the defaults.

1. Open some website; Otter has images and JavaScript enabled by default
2. Press **F12**, untick **Enable JavaScript** and set **Images** to **No Images**
3. Refresh to check that it did apply and keep the changes
4. Clone the tab: the first tab is still as it should be; the new one is back to the defaults

**Comment by beastie1** [comment]
And it's the same thing with the opposite scenario. If I disable them globally, enable them in the current tab and clone it, the settings will be back to the disabled defaults in the new tab.

**Comment by Emdek** [comment]
@beastie1, yeah, it seems to be unexpected side effect of Start Page related work caused by `QWebEngineView` issues.

**Comment by beastie1** [comment]
It works fine now. Thanks!
