### ISSUE TITLE
Action: Text selection mode

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#536]
Opera was able to switch between text selection and "grab" mode. I am bringing this up for a very specific reason. Namely, Opera Presto is, as far as I know, the only engine in the world where the user was able to select text from the middle of links. 

I would be very happy if Otter could implement a text selection mode which enables text selection from the middle of links. I don't know if this userjs directly helps, but it's good that it exists :) https://gist.github.com/jonathantneal/1347070

**Comment by Emdek** [comment]
Superseded by #730.
Note that text selection in links has own ticket: #109.
