### ISSUE TITLE
Calculate readable foregound colors for dark themes

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#537]
I am very happy with the way QuickFind works, but not so with Proper Find (Ctrl+F). 

In current Mozilla (Seamonkey) Ctrl+F keeps the search open when I switch tabs. I mean, when I search for something in one tab, then I switch to a different tab, then F3 repeats the same search in the different tab. 

For this to make sense in UI, the Proper Find toolbar should be placed above Address field and stay open when tabs are switched. This informs the user that Find is still available after the tab is switched. QuickFind should stay as it is. 

Proper Find used to be the behaviour in Opera, and in all browsers really, as long as they had the find dialogue rather than the find toolbar. Now it's only in Seamonkey. 

Further enhancement idea: Make Proper Find also work in Downloads manager, Bookmarks manager, History manager, etc. There it should filter the items. This way the separate search field for those managers is optional.

**Comment by ersi-dnd** [comment]
GUI does not obey dark system theme anymore. (Hopefully this is the right place to announce this.)

**Comment by Emdek** [comment]
@ersi-dnd, works for me:
http://i2.simplest-image-hosting.net/picture/screenshot-20170201-153736.png

**Comment by ersi-dnd** [comment]
So I will never get this to work. I never understood this Qt thing. Skype obeys `qtconfig-qt4` but no other Qt program does. Qpdfview never obeys the system style. Otter occasionally does, but every update of Qt breaks it.

**Comment by Emdek** [comment]
@ersi-dnd, it should follow GTK style if you don't use Qt based Desktop Environment, perhaps you are missing GTK style plugin.
It's a question that you should ask maintainers of your distribution.

**Comment by ersi-dnd** [comment]
Maybe. But it worked in the past, occasionally. Right now I have Otter on three different computers in four different window managers (Cinnamon, Xfce, i3wm, Openbox) and the system style works in none of them.

**Comment by Emdek** [comment]
@ersi-dnd, for unknown for me reason that style plugin was moved to separate repository (in Qt 5.6 or 5.7) and my guess is that it's no longer installed by default but has to be installed manually.

**Comment by ersi-dnd** [comment]
Yes, when the issue came up (the second time, I think), I followed these instructions and they worked https://github.com/manjaro/release-plan/issues/73#issue-162521933

Now it's the third time that Otter's GUI style breaks.

**Comment by Emdek** [comment]
@ersi-dnd, yeah, I've seen that discussion.
I have no idea why they decided to move it, probably they didn't want to have GTK dependency in QtBase or something like that.
Anyway, simply installing that plugin should be enough.
You can force Qt style in Preferences -> Advanced  -> Appearance, without installing extra tools.
Note that AppImage shouldn't be affected since it uses Qt 5.6 (at least it will be using it from now on).

**Comment by ersi-dnd** [comment]
Ah, I found the solution. The plugins have been moved (again) and Arch documentation is already there to help me out: 

> Note: QGtkStyle has been removed from qt5-base 5.7.0 [1] and added to qt5-stylepluginsAUR 

https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications#QGtkStyle

Sorry for bothering you with this.

**Comment by Emdek** [comment]
We are going to switch away from using color for informing about find text result so the last use case of this ticket will be gone soon.

**Comment by beastie1** [comment]
> We are going to switch away from using color
How will it be then?

**Comment by Emdek** [comment]
@beastie1, final version is supposed to use numbers like Chrome, but since for now backends can only tell us that there are results or not it will be textual.
