### ISSUE TITLE
Notes feature

### ISSUE THREAD

**Issue by weems** [OtterBrowser/otter-browser#559]
Otter should include in the features of the sidebar the Notes feature of Opera 12.16. As of Version 0.9.04 Week 48 Notes is not available in the sidebar. 

![2014-12-07 17_13_07-new issue emdek_otter - otter](https://cloud.githubusercontent.com/assets/470705/5333148/b7d2382c-7e66-11e4-9b5a-98a8f3d86e13.png)
Otter should include in the features of the sidebar the Notes feature of Opera 12.16. As of Version 0.9.04 Week 48 Notes is not available in the sidebar.

**Comment by Emdek** [comment]
Option for rich text can be added in future.

**Comment by ersi-dnd** [comment]
Notes are ready? How to enable them?

**Comment by Emdek** [comment]
@ersi-dnd, just add them to sidebar or use *about:notes*. ;-)

**Comment by ersi-dnd** [comment]
I tried all that. I also tried adding the menubar.json, uninstalling and reinstalling, but nothing.

In the end I uninstalled Otter, hunted the system for leftover files, deleted them, and then reinstalled. Now it works. 

Looks like my Otter installation had gone confused when I built packages on my own meanwhile. I didn't use cmake with the proper switch. But I think I fixed it now. There are bigger toolbar buttons now and Notes are visible. Thanks :)

**Comment by beastie1** [comment]
@ersi-dnd
>> There are bigger toolbar buttons now
Do you like them this way or it bothers you? Personally I like them smaller so I used **iconSize** in **toolBars.json**:
```
...
		"identifier": "NavigationBar",
		"title": "Navigation Bar",
		"iconSize": 16,
		"actions":
		[
			"GoBackAction",
			...
```

**Comment by ersi-dnd** [comment]
Thanks for the tip, beastie :)

**Comment by ersi-dnd** [comment]
Instead of bloating the other toolbars, it seems to me that the status bar would gain from bigger size.

**Comment by weems** [comment]
I still havent figured out how to turn it on in week 64. about:notes took me to a blank page.

**Comment by ersi-dnd** [comment]
@weems 

Notes are available from weekly 65. If your installation is playing tricks on you, uninstall completely and then reinstall.
