### ISSUE TITLE
Ask what to do when file download is requested

### ISSUE THREAD

**Issue by AlexTalker** [OtterBrowser/otter-browser#58]
Added a enu action for download(open, donwload, downolad where) and button 'copy link in buffer', really support some sites, where js redirect you to file and you don't support copy link before press button.

**Comment by opticyclic** [comment]
The temporary_downloads is useful if I have a web mail client such as Outlook Web Access open and I want to open an attached Word document.
The default behaviour in the fat clients I have used is to open the Word document directly and not to ask where to save it.
In that resepct using the temporary_downloads is obvious for end users as they don't expect to have to save the file somewhere else.

**Comment by Emdek** [comment]
When user chooses Open then transfer stays as temporary file, deleted when removing transfer or closing browser.
Also note that right now use of Open might end up with crash, I'm still investigating this issue.

Hopefully I'll add configuration for file types in near future.

**Comment by beastie1** [comment]
Thanks for the feature. It's even better than Opera's hehe!
