### ISSUE TITLE
Open session in current window

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#582]
http://cdn5.howtogeek.com/wp-content/uploads/2012/07/20_manage_sessions_dialog.png

This is how Otter's session management dialogue looks like right now. I have already requested for more common-sense features in #577 Here's one more request.

There's the option "Open tabs inside current window". I would like this option to be sticky. By "sticky" I mean that once I have checkmarked the option, it should stay so in the profile. When I close the browser and open it again, I want it to stay checked. Any time I open the dialogue, I want to see it checked. When I open sessions from the session management dialogue or from the menu, the sessions should behave as per that option. 

Right now it's possible to open sessions inside Otter window only when I check it for the specific session every time. That's why I would like this option to be sticky.

**Comment by ersi-dnd** [comment]
Until you introduce more complicated enhancements, I would very much appreciate if you made the current "Open in current window" checkmark behave sticky.

**Comment by Emdek** [comment]
@ersi-dnd, after testing some implementations I've decided to go for simpler variant.
There will be global switch, defaulting to current behavior (do not reuse current main window), which can be switched only in *about:config* (one time message box with question appears to be not feasible after some testing).
It will affect state of checkbox in manager and opening sessions using menu.
I might revisit idea of setting this per session in future.
