### ISSUE TITLE
Some things that don't work on about:- pages

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#604]
a. CloneTab does not work on about:- pages.
b. Find and QuickFind don't work. I think Proper Find should work everywhere globally (that's what makes it Proper Find). 
c. There's a search field on some about:- pages. Is there an action so we could set a keybind to access the search field?
d. Delete, Cut, and Select All by keybind don't work for the items on about:- page. But Copy works in a way.
e. Drag&Drop doesn't work.

**Comment by Emdek** [comment]
It's related to #366 and we have other related tickets out there, I'm considering opening one bigger one to track progress as all managers share enough code to add one feature in all of them in single commit.

**Comment by Emdek** [comment]
Superseded by #771.
