### ISSUE TITLE
Win Weekly 51 doesn't remember window size on restart

### ISSUE THREAD

**Issue by resbro** [OtterBrowser/otter-browser#607]
Or state of sidebar (open / Closed)

**Comment by justintimberland** [comment]
What is the state of affairs with this issue?

**Comment by Emdek** [comment]
@justintimberland, waiting in queue.
I'll take a look at this issue after completing some other tasks first, maybe later this week.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
A workaround is to start otter with a command line option, eg:
-geometry 800x740

**Comment by Emdek** [comment]
@ThebestwaytodesignJoinGitHub, we don't have such options built-in, if there are any then from Qt itself:
http://doc.qt.io/qt-5/qguiapplication.html#QGuiApplication

**Comment by ThebestwaytodesignJoinGitHub** [comment]
otter-browser.exe -qwindowgeometry 1000x800 makes it on windows
