### ISSUE TITLE
MacOS X packages

### ISSUE THREAD

**Issue by Emdek** [OtterBrowser/otter-browser#622]
We need someone to become maintainer of MacOS X packages.
While it is possible to use Otter there we don't have official packages so far.
Also we would need someone to test out and report possible issues specific to that platform.
It would be also nice to find someone to create platform integration for MacOS X (native notifications, listing of associated applications for given MIME type etc.).

Use of virtual machine is last resort.

**Comment by kboratynski** [comment]
I offer myself for packaging.

**Comment by BugraK** [comment]
Now I am making Mac OS X packages.
