### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by Katarn** [OtterBrowser/otter-browser#63]
I think we need now share GUI and QWebKit-parts into separate streams. For example, now, when I close the tab with heavy HTML/JS/CSS, there is a noticeable lag with its destruction and frozen whole GUI.

Quick fix might be:
1. Switch to the last open tab.
2. Hide closed tab widget in tabbar.
3. Destroy QWebKit.
4. Destroy closed tab in tabbar.

A similar delay occurs when you create a new tab. If in the future will be the animation interface, the delay will be even more noticeable. Therefore I propose to consider the division of GUI and QWebKit-parts now.

This is one example, and of course, over time, they can be much more.

**Comment by vinnitu** [comment]
on Windows7 Pro x64 my app with QWebEngineView very very slow, but on other 2 machines win win8 x64 it's ok, why? somebody know?

**Comment by Emdek** [comment]
@vinnitu, it might depend on GPU drivers etc.

**Comment by vinnitu** [comment]
I am not sure, but if Chrome Browser works without delays it is not GPU

**Comment by Emdek** [comment]
@vinnitu, that is a bit more complex topic, see:
http://qt-project.org/wiki/Qt-5-on-Windows-ANGLE-and-OpenGL
