### ISSUE TITLE
After 1-2 hours of browsing... empty menus

### ISSUE THREAD

**Issue by SJ-Diamond** [OtterBrowser/otter-browser#632]
Hi :)

Some very strange thing with the latest weekly: After around 1-2 hours of browsing to various pages suddenly right mouse context menu got blank and menu items only appear if i move with the mouse over the context menu items. Same also for example for the options menu. Have attached 2 pics.

I also was not able anymore to choose a picture to upload here in github because file dialogue was white and blank, similar like the 2 pics beyond.

Appears after some random browing time with random webpages visited, happes already the second time, so it can be reproduced.

Got no error or crash messages. Operating System is Windows 8.

![problem](https://cloud.githubusercontent.com/assets/1733238/5589247/c245258c-911a-11e4-965c-efadb52aa560.jpg)

![pref](https://cloud.githubusercontent.com/assets/1733238/5589251/d4ff1f02-911a-11e4-9314-b52dea9da87e.jpg)

**Comment by Emdek** [comment]
@SJ-Diamond, could you please try to reproduce that using 32 bit build?

**Comment by SJ-Diamond** [comment]
Testing the newest Otter Weekly 32 bit - Seems like it is only a problem
with the 64 bit variant, so far no empty menus under 32 bit, using if for
over 2 hours now.

2015-01-01 18:18 GMT+01:00 Michał <notifications@github.com>:

> @SJ-Diamond <https://github.com/SJ-Diamond>, could you please try to
> reproduce that using 32 bit build?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Emdek/otter/issues/632#issuecomment-68492083>.
>



-- 
---------- Wikus Van De Merwe was right - Fookin' Planet!!! ----------

**Comment by Emdek** [comment]
Closing as according to reporter it doesn't happen anymore, can be reopened if it would show up again.
