### ISSUE TITLE
UI for mouse gestures

### ISSUE THREAD

**Issue by Emdek** [OtterBrowser/otter-browser#633]
This ticket will be used to track progress for UI for mouse gestures, both configuration page and helper shown when performing gestures.
It may also be also used for adding support for additional gestures, like generic flipping and diagonal dragging.

**Comment by Katarn** [comment]
http://www.opera.com/help/tutorials/gestures/

**Comment by beastie1** [comment]
This is some minor request, but I think double-clicking a profile should open the edit dialog box. I guess this should be the case for keyboard profiles too.
