### ISSUE TITLE
[Windows] Facebook crash with custom user agent

### ISSUE THREAD

**Issue by Pointer1992** [OtterBrowser/otter-browser#634]
Witaj Emdek 
Ja ponownie chce uderzyć w temat problemu z facebookiem pomocne okazuje się kombinowanie z identyfikatorem przeglądarki z zaawansowanych ustawień opcja sieć 
z wyjątkiem maski google chrome 28 gdzie facebook nie ładuje się wcale
na pozostałych się ładuje ale chat się nie otwiera 
ja dopisałem user agent id po comodo dragon to się chat otworzył ale zrobiłem 3 ruchy kółkiem myszki i zaliczyłem crash 

[code]
Nazwa zdarzenia problemu:	APPCRASH
  Nazwa aplikacji:	otter-browser.exe
  Wersja aplikacji:	0.9.0.4
  Sygnatura czasowa aplikacji:	042d0770
  Nazwa modułu z błędem:	Qt5WebKit.dll
  Wersja modułu z błędem:	5.4.0.0
  Sygnatura czasowa modułu z błędem:	6537746e
  Kod wyjątku:	c0000005
  Przesunięcie wyjątku:	00d819c0
  Wersja systemu operacyjnego:	6.3.9600.2.0.0.256.48
  Identyfikator ustawień regionalnych:	1045
  Dodatkowe informacje 1:	5861
  Dodatkowe informacje 2:	5861822e1919d7c014bbb064c64908b2
  Dodatkowe informacje 3:	a10f
  Dodatkowe informacje 4:	a10ff7d2bb2516fdc753f9c34fc3b069
[/code]

**Comment by Emdek** [comment]
Witam

Tak, ale dodatkowo trzeba uważać na zoom, gdy element przestaje być widoczny to następuje rozłączenie, tak donoszą użytkownicy na forum.

A co do wywrotki, czy jest powtarzalna?
Bo taki opis błędu jedynie sugeruje, że to raczej nie u nas bezpośrednio.

Z innej beczki, obowiązuje tu język angielski, choćby i łamany, z pomocą Google Translate. ;-)

**Comment by Pointer1992** [comment]
Tak facebook się otwiera, (marginesem tak długo że przeglądarki się zawiesza na chwilę) i robie między 3 a 4 ruchy kółkiem myszki i przeglądarka się wysypuje z komunikatem program otter browser przestał działać i to wszystko na masce comodo dragon 

Filmy z youtuba zaczeły działać tylko jak ktoś ma ustawione odpalanie wtyczek na rządanie to nie pojawia się ten szary przycisk do odpalania wtyczki chyba ze masz ustawioną maskę Firefoxa bo na tej masce to jest 

to wszystko dzieje się na Windowsie 8,1 Update 1 X64



So facebook is open, (margin so long that the browser hangs for a while) and I do between 3 and 4 moves the mouse wheel and the browser is crashing with a message otter browser program has stopped working and it's all on the hood comodo dragon

YouTube videos had already begun to work just like anyone has a set of plugins on-demand firing it does not appear that the gray button for firing the plug unless you have set Firefox as a mask on the mask is

It all happens on Windows 8.1 Update 1 X64

Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/532.5 (KHTML, like Gecko) Comodo_Dragon/4.1.1.11 Chrome/4.1.249.1042 Safari/532.5

**Comment by Emdek** [comment]
@Pointer1992, cannot reproduce that crash using Windows 7 32 bit.
It might be related to  #548 (but should occur at different time) but it looks more like something random in QtWebKit itself. 
We could try to debug it but you would have to install Qt SDK to get debugger...

In case of YT, when change of user agent helps then it means an issue with site itself. ;-)
In such cases the only solution is to continue masking for that page (for example set it in Website Preferences).

**Comment by Pointer1992** [comment]
Good we will try to install Qt SDK and, you and try to catch the Buga :)

**Comment by Emdek** [comment]
@Pointer1992, OK. :-)
Short instructions, after installing Qt SDK you need to open *otter.pro* with QtCreator, it should show dialog asking to configure it, showing release and debug build as options.
We should go for debug one, after accepting that dialog you will need to select debug build by clicking on computer icon in bottom left corner and select Debug in Version column.
After that you just need to click that green player like icon, but the one with bug symbol on it.
Then it will start Otter in debug mode (it might take some time, depending on your hardware, it will be normal if it will work slower than usual) and try to reproduce that issue.
When crash will occur just click OK (or similar) button in dialog and then take screenshot of bottom pane (please extend first two columns, they might be too narrow) and post here.
After that you can use red square button to quit Otter.

If you have additional questions then it would be best to ask them on our IRC channel:
http://irc.lc/freenode/otter-browser-pl

**Comment by Pointer1992** [comment]
Unfortunately, I don't I will you złapac this Buga :( what whithersoever the ends zawiechą to reset

**Comment by Emdek** [comment]
@Pointer1992, well, it is enough to tell that it's something in QtWebKit itself (it crashes in *QRawWeb[...]*, whatever it is exactly, it's not part of our code base).
But it's not enough to report upstream yet.
If you have some time then please try again, close that dialog with OK and then resize column "Funkcja" and resize that panel vertically, so it will show more entries.

**Comment by Pointer1992** [comment]
Okej attempts to once again, but I will do this tomorrow because today no longer council dam

**Comment by Pointer1992** [comment]
Interestingly this bug affects versions on 32 bit systems because, as again updated my Ottera for beta 4 was not up to 64 bits for a moment so I upgraded to version 32, now I went back to 64 and i can not force the Buga on Facebook
