### ISSUE TITLE
One instead of multiple save buttons in about:conf?

### ISSUE THREAD

**Issue by uahim** [OtterBrowser/otter-browser#635]
happy new year and many thanks for beta 4!

as I had to delete otter.conf so beta 4 was able to save all settings again it occured to me how annoying it is to save each and every single setting in about:conf. is there any chance to replace individual save buttons with one, global, at the bottom of the page or so? or is this just how QtWebKit is built?

**Comment by Emdek** [comment]
Happy New Year. :-)

No, this is our part, we don't use HTML for special pages.
I can consider that, as I'm planning to add some small improvements there, at least context menu to copy key name or value.

**Comment by uahim** [comment]
ah, cool, whatever works :)

as for the non-saving-settings behavior, my bad, only the tab bar position is not being saved on Win32, I'll open an extra issue for that

**Comment by Emdek** [comment]
@uahim, don't bother, to be done as part of #31.

**Comment by lollox** [comment]
About config manager here there is some other stuff:

1. The actual context menu shows the "lock toolbars" item ... this is quite useless and non-sense here, don't you think so?

2. An Import/Export button could be very interesting here, so the user can save its preferences within the GUI

3. With the suggested "Save all" button we could consider also stuff like "Discard all changes" and "Restore defaults"

**Comment by Emdek** [comment]
@lollox , that menu belongs to main window itself and it is shown because nobody intercepts context menu event.
Import and Export? I don't see real use case here.
But at least Restore Defaults might be handy.
Discarding could be done by simply closing page without saving changes.
In future it would be nice to have support for undo, redo and maybe save (as save all, not export).

**Comment by lollox** [comment]
About Import/Export is useful to rapidly export your changed preferences in a single file and then be able to reimport them (for example in a second PC, or after a clean install of the PC, etc) with a single click .... Useful for the average user that doesn't like to mess with INI files ;)

About Discard, is the fastest way to reset all changes without closing/reopening the tab

However these are only some ideas to make the about:config more handy, not a MUST for sure :)
