### ISSUE TITLE
Edit bookmark?

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#638]
This menu item does not work well at all. It always opens a new bookmark dialog box for me. It sometimes shows up on pages that I have not bookmarked (i.e. the bookmarks star is not yellow. I have bookmarked something on the same domain though). 

Not just the bookmark detection is wrong, but the functionality as a whole.

**Comment by Emdek** [comment]
I've seen this earlier today but now I can't reproduce that.
It's totally separate from icon in address field (this one checks against current text in address field) by checking if URL is bookmarked when WebKit tells us that current URL changed.
I've added some debug output and it shows correct values, maybe I'll be able to catch it later.
