### ISSUE TITLE
Not working music playing on Yandex.Music

### ISSUE THREAD

**Issue by MazheM** [OtterBrowser/otter-browser#670]
I try to listen music on Yandex.Music service (http://music.yandex.ru) and it doesn't work. Nothing happens when click on play button. Info: Win 8.1 x64, Otter 0.9.05 and Beta 4.
Errors in console:
![console log](https://cloud.githubusercontent.com/assets/5282790/5841751/572641ea-a1b0-11e4-96bd-fd6431445009.png)

**Comment by Emdek** [comment]
Could you please check if directly opened MP3 files work for you?
It may be a missing codec or missing feature in QtWebKit.

**Comment by MazheM** [comment]
When i try open some mp3 file on other site directly Otter crashes and i don't know how to watch logs or something like that.

**Comment by Emdek** [comment]
@MazheM, that might suggest something wrong in QtMultimedia (we don't handle media directly at all), are you using some kind of codecs pack?
QtWebEngine has "advantage" (well, makes it harder to extend built-in set...) of shipping basic codecs (but not MP3), you could try that backend when we will be ready to ship experimental build for Windows (it works just fine under X11).

**Comment by MazheM** [comment]
I tried without codec packs and after that install K-Lite Codec Pack but still same - music don't playing and direct opened files crashes Otter.

**Comment by Emdek** [comment]
@MazheM, does it behave the same way with recent Qt releases?

**Comment by MazheM** [comment]
@Emdek, yeah, its still does not work.

**Comment by Emdek** [comment]
@MazheM, I've done some research and it appears that there is no way to ship codecs for QtWebKit, at least not without triggering separate installers etc...
In case of QtWebEngine backend (testing packages will be available for weekly `#79`) it might work after replacing `ffmpegsumo.dll` with the one shipped by Chrome or Opera (it can be obtained separately, form sites providing missing DLL files).
We will need to do some research to check if we need permission to redistribute them.

Closing it as upstream QtWebKit issue for now.

**Comment by MazheM** [comment]
I have not tested Otter for a long time, but in version 0.9.08 service is working properly. Win 10

**Comment by Emdek** [comment]
@MazheM, there was missing DLL, we found out which one recently.
