### ISSUE TITLE
Certain characters don't appear at all (📶)

### ISSUE THREAD

**Issue by jernejs** [OtterBrowser/otter-browser#675]
Otter doesn't display certain Unicode characters at all for me (not even a box/placeholder). Example here: https://community.imgur.com/t/why-do-people-get-so-sensitive-when-i-give-just-state-facts-like-the-buggy-ness-of-windows-8-1/2509/6 (there should be the character I also used in the title at `name your WiFi "📶"`, but the quotes appear empty).

This happens at least with today's Win64 build (weekly 56, WebKit 538.1, Qt 5.4.0)

**Comment by Frenzie** [comment]
Confirmed on Debian Jessie x64 compiled against Qt 5.4. This doesn't happen in Qupzilla (with Qt 4.8.6).

**Comment by Emdek** [comment]
Works fine here, Qt SDK 5.4, from official site.
Appears to be packaging issue in Debian, maybe something wrong with ICU, HarfBuzz etc.?

**Comment by The-Compiler** [comment]
FWIW, I get the same issue here on Archlinux with the packaged Qt 5.4

**Comment by Emdek** [comment]
@The-Compiler, is there any upstream report already?

**Comment by The-Compiler** [comment]
I don't think so. It shows up as a box everywhere else by the way, e.g. if I copy it into the address bar.

**Comment by Emdek** [comment]
@The-Compiler, uhm, then I'll report it later, maybe trying first with other versions (5.2, 5.3 and 5.3 from packages).

**Comment by Frenzie** [comment]
@Emdek 
It occurs both in Qt 5.3 (comes with Debian Jessie) and Qt 5.4 (the SDK). However, the placeholder does show up in the titlebar, addressbar, etc. It's just on this very page that it doesn't.

**Comment by Emdek** [comment]
@Frenzie, uhm, maybe it's indeed something related to HarfBuzz?
Like that time when it caused crash only on some distros (5.2)?

**Comment by Emdek** [comment]
BTW (Qt 5.4, QtWebKit backend, not QtWebEngine):
http://simplest-image-hosting.net/png-0-bn2656

**Comment by jernejs** [comment]
[Here](https://eternallybored.org/misc/uni.html)'s the page, and [how it looks](https://eternallybored.org/misc/uni.png) in different browsers.

**Comment by Frenzie** [comment]
@Emdek I'll backport 0.9.37-1 from experimental tomorrow to see if it helps (assuming no complications). Currently on Jessie's 0.9.35-2.

**Comment by Frenzie** [comment]
0.9.37 doesn't seem to make a difference.
