### ISSUE TITLE
Delete All cookies

### ISSUE THREAD

**Issue by landroni** [OtterBrowser/otter-browser#677]
Please provide a `Delete all` cookies in the Cookies Manager. This very useful, very often, and avoids having to select all and then click `Delete`. Other browsers (e.g. Midori) provide such a button.

**Comment by uahim** [comment]
if you are using the classic file menu bar ('file, edit, view, etc' -use ALT+F11 to toggle it) you can do just do this via history | clear history and unchecking all boxes but cookies. the "menu" icon is missing this option mysteriously, I just noticed.

but I agree with you that this button should also be on the about:cookies page or in the sidebar

**Comment by resbro** [comment]
Cookies is theone about: page that you can "select all" from menu

**Comment by uahim** [comment]
@landroni & @resbro not sure if this is what you mean, but I just discovered that a simple right click on an empty white space on about:cookies leads you directly to the "clear history" dialog

**Comment by landroni** [comment]
Hmm, "Clear history" is nice, but its goal is somewhat different: it proposes you to delete quite a few other things, and this may not be what the user wants to do. IMO a dedicated "Delete all" cookies button would be very useful.

**Comment by Emdek** [comment]
@landroni, it doesn't make much sense to have them both in single menu, so we should use such Delete All also in other places, maybe except history viewer, where it makes more sense that way.
It should be shown in all cases, I guess, not just when there is no entry under cursor.

**Comment by landroni** [comment]
If understand you correctly, what you mean is to put a `Delete All` cookies button in the Cookies Manager and have it always enabled, whether a cookie is currently selected or not. If so, this is what I was indeed proposing...

**Comment by Emdek** [comment]
@landroni, I would prefer context menu action for now, later we can try something more flexible, like approach for global actions, but no promises yet.

**Comment by landroni** [comment]
A context menu action would work neatly! As long as the functionality is there, and can be easily accessed, it's just as swell. 

My only issue with `Clear History` is that this dialog may be used routinely for something different than simply deleting all cookies... So a `Delete all cookies` solution sounds like a good idea to me...

**Comment by Emdek** [comment]
@landroni, sure, as dedicated action, as noted earlier. :-)
