### ISSUE TITLE
always reuse empty tabs 

### ISSUE THREAD

**Issue by landroni** [OtterBrowser/otter-browser#678]
One of the most sane behaviors in Opera 12 (and probably it was better in earlier versions) was that empty tabs were treated as such. 

For instance, if you open a new tab and then access a bookmark, the bookmarked will be opened inside the empty tab (and not open a new tab next to the empty tab). If you have an empty tab opened and search for something from the toolbar, then the search will occur within the empty tab. 

And the third use case, which Otter already respects, is that when you Paste and Go in an empty tab, the URL will be entered in the existing empty tab. 

Of course, if the tab is already displaying a web page, then the "Reuse current tab" option should be respected. But otherwise, empty tabs should always be reused.

**Comment by Emdek** [comment]
Uhm, it should work like that currently, any specific issue?

**Comment by resbro** [comment]
Already works like that for me!

Win 7 x 64

**Comment by landroni** [comment]
Two issues (latest GIT on Ubuntu Linux): 

* if I have an empty tab opened and then access a bookmark, the bookmarked website will be opened in a new tab (next to the empty tab)
* if I have an empty tab opened and search for 'something' from the toolbar, then the search will occur in a new tab (next to the empty tab)

In both cases the empty tab is not being reused.

**Comment by vapaamies** [comment]
@landroni is right.
