### ISSUE TITLE
All site selection when Ctrl+A in address field

### ISSUE THREAD

**Issue by MazheM** [OtterBrowser/otter-browser#680]
Sometimes when i try to select url in address field and do it with Ctrl +A, Otter select URL and all text on site. I do not know exactly how to do it again but i happend already twice. Win 8.1 x64, Otter 0.9.05
![Otter selection](https://cloud.githubusercontent.com/assets/5282790/5965782/c64308a0-a80f-11e4-8222-f9ea01cbed2f.png)
UPD: And have some problem with Ctrl+V in address field, sometime text insert in some input on page and sometime nothing happend.

**Comment by Emdek** [comment]
Uhm, cannot reproduce so far (well, at least not under X11), maybe someone will find a reliable way to do that.

**Comment by MazheM** [comment]
@Emdek Ok, I found a way to reproduce the problem, but it does not always work.
1. Open otter-browser.org for examo\ple.
2. Close browser and open it again.
3. Go to address field and press Ctrl+A.
Maybe its only Windows problem(On work notebook with Vista(Yeah...) its simple to reproduce)

**Comment by Emdek** [comment]
@MazheM, go to address field by clicking on it, using Tab or keyboard shortcut? ;-)

**Comment by MazheM** [comment]
@Emdek By clicking on it.

**Comment by Emdek** [comment]
@MazheM, thanks, I'll try to reproduce it using Windows 7 later this week.

**Comment by Emdek** [comment]
@MazheM, no luck with catching it so far...
One question, is text cursor blinking in address field after clicking it?
Maybe text gets selected but focus is not set on that widget?

**Comment by MazheM** [comment]
@Emdek  Ok, on Win 8.1 that's hard to reproduce, but i'm recorded this when was at my work: [youtube](http://www.youtube.com/watch?v=UxOSKVy3rkw)

**Comment by Emdek** [comment]
Superseded by #826.
