### ISSUE TITLE
some adblock lists are broken (weekly 56)

### ISSUE THREAD

**Issue by codespotx** [OtterBrowser/otter-browser#685]
in dialog tools -> content blocking ..

when selecting "German" the according list is not downloaded.
(opening the dialog again shows no "last update")

when downloading and adding the file "easylistgermany.txt" manually the checkbox  selection will be ignored (opening the dialog shows "last update" but checkbox is gone).

needless to say that the according filter does not work.
6 out of 15 lists seem to be "problematic" and show this behavior.

testing environment: otter weekly 56 (32 and 64 bit), windows 7 64, QT 5.4.0 (isn't that defined by otter distribution?)

**Comment by codespotx** [comment]
tested weekly 58, 64bit, QT5.4.0 with no success.
new behavior is worse: not a single list is downloaded.
I would reopen this issue, but I can't...

**Comment by Emdek** [comment]
@codespotx, it's unrelated.
Updates are temporarily disabled until widget to set update interval will be ready (it's almost ready).

**Comment by Felipefpl** [comment]
there is one list that needs to be added for testing https://raw.github.com/rbrito/easylist-ptbr/master/adblock-rules.txt it's the brazilian one.

**Comment by codespotx** [comment]
still broken in weekly 59 :-/
whatever "other" thing is almost ready, it should have a ticket to track it properly.
