### ISSUE TITLE
Show Tabbar: more options

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#690]
Thanks for the option to switch off tabbar, but it needs more options. In Opera there's an option like "Show only as needed" which hides tabbar when only one tab is open. This is a good option.

Moreover, I don't see the option in about:config. I think that it's a good policy to have all options (I mean absolutely all options) in about:config, so that when the user cannot find something in menus or dialogs, he will be sure to find it in about:config.

**Comment by Emdek** [comment]
Sure, it's all part of #31. ;-)
We won't use main configuration file for this purpose, it will be done as profiles, like keyboard shortcuts.
