### ISSUE TITLE
[Windows] Passing url to otter-browser.exe (via command line etc) results in resized window

### ISSUE THREAD

**Issue by uahim** [OtterBrowser/otter-browser#691]
as I'd often like to pass an entire from Opera to Otter, I tried via command line or shortcut
`otter-browser.exe %url%`
where %url% is a well-formed, working url without any special characters
this results in Otter loading the url, but resizing itself from maximised to a small window, centered on screen
is this a bug? glitch?

it may be related in some way to this (in the meaning that it still/again doesn't work)
https://github.com/OtterBrowser/otter-browser/issues/337

**Comment by Emdek** [comment]
Does it apply to existing or to new window?
In case of the latter try to disable *Interface/MaximizeNewWindows* in **about:config**.

Are you using 32 or 64 build? AFAIK both use different APIs, AFAIR one had some issues, I'll ask @bajasoft.

**Comment by uahim** [comment]
existing window, Win32
