### ISSUE TITLE
Additional transfer tab opened on program start

### ISSUE THREAD

**Issue by Stullemon** [OtterBrowser/otter-browser#692]
I have a habit of keeping the Transfer tab open. Whenever I close the browser (or it crashes) and I reopen the browser, I get a new Transfer tab right next to the one from the last session. If I do not close the additional one I get a third one upon closing and opening Otter.

This happens with the latest upstream build (also previous weeklies) on Linux Mint 17.1.

I did not find a similar issue. Please give me a hint, if you need any other information.

**Comment by pmattern** [comment]
I'm seeing something similar on a profile where "Startup behaviour" is set to "Continue previous session" and five windows containing five to nine tabs each are opened that way.
Here, the transfer tab sometimes gets opened upon launching Otter for apparently no reason in two of those five windows. I'm sure it wasn't opened when exiting Otter before. Couldn't nail down the exact conditions when this happens, though.

**Comment by Emdek** [comment]
Looks interesting, if your session doesn't contain anything private then best way to reproduce it seems to be sending a copy to me (email address is in header of source code files).
My main suspect is `MainWindow::transferStarted()` being called each time when session is restored, which should be triggered after accepting request to download file.

**Comment by resbro** [comment]
I've noticed this happening in windows (7) also. Doesn't happen every time, but oten enough to notice it.

**Comment by Emdek** [comment]
That issue is odd, can't reproduce on my Linux machine, but it is reproducible on Windows 7, but only when built with mingw, not msvc.
Uhm, I'm using clang, maybe it is somehow connected to compiler, no idea.

**Comment by Stullemon** [comment]
Well, if it makes any difference, I am using a Linux Mint Mate 17.1 OS. All packages are up-to-date. The kernel I am using is 3.13.0-37. For building I am using the commands provided in the install document in the repository.

Should I send you the binaries I built?

**Comment by Emdek** [comment]
@Stullemon, there are some options to be checked first, it seems that there are two separate issues, almost for sure ``MainWindow::transferStarted()`` is called for some reason when restoring session, with is wrong.
I'll have more time to debug it on Saturday.
