### ISSUE TITLE
Two issues with "All settings" in Preferences dialogue

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#694]
**Problem 1**

1. Select Manage search engines from the toolbar.
2. Select "All settings" in the dialogue.
3. The problem: Crash

**Problem 2**

1. Go to the Preferences dialogue
2. Select "All settings" 
3. about:config opens up in the background
4. Select "All settings" again and again
5. More and more about:config pages open up

**Comment by ersi-dnd** [comment]
Besides, I thought you didn't want about:config anywhere prominent. Now it's prominently placed and does not work right. What's the code for the button so I could make a menu item of it like I always wanted?

**Comment by Emdek** [comment]
I was unable to reproduce crash, but this should ensure that it won't happen.

**Comment by Emdek** [comment]
And apparently the issue is more complex.
