### ISSUE TITLE
Option to not show close button on tabs + common MDI button to close active tab

### ISSUE THREAD

**Issue by komoku** [OtterBrowser/otter-browser#70]
Many old Opera users like me like to unset the Opera setting to "show close button on each tab". The effect of this (at least under Windows) is that said button is not shown, but instead, we get the standard MDI control to close the active tab. This has the advantage of being always in the same position, and also coincident with other MDI and TDI programs that have the closing control in the same position, which helps efficiency because we have muscle memory of where it is.

Here is an image of how it looks in Opera:

![button](https://f.cloud.github.com/assets/6391291/1902387/9d54d59c-7c71-11e3-9c51-8edf7cfb590b.png)

It would be great to have this as an option in Otter as well.
 
(I already told you about this on IRC, but I know it's always useful to have all the feature requests filed, or at least I like that as a developer...)

**Comment by Emdek** [comment]
It's already possible to have single tab close button as part of #31 (by adding *CloseTabAction* to existing or new toolBar) combined with *TabBar/ShowCloseButton* option.
There will be also dedicated MDI control widget as part of #212.
