### ISSUE TITLE
Menu button and discarding menubar

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#700]
Hi all,
I just noticed a possible cornercase issue regarding menu button - 
with Menu bar disabled and Menu button shown, I just tried to discard Toolbars: [ ] Show tabbar
... and was surprised, that it worked just as advertised - the tabbar including the menu button disappeared and couldn't be brought back easily. Before digging into config files, I fortunately somehow remebered the shortcut Alt+F11 and was able to recover the tabbar including the menu button.
Could possibly such items, which are important for the application control, be added to the context menu? - currently there is only Fullscreen toggle, i believe, the menu bar (or possibly tabbar) toggles would be useful here - at least in case they are discarded and cannot be recovered in a straightforward way.
(using Otter 0.9.05 weekly 57, windows 7)

  regards,
     vbr

**Comment by lollox** [comment]
I think the main problem here is that actually in Otter tabbar and titlebar are not merged and the Menu button is placed as a button in the tabbar

IMHO we should merge tabbar and titlebar so if you "hide" tabbar you really simply hide the tabs and all the related stuff, but the Menu button is not touched at all (and however the Menu button should be placed an a own "toolbar" like in Opera in which you can put all buttons you want and move it where you want)

My idea however is heavily dependent on the "rewrite" of the whole tabbar I suppose ( @Emdek wrote some issue on it if I recall well )
