### ISSUE TITLE
Crash on Save by URL

### ISSUE THREAD

**Issue by VSHY** [OtterBrowser/otter-browser#701]
STR:
1. Right-click on any link.
2. Pick "Сохранить по ссылк..." (this label on russian) from context menu.
3. Click Cancel in "file-dialog".
Result: crash.

Environment: Win7 x64, Otter 32-bit #57-#58 portable.

P.S. The correct name of the menu item: "Сохранить по ссылке..."
"Show Tabbar" (en) = "Показать панель вкладок" (ru)

**Comment by Fot0n** [comment]
Есть такое, да.

**Comment by Emdek** [comment]
It appears to be upstream issue, there are some closely related bug reports:
https://bugreports.qt.io/browse/QTBUG-33119
https://bugreports.qt.io/browse/QTBUG-41416

**Comment by Emdek** [comment]
Superseded by #899.

**Comment by VSHY** [comment]
The crash is still present.
Win7 64-bit, in otter-browser-win32-weekly84.zip or otter-browser-win32-weekly84-qtwebengine.zip.

---
Exception Analysis
---

*** WARNING: Unable to verify checksum for C:\Portable\Otter\Qt5Core.dll
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for C:\Portable\Otter\Qt5Core.dll - 
*** ERROR: Module load completed but symbols could not be loaded for image00000000`01380000
*** WARNING: Unable to verify checksum for C:\Portable\Otter\Qt5WebKit.dll
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for C:\Portable\Otter\Qt5WebKit.dll - 

FAULTING_IP: 
ntdll32!RtlpBreakPointHeap+23
77b6087c cc              int     3

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 0000000077b6087c (ntdll32!RtlpBreakPointHeap+0x0000000000000023)
   ExceptionCode: 4000001f (WOW64 breakpoint)
  ExceptionFlags: 00000000
NumberParameters: 1
   Parameter[0]: 0000000000000000

FAULTING_THREAD:  00003088

DEFAULT_BUCKET_ID:  ZEROED_STACK

PROCESS_NAME:  image00000000`01380000

ERROR_CODE: (NTSTATUS) 0x4000001f - <Unable to get error code text>

EXCEPTION_CODE: (Win32) 0x4000001f (1073741855) - <Unable to get error code text>

EXCEPTION_PARAMETER1:  0000000000000000

NTGLOBALFLAG:  70

APPLICATION_VERIFIER_FLAGS:  0

APP:  image00000000`01380000

ANALYSIS_VERSION: 10.0.10075.9 amd64fre

BUGCHECK_STR:  APPLICATION_FAULT_ZEROED_STACK

LAST_CONTROL_TRANSFER:  from 0000000077b22d22 to 0000000077b6087c

STACK_TEXT:  
00204924 77b22d22 00205ed0 00205ed0 77abb92a ntdll32!RtlpBreakPointHeap+0x23
00204940 77b618d7 00390000 00205ed0 77abb92a ntdll32!RtlpValidateHeapEntry+0x16d
00204988 77b1ae62 00390000 50000063 00205ed8 ntdll32!RtlDebugFreeHeap+0x9a
00204a7c 77ac34c2 00205ed0 00205ed8 00205ed8 ntdll32!RtlpFreeHeap+0x5d
00204a9c 754c14bd 00390000 00000000 00205ed8 ntdll32!RtlFreeHeap+0x142
00204ab0 6d46ecfa 00390000 00000000 00205ed8 kernel32!HeapFree+0x14
00204ac4 6b697a19 00205ed8 194d1a45 07b45e80 MSVCR120!free+0x1a
WARNING: Stack unwind information not available. Following frames may be wrong.
003bc9e8 0020f764 00000000 0047e698 baadf030 Qt5Core!QTemporaryFile::~QTemporaryFile+0x139
003bc9ec 00000000 0047e698 baadf030 00000000 0x20f764


FOLLOWUP_IP: 
ntdll32!RtlpBreakPointHeap+23
77b6087c cc              int     3

SYMBOL_STACK_INDEX:  0

SYMBOL_NAME:  ntdll32!RtlpBreakPointHeap+23

FOLLOWUP_NAME:  MachineOwner

MODULE_NAME: ntdll32

IMAGE_NAME:  ntdll32.dll

DEBUG_FLR_IMAGE_TIMESTAMP:  55636317

STACK_COMMAND:  ~0s ; kb

FAILURE_BUCKET_ID:  ZEROED_STACK_4000001f_ntdll32.dll!RtlpBreakPointHeap

BUCKET_ID:  X64_APPLICATION_FAULT_ZEROED_STACK_ntdll32!RtlpBreakPointHeap+23

PRIMARY_PROBLEM_CLASS:  X64_APPLICATION_FAULT_ZEROED_STACK_ntdll32!RtlpBreakPointHeap+23

FAILURE_PROBLEM_CLASS:  ZEROED_STACK

FAILURE_EXCEPTION_CODE:  4000001f

FAILURE_IMAGE_NAME:  ntdll32.dll

FAILURE_FUNCTION_NAME:  RtlpBreakPointHeap

FAILURE_SYMBOL_NAME:  ntdll32.dll!RtlpBreakPointHeap

ANALYSIS_SOURCE:  UM

FAILURE_ID_HASH_STRING:  um:zeroed_stack_4000001f_ntdll32.dll!rtlpbreakpointheap

FAILURE_ID_HASH:  {0707fff2-6b05-1739-55d7-6da8061a850d}

Followup:     MachineOwner
