### ISSUE TITLE
Switching tabbar off does not stick

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#702]
View > Toolbars > Tabbar

I switch it off but the tabbar returns at program restart.

**Comment by VSHY** [comment]
The problem is that the other way it does not return.
I switched it "off", whereupon I wanted to switch "on" - in program settings (F12) this switcher (option) is absent, in "all settings" too...

P.S. I suppose that you need first option in settings of tabs.
