### ISSUE TITLE
option to load tabs only on access upon a restart

### ISSUE THREAD

**Issue by landroni** [OtterBrowser/otter-browser#704]
Some browsers (e.g. Firefox) have this nifty feature where upon restart they load tabs only when clicking on them. This helps when having a lot of tabs, and opening the browser: it avoids assaulting the CPU, memory consumption, and it makes things much quicker... 

Will you consider adding such an option to Otter?

**Comment by Emdek** [comment]
Nope, no need to consider it since it is available for long time already. ;-)
See **Browser/DelayRestoringOfBackgroundTabs**.

**Comment by landroni** [comment]
Nice! How do you access the hidden prefs?

**Comment by Frenzie** [comment]
about:config :)

**Comment by landroni** [comment]
Of course, silly me. :)
