### ISSUE TITLE
Actions for "open link in private tab" and "open link in private window"

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#707]
I generally don't get the idea with private tabs and windows, but when they exist, should they not be in the link right-click menu along with "open in new tab" and "open in background tab"?

Is it possible to make actions for "open link in private tab" and "open link in private window"?

**Comment by Emdek** [comment]
Yes, it is possible to add them, but one should be sufficient, to have full set we would need six new actions in total, that is a lot.

**Comment by Emdek** [comment]
Uhm, after rethinking this case, only four of them make sense in this case.

**Comment by ersi-dnd** [comment]
That's why there should be a possibility to edit menus. And a function like this would be easy to create by users themselves with macros, if macros were available, e.g. `Copy link url & Open private window & Focus address field & Paste and go` and a separate request would not even exist.
