### ISSUE TITLE
Something wicked about history

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#708]
**Issue A**

On the history page (about:history), question marks (?) get hexified into `%3F` and quite likely some other marks too. Not sure if this is due to Qt or the way Otter's history management has been built.

**Issue B**

Another thing is that I have been long thinking how to report serious crashes and lockdowns affecting the entire system. Qt programs have been occasionally affecting my system in various ways, but the most serious impact was from Otter's history management. The way to reproduce it:

1. Do not clean history at program quit, 
2. Have Otter start up with "continue from last session" and a generous amount of tabs, say 8
3. After a day or so of using Otter this way, it becomes sluggish and brings down the entire desktop environment with it.

This must be to do with Otter's history because the way to get Otter working again is to go to the profile folder and:

1. Remove `browsingHistory.sqlite` 
2. Remove `browsingHistory.sqlite-journal`
3. Remove `sessions/default.ini`

This must be due to Otter's history management because the history files are full of history, obviously, and session ini's are also full of history. It doesn't help to remove just one of these files. All have to be removed.

**Comment by ersi-dnd** [comment]
As to issue A, I chose a URL from about:history, but could not go there. The hexified bit prevented it. I had to manually modify the hexified bit in the address field to get to the real address.

**Comment by Emdek** [comment]
Uhm, maybe there is not enough memory on your system and swapping triggers some system wide issue?
You can try to limit amount of saved entries using **History/** options, I'm especially curious if setting **History/RememberBrowsing** to *FALSE* (basically, disabling global history) helps. 
If that won't help then you could try to set low limit for **History/BrowsingLimitAmountWindow** (amount of entries per tab in session).

**Comment by ersi-dnd** [comment]
I haven't tried RememberBrowsing with FALSE, but the last month or so the problem does not exist, ever since I activated ClearOnClose. It does basically the same thing as RememberBrowsing FALSE. 

It's not a memory issue. I have 4GB. It's something to do with how Qt handles resources.

**Comment by Emdek** [comment]
@ersi-dnd, so it's more like an issue with global history, not with session?

**Comment by ersi-dnd** [comment]
Not sure. When Otter has totally bogged down the system, the only thing that helps is to delete all files that contain history, both global sqlite files and the session.ini. When I leave the session.ini untouched and delete just the sqlite files, Otter either fails to start or bogs down the system again.
