### ISSUE TITLE
"sidebar panel switcher" (?) can disable but not reenable sidebar

### ISSUE THREAD

**Issue by uahim** [OtterBrowser/otter-browser#710]
![screenshot](http://thewilderness.bplaced.net/otter-updater/screenshots/github/switcher.png)
the first icon on top, "sidebar panel switcher" or whatever it's called, can disable (hide) the sidebar, but when clicked next time it does nothing.

**Comment by Emdek** [comment]
This entry appears to be broken, does it work properly after removing it from value of *Sidebar/Panels* in *otter.conf*?

**Comment by uahim** [comment]
indeed it seems to have been a glitch, for some reason it was there twice with double quotes
´"Panels=bookmarks, history, transfers, cookies, config, cache", bookmarks, history, transfers, cookies, config, cache´
