### ISSUE TITLE
certain actions not configurable as keyboard shortcuts

### ISSUE THREAD

**Issue by pmattern** [OtterBrowser/otter-browser#711]
Assigning some actions a keyboard shortcut at Tools - Preferences - Advanced - Keyboard - \<copied "Platform"\> fails besides the shortcut itself can be used with other actions. No apparent problems while editing and saving the shortcut, just no effect applying.
E. g. assigning Ctrl+PgUp to "About Otter..." works but assigning the very same shortcut to any of "Go to Home Page" or "Go To Tab on {Left,Right}" fails.

Latest Git version compiled against Qt 5.4 on Arch Linux x86_64. Shortcuts tested are working flawlessly in other applications such as Firefox or gvim and hence aren't reserved e. g. by desktop environment either.

For the record, this has been discussed on IRC some days ago. But I won't be able to join IRC on a regular basis for a while and hence thought it might make sense to go on discussing as an issue.

**Comment by ersi-dnd** [comment]
I also have the same complaint for many actions. For example, "Close other tabs" does not seem to work at all.

**Comment by pmattern** [comment]
Not sure about the meaning of "references" but https://github.com/OtterBrowser/otter-browser/commit/09ead75fb1ecd7f2bfc3539e8e64204a126aed50 doesn't seem to have changed anything regarding this issue.

**Comment by Emdek** [comment]
@pmattern, it was fix for "Close other tabs".

**Comment by Emdek** [comment]
@pmattern, I think that we have totally different issue here than that reported by @ersi-dnd, missing warning about shortcut duplicates.
If the same shortcut gets assigned to multiple actions then it will work only for first one.

**Comment by Emdek** [comment]
@pmattern, after some more digging I've found true reason for this issue, if action had shortcuts defined in more than one profile then only one set was used instead merging shortcuts defined by all profiles into single list.

**Comment by pmattern** [comment]
Problem has gone indeed which means a major step forward to me.

As already discussed on IRC there's still as minor issue regarding those profiles which is probably some remnant of https://github.com/OtterBrowser/otter-browser/commit/7831b8d18692ef493b4bf0df7f001ea3e6fdd063 as well as https://github.com/OtterBrowser/otter-browser/commit/a1a4ad0e30cd931e203db844ef5579d21d16d99d and https://github.com/OtterBrowser/otter-browser/commit/3d5b9b77750db185ee5fe448c2d77c9f06660386:
A new keyboard shortcut configuration profile that gets created by invoking Preferences - Advanced (Tab) - Keyboard (left pane), selecting either profile 'Platform platform' or 'Default default' in field Keyboard Shortcuts (right pane) and hitting "Clone" can't be edited at once. Button "Edit" stays grayed. Editing only works once dialog window "Preferences" has been closed by hitting "OK" and opened again.
New profiles that get "Cloned" from a profile that itself is a copy of one of those two default profiles aren't affected.
Given that keyboard configuration will start by copying one of those two default profiles most of the time I think fixing this albeit minor issue did have some impact regarding usability.

Side note: As you may remember I stumbled upon this issue's actual problem after seeing that "Go to Home Page" default setting Alt+Home had stopped working with some but not all profiles for apparently no reason.
This issue has now gone as well which is pretty plausible considering your commit message.

**Comment by pmattern** [comment]
Just as a short feedback: last remaining issue as stated in previous posting got indeed fixed by bfc3fca, consistent with its commit message.
