### ISSUE TITLE
endless loading on dict.leo.org

### ISSUE THREAD

**Issue by pmattern** [OtterBrowser/otter-browser#712]
As soon as a word was submitted, Otter loads endlessly ("red button" in navigation bar) and status bar keeps stating 'Elements: (n-1)/n'. No apparent malfunction.

Latest Git version compiled against Qt 5.4 on Arch Linux x86_64. Problem can't be seen with QupZilla compiled the same way and hence seems to be specific to Otter.

For the record, this has been discussed on IRC some weeks ago. But I won't be able to join IRC on a regular basis for a while and hence thought it might make sense to go on discussing as an issue.

**Comment by pmattern** [comment]
The problem was indeed fixed regarding dict.leo.org.

But the very same problem is now appearing when links pointing to anchors within the actual web page are followed.

So unfortunately this isn't fixed yet.

**Comment by Emdek** [comment]
@pmattern, it's different issue.
