### ISSUE TITLE
The little x on sidebar has vanished

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#713]
The x button that closed the sidebar has vanished. Those who prefer to point and click would appreciate it. 

As a principle, extant features should never be removed. Instead, provide an option to turn them off.

Additionally, in old times Opera had a >> button next to the x button. The >> button opened the sidebar's feature in the main. For example, when bookmarks sidebar was open, and the user pressed >>, then the full-window bookmarks manager opened up.

**Comment by Frenzie** [comment]
Old times? I have the >> button right here in 12.16. :P (Oh, you meant by default? I wouldn't know about that.)

**Comment by ersi-dnd** [comment]
The >> button was dropped somewhere along the way by v.11 for new installs, but kept available in Appearance > Buttons > Panels

**Comment by Chocimier** [comment]
Now x button works like in Opera :)
