### ISSUE TITLE
The sidebar switcher toolbar issues

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#714]
*Issue 1*

Tabbar can be replaced anywhere by dragging. Why not provide the same for the sidebar toolbar? In fact, for all toolbars!

*Issue 2*

The new wrench button on the sidebar toolbar is nice to add/remove the other buttons, but is there a way to remove the buttons by other means? How is it possible to remove the new wrench button itself?

*Issue 3* 

The way I used Opera, I didn't have that toolbar at all. I switched the sidebar features from a menu similar to what appears under the new button in Otter. I want access to that menu and to place it anywhere. 

Look at the image. The text that says Notes was actually a button that opened the menu to switch to other sidebar features. This menu button did not need an image because it served as a label for the currently open sidebar feature.  
![03-panels](https://cloud.githubusercontent.com/assets/6865273/6268378/e7395b72-b854-11e4-9c13-3537b2b59d5f.jpg)
 For me this menu button was all I needed so I had the switcher toolbar turned off. To do the same in Otter, I need to be able to

- Place the toolbar on top of the sidebar, not to the side as it is now
- Remove all buttons, absolutely all, including the wrench button
- Place the menu (the menu that appears under the new wrench button) on the toolbar as a button

**Comment by lollox** [comment]
Yes, I agree that current GUI isn't very customizable as I hoped (in opera I can place/remove/add anything everywhere... it's a whole different experience) and I agree with your specific requests about the sidebar... and talking about sidebar I've to add another important request:

*Issue 4*
Add the sidebar toggle (the tiny bar (1-2px) placed at the left border that when clicked opens the sidebar) ... I find it a lot more convenient than a button. The implementation made in Opera was very good (tiny and discrete) while I see that when others try to "copy" it the result is a bit less good (for example in AiOS extension of Firefox, or in Vivaldi browser > the toggle is too much big) ... I like instead how it has been implemented in the [OmniSidebar](https://addons.mozilla.org/it/firefox/addon/omnisidebar/) extension of Firefox (1px border that when hovered shows a sort of blue light effect to catch attention)

**Comment by Chocimier** [comment]
4. This is ready - you can enable it by Sidebar/ShowToggleEdge option. Maybe there should be some options for sidebar in settings window?

**Comment by lollox** [comment]
@Chocimier : oh, didn't see it .... Well, I don't know what is planned for Otter about Preferences/Customization dialogs, but I hope they will cover all these basics in some way

**Comment by uahim** [comment]
an addition, just in case this isn't on the TODO list yet: so now that I can switch the sidebar content by simply clicking on the title (thanks for that) and toggle it via "edge", I'd like to hide the switcher even if I see the sidebar itself, as it is not needed anymore.

**Comment by lollox** [comment]
@uahim : This is why in a previous post I asked for trasforming that toolbar (actually quite "hardcoded" in the whole sidebar) in a more general toolbar

**Comment by uahim** [comment]
@lollox ah, yes, that'd make sense

**Comment by Emdek** [comment]
Superseded by #1086.
