### ISSUE TITLE
Ctrl-A Doesn't Select All Cookies In The Sidebar

### ISSUE THREAD

**Issue by opticyclic** [OtterBrowser/otter-browser#715]
I can select the top cookie then Shift-Select the bottom one but I can't press Ctrl-A to select all Cookies in the sidebar.

**Comment by ersi-dnd** [comment]
And when a cookie is deleted, the selection is not focused on the next cookie.

**Comment by Emdek** [comment]
@ersi-dnd, works here, that was fixed long time ago.
When next branch gets focused you can use right arrow to expand it.

**Comment by Emdek** [comment]
Superseded by #826.
