### ISSUE TITLE
search page tabs pin themselves

### ISSUE THREAD

**Issue by resbro** [OtterBrowser/otter-browser#719]
Lately, (weekly 60 x32) if I run a search for something from the searchbox, when the results come up if I hover the mouse over the tab it pins itself. Is that a feature or a bug? Only seems to happen if I have a tab pinned already. Unpinned tabs open and it works fine. Works with all search engines, Default and custom.

Win 7 x64

**Comment by Emdek** [comment]
Definitely it is not intended feature.
