### ISSUE TITLE
Bug: Chevrons missing on Google News

### ISSUE THREAD

**Issue by Otteruser** [OtterBrowser/otter-browser#720]
![missing chevrons on right hand side](https://cloud.githubusercontent.com/assets/7341801/6412076/4d889232-be4d-11e4-82e2-59ecf8f83cea.PNG)
 
Look closely at the screenshot taken of Google News. The chevron to contract or expand the number of stories is missing on the right hand side.

**Comment by Otteruser** [comment]
This is how the exact same part of Google News appears in Opera 27.0.1689.76:
![opera](https://cloud.githubusercontent.com/assets/7341801/6412129/ebb2aeca-be4d-11e4-8372-19572ade02a7.PNG)

See the chevron on the right hand side ?

**Comment by Emdek** [comment]
Such stuff is beyond our control, there are two options:
 - try to use UA masking (there is slight chance that it will help in this case),
 - wait for more mature version of QtWebEngine (Blink) backend: #615.
