### ISSUE TITLE
links comprising anchors handled faulty if opened in new tab by middle-click

### ISSUE THREAD

**Issue by pmattern** [OtterBrowser/otter-browser#721]
If links comprising anchors are opened in a new tab by middle mouse-click Otter doesn't display the page at the anchor's position but at some arbitrary one.

Address bar is displaying the correct URL. Reloading the page displays the correct position for a moment but then falls back to the wrong one. Placing the cursor behind the URL in address bar and hitting "Enter" gets the display correct.
Problem neither appears if links are simply (left-) clicked or opened in a new tab by selecting "Open in New Tab" from a link's context menu.
It is independent from the anchor-related issue described in https://github.com/OtterBrowser/otter-browser/issues/712#issuecomment-76491306. It cannot be seen with latest QupZilla compiled the same way.

Latest Git checkout compiled against Qt 5.4.0 on Arch Linux x86_64.

**Comment by The-Compiler** [comment]
FWIW, I also see this in [qutebrowser](https://github.com/The-Compiler/qutebrowser) which is a completely different codebase.

**Comment by Emdek** [comment]
@The-Compiler, I guess that it could be worked around by scrolling to anchor on ``loadFinished()``.

**Comment by Frenzie** [comment]
@Emdek That's debatable. Pictures and stuff pushing the page around is annoying, but if you already started scrolling and reading you probably don't want yet another scrolling event messing things up. Of course, none of that applies to tabs that aren't focused.

**Comment by Emdek** [comment]
@Frenzie, I'm aware of that, we can try to detect it and skip it then.
It's a case similar to restoring state of page when going back or forward, there we check if scroll position is 0, 0.
We can try to make it more generic, for example capture manual scrolling, use of scrollbars, use of mouse wheel or dragging.

I'll need to do some testing to determine best approach, maybe it's related to zoom level or not related to images at all.

**Comment by Emdek** [comment]
Seems to work fine with revived QtWebKit.
