### ISSUE TITLE
Links not working on hitparade.ch

### ISSUE THREAD

**Issue by ThebestwaytodesignJoinGitHub** [OtterBrowser/otter-browser#723]
Try to search something on http://hitparade.ch/search.asp, for convenience enter "cars".
Scroll down the resulting site, there you can find links named "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15" to navigate through the subpages. But otter does not open these subpages, it jumps only back to the top.
(No problem with qupzilla)

**Comment by Emdek** [comment]
Ii works for me that way also in Opera and Chromium...

**Comment by ThebestwaytodesignJoinGitHub** [comment]
Yes, works in the other browsers.
Tried without adblocking, all javascript enabled, third-party cookies allowed, but to no avail.
