### ISSUE TITLE
Two weird things about the Transfers Manager

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#724]
1. This one's more like a bug. When I download a file, no **Transfers Manager** tab launches, and when I open one I can see 2 transfers: one normal transfer and another, stopped transfer, duplicate of the first one.
**Browser/TransferStartingAction** is set to **openBackgroundTab** in case that matters.

2. The finished date/time gets set when you **Stop** a transfer, which is technically not the same as actually *finishing* it.

**Comment by ersi-dnd** [comment]
Cannot confirm. I have the same setting.

I tried at Sourceforge. At what site did you try?

**Comment by elebow** [comment]
I have seen the first issue when downloading from various websites, but I could not reproduce it just now when I tried.

When I encountered the problem in the past, I was running commit ≤ https://github.com/OtterBrowser/otter-browser/commit/8cc365109d21d0e767947db3e4fd50f0416505ea, with Qt version 5.3.2.

**Comment by Emdek** [comment]
@beastie1, can't reproduce that issue with duplicate.
Is it reproducible or this could be some old transfer with the same target path?

**Comment by pmattern** [comment]
I had seen those double entries as well but couldn't reproduce running latest Git code any longer. Maybe it was fixed as side-effect of f2f1cc7? Couldn't reproduce any of the OP's other findings either.
There seem to be two issues related that I'd like to mention, though:

Hovering over those separators within the heading of the table in tab "Transfer Manager" yields some double arrow icon, but this doesn't apply to the two separators at the left, namely the one between the column displaying icons (header itself empty) and Filename as well as between Filename and Size.
The result of dragging and dropping those double arrow icons is rather odd and counter-intuitive, imo. It seems as if the separator left of the one that's dragged and dropped gets moved. As a consequence, it's e. g. not possible to have those timestamps in column Finished shown completely.

If a rather large file gets downloaded and the choice in dialog "Save as" is submitted by hitting "Save" only when the actual download has finished already the dialog seems frozen for a moment and Transfer Manager displays an incomplete download as complete.
Reproducibly 100% by downloading an about 600M ISO image from a web server residing on the same host as Otter. Small files don't seem to be affected.

**Comment by beastie1** [comment]
Okay just to be sure it's not my custom settings or an old issue, I've built from the latest MASTER and launched Otter with a blank **--profile**.

It happens with many websites, including both Yahoo and Gmail webmails.

Simply download any attachment and issue 1 occurs.

**Comment by beastie1** [comment]
By the way I'm using Qt 5.3.2 on FreeBSD 10.1

**Comment by beastie1** [comment]
The first issue hasn't been occurring for quite some time, so I'm closing this ticket.
