### ISSUE TITLE
MiddleClick issue and feature request

### ISSUE THREAD

**Issue by uahim** [OtterBrowser/otter-browser#728]
PasteAndGoOnMiddleClick seems not to be working (anymore?) on Win32, despite being set to "true" in the config

also, any chance to open pages in background tabs when links are clicked with the middle button?

**Comment by ersi-dnd** [comment]
Isn't it so that addressbar should be in focus for it to work?

**Comment by uahim** [comment]
@ersi-dnd yes of course the addressbar is in focus when I hit the middle mouse button

**Comment by ersi-dnd** [comment]
Then cannot confirm. There could be some other specifics involved that cause the issue for you.

**Comment by uahim** [comment]
@ersi-dnd oops indeed it was my bad, not Otter's fault.
