### ISSUE TITLE
Add action to set or toggle value of an option

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#729]
Pursuant #717 there was created an about:config setting to make scrollbars disappear. However, I notice that there is no general policy to make all about:config settings available as actions at the same time. 

It's true that now we can make scrollbars disappear in about:config, but what if we want a toggle to make them appear-disappear via keybind or menu item? I propose that for each about:config setting, it should be considered if a corresponding action would make sense.

**Comment by Emdek** [comment]
@ersi-dnd, there is a policy to avoid adding too many new actions, but instead we can make use of parameters feature for actions and create one that can both set explicit value for any action, toggle values for boolean options and maybe even reset them to defaults too.

**Comment by Emdek** [comment]
Here are examples to be used in menus:
```
{
    "type": "action",
    "identifier": "SetOption",
    "parameters":
    {
        "option": "Permissions/EnableJavaScript",
        "mode": "set",
        "value": "false"
    }
},
{
    "type": "action",
    "identifier": "SetOption",
    "parameters":
    {
        "option": "Permissions/EnableJavaScript",
        "mode": "reset"
    }
},
{
    "type": "action",
    "identifier": "SetOption",
    "parameters":
    {
        "option": "Permissions/EnableJavaScript",
        "mode": "toggle"
    }
},
{
    "type": "action",
    "identifier": "SetOption",
    "parameters":
    {
        "option": "Permissions/EnableJavaScript",
        "mode": "toggle",
        "host": "github.com"
    }
},
```
They would look similar in case of shortcuts and gestures.
