### ISSUE TITLE
Webpage scrolling action

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#730]
In Preferences > Advaned > Keyboard >  {select} > Edit there are new actions, such as 
- Enter Drag Scroll Mode
- Enter Move Scroll Mode
- Exit Scroll Mode

I understand that some scrolling should be available, but I don't get what the difference is between the two modes. Is "Move Scroll Mode" the one which is toggled by means of mid-click by default? How to enter the other mode?

Furthermore, why is "Exit Scroll Mode" a separate action? 

**Problem A**

These actions are in keyboard configuration, and the normal way I use keyboard shortcuts is to use the same shortcut to enter and exit a certain mode, e.g. F11 to both enter full screen and to get out of full screen. Meaning - TOGGLE. When the actions are structured the way they are right now, I cannot create a toggle. 

Luckily, I figured out the mid-click scrolling action somewhat. However, I don't know which one of those modes is under mid-click. And the problem is that I cannot configure mid-click when focused on webspace.

**Problem B**

Mouse buttons and touchpad gestures seem to be doing their own thing with regard to scrolling, i.e. sometimes it looks like mid-click is activated when I didn't do any mid-click. This is why I feel it should be possible to turn scrolling off in about:config. When mouse-based mid-click scrolling is turned off, the keyboard-based scrolling should remain active. For example in Elinks there are separate configurable actions to scroll left and right (horizontal scrolling). I think this should be so in Otter too.

All in all, I don't like mid-click scrolling. I would do horizontal scrolling either by keyboard shortcuts or some mouse gestures (e.g. right-click + gesture right, which is designated for "History Forward", I would put it to do "Scroll Horizontally Right"). 

This is why there should be a setting in about:config to turn mid-click scrolling off and allow more configuration options for mid-click in webspace. Some good about:config options for mid-click in webspace are "none/disabled" or "Toggle caret browsing" as per #536

**Comment by ersi-dnd** [comment]
Some clarification to my last paragraph in the last post. A setting that would, in my opinion, make sense in about:config would look something like this:

MidclickInWebspace - None(disabled)/ScrollMode(*)/CaretBrowsing(**)

(*) Is it Drag or Move scroll mode? I don't know. But it should say which one it is. And naturally, this setting should mean a toggle: one mid-click enters the scroll mode, the second mid-click exits.

(**) Naturally, this setting also should mean a toggle: one mid-click enters the scroll mode, the second mid-click exits.

And I think there should be more options. I just cannot think of more right now.

**Comment by Chocimier** [comment]
These actions are implemented, but not configurable yet. They are meant to activate with MMB. We plan to allow to fire any (or none) action with MMB.

**Comment by ersi-dnd** [comment]
What does MMB stand for? Midclick?

**Comment by Emdek** [comment]
@ersi-dnd, probably middle mouse button, so yeah, it maps to "midclick". ;-)

**Comment by Emdek** [comment]
Related ticket: #77.
Letting these actions to work as toggles could be a god idea, but we should keep action to exit or  maybe rename it so it could be kind of third mode.

**Comment by Emdek** [comment]
I guess that we should rename them now, at least drop "Start" prefix.
