### ISSUE TITLE
Sidebar size inconsistency

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#731]
The different sidebars (history, bookmarks, transfers, cookies) seem to have different minimal width. Cookies have the widest width. When a sidebar is resized narrow and then I switch to cookies, the sidebar widens. Visual glitch.

**Comment by Emdek** [comment]
We need special layouts for sidebar, simply disabling details pane of each widget should be enough.

**Comment by Emdek** [comment]
Right now it should be possible to have consistent sizing for sizes not smaller than 200 pixels, some stuff simply cannot be smaller...
