### ISSUE TITLE
Panel positioning in about:config

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#732]
There's a weird entry in about:config

Sidebar/Reverse true|false

I think it deserves a better name. Something like

Sidebar/Position left|right

**Comment by lollox** [comment]
Better: I hope stuff like this will be moved to what in Opera was the toolbars.ini (so something out of the preferences) ... apparency and preferences should remain separate stuff.

But actually I don't know how emdek is building Otter on this aspect ...

**Comment by Emdek** [comment]
@ersi-dnd, it was named that way to make it more generic, so it will fit RTL languages.

@lollox, sidebar settings will be moved to *toolBars.json* (at least partially).

The biggest issue is that design of sidebar(s) is not finalized yet, there are three possibilities:
 * keep single sidebar able to show only a single panel (current state);
 * add secondary sidebar, both able to show only a single panel;
 * add secondary sidebar, allow to display multiple panels.

Third case is the most flexible one, but it would require removal of vertical bar with buttons (as it is suitable only for cases when there is only one panel) but now we have menu button to switch current panel anyway.

**Comment by Emdek** [comment]
This ticket is closely related to #714.

**Comment by lollox** [comment]
To me the second one is the best, but even the first is OK... the third one to me is not very suitable because I use a lot that vertical toolbar ... but I don't know how much other users depend on it

**Comment by lollox** [comment]
however I was thinking... if it will be possible to "target" the two sidebars, there will be not real problems  'till we could make a customized vertical toolbar with the buttons we want 

i.e. : make a toolbar with, for example, a button that will open the bookmarks sidebar in the sidebar 1, etc

I hope I was able to explain my idea :)

**Comment by Emdek** [comment]
@lollox, yeah, we can provide such API for all three cases, obviously it would be more complex in case of multiple panels per sidebar.
There is also another possibility, keeping vertical bar but somehow marking panel that has focus and applying actions only to active one.

**Comment by Emdek** [comment]
Superseded by #1086.
