### ISSUE TITLE
improvements regarding zoom ruler

### ISSUE THREAD

**Issue by pmattern** [OtterBrowser/otter-browser#733]
I think it would be good if the current zoom value wasn't shown while hovering over the ruler (status bar's right end) only but also real-time when it's adjusted by moving the ruler.

Also, I think it would be pretty handy to have a simple means to revert to 100%, e. g. by double-clicking somewhere over the ruler, introducing vertical bars that can be clicked (see LibreOffice) or whatever.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
I think so too.

**Comment by Emdek** [comment]
@pmattern, I'm planning to add menu next to zoom slider as soon as we will have more actions related to zoom, just like in classic Opera.

For now you can add "Zoom to Original" to status bar by creating *toolBars.json* in profile directory:
```
[
	{
		"identifier": "StatusBar",
		"title": "Status Bar",
		"actions":
		[
			"StatusMessageWidget",
			"ZoomOriginalAction",
			"ZoomOutAction",
			"ZoomWidget",
			"ZoomInAction"
		]
	}
]
```
