### ISSUE TITLE
keyboard configuration: allow for moving separator between actions and configured shortcuts

### ISSUE THREAD

**Issue by pmattern** [OtterBrowser/otter-browser#734]
I would find it pretty handy if that line separating the list of available actions from the one with configured shortcuts in dialog window "Profile Configuration"
![otter keyboard configuration edited](https://cloud.githubusercontent.com/assets/9860801/6604333/ea896438-c827-11e4-92b1-704dba918f61.png)
could be moved vertically.

Most of the time the number of actions will exceed the number of configured shortcuts by far. But if the dialog window gets enlarged the ratio of the two panes is reflecting just the opposite.

**Comment by Emdek** [comment]
I don't think that splitter is really required there, I've set more usable stretch values so list of actions has priority when dialog is resized.
