### ISSUE TITLE
system qt and opt qt confusion

### ISSUE THREAD

**Issue by ThebestwaytodesignJoinGitHub** [OtterBrowser/otter-browser#739]
When executing otter from within its build directory, it uses the 'opt' qt5 files it was compiled against (5.4.1) and everything works fine.
Next step, after installing otter (with make install or checkinstall), it uses the system's qt5 files, which have a lower version number (5.2) and are not fully installed.
This is something I do not understand. It would be better if we could install otter like all the other software, in my case as deb file (with checkinstall) to have it listed in synaptic package manager.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
In my opinion this has nothing to do with #722. The adress bar is empty when it uses the correct library. When otter tries to use the system qt library, I can't even launch it, because I have not installed the system qt library

**Comment by Emdek** [comment]
See: 
http://www.cmake.org/Wiki/CMake_RPATH_handling

It's up to packagers / distribution to modify it if needed, it's better to keep defaults at least for now.

I'm planning to add warning for such cases, when runtime version has lower version number than compile time version.
