### ISSUE TITLE
switch --profile: inconsistency regarding relative and absolute paths

### ISSUE THREAD

**Issue by pmattern** [OtterBrowser/otter-browser#740]
If otter gets launched `otter-browser --profile /home/<user>/.config/otter/foo` directory foo as stated gets used as profile directory.
But if a relative path is stated in $HOME, `otter-browser --profile .config/otter/foo`, some directory $HOME/.config/otter/profiles/.config/otter/foo gets created.

I don't know what the intended behavior looks like, in particular whether it's intended to have that subdirectory .config/otter/profiles. Nevertheless there shouldn't be a difference caused by stating an absolute or relative path.

Seen running latest Git code on Arch Linux i686.

**Comment by Emdek** [comment]
It's not a bug, it's a feature. ;-)
If path is relative then profile is created in subdirectory of main profile.
I guess that it would make more sense to do that only if argument doesn't contain directory separator.
