### ISSUE TITLE
switching search engine with pull down deletes search term

### ISSUE THREAD

**Issue by hunderteins** [OtterBrowser/otter-browser#741]
Hi, 
when I switch the search-engine in the toolbar with the mouse wheel, the search term ist rescued and send to the choosen engine.
When I click left and choose a search engine in the pull down, the search term got lost.

I traced this issue to src/ui/toolbars/SearchWidget.cpp. SearchWidget::setSearchEngine and SearchWidget::wheelEvent are handles differently. In setSearchEngine the text is stored in a local variable named query. In wheelEvent setText is just called with the global m_query.

To make this consistent over the source I propose to remove the local query-variable in setSearchEngine and use lineEdit()->setText(m_query);

Regards,
hunderteins

**Comment by ThebestwaytodesignJoinGitHub** [comment]
Can confirm this
