### ISSUE TITLE
Pandora.com cause complete crash

### ISSUE THREAD

**Issue by hellofu** [OtterBrowser/otter-browser#743]
you need to have plugins enable to cause the crash. if plugins are on demand the page will load but you cant lisen to music and will be asked about to fix/install flash.

attemping to load the page causes the crash.

**Comment by Emdek** [comment]
Can't reproduce, no crash, audio plays correctly (Qt 5.4, Linux and... proxy).
Which operating system and Qt version are you using?

**Comment by hellofu** [comment]
QT 5.2.1
linux mint 17.1
Otter daily build

**Comment by Emdek** [comment]
@hellofu, yeah, it's reproducible with Qt 5.2.1, apparently it was fixed in later release, Qt 5.4.1 is not affected.
Maybe there exists somewhere repository with more up to date Qt version.
