### ISSUE TITLE
Tabbar still interfering with fullscreen

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#747]
This ticket is to highlight two principles

1. Stickiness of options
2. Consistency of interface mode

based on the example of the current behaviour of tabbar in fullscreen in Otter.

**Stickiness of options**

Opera had the ability to hide any toolbar. This was a sticky option in every case, i.e. the hidden toolbar stayed hidden across app restart. For example, I want the tabbar gone. I don't need the tabbar, because Ctrl+Tab dialog is enough for me. (There's also the sidebar panel, eventually meant to house the open tabs and windows in some way.) 

We have a Show/Hide tabbar action in Otter, but the problem is that it's not sticky. I can hide the tabbar, but the next time I open Otter, the tabbar is back again. Opera did not behave this way.

I have a similar problem with opening sessions. I want them always inside the current window. Otter has the option to open sessions in current window, but this option has to be specifically re-selected when I have closed Otter meanwhile. To me it's self-evident that this should be a sticky option.

**Consistency of interface mode**

Now that we have proper fullscreen, there's a glitch in it with the tabbar. When Show tabbar is enabled, the tabbar appears in fullscreen mode when the mouse pointer is moved to the screen top edge. When Show tabbar is disabled, the tabbar does not appear this way in fullscreen. 

I don't think this should be viewed as a bug and removed. It can be viewed as a legitimate user preference. However, it highlights the fact that Show tabbar should be a sticky option, different from what it is now. When Show tabbar is a sticky option, users can properly choose how the browser behaves.

**Comment by Emdek** [comment]
Superseded by #764.
