### ISSUE TITLE
Panel icons

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#750]
The **Configuration** panel and the panel configuration button that allows you to add/remove panels both have the [same icon](https://github.com/OtterBrowser/otter-browser/blob/master/resources/icons/configuration.png) which can be visually confusing, especially when the **Configuration** panel is set as the lowest panel (right above the panel configuration button).

What about changing the panel configuration button to a "pen" [modify icon](https://www.google.com/search?q=modify+icon&tbm=isch) or "wheel" [settings icon](https://www.google.com/search?q=settings+icon&tbm=isch)?

I think these two options would be more accurate than Opera's "+" icon since you can both add *AND* remove panels.

**Comment by Emdek** [comment]
We can go for the same concept like in Opera, "plus sign".

**Comment by beastie1** [comment]
An reason why you prefer this to the other 2 options?

I think Otter should improve on Opera here as it has already done in many other places.

Just my 2 cents.

**Comment by Emdek** [comment]
@beastie1, at least two. ;-)
 1. we don't need to bundle special icon,
 2. we can allow to load it from icon theme of desktop environment.

**Comment by beastie1** [comment]
Ah okay, it sounds fair.

**Comment by Emdek** [comment]
I thought that we had these two icons already... Well, these two will be useful anyway.
In future we can try some approach to distinguish them more, maybe even using tab bar like widget.
