### ISSUE TITLE
Visual glitch with the ZoomWidget slider button

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#751]
Am I seeing wrong or is the **ZoomWidget** slider button cut on the top?

**Comment by Emdek** [comment]
If it is then it could be considered a bug in this specific style, doesn't occur with default one.
I can modify it a bit to allow to control height through *toolBars.json*.

**Comment by Emdek** [comment]
They way how the height is controlled may be changed in future, but that should be good enough for now.
