### ISSUE TITLE
Some main tools not available in Private window

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#755]
1. Open Private window 
2. Try the Tools menu
3. Content blocking and Transfers is available as usual.
4. Cookies and Notes are not available via Tools menu. 
5. In Private window, Cookies and Notes are available in Panel, but the "Open Panel as Tab" button does not work.
6. about:cookies and about:notes are also available, so there really should be no obstacle to Tools/Cookies and Tools/Notes either.

**Comment by lollox** [comment]
I don't know what you refer to when you talk about Notes but I can't confirm nothing... I can open cookie tab in every way when I'm in a Private window

Otter x86 weekly 63 on Win7 SP1 x64

**Comment by ersi-dnd** [comment]
I made another Otter installation on another machine, and the issue is not present there. It's present in the first machine as reported, but probably just something I messed up, i.e. affecting only me.

**Comment by Emdek** [comment]
@ersi-dnd, looks like something wrong in configuration files, we won't guarantee full compatibility until 1.0 (of course we try to avoid breaking stuff ;-)).
