### ISSUE TITLE
Customise buttons

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#756]
In addition to customise toolbars and customise menus, I thought to create a ticket to discuss button issues.

**BUTTONS DISPLAY**

In Opera it was a toolbar feature to display all its buttons either as icon or text or icon+text. In Otter (or Qt) on the other hand, the icon is inbuilt into the action, in which case it displayed  as icon on the toolbar, or if the icon is not inbuilt into the action, the button gets displayed as text. 

For example `ShowTabBarAction` gets displayed as text on any toolbar, but any bookmark item gets displayed as only icon. There's no option for the user to choose icon+text at all, or to switch from icon-only to text-only. 

**COMBINED BUTTONS**

In Opera, there was a way to combine button actions, e.g. 
```
Button4, -1320335960="Enable display images > Disable display images, , , -383776252 > Display cached images only, , , 333270751 + Show popup menu, "Style Menu""
...
Button17, 380699176="Go to homepage + Show hidden menu, "Browser Session Menu""
```

Questions: Will scriptlets be able to do the same? And will they be able to switch icons the way `ReloadOrStop` does currently, plus provide an option to display buttons as icon+text or text-only? How far are scriptlets anyway?

Another small question: Is there a menu/button to list open tabs, i.e. tabbar as menu?

**Comment by Emdek** [comment]
You can already set style of button. ;-)
I'm exposing this in UI right now.
And setting custom icon per button is also planned.

Combined buttons means custom menus in toolbars? That is planned too.

Basically it's fine-tuning for #31.

**Comment by ersi-dnd** [comment]
Thanks for working on it :)

> Combined buttons means custom menus in toolbars? 

Not only. The "Display images" example in my first post demonstrates cycling actions, i.e. if Images are enabled, disable them, but if images are disabled, enable image cache (plus the button has a menu attached too). 

Similar cycles can be combined for other actions, e.g. right now I thought of Notes display. You have a horizontal bar there separating folders from the display/editing area. What if the user wants a vertical bar, or just the editing area. This would be button that cycles the view modes, something like:
```
View=Split horizontally > Split vertically > Textarea > Folders
```  

(There's another issue with the Notes manager: The bar should be draggable to resize the editing/Folders&items area. It's a necessary design element in such manager windows.)

**Comment by Emdek** [comment]
@ersi-dnd, cycling looks like task for scriptlets, but it could be also built-in, I'll rethink that later.

**Comment by ersi-dnd** [comment]
More on combined buttons:

I'd like to make several toolbars disappear at one go. As I understood, scriptlets should be able to make it eventually. In Opera, this would be something like
```
Button "Expand/Normalise" = Disable tabbar & Disable menubar & Disable statusbar | Enable tabbar & Enable menubar & Enable statusbar
```

However, instead of listing specific toolbars like this (which is good for some purposes and should be available in some form anyway), I would like there to be a single action to enable/disable all "global" toolbars at one go, and I'd like it to work as intended even when one of the "global" toolbars happens to be disabled as a sticky setting. If this kind of depth is accessible to scriptlets, I would most definitely build such an action.

**Comment by VSHY** [comment]
I like Opera Presto, but the old way to set the code of menus or buttons (macro: "&", ">", etc.) is terrible and has a lot of shortcomings. In my opinion, the realisation of this way will spend much time unreasonably.
Better to use in configs a new browser's JavaScript-API.

**Comment by Emdek** [comment]
@VSHY, we are using JSON based structures for such stuff, so it's more readable (especially for JS developers ;-)).
Menu buttons for toolbars will use the same structure as *menuBar.json* etc.
