### ISSUE TITLE
Clear history when application closes does not work

### ISSUE THREAD

**Issue by ThebestwaytodesignJoinGitHub** [OtterBrowser/otter-browser#758]
Clear history when application closes does not work.
I have selected 'Clear caches' but caches aren't cleared automatically.
When I select it manually from 'Clear history', all cache is deleted immediately.
Also, per-site setting would be great.

**Comment by Emdek** [comment]
Per site option to control cache looks interesting, I'll add that to my list of stuff to investigate.
It should be at least possible to add option to disable cache for specified pages.
