### ISSUE TITLE
Fine-tuning for tabbar

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#759]
First, thanks for providing a way to make the tabbar permanently invisible.

**Show only as needed**

In Opera, there was a setting for every toolbar - "Show only as needed". This makes most sense for tabbar: When there's just one tab, there's no reason to show the bar. This setting is missing in Otter. I realise that when you hide tabbar, the useful trashcan icon (closed tabs button) has to be moved elsewhere. I always preferred it in bottom right corner on the status bar.

**Width and breadth**

Another issue is the tabbar style. With a recent change in interface styling, both the tabbar and the navigation bar have acquired unjustifiedly wide margins or paddings. I just moved the tabbar to the bottom (by tweaking toolBars.json), and it looks egregious. I also set `"iconSize": 20,` but it seems to have no effect on the look of the tabbar.

**Comment by Emdek** [comment]
There is such option, in dialog, exactly for this purpose. ;-)
But right now it is ignored.

Yes, icon size has no effect there, at least not yet, that part is duplicate if #190.

**Comment by ersi-dnd** [comment]
Shouldn't the "only as needed" setting along with other settings be available in about:config/Tabbar also?

**Comment by Emdek** [comment]
@ersi-dnd, no, it's not that kind of option.

In theory such options (there are also other categories that do not show up there) could be added dynamically there but that would complicate code a lot without too big gain (as these settings have own, dedicated configuration methods).

But if we will follow that way then someone could ask to add there User Agents etc., that could lead to extreme amount of entries there, making quick changes way harder.
