### ISSUE TITLE
Fine-tuning for statusbar

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#760]
I have moved the trashcan (closed tabs button) to the bottom right corner on the status bar, but there's still plenty of space to the right of the button. Does this space have some unknown future purpose or is it a design glitch?

**Comment by Emdek** [comment]
It's size grip, it could be a good idea to treat is as special entry and show only if it is on the list.
There is also issue with initial width of that widget, but it might be harder to fix (at least without workarounds).
