### ISSUE TITLE
Bookmark saving: folder selector does not work

### ISSUE THREAD

**Issue by ThebestwaytodesignJoinGitHub** [OtterBrowser/otter-browser#762]

**Comment by Emdek** [comment]
Please elaborate more, I have no idea to which element exactly you are referring.
This could be bookmarks combo box or bookmarks menu or other stuff.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
Bookmarks Menu -> Add Bookmark... -> Folder: [select a subfolder]
Press OK
The new bookmark is NOT saved in the selected subfolder, it appears on top of the hierarchy
