### ISSUE TITLE
Lock toolbars not working

### ISSUE THREAD

**Issue by resbro** [OtterBrowser/otter-browser#766]
weekly 65 both x32 and x64
Windows 7 x64

**Comment by Emdek** [comment]
Can't reproduce, Windows 7 32 bit and Linux.
What exactly doesn't work correctly, drag handles are still visible (this is the only thing that is locked)?

**Comment by resbro** [comment]
sorry Michal, I thought it was supposed to suppress the dialog box and not allow any changes. If all it's supposed to do is hide the drag handles, then it works fine!

**Comment by Emdek** [comment]
@resbro, no problem.
It will become more useful when there will be a possibility to rearrange toolbar items by drag and drop. ;-)
