### ISSUE TITLE
Browser isn't starting after "Toolbars > Reset to Defaults..."

### ISSUE THREAD

**Issue by VSHY** [OtterBrowser/otter-browser#767]
STR:
1. Start browser.
2. Open "Navigation bar > Configure..." and add any action, press Ok in this dialog.
3. Choose "Toolbars > Reset to Defaults..." (after that in Otter profile was created "empty" file toolBars.json).
4. Close browser.
Try to start browser.

AR:
The browser isn't started.

**Comment by VSHY** [comment]
I installed otter-browser-win32-beta5-hotfix.zip, but apparently the changes "Add an extra check, references"  didn't included. The browser isn't started also.
File toolBars.json contained:
---
[
]

---

**Comment by Emdek** [comment]
@VSHY, I've  tried to reproduce it using Windows 7 and Linux, but cannot reproduce it so far. :-/
I can later try to prepare some kind of debug build and check the output to determine where exactly it breaks.
The likely cause is missing instance of *TabBarWidget*, but there are checks that should readd it anyway (and shouldn't be needed if that file is empty anyway).

**Comment by VSHY** [comment]
@Emdek 
I'm using Win7 64-bit and Otter 32-bit with a 100% reproduction.
Ok. This can be investigated later, there are more important things now.

**Comment by Emdek** [comment]
@VSHY, well, that is kind of important issue. ;-)
It would be good to fix it for next weekly.

**Comment by VSHY** [comment]
In #67 build I can't reproduse this bug.
Thanks!
