### ISSUE TITLE
"Navigation Bar > Remove..." is not working

### ISSUE THREAD

**Issue by VSHY** [OtterBrowser/otter-browser#768]
1. Right-click on a enabled button, choose "Navigation Bar > Remove..." - nothing happens.
2. Right-click on disabled buttons isn't working, although the ability to delete of the buttons should be, regardless of their availability. For example: open browser, add button "List of Closed Windows" into Navigation Bar, after this try to press right-click on it.

**Comment by Emdek** [comment]
You can't remove predefined toolbars, just hide them (which means that they won't be created anyway until shown again, with exception of tab bar).

Context menus are blocked by implementation of ``QToolButton`` and ``QAbstractButton``, I'm trying to override it but for some reason that works only for bookmark buttons, but I have one more idea how to workaround it.

**Comment by Emdek** [comment]
Blah, I was testing that on the only button that wasn't based on ``ToolButtonWidget``, well, at least now it uses proper base class. ;-)

**Comment by VSHY** [comment]
:)
Thanks for what you are doing!

**Comment by VSHY** [comment]
In #67 build, I noticed that "Remove..." the menu item is always desibled on any buttons.
