### ISSUE TITLE
Exceptions for third party cookies

### ISSUE THREAD

**Issue by Emdek** [OtterBrowser/otter-browser#770]
We need to allow to define list of hosts to accept third party cookies when policy is set to ignore them and list of hosts to ignore them when policy is set to accept third party cookies.

Related ticket: #463.

**Comment by VSHY** [comment]
First of all I would like to have the option "Accept cookies only from the sites I visit" (without third party cookies) that there is in Opera Presto. In common Preferences the option "Accept third-party cookies" I setted to "Never", but it isn't working - I see a third-party cookies in the Cookies Manager.

**Comment by Emdek** [comment]
@VSHY, weird, that should be handled by QtWebKit, I'll check, maybe something is missing or got broken.

**Comment by VSHY** [comment]
Third-party domains like are created. But sometimes I open some site and in corresponding cookie-domain I see "MarketGidStorage", is it normal?

**Comment by Emdek** [comment]
@VSHY, could you please provide some screenshot illustrating this issue (it can be cropped to just that entry plus information about parent domain)?

**Comment by VSHY** [comment]
@Emdek 
I don't see it in the last few builds. Question withdrawn.
Thanks!
