### ISSUE TITLE
Accessibility of about: pages

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#771]
For example in about:history I can navigate up and down the list with keyboard, but I cannot go to a selected URL by pressing Enter.

Also, when I make Otter window small with the about:history page in it, and I have keyboard shortcuts to scroll left-right, the same keybinds don't work in the about:history page.

And there are tooltips in about: pages when I have set them off in the settings as best I could.

**Comment by Emdek** [comment]
Lets keep single ticket for such stuff, so I'm adding here relevant points form #604:
 - bind find and quick find to search fields;
 - support basic editing shortcuts (Delete, Copy, etc.) everywhere;
 - drag and drop where applicable.

**Comment by Emdek** [comment]
Related ticket: #366.

**Comment by Emdek** [comment]
> bind find and quick find to search fields;

Done.

**Comment by Emdek** [comment]
Seems to be done now.
