### ISSUE TITLE
Flash buttons not accessible when page zoom decreased

### ISSUE THREAD

**Issue by ghost** [OtterBrowser/otter-browser#772]
I have to zoom the pages to 100% first, windows and linux.

**Comment by Emdek** [comment]
That looks like an upstream issue, maybe incorrectly mapped events or something like that.
It would be best if you could confirm that using some simple *QtWebKit* based application, the best would be *demobrowser* from SDK.
Then it can be reported upstream.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
Any google video?
Btw where can I get this demobrowser?

**Comment by ThebestwaytodesignJoinGitHub** [comment]
Windows only, sorry

**Comment by Emdek** [comment]
Confirmed with *test-qtwebkit* and reported upstream as [QTBUG-46520](https://bugreports.qt.io/browse/QTBUG-46520).
