### ISSUE TITLE
No way to disable all notifications?

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#773]
Notifications can only be disabled individually through the **Preferences**.

Does **Browser/EnableNotifications** really work?!

Shouldn't it override individual settings?

**Comment by Emdek** [comment]
That setting is for HTML5 notifications. ;-)
For built-in ones there is only fine-grained configuration, but don't worry, most likely by default  there will be enabled only one more notification, about availability of new version, which could be disabled by disabling checking for updates (and auto updates won't be enabled by default anyway).
