### ISSUE TITLE
If install's folder contains Cyrillic symbols then browser isn't starting

### ISSUE THREAD

**Issue by VSHY** [OtterBrowser/otter-browser#774]
Download a archive with Otter (I used zip), than unpack it to ...\Программы\. (in Russian; same in English: ...\Programs\.).
Try to start the browser, and see:

1st error message:
____
otter-browser
____
This application failed to start because it could not find or load the Qt platform plugin "windows".
Reinstalling the application may fix this problem.
____
ОК   
____

2nd error message:
___
Microsoft Visual C++ Runtime Library
___
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
___
ОК   
___

As a result the browser wasn't started.

P.S. The other Qt-programs: VLC media player, CoolReader, etc. are working in the same folder.

**Comment by Emdek** [comment]
Works fine here, at least when using 32 bit variant under Windows 7.
Are you using 64 bit version?

**Comment by VSHY** [comment]
I used Otter 32-bit version under Win7 64-bit.

**Comment by Emdek** [comment]
@VSHY, which drive was that?
Posting full path would be best.

**Comment by VSHY** [comment]
d:\Downloads\Программы\Otter\<otter-files>

**Comment by bajasoft** [comment]
Just tested it on clean Win 8.1 with 64bit version. It really fails when there is no Qt installed. When I changed the folder name to latin only it worked fine.
