### ISSUE TITLE
Processing browser closing button

### ISSUE THREAD

**Issue by VSHY** [OtterBrowser/otter-browser#775]
The people want the option in common Preferences which subj; actions:
- close program (as it is now) - by default;
- ask (this asking more of all);
- hide to tray.

This option should be related to the button for closing window only. Menu action "File > Exit" should just close the browser.

**Comment by beastie1** [comment]
Do you mean like setting **Choices/WarnQuit** (in [about:config](about:config) ) to something other than **noWarm**?

**Comment by VSHY** [comment]
This is what I need! Thank you!
I apologize for this ticket.
