### ISSUE TITLE
Race condition when middle-clicking the New Tab button

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#780]
This doesn't cause any trouble as far as I can tell, but it's just some weird behavior.

1. Set **TabBar/LastTabClosingAction** to **doNothing**
2. Make sure there are no tabs open
3. Middle-click the **New Tab** button: a new tab is created but with no visible **WebWidget**; I guess it's created but gets destroyed right away by the middle-click, yet Otter doesn't destroy the tab's title button

**Comment by Emdek** [comment]
Nope, it was just trying to open it in background (that means without setting current index to that tab, which would show ``WebWidget``) while there were no other tabs, simple exception will fix that. ;-)
