### ISSUE TITLE
Microsoft Visual C++ and newest stable Qt in Otter browser in portable version and installer.

### ISSUE THREAD

**Issue by Piter432** [OtterBrowser/otter-browser#781]
Hello.

Currently both - portable and normal installer versions have only Otter browser and some it's components, but don't have integrated to install newest stable Qt and proper version of Microsoft Visual C++. I think, you should implement in the installer a downloader and installer, which will download and install both newest stable Qt and proper version of Microsoft Visual C++, similar is with portable version.

Don't you agree? :)

**Comment by Emdek** [comment]
It's not feasible to allow to download newest Qt, due to #631.
I don't think that MSVC redistributable is released very often, shipping it should be enough.
