### ISSUE TITLE
Site Specific Proxies

### ISSUE THREAD

**Issue by opticyclic** [OtterBrowser/otter-browser#785]
In order to access certain websites I have to use a tunnel.
However, I don't want to use the tunnel for all websites and I don't want to use a proxy at all for intranet sites.

FoxyProxy (https://addons.mozilla.org/en-us/firefox/addon/foxyproxy-standard/) allows you to specify sites or wildcards to use different proxies.

**Comment by lollox** [comment]
For what I see in current build, this is already planned (Website preferences > Network > Proxy)

**Comment by Emdek** [comment]
Yeah, it is planned.
But only after separating proxy definitions from main configuration file, allowing to define list of them, so user could select one just like in FoxyProxy.
The main blocker right now is storage, I'm not sure if it would be better as single JSON file or multiple INI files etc.
I'll need to check how FoxyProxy stores them. ;-)

**Comment by The-Compiler** [comment]
> The main blocker right now is storage, I'm not sure if it would be better as single JSON file or multiple INI files etc.

For what it's worth, I plan to use [yaml](https://en.wikipedia.org/wiki/YAML) for qutebrowser as it's a nice hierarchical format, and easily human-readable. But I don't know what C++ libraries there are for it, and if you want to use non-Qt libs.

The problem with JSON is it usually doesn't allow comments, which is nice in config files...

**Comment by Emdek** [comment]
@The-Compiler, well, comments wouldn't be preserved anyway, dedicated fields for description etc. are better idea for a file that is supposed to be overwritten. ;-)

**Comment by KottV** [comment]
I've tried lates -git, per site proxy settings still doesn't applies.
