### ISSUE TITLE
occasional errors on google-redirected pages (Error 3)

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#786]
Hi, I'd like to report occasional errors with loading of some apparently redirected pages from the result list of a google search.
Most regularly I am getting this in connection with the price comparison portal heureka.cz; 
a google search for "heureka.cz":
https://www.google.cz/search?q=heureka.cz
the first hit I am getting links to that very mainpage, its google-URL is something like:
https://www.google.cz/url?q=http://www.heureka.cz/&sa=U&ei=5a0lVa7MFYqNsgHUhoCIDQ&ved=0CCYQFjAA&usg=AFQjCNFBU_RdAmZDO3M-r3GVbFU8fik5dA  

but this link can't be opened in Otter, only "http:/" appears in the address bar, an the following errorpage is shown:
Error 3
Host not found
I am not sure, what content or headers is being served, but other browsers I tried can handle this address and load the target page.
reards,
   vbr

**Comment by vbr** [comment]
Just a quick addition I just noticed - after the mentioned error appears, I am even unable to load that page using the direct address ( http://www.heureka.cz/ ) in the respective tab - it leads to the same Error 3; in a new tab, however, this succeeds. It appears, the tab/session data are somehow invalid till the tab ic closed.
vbr

**Comment by Emdek** [comment]
@vbr, which platform are you using?
There is special package for Windows (32 bit) that could be used in conjunction with 32 bit build to test such issues using basic QtWebKit browser, to determine if issue is upstream or not.

**Comment by vbr** [comment]
Hi,
I am currently using Windows 7 Home Premium, SP 1, Czech, 64bit
and 32bit Otter: 0.9.06 weekly 67  (otter-browser-win32-weekly67.7z)

It turns out, that the problem isn't connected with google redirection (the title of the issue might be changed accordingly).
The mentioned page http://www.heureka.cz/ can be loaded, but most of the links "don't work" and lead to the errorpage "Error 3 - Host not found", while only "http:/" appears in the adressbar.
opening the same links in new tabs works ok, but the same error occurs few clicks later.
I am not sure about the mentioned testing package, but using "browser.exe" from the Otter directory (possibly some leftover form the ancient releases) I don't see the mentioned problems.

Well, now, when I am testing a fresh unpacked folder with the latest Otter, the problems don't appear. Could it be, there are some version mismatches  from older leftovers, which remain in place as new version are simply copied over and only the existing file are overwritten.
On the other hand, is it possible, that such problem only appear on specific pages?
vbr

**Comment by bajasoft** [comment]
I believe it is a problem in content blocking with czech easylist, I can reproduce it too. It should block heureka links on third party sites, but somehow it fails also for direct access.

**Comment by vbr** [comment]
Thanks for the hint, it indeed seems to be the case. With deactivated blocklist I don't see the mentioned problems, the fresh "install" probably also has no blocking set.
The specifically targeted handling of the content blocking would also explain, that the problems appear on the single web.
Thanks and regards,
           vbr
