### ISSUE TITLE
Image centring

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#787]
I noticed that when I go to image documents, such as here http://www.slackel.gr/isos/screenshots/openbox-live-6.0.3/ 
there is a kind of centring script at work. 

The problem with it is that it's slow and sluggish. The image loads at the left edge first and then jumps to the centre. It should load in the centre. 

Image centring should feel totally native and natural, glitchless, not an imposed extra  fanciness.

**Comment by Frenzie** [comment]
It's a QtWebKit issue. But I can probably work around it by simply hiding the original image through CSS. Next week at the earliest.

**Comment by ersi-dnd** [comment]
thx cheers :)
