### ISSUE TITLE
Tabs on bottom

### ISSUE THREAD

**Issue by Hombremaledicto** [OtterBrowser/otter-browser#788]
Hello, 
I would like to ask if there's any chance to get an option to set tabs below the main toolbar, this would help integrating otter with some Qt styles: 

<a href='http://postimg.org/image/hga1lwi1p/' target='_blank'><img src='http://s14.postimg.org/hga1lwi1p/schermata1165.jpg' border='0' alt="schermata1165" /></a>

**Comment by uahim** [comment]
on Windows, if you right click on the toolbar and deselect/uncheck 'lock toolbars' you can drag the tabbar to the bottom. I would assume this should apply to Linux versions too?

**Comment by srgloureiro** [comment]
You are saying two things completely different from each other.  

@Hombremaledicto wants to have the tabs below the title bar, oriented in reverse,  the same way it happens in Safari browser.

@uahim is speaking about having tabs at the very bottom of the application window, a tabbing mode mode supported on Classic Opera.

**Comment by uahim** [comment]
indeed, my bad, sorry.

**Comment by Hombremaledicto** [comment]
> on Windows, if you right click on the toolbar and deselect/uncheck 'lock toolbars' you can drag the tabbar to the bottom. I would assume this should apply to Linux versions too?

I've actually already tried with dragging the tabbar, and i can put it anywhere apart from below the Navigation Bar (that's what i'm trying to do). 

> @Hombremaledicto wants to have the tabs below the title bar, oriented in reverse, the same way it happens in Safari browser.

No, the tabbar is already below the titlebar (the deco) and reveres a la safari, which is done by the Qt style i'm using. 

I managed to get what i want by creating another toolbar with the same layout/buttons of the Navigation Bar, but for some reason the customizing dialog vanished after the first try (maybe i should open a separate issue for this)

**Comment by Emdek** [comment]
@Hombremaledicto, navigation bar is special case, it belongs to tab itself, just like it used to be in Opera.
That is needed due to MDI.

Which version are you using?
That issue with configuration dialog of toolbar existed in beta, it affected only the last toolbar.

**Comment by Hombremaledicto** [comment]
@Emdek just checked, it was 0.9.05 ( i just took the wrong version from the arch user repository, i was looking for the git one), now i compiled 0.9.06 and the toolbar issue is indeed fixed.

**Comment by Emdek** [comment]
@Hombremaledicto, OK, then we can consider this ticket as invalid.

In theory we could allow to drag navigation bar elsewhere but that would lead to other issues (if it could be dragged out then it should be possible to drag it back there etc.).

**Comment by Hombremaledicto** [comment]
Indeed... And thanks!
