### ISSUE TITLE
Weekly 68 zoom issues

### ISSUE THREAD

**Issue by resbro** [OtterBrowser/otter-browser#792]
Trying to sign in to GitHub with the new weekly 68, The zoom out is actuated by the  number 9. Doesn't do it with weekly 67. Also, I think the backspace button is making the page history go back to previous page. at least occasionally.

Windows 7

Otter weekly 68 x32

**Comment by resbro** [comment]
The zoom thing has stopped happening (week 70).

Win 8.1 x64

**Comment by Emdek** [comment]
@resbro, there was a regression, probably caused by outdated or mixed libraries.
