### ISSUE TITLE
View background image: is this really missing?

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#794]
Even FF has "View background image" under right-click. Somehow I am not seeing this in Otter. Is it intended to keep the right-click menu the same regardless whether there's a background image or not?

**Comment by Emdek** [comment]
Such action is definitely doable, but yeah, do we really need it?

**Comment by ersi-dnd** [comment]
Do we have scriptlets now so I could try composing my first scriptlet for this function?

I would very much like scriptlets to be able to extract all kinds of data from webpages and launch it on address field or save to notes or display as an info panel or direct to an external app or whatever. Would be great.

**Comment by beastie1** [comment]
IMHO of course, this is not indispensable, but still valuable and nice to have.

**Comment by Emdek** [comment]
It's definitely task for extensions.
