### ISSUE TITLE
Back button stops working correctly

### ISSUE THREAD

**Issue by resbro** [OtterBrowser/otter-browser#795]
Once in a while the back button stops working right. The dropdown menu still works if you hold it down, (and keyboard Z) so it's not that bad but, sometimes it just wont go back be pushing the back button with a mouseclick alone.

Win 7 x64
Otter week;ly 68 x32

**Comment by ThebestwaytodesignJoinGitHub** [comment]
Same as #642

**Comment by resbro** [comment]
yeah, could be.I remember that one now. I could never make it happen in win 7 til now.

**Comment by ThebestwaytodesignJoinGitHub** [comment]
Has never been fixed for me, too.

**Comment by Emdek** [comment]
@resbro, have you seen that issue in recent weeklies?
Recently there was change that eliminated one of possible reasons for this issue.

**Comment by resbro** [comment]
Actually, it does seem better this morning. I'll keep an eye on it today, but so far it seems to be OK.

**Comment by resbro** [comment]
This does seem MUCH better. there are still some issues, but it has not gone "dead" all day.

**Comment by Emdek** [comment]
@resbro, thanks for testing.
