### ISSUE TITLE
issue with loading a page with unity 3D web player 

### ISSUE THREAD

**Issue by ejoshva** [OtterBrowser/otter-browser#797]
I have tried loading a page with Unity 3D web player. 
It gets loads with out any issues in Windows 7.

I have downloaded the code and build the browser using Qt creater and tried loading the same page, only blank page is shown.

I would like to know, how is this Unity 3D plugin loaded in QWebEngineView.

Thanks

**Comment by Emdek** [comment]
Duplicate of #798.
