### ISSUE TITLE
issue with loading a page with unity 3D web player 

### ISSUE THREAD

**Issue by ejoshva** [OtterBrowser/otter-browser#798]
I have tried loading a page with Unity 3D web player. 
It gets loads with out any issues in Windows 7.

I have downloaded the code in Mac and build the browser using Qt creater and tried loading the same page, only blank page is shown.

I would like to know, how is this Unity 3D plugin loaded in QWebEngineView.

Thanks

**Comment by Emdek** [comment]
Which technology is used by Unity 3D web player?
QtWebEngine is far from being complete, AFAIK it finally got support for PPAPI flash in dev branch.

**Comment by Type-kun** [comment]
Just for a record, Unity 3D uses the same NPAPI plugin architecture that old Flash or Java plugins do. Even heavy apps like http://superhotgame.com/play-prototype for instance work fine, as expected. Perhaps the plugin was not installed or blocked until clicking (that's the default behavior, I think)

**Comment by Emdek** [comment]
@Type-kun, in that case I have bad news, it seems that it won't be available in QtWebEngine, as upstream is going to remove support for NPAPI:
http://en.wikipedia.org/wiki/NPAPI#Browser_support

There is some initial work on bringing pepper for flash, but scheduled after Qt 5.5...
https://trello.com/c/xH2kPw8T/81-add-support-for-plugins

**Comment by Type-kun** [comment]
> it seems that it won't be available in QtWebEngine, as upstream is going to remove support for NPAPI:

Huh. That's a bad idea, since that means no Unity, no Java and no Silverlight, to name just a few. I think that out of popular webapp platforms, only Flash is ported to PPAPI. Chromium dropped the support recently, and the only response that all these plugin users got from their respective developers, including Unity's, was "switch to Mozilla". It is not a smart move on QT's side to drop support now, I think.

**Comment by The-Compiler** [comment]
Qt isn't dropping support - it just never was implemented for QtWebEngine, and it makes little sense as Chromium (as an upstream of QtWebEngine) is phasing it out:

>  In September 2013, Google announced that it would phase out NPAPI support in Chrome during 2014 because "NPAPI's 90s-era architecture has become a leading cause of hangs, crashes, security incidents, and code complexity".[6] NPAPI support was removed from the Linux version of Chrome in May 2014 (version 35).[7] NPAPI support is disabled by default since April 2015 (version 42) for Windows and OS X, but can be turned on in the settings. Google plans to drop Chrome NPAPI support from all platforms in September 2015.[8]

**Comment by ejoshva** [comment]
But how is that it's getting loaded with out any issues in windows 7

**Comment by Emdek** [comment]
@ejoshva, no idea, maybe someone started to work on support for plugins starting with that platform and forgot to remove / disable that code...
BTW, you should check which backend is used (in About Application dialog), just to be sure if it was QtWebEngine and not QtWebKit.
