### ISSUE TITLE
Link salad

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#799]
Link salad is my own term. I don't know of any better more official name for it. It means series of links immediately or near-immediately following each other, such as in menus or in forum pagination. 

It's a nice convenience feature to truncate link salads. Opera Mini does this by showing a plus sign and only the first link. The rest of the links can be expanded by clicking the plus sign.

It could be a config option - Truncate link salad: true | false

This feature could fit nicely together with spatial navigation and such.

**Comment by Emdek** [comment]
This sounds like a task for some extension.
