### ISSUE TITLE
Single-key shortcuts fire while inside input tags and flash applications

### ISSUE THREAD

**Issue by Type-kun** [OtterBrowser/otter-browser#802]
A primary reason for why #801 is necessary: single-key shortcuts fire when they should not. Pressing `z` or `backspace` key while the focus is in the textbox will actually change page to the previous one instead of typing `z` or deleting the symbol. Same will happen when the focus is inside a flash app or game: anything pressed while the focus is inside the app will bubble to the browser and execute a corresponding single-key shortcut action. That's pretty ridiculous and I'm not sure how it went unnoticed for about 3 months (I think it first occurred around the end of January).

E: Forgot to mention this happens on Windows x32 build, didn't test other versions.

**Comment by Emdek** [comment]
Which Windows version?
It's known to happen for flash content, but there was also report for Windows XP.
https://bugreports.qt.io/browse/QTBUG-39714

**Comment by Type-kun** [comment]
Yes, the symptoms for that bug look just like mine. Happens on Windows XP SP3, x86. Also, just tested on a virtual machine with Win7 x86, it shows same behavior for inputs, can't test flash at the moment.
