### ISSUE TITLE
Ugly tabs in KDE5

### ISSUE THREAD

**Issue by tmysik** [OtterBrowser/otter-browser#803]
Just updated to Kubuntu 15.04 which has the new KDE5 and Otter Browser looks more ugly than on KDE4, especially the tabs - see screenshots.

Thanks.
![otter-1](https://cloud.githubusercontent.com/assets/331924/7468788/e8626ec4-f30c-11e4-8cda-c70c2595359e.png)
![otter-2](https://cloud.githubusercontent.com/assets/331924/7468789/e86c6078-f30c-11e4-9a42-e509bfbdff84.png)

**Comment by Emdek** [comment]
@tmysik, we don't mess with style of tab bar yet (except of vertical mode) so this one can be considered a style issue (bug or feature) if it differs from other tab bars.
Are you using pinned tabs or there is sizing issue for tabs?

In case of zoom slider this is definitely a bug in style as it seems to ignore available size which results in cut of handle.

Address field will be tricky, it seems that this style adds extra padding which results in incorrect drawing of badge, that one probably could be fixed somehow, could you please post some details about that theme (at least name)?

**Comment by tmysik** [comment]
@Emdek 
> Are you using pinned tabs or there is sizing issue for tabs?

Yes, the "squares" are pinned tabs.

BTW I reported this issue since I am using KDE4 as well as KDE5 and have to say that KDE4 version looks much nicer - but not sure whether it is problem of Otter Browser or Qt, of course.

Thanks for your great work!

**Comment by Emdek** [comment]
@tmysik, since I'm currently forced to use KDE5 (Kubuntu doesn't give choice and forces it with 15.04 :-/) I've tested it and it appears to be a bug (more likely, as that rectangle is cut off when buttons next to tab bar do not increase height of toolbar) or feature in Breeze widget theme.
For some reason it doesn't behave that way when tab bar is placed on the bottom.

**Comment by Emdek** [comment]
This bug (or maybe feature?) is also visible on scaling animation here:
http://blog.davidedmundson.co.uk/blog/high_dpi_again
