### ISSUE TITLE
several about:config pages can be opened

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#805]
many about:config pages can still be opened one by one by opening a new tab and typing it to the address field, also the secondary address field

**Comment by Frenzie** [comment]
I'm not quite sure how that's a problem?

**Comment by ersi-dnd** [comment]
Well, imagine someone tweaking the settings. Then turning the attention somewhere else meanwhile, changing the tab. Then he thinks to tweak some more, but does not remember/not notice that about:config is open, so he opens a new one. Questions arise:

Will the new about:config show what's already tweaked even when it was not saved? What will happen when he tweaks some in the new page and presses save? Will the previous unsaved tweaks be also saved? Etc.

All these questions would have their natural answer when only one about:config page is permitted.

But yeah, it's only a theoretical problem, a fine-tuning sort of thing.

**Comment by Frenzie** [comment]
Conversely, you could imagine someone having two configuration pages open
at once on different sections of about:config. Or perhaps even two
instances: a "before" and a "tweaking" about:config.

I suppose it might be interesting to investigate what e.g. Opera (both old
and new) and Firefox do. All of them allow multiple
opera:settings/about:config pages.

How would you propose only being able to open one about:config? An
automatic tab switch?

**Comment by ersi-dnd** [comment]
@Frenzie 
> How would you propose only being able to open one about:config? An automatic tab switch?

No idea. Some rule that says "When about:config is open, switch to it rather than opening a new one. But maybe there are indeed legitimate user cases to have a bunch of them open. Since Otter allows opening multiple windows and profiles at the same time, maybe it's easiest just to forget about this ticket.

**Comment by DI555** [comment]
I can do this in Otter, FF, opera12.....it's useful when you editing multiple options!!!    why should I not to do this ????????
>>>>Since Otter allows opening multiple windows and profiles at the same time
-multiple windows-yes, profiles - not yet
>>>>>maybe it's easiest just to forget about this ticket
-may be....-you shoud asking about optional(switchable) future "switch to existant tab when open duplicate tab"(any tab with exactly the same url)

**Comment by ersi-dnd** [comment]
@DI555 
> -may be....-you shoud asking about optional(switchable) future "switch to existant tab when open duplicate tab"(any tab with exactly the same url)
Nah, this is too Firefoxy. I guess since you are okay with multiple about:config pages, then so will I.

**Comment by DI555** [comment]
btw imho the optional future "switch to existant tab when opening duplicate tab" with suboption "ask if it is so"

it would be great if you have a lots of tabs (more then 50 like I have))) and need to quickly switch to needed tab !!! and the suboption "ask to switch" makes it more comfortable !

**Comment by Emdek** [comment]
@DI555, we are switching to existing tab if special page is triggered by action.
