### ISSUE TITLE
Enables running multiple instances of the application with different profiles

### ISSUE THREAD

**Issue by DI555** [OtterBrowser/otter-browser#807]
Something like mozilla's "no-remote" command in command line would be great to implement!

**Comment by Emdek** [comment]
It is already possible:
> --profile <path>     Uses <path> as profile directory

**Comment by DI555** [comment]
nope((( it starts... but it doesn't work((( with :
"Error 203
Error opening http://..."

**Comment by DI555** [comment]
...I mean the same program copy with different profile (win build)

**Comment by Emdek** [comment]
@DI555, works fine for me, just tested under Windows 7 32 bit.
Please post more details about your setup (most important is if you are using 32 bit or 64 bit build).

**Comment by DI555** [comment]
it's Win7-32
the second copy with different profile(and different cache folder) starts well, but it doesn't load pagees at all((
now it's:
"Error 1
Connection refused"

I didn't find error console((, so I could see the exact error cause.

**Comment by Emdek** [comment]
@DI555, this error translates to:
*the remote server refused the connection (the server is not accepting requests)* (`QNetworkReply::ConnectionRefusedError`).
Does the same happen when trying to use private tabs in that instance?

**Comment by DI555** [comment]
yes, exactly;  and the private tab "private" icon is dissappeared
