### ISSUE TITLE
QtWebEngine - leaving the trash RLZ code(library).

### ISSUE THREAD

**Issue by DI555** [OtterBrowser/otter-browser#808]
Somewhere in deep of Chromium saurce there in one big bunch of code named RLZ ...
It wispers, spying etc/ to bigG... in Chromium people say that its needed onlu switch off the swithers... but it might not true...there is might some api in that RLZ code... and that's might the big G pays for using Chromium...
So the Digia porting it to QtWebEngine ... and I'm sure RLZ code is there ((((
And may be even not effective pick this topic in QtWebEngine discussion ((( if bigG is in. So Digia won't cutting it in QtWebEngine(((

The main asking is to cut off the all RLZ code(library) from QtWebEngine in Otter!
(some "spying" honey words:
http://blog.chromium.org/2010/06/in-open-for-rlz.html )

I hope this spying RLZ library could be eliminated from the Otter!!! at all!

**Comment by The-Compiler** [comment]
According to the blog post you've linked, only Chrome but not Chromium includes RLZ (emphasis mine):

> **Chromium will also continue to exist as it always has, without any RLZ library included.** And, you can still download a Google Chrome with no RLZ behavior at www.google.com/chrome. But now that RLZ is open, Google Chrome distributed through promotional means will include this open-source implementation of RLZ.

**Comment by DI555** [comment]
nope(((, it's with that bad code(or some other) ((( and still wispinig(((
people tested chromium on wireshark -
http://translate.google.ru/translate?hl=en&sl=ru&u=http://habrahabr.ru/post/101396/

**Comment by DI555** [comment]
as I know chromium now is building by default with this RLZ code.....so imo - RLZ is in QtWebEngine !!! (((

**Comment by Emdek** [comment]
@DI555, I guess it would be best to simply ask devs, for example using #qtwebengine IRC channel at Freenode.
