### ISSUE TITLE
Improve sizing of tab modal dialogs

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#810]
When I need to log in to my work's intranet, other browsers provide a prompt for username and password. Otter attempts to do the same, but the prompt looks unusable.
![ekraanipilt_2015-05-13_13-36-16](https://cloud.githubusercontent.com/assets/6865273/7608774/57f74b56-f975-11e4-876b-3f3732e52a55.png)
(Note: To make the screencapture, I resized Otter window to smaller. Otter was maximised at first. But the prompt looks the same regardless the size of the main window.)

**Comment by ersi-dnd** [comment]
This affects one Otter installation on one of my machines. On the other machine I get a normal prompt. But since the profiles are identical, it's still wtf. The only important difference here is that on the new machine (on the screenshot) I have the latest GIT update.

**Comment by Emdek** [comment]
@ersi-dnd, most likely it was caused by window size.

**Comment by ersi-dnd** [comment]
The window was not fully maximised when I entered the URL and this triggered a bug?

**Comment by Emdek** [comment]
@ersi-dnd, yes.
