### ISSUE TITLE
Closed tab list doesn't show favicons

### ISSUE THREAD

**Issue by Type-kun** [OtterBrowser/otter-browser#817]
This is a minor bug, but closed tab list doesn't show any favicons as of last version, looking like this: http://puu.sh/hPDhJ.png . It did in Opera 12, and it was handy enough to find relevant entries quickly without having to read each and every one.

**Comment by Emdek** [comment]
It appears that QtWebKit forgets about favicon as soon as page gets closed. :-/

**Comment by Emdek** [comment]
To be improved as part of #820.

**Comment by VSHY** [comment]
The build 72 doesn't show favicons. It can see if close the site otter-browser.org.

**Comment by Emdek** [comment]
@VSHY, there is some kind of issue with how they are stored or retrieved from history, this need some debugging as part of above ticket.

**Comment by VSHY** [comment]
@Emdek,
In my some Opera skin was the old icon. Time passed and I changed it to a new, because it did not correspond icon which located into the address bar, history, etc.
Therefore, a static icon - not a good idea.
It has two different logic, and each has a right to exist.
