### ISSUE TITLE
A few issues when editing a note item

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#819]
*F8 (Activate address field) opens up secondary address field* both inside a note item and in the notes list. Maybe this is intended, but in my opinion F8 is more appropriate only for the primary address field. Primary address field is nowhere in Notes, so F8 should do nothing. Or, if the user has moved the primary address field to e.g. statusbar or menubar, then F8 should go there.

*F9 (Activate content) does nothing.* This is the action that I would distinctly like to do something when I am in a note item and editing it. Namely, I would like it to take the focus out of the editing area. Let's say I am typing in the note item, and then I need to switch tabs. The natural keyboard way is to take the focus out of the editing area and then Ctrl+Tab. 

I noticed that *Shift+Tab* takes focus out of the note editing area. It does pretty much what I wanted F9 to do, and I think that, for the sake of consistency, F9 ("Activate content") should indeed do it. F9 should  take me out of the editing area and put the focus maybe on the notes list. 

There's no fonts configuration in Notes list, Notes item, in fact nowhere in about:pages, in Bookmarks, Downloads list, etc. I suggest that editable areas in about:pages and panels should have one kind of font, ineditable places should have some other, and there should be settings to adjust them both.

**Comment by ersi-dnd** [comment]
And the editing interface: Good to have a resizable editing area, but it would be even greater to have an option to split it the other way too. I mean, the Notes List and Editing area has a horizontal separator right now, but it would be nice to be able to toggle it to vertical.

**Comment by Emdek** [comment]
@ersi-dnd, fonts now have own ticket, #847.
Option to use horizontal view might be added in future.
