### ISSUE TITLE
"Return the closed tab" item in tabs-menu

### ISSUE THREAD

**Issue by VSHY** [OtterBrowser/otter-browser#821]
Please, add subj and shortcuts Ctrl+Shift+T and Ctrl+Y for this command!
The menu item is very useful especially when you are placed far from keyboard.

**Comment by Emdek** [comment]
`Ctrl+Shift+T` is already available while `Ctrl+Y` is already used by Redo.
It will be possible to add this action in almost any menu when #65 will be implemented.
