### ISSUE TITLE
New tab issues

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#824]
Right-click on a link and Open in new tab opens a new tab.

Right-click on a link and Open in new background tab opens in foreground tab. This should open a background tab.

Ctrl+click on a link opens a new window. This used to open a new tab.

Shift+click on a link opens a new window. This used to open a new background tab.

And perhaps there's more similar glitchy behaviour.

**Comment by Emdek** [comment]
@ersi-dnd, first issue happened only if MDI was enabled, this is already fixed.
Other cases seems be caused by setting *Browser/OpenLinksInNewTab* to *FALSE*.

**Comment by ersi-dnd** [comment]
Midclick on a link opens new window. Shouldn't.

**Comment by ersi-dnd** [comment]
Mmno.. Thinking backwards more carefully, I did not touch that setting when I enabled MDI. I had OpenLinksInNewTab set at False long before, and it behaved differently until MDI was implemented. 

Anyway, it's okay as it is, I think. I have set it to True now and I am not too worried about the new tabs I keep getting. They are tabs now, not windows.

**Comment by Emdek** [comment]
@ersi-dnd, I guess that in this case it would be best to check how classic Opera behaves in this case.

**Comment by ersi-dnd** [comment]
I don't like exactly how old Opera behaves in all details either, because there were a few inconsistencies. 

However, old Opera was very consistent about Ctrl+click on link and Shift+click on link. Right now, in Otter, both these open a new foreground tab. In old Opera, Ctrl+click on link used to open a background tab.

**Comment by Emdek** [comment]
@ersi-dnd, that issue with background tab is already fixed, at least works fine for me (MDI enabled).
Currently these modifiers are affected by option to prefer new windows over new tabs, the question is, should it stay like this or be fixed to always open tabs.

**Comment by ersi-dnd** [comment]
@Emdek  Yes, Ctrl+click and Shift+click look fixed now (I had not updated Otter for a while). 

About tabs versus windows, I always prefer tabs. In my opinion, the very idea of tabs (Opera called them pages originally) is to never have windows. When I want another window, I open it explicitly, via the explicit menu item or keybind built just for that. 

Then again, Opera has opera:config#UserPrefs|SingleWindowBrowsing and I never knew what it does. Was it meant to switch to IE5-like windows? Does it even make sense to have such an option?

**Comment by Emdek** [comment]
@ersi-dnd, I've just checked and classic Opera behaves the same, when windows are preferred then these modifiers open new windows, so I'm assuming this issue as invalid.

According to description that option should affect only popups:
> Use the current window instead of creating new ones for pop-ups

Note that #77 is meant to allow to configure such stuff, to decide what should be done depending on modifiers or mouse button.
