### ISSUE TITLE
Shortcut intercepted by the interface

### ISSUE THREAD

**Issue by Plaristote** [OtterBrowser/otter-browser#826]
Greetings,

Some of the shortcut seems to be intercepted by the interface, while they should only be intercepted by the webview.
For instance, in the javascript console from the web inspector, Ctrl+L is supposed to clear the console: instead, it focuses on the url bar. In the Google Doc applications, Ctrl+F is often supposed to open a search feature inside the webapp, but instead it opens the navigator's search feature.

Probably these events should be ignored when a webview is focused, and only triggered if they aren't intercepted by said webview.

**Comment by beastie1** [comment]
I believe this is the same issue.

Like in many programs, I've always used Ctrl+left/right arrows to go to the previous/next word in a textarea like the one I'm typing in right now.

It doesn't work in Otter anymore.

**Comment by Emdek** [comment]
This is a complex issue, in case of shortcuts mentioned by @Plaristote the best solution might be to add setting to allow to override global shortcuts by webpage, as not everyone likes when it steals it to set focus to some custom search field which works in completely different way (like in case of github itself ;-)).

@beastie1, this is a known issue, I won't touch it before beta as algorithm which decides if shortcut should be ignored is too fragile to experiment on it now. ;-)
Although I may decide to disable these two shortcuts for release and reenable them after adding some exceptions for editable content.

There is one more case, some standard editing shortcuts (``Ctrl+A``, ``Ctrl+C``) are currently by default binded to global actions, which causes issues like #680, #715 or inability to paste text into inspector.
These need to become local actions but also showing standard shortcuts as default ones.

**Comment by Emdek** [comment]
Remaining part of this ticket was split into separate one: #926.
