### ISSUE TITLE
Html5 video

### ISSUE THREAD

**Issue by yellowhat** [OtterBrowser/otter-browser#830]
Hi all,
I am using otter 0.9.06-dev on gentoo.
If I try to play an html5 video it plays just the sound but no video.
For example if I go here http://www.w3schools.com/html/html5_video.asp and click play it plays just the sound but the area where the video should be stays white.

Thanks

**Comment by Emdek** [comment]
QtWebKit uses GStreamer through QtMultimedia, you need to install plugins, at least *gstreamer-plugins-good* (or with similar name), usually for GStreamer 0.10 (or 1.0, depending on version used when building Qt).

**Comment by The-Compiler** [comment]
Something similar to `gst-libav` (that's how it's named on Arch) might also be needed.

**Comment by yellowhat** [comment]
media-plugins/gst-plugins-libav was missing.

Thanks

**Comment by oliver1111333** [comment]
How to work on windows?  For windows user, it is so important to play video. It is a basic feature.
I try to compile qtmultimedia to support gstream, but failed. Can we provide ways to do?
If our installer or portable executable file support video playing on windows, otter will be more powerful.
