### ISSUE TITLE
Source viewer: monospace font per default (or user defined) 

### ISSUE THREAD

**Issue by uahim** [OtterBrowser/otter-browser#835]
title says it all; thanks for beta 2!

**Comment by Emdek** [comment]
I think that we should with just setting monospace there, then allow to modify it after adding support for configuring fonts for the whole UI, which will require some research first (determine how many groups do we need and the safest way to propose sane defaults in Preferences / about:config).

**Comment by Emdek** [comment]
There is now separate ticket for adding support to customize fonts used by the interface: #847.
