### ISSUE TITLE
Preferences dialog size issue

### ISSUE THREAD

**Issue by uahim** [OtterBrowser/otter-browser#836]
upon opening preferences, the window is always resized to this
![pref1](https://cloud.githubusercontent.com/assets/6866794/7961440/ed9da4aa-0a07-11e5-9592-84220787292e.png)

only if you click advacned, it resizes to this
![pref2](https://cloud.githubusercontent.com/assets/6866794/7961441/eda09e4e-0a07-11e5-9ce1-5f50d5a9b3c1.png)

this is reproducable i.e. the desired size isnt saved anywhere

OS is Win32

**Comment by Emdek** [comment]
I'm not sure if it can be solved properly without implementing #128.
Currently we are using ``adjustSize()`` to ensure that translatable strings will fit, but the issue is that each page is loaded separately (to save resources).

**Comment by Emdek** [comment]
Superseded by #917.
