### ISSUE TITLE
Add option "remove search from StartPage"

### ISSUE THREAD

**Issue by uahim** [OtterBrowser/otter-browser#837]
title says is all

**Comment by lollox** [comment]
Well, I think the current Speed dial is only a first step :P ... a more customizable one is surely something to have (groups, folders, etc) but for now at least we have one to use ;)

**Comment by uahim** [comment]
@lollox yes I'm aware of that, just making sure this stays on the agenda :))

**Comment by Emdek** [comment]
@lollox, folders are already supported, but you need to create them using Bookmarks Manager (as Start Page uses them as data source).
We can definitely add context menu action to create them, but I'm not sure if we should also modify the "plus tile" (or whatever we should call the one which allows to add new entries ;-)) to show menu when activated asking if new entry should be an URL or a folder.

**Comment by lollox** [comment]
Oh didn't see it. Awesome!

About the question, IMHO we don't need to modify the + tile. Simply drag&drop a tile on another one should create a new folder as in other Speed dial implementations ;)

PS
This is not very important but still a good addition: do you plan to support a "multi-page" speed dial as implemented in Vivaldi?

**Comment by Emdek** [comment]
@lollox, multi-page? I haven't heard about that.

**Comment by lollox** [comment]
In Vivaldi you can create as many Speed dial page as you want. I proposed this here too when we discussed about it some months ago when Vivaldi wasn't yet released ;P

The best scenario is for example you can divide your tiles for Work/personal/etc

As said, it's not very important since we already have folders. I simply proposed for a complete overview if someone could be interested :D

**Comment by Emdek** [comment]
@lollox, how does it work exactly?
In theory we could allow to open URLs like:
``about:start/path/in/bookmarks/``

**Comment by lollox** [comment]
In Vivaldi all Speed dials pages are simple bookmark folders with some metatag applied to them so the browser can process them as Speed dial pages

http://i.imgur.com/vsOPKEe.jpg

**Comment by Emdek** [comment]
@lollox, in our case it's even simpler, we don't need any special data for them, thumbnails (using bookmark identifier as file name) are stored as files anyway (and they are the only extra data that is needed), just pick a folder and thumbnails will be automatically created if missing.
So we only need to come up with the best way to access other folder that way.
