### ISSUE TITLE
Cloning tab corrupts POST requests

### ISSUE THREAD

**Issue by The-Compiler** [OtterBrowser/otter-browser#838]
When cloning a tab which did a `POST` request, the data seems to be corrupted somehow, which can show up as server errors.

This can be reproduced by going to http://httpbin.org/forms/post and submitting the form, which will do a `POST` request to http://httpbin.org/post like this:

```json
  "form": {
    "comments": "", 
    "custemail": "", 
    "custname": "foobar", 
    "custtel": "", 
    "delivery": ""
  }, 
```

When cloning the tab, the request suddenly shows up as this:

```json
  "form": {
    "\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001": ""
  }, 
```

Looking at wireshark, it seems this data is really transmitted as `application/x-www-form-urlencoded`:

```
0000   01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01  ................
0010   01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01  ................
0020   01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01  ................
0030   01 01 01 01 01 01 01                             .......
```

I'm not sure whether this is an upstream issue or an issue with the reverse engineered serialized history, so I thought you might know more :smile:

**Comment by Emdek** [comment]
In case of cloning we simply copy stream to try to avoid such issues:
https://github.com/OtterBrowser/otter-browser/blob/master/src/modules/backends/web/qtwebkit/QtWebKitWebWidget.cpp#L1876
So there is a chance that method that decodes this in QtWebkit fails to do that properly.
I guess that the best idea is to create some minimal test case and check if it works correctly (although there should be no difference as this code doesn't modify the stream at all).

**Comment by The-Compiler** [comment]
Good point, I wasn't realizing it's a 1:1 copy.

Do you have the time to write a small test case? Otherwise I can take a look at it, but I'm not fluent with C++ at all...

**Comment by Emdek** [comment]
@The-Compiler, I can try that in near future.
BTW, does it need to be a C++ anyway?
It's just a ``QDataStream``, it should be possible to do that in Python. :-)

**Comment by The-Compiler** [comment]
Sure, but if it's a QtWebKit issue (which it most likely is), it helps to have a test case to attach to the issue - and I know carewolf/Allan Jensen doesn't have PyQt installed, so it'd be pointless to attach a PyQt example :)

**Comment by Emdek** [comment]
@The-Compiler, that is kind of a weak excuse, although in theory they should prefer PySide. ;-)

I guess that the simplest way is to modify ``test-qtwebkit`` by adding some button with action that creates new ``QWebPage``, then copies history to that new object and then dumps both original stream and from new instance to output.
Both should be the same, assuming that WebKit doesn't need to change values of these two counters.

**Comment by Emdek** [comment]
@The-Compiler, I've added support for testing that to *test-qtwebkit*:
https://github.com/OtterBrowser/test-qtwebkit/commit/0c3179f7660f331a03d53123f46c47210f1d701e

It happens after using stream with different instance of ``QWebPage`` (setting it on the same instance after clearing history appears to work fine).

**Comment by Emdek** [comment]
Upstream bug report:
https://bugreports.qt.io/browse/QTBUG-47889
