### ISSUE TITLE
POST requests are stored as GET in sessions

### ISSUE THREAD

**Issue by The-Compiler** [OtterBrowser/otter-browser#839]
May or may not be related to #838:

When going to http://httpbin.org/forms/post and submitting the form (which will do a `POST` request to http://httpbin.org/post), that works fine.

However, when then the session is saved and reopened, "Method Not Allowed" is displayed as a `GET` request is executed.

Without actually looking at the code, I can think of two solutions: Storing all POST data in sessions, or ignoring POSTs entirely when saving the session.

**Comment by Emdek** [comment]
Storing POST data in session is bad idea, very often it contains sensitive data (like passwords etc.) and data streams usage makes it very hard to store and restore it (at least when you don't want to store it in semi binary form).
So I guess that it would be best to simply ignore them, but that won't be easy either, as it will most likely require parsing the stream. :-/
