### ISSUE TITLE
Otter Browser 0.9.06 does not start on KDE4

### ISSUE THREAD

**Issue by tmysik** [OtterBrowser/otter-browser#840]
Today I updated to the latest Otter Browser release via Ubuntu PPA - and the browser does not start. It prints nothing to the console so let me know what more I can do to help investigate this issue. I tried to remove ```~/.config/otter``` but it does not help.

Using Kubuntu 14.04 LTS with Kubuntu backports PPA.

Thanks.

**Comment by tmysik** [comment]
BTW the process is running and can be easily killed (using ```killall``` command).

**Comment by tmysik** [comment]
One more note - this issue does not happen on my other PC where I have Kubuntu 15.04 with KDE5.

**Comment by tmysik** [comment]
Downgrading to 0.9.05 "solved" the problem for me :)

**Comment by Emdek** [comment]
Yeah, @landroni noticed the same but with XFCE in Trusty, we have started debugging it, it appears that there is some kind of lockup while creating ``MainWindow ``.
I can't reproduce that with Kubuntu 14.10.

Which Qt version are you using now?
And QtWebKit version too, as AFAIR that release had buggy older one to avoid issues with touch events...

**Comment by tmysik** [comment]
Otter Browser says this:

```Tento program používá Qt-verze 5.2.1.```

What is the exact name of QtWebKit package please?

```
gapon@cattie ~ $ dpkg -l libqtwebkit4
Požadované=Neznámé/Instalovat/Odinstalovat/Vyčistit/Podržet
| Stav=Ne/Instalován/Konfigurační soubory/Rozbalen/Nezkonfigurován/Nekompletní
| instalace/Očekávané spouštěče/Nevyřízené spouštěče
|/ Chyba?=(nic)/Nutná přeinstalace (Stav,Chyba: velké písmeno=chyba)
||/ Název                                                 Verze                           Architektura                    Popis
+++-=====================================================-===============================-===============================-===============================================================================================================
ii  libqtwebkit4:amd64                                    2.3.2-0ubuntu7                  amd64                           Web content engine library for Qt
ii  libqtwebkit4:i386                                     2.3.2-0ubuntu7                  i386                            Web content engine library for Qt
```

Thanks.

**Comment by Emdek** [comment]
@tmysik, it's *libqt5webkit5*.
I'm preparing patch that should help in determining where it locks up.

**Comment by tmysik** [comment]
@Emdek In such case:

```
cattie ~ # dpkg -l libqt5webkit5
Požadované=Neznámé/Instalovat/Odinstalovat/Vyčistit/Podržet
| Stav=Ne/Instalován/Konfigurační soubory/Rozbalen/Nezkonfigurován/Nekompletní
| instalace/Očekávané spouštěče/Nevyřízené spouštěče
|/ Chyba?=(nic)/Nutná přeinstalace (Stav,Chyba: velké písmeno=chyba)
||/ Název                             Verze                 Architektura          Popis
+++-=================================-=====================-=====================-========================================================================
ii  libqt5webkit5:amd64               5.1.1-1ubuntu8        amd64                 Web content engine library for Qt
```

Thanks.

**Comment by Emdek** [comment]
@tmysik, thanks, personally I think that someone should punish Ubuntu packagers for packaging outdated QtWebKit 5.1 as part of Qt 5.2. ;-)
Debug patch is almost ready.

**Comment by tmysik** [comment]
@Emdek 
> personally I think that someone should punish Ubuntu packagers for packaging outdated QtWebKit 5.1 as part of Qt 5.2. ;-)

I see... and I agree! :)

> Debug patch is almost ready.

I would need exact instructions what to do ;)

Thanks.

**Comment by Emdek** [comment]
@tmysik, here is the patch:
https://gist.github.com/Emdek/431caa6fb688f06589fe
In order to test it you will need to get current sources (you can use [Download ZIP](https://github.com/OtterBrowser/otter-browser/archive/master.zip)), then unpack it, save contents of that gist as *patch.diff* in directory containing *otter.pro*, apply patch:
``patch -p1 < patch.diff``
Then follow instructions from *INSTALL* (you will need to fetch some extra development packages if you don't have them already: cmake, qtbase5-dev, libqt5webkit5-dev, qtdeclarative5-dev, qtscript5-dev, qtmultimedia5-dev), but skipping ``make install``.
After that go to *build/* and run ``otter-browser`` from terminal set to that directory (if you are using Dolphin then you can simply go to that directory and open terminal pane using F4 or separate window using Shift+F4).
You should get output similar to this one:
https://gist.github.com/Emdek/0e6e6a56e29b200d0168

**Comment by tmysik** [comment]
@Emdek The output is:

```
gapon@cattie ~/tmp/otter/otter-browser-master/build $ ./otter-browser 
Debug: initializing MainWindow  (/home/gapon/tmp/otter/otter-browser-master/src/ui/MainWindow.cpp:82, Otter::MainWindow::MainWindow(bool, const Otter::SessionMainWindow&, QWidget*))
Debug: updating shortcuts  (/home/gapon/tmp/otter/otter-browser-master/src/ui/MainWindow.cpp:87, Otter::MainWindow::MainWindow(bool, const Otter::SessionMainWindow&, QWidget*))
Debug: creating WindowsManager  (/home/gapon/tmp/otter/otter-browser-master/src/ui/MainWindow.cpp:92, Otter::MainWindow::MainWindow(bool, const Otter::SessionMainWindow&, QWidget*))
Debug: updating WorkspaceWidget  (/home/gapon/tmp/otter/otter-browser-master/src/ui/MainWindow.cpp:99, Otter::MainWindow::MainWindow(bool, const Otter::SessionMainWindow&, QWidget*))
Debug: restoring session  (/home/gapon/tmp/otter/otter-browser-master/src/ui/MainWindow.cpp:161, Otter::MainWindow::MainWindow(bool, const Otter::SessionMainWindow&, QWidget*))
Debug: initializing QtWebKitWebBackend  (/home/gapon/tmp/otter/otter-browser-master/src/modules/backends/web/qtwebkit/QtWebKitWebBackend.cpp:141, virtual Otter::WebWidget* Otter::QtWebKitWebBackend::createWidget(bool, Otter::ContentsWidget*))
Debug: creating cache directory "/home/gapon/.cache/Otter"  (/home/gapon/tmp/otter/otter-browser-master/src/modules/backends/web/qtwebkit/QtWebKitWebBackend.cpp:150, virtual Otter::WebWidget* Otter::QtWebKitWebBackend::createWidget(bool, Otter::ContentsWidget*))
Debug: initializing QtWebKitWebWidget  (/home/gapon/tmp/otter/otter-browser-master/src/modules/backends/web/qtwebkit/QtWebKitWebBackend.cpp:169, virtual Otter::WebWidget* Otter::QtWebKitWebBackend::createWidget(bool, Otter::ContentsWidget*))
Debug: creating QtWebKitNetworkManager  (/home/gapon/tmp/otter/otter-browser-master/src/modules/backends/web/qtwebkit/QtWebKitWebWidget.cpp:104, Otter::QtWebKitWebWidget::QtWebKitWebWidget(bool, Otter::WebBackend*, Otter::QtWebKitNetworkManager*, Otter::ContentsWidget*))
```
Waiting for next instructions ;)

Thanks.

**Comment by Emdek** [comment]
@tmysik, I think that I know what is wrong, workaround for known Qt 5.2 bug got accidentally reverted recently, this should fix that issue:
https://gist.github.com/Emdek/7d93b261266de6c65bc7

**Comment by tmysik** [comment]
@Emdek I can confirm that your second patch solves the problem, Otter Browser is up and running now.

Would you please rebuild and publish a new package for 0.9.06 version with this hotfix? Thanks!

**Comment by Emdek** [comment]
@tmysik, sure, thanks for testing. :-)

**Comment by tmysik** [comment]
@Emdek Thanks a lot! :)

**Comment by Emdek** [comment]
@tmysik, no problem. :-)

**Comment by tmysik** [comment]
@Emdek 

> Would you please rebuild and publish a new package for 0.9.06 version with this hotfix? Thanks!

I meant Ubuntu PPA - would it be possible please?

**Comment by Emdek** [comment]
@tmysik, sure, I'm working on it right now. :-)

**Comment by tmysik** [comment]
@Emdek Perfect, thanks!

**Comment by tmysik** [comment]
:+1:

**Comment by tmysik** [comment]
(just wanted to try that :)

**Comment by The-Compiler** [comment]
Note you're spamming the mail inboxes of at least 87 people this way :wink: (repo watchers and Emdek)

**Comment by tmysik** [comment]
@The-Compiler Mea culpa, did not know that :/ I thought just @Emdek will get a notification.
