### ISSUE TITLE
Make it easier to enable portable mode

### ISSUE THREAD

**Issue by beppe9000** [OtterBrowser/otter-browser#842]
As the title says, making the browser's data storage independent from the system, by default would be very helpful to hose who want to try other otter versions or simply keep valuable user data & configuration alongside the browser. 

While it is still under development I think it would be the best way. Having self-contained instances of Otter would certainly help bug fixing because we could also have a zip with the browser rigged to trigger the bug again.

SO, please implement PORTABILITY AS A DEFAULT BEHAVIOR unless some "USE_LOCAL_APP_DATA_FOLDER" file is present in the main folder.

**Comment by lollox** [comment]
Already proposed by me some time ago. The best way is copy from old Opera that makes use of a simple "operaprefs_default.ini" in the program folder to tell the browser where to search for the profile. (multiuser goes in %appdata%, standalone is the "portable" mode)

Hope to see it :)

**Comment by Emdek** [comment]
@lollox, I'm considering a bit similar solution, ability to place a file with command line arguments next to binary file.

@beppe9000, I think that above solution would be enough, especially if it would be documented somewhere, INSTALL file might be a good enough place to do that.

It could be either an INI file with key value pairs or just a simple TXT file with single line, in this case it would be just:
> --portable

**Comment by VSHY** [comment]
I want to defaults:
- profile was stored in c:\Users\<user>\AppData\Roaming\Otter\profile_file_&_folders
- cache - in c:\Users\<user>\AppData\Local\Otter\cache_file_&_folders
like is in other programs.

**Comment by Emdek** [comment]
@VSHY, default paths are set by Qt according to table on that page:
http://doc.qt.io/qt-5/qstandardpaths.html#StandardLocation-enum
