### ISSUE TITLE
Strings which contain "…" aren't translated

### ISSUE THREAD

**Issue by pejakm** [OtterBrowser/otter-browser#848]
All languages affected.

https://imgrush.com/M2WUEBLM_nlP
https://imgrush.com/RGHRfMf2Joq1

**Comment by Emdek** [comment]
Are you sure?
I've just tried Polish, German and Japanese and these strings show up properly.
Note that quite recently we had switched to use special character for that, most likely not all languages got updated since that change.

**Comment by aurhat** [comment]
pejakm: do you use official language files or you created them? Such problem appears, when you use Qt Linguist 4.x to generating language file (there shouldn't be problems in case of Qt Linguist 5.x).

**Comment by pejakm** [comment]
@aurhat: yes, I used linguist-qt4. I'll try now with the qt5 version and report back.

**Comment by pejakm** [comment]
Okay, the problem really was in linguist. Translation files generated with linguist-qt5 have no problems. Sorry for false alarm.
