### ISSUE TITLE
Middle Click Scroll can only be de-activated with Right click

### ISSUE THREAD

**Issue by NokTham** [OtterBrowser/otter-browser#854]
https://dl.dropboxusercontent.com/s/smptmjq5m5l3e6j/2015-06-11_23-39-03.mp4?dl=0

like the title says, and like the video shows (somehow) the middle click scroll can only be de-activated using Right Click.

Anyone else having this issue?

Otter 0.9.07 Weekly 75
Windows 7 64-bit

**Comment by fguzm** [comment]
Yes, and then the contextmenu opens

**Comment by MazheM** [comment]
In Otter 0.9.06(Win 8.1 x64)  work properly, deactivate when press LMB, MMB and RMB without context menu opening
