### ISSUE TITLE
Content Blocking Window Size not saved

### ISSUE THREAD

**Issue by NokTham** [OtterBrowser/otter-browser#855]
The Content Blocking WIndow keeps its default size despite resizing.

https://dl.dropboxusercontent.com/s/82uoys2iej385m2/2015-06-14_22-53-56.mp4?dl=0

Otter 0.9.07 Weekly 75
Windows 7 64-bit

**Comment by NokTham** [comment]
Same thing seems to happen with the Search Engine Manager Window.

https://dl.dropboxusercontent.com/s/g6kmrgdgzozdhnt/2015-06-15_13-25-29.mp4?dl=0

Otter 0.9.07 Weekly 75
Windows 7 64-bi

**Comment by Emdek** [comment]
Duplicate of #128.
