### ISSUE TITLE
(Unknown) Content Blocking List | Youtube page issue

### ISSUE THREAD

**Issue by ZarkBit** [OtterBrowser/otter-browser#856]
(Unknown) Content Blocking list is causing some issues with youtube page (probably other websites also).

https://dl.dropboxusercontent.com/s/h2h54foq07iq5ew/2015-06-14_23-05-16.mp4?dl=0

Otter 0.9.07 Weekly 75
Windows 7 64-bit

**Comment by MazheM** [comment]
Content Blocking is real problem, not only with YT. If i enable blocking, i cant watch videos inserted from yt and other services and, for example, transifex.com not working because scripts not working.

**Comment by bajasoft** [comment]
@ZarkBit, @MazheM: Please, try if the problem still occurs with latest weekly.

**Comment by ZarkBit** [comment]
@bajasoft looks like it's fixed, thanks

**Comment by MazheM** [comment]
@bajasoft, yeah, it seems to be working fine
