### ISSUE TITLE
Start Page | Edit (context menu) only applies to the first Tile

### ISSUE THREAD

**Issue by NokTham** [OtterBrowser/otter-browser#857]
On the Start Page, the option to edit Tiles properties, only applies to the first Tile.

https://dl.dropboxusercontent.com/s/ikdfbz8i4aetuzt/2015-06-14_23-23-40.mp4?dl=0

Otter 0.9.07 Weekly 75
Windows 7 64-bit

**Comment by Emdek** [comment]
Duplicate of #853.
