### ISSUE TITLE
Dragging Tab | Blank Text

### ISSUE THREAD

**Issue by ZarkBit** [OtterBrowser/otter-browser#859]
When dragging a Tab on the TabBar, its text get's blanked.

https://dl.dropboxusercontent.com/s/viuzi78udeohkmq/2015-06-15_13-20-38.mp4?dl=0

Otter 0.9.07 Weekly 75
Windows 7 64-bit

**Comment by ersi-dnd** [comment]
Confirmed.

**Comment by Emdek** [comment]
It appears to be somehow connected to ``QToolBar``, I'll run some extra tests  and most likely will create upstream bug report.

**Comment by Emdek** [comment]
It's an upstream issue, reported as:
https://bugreports.qt.io/browse/QTBUG-47189

I'm planning to get rid of `QToolBar` anyway, so it could get "fixed" earlier.
