### ISSUE TITLE
Proxy PAC file not loaded from web server, only local file works

### ISSUE THREAD

**Issue by loetmeister** [OtterBrowser/otter-browser#860]
When I configure Otter to use a PAC file in the nework settings, the file works fine when it's stored locally on my PC. Once I change the path to an web address, pointing to the exact same file (e.g. http://proxy.mydomain.local/proxy.pac) it does not work. It looks like it ignores this setting and uses the system configuration.

OS Windows 7 x64
otter-browser-win64-weekly76

**Comment by Emdek** [comment]
URLs are not supported as value for path, at least not yet.
