### ISSUE TITLE
QNAM gives garbage data for https POST data

### ISSUE THREAD

**Issue by parmarpritish** [OtterBrowser/otter-browser#863]
Open Otter browser and navigate to this url - http://www.yesbank.in/popup.php?type=CO
This url is redirected to hit a POST url - https://netbanking.yesbank.co.in/corpbanking/entry with data in body. When this is hit, the QNAM provides garbage data to the browser. 
It seems to be QtNetwork issue. Kindly confirm and raise.
![otter-error](https://cloud.githubusercontent.com/assets/13017595/8306703/b90cce48-19d7-11e5-95fd-62f1d47dafd1.png)

**Comment by The-Compiler** [comment]
I just noticed @parmarpritish already reported this upstream as [QTBUG-46825](https://bugreports.qt.io/browse/QTBUG-46825).

From the `#qt-labs` IRC chan:

```
16:27 <+richmoore> I just had a quick glance at QTBUG-46825 and I notice that the site (which doesn't work properly) is sending differing charset info in the content-type header and the meta-equiv
16:27 <+richmoore> I wondered if that is a likely cause for what he's seeing?
16:28 <+richmoore> i've no idea which would 'win' when they disagree
```

**Comment by parmarpritish** [comment]
Yes, after trying on Otter browser, I tried on Qt's examples and found that the issue is prevailing on their examples as well. After some analysis, I guesses that the issue may be in Qt. Hence I have raised a bug directly in Qt as well. Thanks for linking.

**Comment by Emdek** [comment]
@parmarpritish, for such cases we have own test application:
https://github.com/OtterBrowser/test-qtwebkit
