### ISSUE TITLE
When application starts the toolbars restored in not saved places

### ISSUE THREAD

**Issue by Katarn** [OtterBrowser/otter-browser#864]
More precisely, not always.

![](http://i.imgur.com/ZdYY9mH.png)

Maybe there involved some asynchronous save/loading?

**Comment by Emdek** [comment]
There seems to be a problem with saving order of the toolbars per area.

**Comment by mykurtaccount** [comment]
Any update on this. Irritating to have to put your toolbars back where you want them everytime you start Otter.

**Comment by Chocimier** [comment]
Please reorder your toolbars once again, hopefully last one.

**Comment by mykurtaccount** [comment]
Nope - Toolbars still not saved. Not sure why you would close it without confirmation.

I have a custom toolbar that duplicates the Navigation Bar and I don't show the Naviagtions toolbar. This is so I can have the following layaout

tabbar
custom Navigation Bar
Bookmarks Bar

When ever I close OTTER and restart it always reverts to

Custom Navigation Bar
Tab Bar
Bookmarks Bar

**Comment by Chocimier** [comment]
Fix is not included in beta nor any released version yet. Please check in next weekly. We mark as fixed when fix goes to source code repository.

**Comment by Katarn** [comment]
I tried to run the app about 20 times. Toolbars always display correctly. You can probably to consider the problem as solved for me. Thank you!

But I would have waited for what he would say @mykurtaccount
