### ISSUE TITLE
[Tabs] Several lines of tabs

### ISSUE THREAD

**Issue by DI555** [OtterBrowser/otter-browser#865]
I would like to suggest possibility of tabs multirow - with parameter of it - so would be possible make it 1 - or more
(oh those good-ol-days when I found it in old Opera...)

**Comment by Emdek** [comment]
This can be considered as part of #190.
While basic stuff appears to be quite obvious there are some issues when it comes to details.
And another issue is drawing using theme, it might look ugly when using some themes that assume that there is only one row.
