### ISSUE TITLE
[Tabs] Scroll all line(s) of tabs when them overlaps.

### ISSUE THREAD

**Issue by DI555** [OtterBrowser/otter-browser#867]
Would be great to see an option - scroll all line(s) of tabs by the mouse weel (and reversal option) - when them overlaps.

**Comment by Emdek** [comment]
Please elaborate more, I'm not sure what do you mean exactly.

**Comment by DI555** [comment]
now - when tabs overlaps (more than can be visually placed in tab bar)  -  it's possible switching tabs by a mouse weel only tab-by-tab 
but with this future would be possible to scroll all the tabs line  by a weel (like the function of tabs scrolling buttons now - but with using of weel)

**Comment by DI555** [comment]
I mean optional of course...  but if using a lots of tabs-would be prefered to switch into this mode!

**Comment by DI555** [comment]
visually this could be seen ... like an option "ScrollTabsUsingTheMouseWheel" in a "RightClickOnTabBar>Customize>TabBar"  -near the option "SwitchTabsUsingTheMouseWheel" ...

   even more imo this "ScrollTabsUsingTheMouseWheel" could be working with "SwitchTabsUsingTheMouseWheel" independentelly - I mean together and separatelly...
and in mode when they both "checked" - tabs are switching when non Overflowed - and tabs are scrolling when they're Overflowed!!!      -but using "..Switch.." with "..Scroll.." in Overflowed Tab Bar could be even possible by a hot key + mouse scroll combination anyway...

**Comment by Emdek** [comment]
@DI555, I'm not sure if this is a good idea, it seems to be quite complex...
Anyway, it can be discussed as part of #190.
