### ISSUE TITLE
"Insert Note" from right click menu not working.

### ISSUE THREAD

**Issue by resbro** [OtterBrowser/otter-browser#868]
greyed out

Win 8.1 x64
Otter weekly 77 x32

**Comment by resbro** [comment]
working now.

**Comment by resbro** [comment]
I'm finding a problem with this again. On initial opening, it is greyed out (unavailable) and stays greyed out until I copy a note. Then, "insert note" becomes available again from the right click menu and works fine until I close and reopen Otter.

**Comment by Emdek** [comment]
@resbro, I've seen it once, but can't reproduce anymore.

**Comment by resbro** [comment]
Yup, It only happens initially. (after bootup and first start of Otter. Once I copy something, the right click menu works correctly until I shutdown computer and boot again. 

Win 8.1
Otter weekly 78

**Comment by Emdek** [comment]
@resbro, any change when using `#79`?

**Comment by resbro** [comment]
No, I just checked again. Both with webengine x32 and webkit x64. Still have to copy something (anything) to make "insert Note" become available. (not greyed out)
