### ISSUE TITLE
Action "Open in new tab" does not display the load progress panel

### ISSUE THREAD

**Issue by Katarn** [OtterBrowser/otter-browser#869]
But only when the link is opened the page on the same domain. If there is a transition to another domain - the loading panel is displays.

**Comment by Emdek** [comment]
Can't reproduce, it happens for every webpage?

**Comment by Katarn** [comment]
Yes, you can click to Github logo by RMB, select "Open in new tab" menu item and see it.
I use WebKit backend.

**Comment by Emdek** [comment]
Confirmed, I was trying to reproduce it in wrong way...
