### ISSUE TITLE
Override Browser/EnableImages when the content is just an image

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#870]
**Browser/EnableImages** should be overridden (always set to true) when the content of a new tab is an image.

To see what I mean, set **Browser/EnableImages** to **false**, open let's say **google.com**, right-click where Google's logo usually stands and **Open Image in New Tab**.

It doesn't make sense to have images disabled when the only possible purpose of doing the above is to display the image.

Same thing when opening a [link to an image](http://www.google.com/images/srpr/logo9w.png) or pasting the URL "www.google.com/images/srpr/logo9w.png" in the address bar.

**Comment by Emdek** [comment]
@beastie1, above commit should prevent Start Page from showing above error page (which was BAD).
I'm not sure if we can add such exception for images after all, but I'll try in different way.

**Comment by beastie1** [comment]
Thanks. It's much better like that. But I can see a little problem. Since the code tests for an empty URL, it fails to display the proper URL when *clicking* on the image link since the tab already has a valid URL. It only works when *middle-clicking*, as this opens a new tab/background tab.

**Comment by beastie1** [comment]
This issue has been back for quite some time now.

Just like before, start with a blank profile, set **Browser/EnableImages** to **disabled** and open a [link to an image](http://www.google.com/images/srpr/logo9w.png).

The error is slightly different though.

![screenshot-otter_25062017-120711](https://user-images.githubusercontent.com/6757832/27514884-4d799224-599f-11e7-914b-3c1c7e5c16cb.jpg)
