### ISSUE TITLE
Source viewer features

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#874]
As a minimum, I think these features should be added to the source viewer:

- Wrap long lines (best by default or a sticky option)
- Configure/Remove coloring/formatting

Concerning the second point, the most flexible way is to add a config file in the profile that formats the source viewer. 

Start page configuration, userCSS, userJS and other similar things should also work like this - configurable files in the profile directory.

**Comment by Emdek** [comment]
Wrapping is already available, although it is not exposed in UI, just in about:config.
Configuration of syntax highlighting is also planned.

It's based on widget from application that was part pf my thesis back in 2010, it had all of these features plus initial work on XML based syntax definitions.
But after reviewing it I've decided to only partially reuse that code, it was a bit too old. ;-)

There are also some other features that I would like to add later.

**Comment by ersi-dnd** [comment]
I have scrollbars switched off globally, but in the sourceviewer there are scrollbars.

**Comment by VSHY** [comment]
I would also like:
1. If source viewer have started, then the urls on page when you click on it should not work. To be opened corresponding element in HTML-DOM-tree.
2. Item "Copy" in context menu on status bar (html > body > ...).
3. The possibility of an arbitrary selection in HTML-DOM-tree (like is in Opera Presto) and p.2 for this.

**Comment by Emdek** [comment]
@VSHY, this is currently not possible, but might be in future (but more likely as extension, not a core feature).

**Comment by Emdek** [comment]
@ersi-dnd, now it's possible to configure formatting using *syntaxHighlighting.json*, to disable it completely it is enough to create empty file with that name in profile directory.

**Comment by ersi-dnd** [comment]
Thanks, but I noticed that it's not possible to configure the numbers of rows. It would be great if the numbers of rows somehow followed the Qt theme colouring by default. I happen to have a dark theme.

**Comment by Emdek** [comment]
@ersi-dnd, I've updated algorithm used to calculate their color, I'm not sure if we really need option to set their color manually (and for sure not in that file).

**Comment by srgloureiro** [comment]
Why not call Scintilla for the rescue?

**Comment by Emdek** [comment]
@srgloureiro, it's extra dependency for quite basic and easy to implement feature, we only need basic stuff.
And that would be quite big dependency...

**Comment by pierreporte** [comment]
The source viewer lacks a feature for updating the page with the changes made manually (and maybe saving the results, even if hitting Ctrl+S works). Also, it should have a monospaced font.

**Comment by beastie1** [comment]
Why does the source viewer always rereads the page to load the source?

This causes some delay before the source is displayed. Plus it doesn't work at all when there's no connection or you're in offline mode.

Is this a Qt thing?

**Comment by Emdek** [comment]
@beastie1, it's design limitation of (Qt)WebKit, it allows only to get processed HTML without reloading it. :-/
We try to fetch it from cache but it is not always available there, and forcing cache is a bit unsafe.

@pierreporte, updating page is not planned, as it won't be supported by all backends.
To modify page itself you should use inspector or user scripts in future.

**Comment by uahim** [comment]
@Emdek as @pierreporte suggested - and if it's not limited/impossible by Qt - please change the font to monospace or user defined.
also, something like "Source Viewer: <page title>" would come in handy.

**Comment by Emdek** [comment]
@uahim, fonts will be customizable when #847 will be done, but now it already should use such font, doesn't it work for you?
Adding some more information to tab title is a good idea.

**Comment by uahim** [comment]
@Emdek no it uses a non serif, non fixed width font even with a new profile.
thanks for implementing "Source Viewer [address]" :)
