### ISSUE TITLE
"otter-browser.exe is not a valid Win32 application"

### ISSUE THREAD

**Issue by uahim** [OtterBrowser/otter-browser#876]
v 79-qtwebengine. no more WinXP support?

**Comment by VSHY** [comment]
When I had started Otter, I got this message: http://mepic.ru/view/?id=a36c6db284fe18fe24bc89455604b80a

**Comment by DI555** [comment]
errors in cmd window when starts (win7-32bit, Otter qtwebengine 32bit):

"
Warning: QtWebEngineProcess not found at location C:/Qt/5.5/msvc2013/bin/QtWebEn
gineProcess.exe. Trying fallback path... ((null):0, (null))
Warning: Qt WebEngine data directory not found at location C:/Qt/5.5/msvc2013. T
rying application directory... ((null):0, (null))
Warning: Installed Qt plugins directory not found at location C:/Qt/5.5/msvc2013
/plugins\qtwebengine. Trying application directory... ((null):0, (null))
Warning: Installed Qt WebEngine locales directory not found at location C:/Qt/5.
5/msvc2013/translations\qtwebengine_locales. Trying application directory... ((n
ull):0, (null))
Warning: Qt WebEngine locales directory not found at location c:/Program Files/otter-browser-win32-weekly79-qtwebengine\qtwebengine_locales. Trying fallback directory... Translations M
AY NOT not be correct. ((null):0, (null))
[0708/135439:ERROR:icu_util.cc(154)] Couldn't mmap c:\Program Files\otter-browser-win32-weekly79-qtwebengine\icudtl.dat
[0708/135439:FATAL:content_main_runner.cc(747)] Check failed: base::i18n::Initia
lizeICU().
"



2uahim - It needs MS Visual Studio 2013 firstly....

 I have a question to the developer, is it possible to include all needed msvc libs to the package(and either to the webkit package)?
... imo it's useful especially when using and updating a portable versioins.

**Comment by resbro** [comment]
Same thing happening in Win 8.1

Both x32 and x64 otter browser

**Comment by uahim** [comment]
@Emdek could anyone look into this? thanks

**Comment by Emdek** [comment]
I'm uploading v2 packages for QtWebEngine flavor, please check if they work correctly now.
All missing files should be now included, terminal should no longer show up and Windows XP support should be back.

**Comment by resbro** [comment]
Works great!!!
Win 8.1
Otter 79 x 32 .exe v2

**Comment by Emdek** [comment]
@resbro, thanks for confirmation. :-)

@uahim, I'm not 100% sure if QtWebEngine 5.5 works correctly under XP, I've heard that someone had issues with new version, but upstream devs are willing to support it (at least as long as it won't require too much struggle).

**Comment by uahim** [comment]
@Emdek thanks, v2 works fine. as for Qt, I understand. initially I assumed you guys changed something in the compiler deliberately or accidentally so it wouldnt run under XP (I've seen that happening to other OSS projects before, and mostly it was accidentally in fact)

**Comment by DI555** [comment]
@Emdek
I've found another bug in v2 (from debug.log with win7-32bit, Otter qtwebengine-V2 32bit):
"
[0711/145427:ERROR:resource_bundle.cc(691)] Failed to load C:\Qt\5.5\msvc2013\qtwebengine_resources.pak
Some features may not be available.
[0711/145428:WARNING:resource_bundle.cc(304)] locale_file_path.empty()
[0711/145511:ERROR:resource_bundle.cc(691)] Failed to load C:\Qt\5.5\msvc2013\qtwebengine_resources.pak
Some features may not be available.
[0711/145511:WARNING:resource_bundle.cc(304)] locale_file_path.empty()
"
and I've seen - Qt5Xml.dll is missed also from v2...(?)

Many thanks for including msvc libs! it's very useful for portable updating!



I have another one little thought.... if include in build all needed libs for qtWebKit and for qtWebEngine - could be possible to use both engines in one build... I've just tested it  by switching on-the-fly strokes of engines in "Backends>Web" in about:config  !!!
Works pretty fine!!! (could be come up with a switch botton/menu  for  "... Bar>Configure"!!! ;)  )


..... but blink is much heavy by now(((
- should be a way to optionally switching off lots multiple blink processes to at least one (or couple / triple / quadruple in a future perfection ;)  )
 and optionally switching off using D3D-and/or-OpenGL acceleration off either  -  with these staff it eats a lots of resourses, really huge amount)))  -  and also could be possible to test blink with D3D or OpenGL separtely!

**Comment by Emdek** [comment]
@uahim, -qtwebengine packages are compiled using msvc instead of mingw, QtWebEngine is available only when using that compiler, under Windows...
Apparently it needs extra options to create XP compatible binaries.

@DI555, uhm, that file should be included in package, in main directory.
If it is there but QtWebEngine is looking in (my) install path of Qt then it might be some upstream issue.
According to windeployqt we don't need Qt5Xml.dll, have you seen any issues?
Possibility to select backend from UI are planned, maybe even something more.
I doubt that it is possible to disable acceleration in Blink...
I've heard that it is possible to force single process, but haven't seen any description how to do that.

**Comment by uahim** [comment]
@Emdek sorry, I did not realise there's two different packages now for each 32 and 64 bit. my bad, I had unknowingly uncompressed it over my existing qtwebkit installation.

so here's an update, w/ a "clean" installation: despite the exe is in fact executable and running now, 79 v2 qtwebengine does not work at all under WinXP 32bit SP3. upon opening a new tab and entering an url, nothing is happening. not sure whether or not I should reopen this if the qt guys dont care, just thought I'd share this info for other users.

**Comment by Emdek** [comment]
@uahim, I guess that we will need to wait for upstream to do something about that...

**Comment by uahim** [comment]
@Emdek if it's of any worth to the Qt developers, here's my output from debug log - pretty much the same as @DI555 's - could it be they´accidentally hardcoded paths?
```
[0715/145059:ERROR:resource_bundle.cc(691)] Failed to load C:\Qt\5.5\msvc2013\qtwebengine_resources.pak
Some features may not be available.
[0715/145059:WARNING:resource_bundle.cc(304)] locale_file_path.empty()
```

**Comment by Emdek** [comment]
@uahim, that is separate issue.
That file should be included in archive / installer, could you please check if it is there in your case?
It might look for it in wrong directory.

**Comment by uahim** [comment]
@Emdek qtwebengine_resources.pak is in fact in the same directory as otter-browser.exe

**Comment by Emdek** [comment]
@uahim, here is upstream ticket for red scrollbars issue:
https://bugreports.qt.io/browse/QTBUG-42083

**Comment by DI555** [comment]
@Emdek, yes hmm, Qt5Xml.dll seems for qtWebKit based package specific...and now I'm playing with combined package of Otter (just have put some different files(including Qt5Xml.dll) from qtWebKit package to other)- and it's really pretty interesting - especially testing both engines - but qtWebEngine is a really "pain in..." for resources and stability....Very pitty for qtTeam to drop WebKit with qt5.8 (((. God bless people who will forked qt with WebKit !!!!!
...but I already have an idea ;)

**Comment by DI555** [comment]
upd
@Emdek, and ,yes, - qtwebengine_resources.pak still in app dir.
and very interesting what is qtwebengine_resources.pak for here.....In chromium it's for html5 GUI ...
      Could it be possible disable checking (checksum?) for qtwebengine_resources.pak ?
-if so - it might be possible to make some modifications in it... like access to about:flags and other chromium settings(about:settings etc.) !!!!!!!

**Comment by Emdek** [comment]
@DI555, no idea if checksums can be ignored, you can ask QtWebEngine devs on #qtwebengine IRC channel (at Freenode), note that it might take a lot of time to get a reply...
