### ISSUE TITLE
Speed Dial page must stay in history

### ISSUE THREAD

**Issue by Katarn** [OtterBrowser/otter-browser#878]
Now the "Back" button is disabled immediately after the departure from the Speed Dial page.

**Comment by vbr** [comment]
Hi, I'd like to support this request; I find the behaviour in Opera the most convenient, as it is e.g. possible to quickly check multiple pages saved in Speed dial just with a few clicks and mouse gestures.
regards,
    vbr

**Comment by Frenzie** [comment]
Agreed. 

On September 18, 2015 10:25:45 PM GMT+02:00, vbr <notifications@github.com> wrote:
>Hi, I'd like to support this request; I find the behaviour in Opera the
>most convenient, as it is e.g. possible to quickly check multiple pages
>saved in Speed dial just with a few clicks and mouse gestures.
>regards,
>    vbr
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/OtterBrowser/otter-browser/issues/878#issuecomment-141558265

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Emdek** [comment]
@Katarn, I've tried that in the past and there were some issues with that, but I could try again.
