### ISSUE TITLE
Root element in Notes must be hidden

### ISSUE THREAD

**Issue by Katarn** [OtterBrowser/otter-browser#879]
As I see it, it is completely superfluous in the interface.

**Comment by DI555** [comment]
-Not at all!!!
only click on root element  you may add a new Note entry - by the UI in the "Notes".....others - by selecting and pick "AddToNote"
...so all done right way!!!

**Comment by Emdek** [comment]
@Katarn, while it's not perfect it has some advantages, including easier API.
