### ISSUE TITLE
Cache page opens too slow

### ISSUE THREAD

**Issue by Katarn** [OtterBrowser/otter-browser#880]
Not less than 10 seconds. At the same time a very high load on the hard disk.

**Comment by Emdek** [comment]
There is not much that we could do about that, it needs to read all metadata from disk which is scattered in multiple files.

**Comment by VSHY** [comment]
It would be better to open almost immediately, and the information to add in portions.

**Comment by Zero3K** [comment]
Is it possible to have the all of the metadata stored as one file? If so, maybe it could be changed to be that way.

**Comment by Emdek** [comment]
@Zero3K, I haven't seen such solution yet.

**Comment by Emdek** [comment]
@Katarn, perhaps I'll revisit this ticket, I can try to move file listing to own `QThread` and send it back to UI thread in batches of 25 entries or more.
