### ISSUE TITLE
(Untitled) page title after close special page

### ISSUE THREAD

**Issue by Katarn** [OtterBrowser/otter-browser#881]
How to reproduce the problem:

1. Open any website.
2. Open any special page (for example, Notes).
3. Close the special page.

You can see that the browser title has become (Untitled)

**Comment by Emdek** [comment]
Cannot reproduce, I've opened phoronix.com on the first tab and the about:notes in new one and after closing the latter it was showing correct title (from first tab).

**Comment by Katarn** [comment]
Try in MDI mode.

**Comment by Emdek** [comment]
@Katarn, it seems that ``QMdiArea`` might mess with title of ``QMainWindow``, I've seen similar issue while implementing 7c08a559eb5642dcbd6b088303a448d06e9ff454 (title gets set to concatenated titles of multiple sub windows).
