### ISSUE TITLE
The names of the folders in Bookmarks menu are empty after the change of the application language

### ISSUE THREAD

**Issue by Katarn** [OtterBrowser/otter-browser#882]
I changed the language of the application from the Russian to the System, then opened the Bookmarks menu. And I see the empty folder names.

http://screencloud.net/v/9esT

You can also see that the menu item "Open all" remained untranslated. After browser restart it became in English.

**Comment by VSHY** [comment]
Yes. It is in #827 as p11.

**Comment by Katarn** [comment]
Then I close this ticket.
