### ISSUE TITLE
Startpage tiles connect to their sites at startup

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#883]
Startpage tiles connect to their sites at startup - this should be possible to switch off. The image in the tiles should be handled some other way, perhaps like bookmark icons.

**Comment by VSHY** [comment]
By my opinion, disable of Express-panel tiles update at startup will be enough.

**Comment by Emdek** [comment]
@ersi-dnd, now you can set *StartPage/TileBackgroundMode* to *favicon* or *none* to disable thumbnails, thus need to fetch them (note that it will still connect once to server to fetch title when adding new one using Add Tile).
