### ISSUE TITLE
[Tabs] Tab bar scrollbar

### ISSUE THREAD

**Issue by DI555** [OtterBrowser/otter-browser#884]
to easy manipulate of tabs would like to suggest (an optional of couse) a scroll bar for tabs!
functioning like in that pictures - http://franklion.co.uk/TOS3.html

also scroll bar could be useful in a mode when tab bar is vertical - for quick access to any of many tab)
now all the line of tabs could be scrollable only by the pair of scroll buttons and very-very slow(

**Comment by cattleyavns** [comment]
Firefox tab managing method is the best method ever, this should be a thing that we should implement because simply it is better than Opera/Chrome method.

**Comment by Emdek** [comment]
@DI555, it can be discussed as part of #190.

**Comment by srgloureiro** [comment]
@cattleyavns What? Are you on drugs?
