### ISSUE TITLE
Youtube does not go fullscreen on demand

### ISSUE THREAD

**Issue by mariokamenjak** [OtterBrowser/otter-browser#890]
When I click for youtube to go fullscreen it does not do so. It does not do anything unfortunately. However the player does transform into the big player on request.

**Comment by The-Compiler** [comment]
This is already reported upstream as [QTBUG-43625](https://bugreports.qt.io/browse/QTBUG-43625).

**Comment by mariokamenjak** [comment]
Ok, I will write just one more general issue and one feture request so far.
