### ISSUE TITLE
Disappointing html5 score

### ISSUE THREAD

**Issue by mariokamenjak** [OtterBrowser/otter-browser#891]
The score on html5test is rather disappointing.
http://html5test.com/
Consider improving it as a long term goal. 
The score on css3 test however is quite good, consider giving yourselves a cookie and a pat on the head :)
http://css3test.com/

**Comment by The-Compiler** [comment]
Both aren't implemented by otter directly but by the respective backend (QtWebKit or QtWebEngine). The score is a lot better (nearly the same as Chromium IIRC) with QtWebEngine, and work to integrate that is ongoing in #615.
