### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by TiriliPiitPiit** [OtterBrowser/otter-browser#893]
When I go to the search-settings by clicking
Tools -> Preferences -> Search
and add one new type of search by clicking
Add -> New... -> (fill out text fields) -> OK
and then add a second new type of search by clicking
Add -> New... -> (fill out text fields in another way) -> OK
and afterwards closing the "Preferences" window by clicking
Apply and OK
then this problem appears:

When I go to the search settings again,
there are more new entries than I added previously and these excessive ones have the same
name as the last one added manually.
Everything seems messed up and broken at this point. Trying to correct it creates even more chaos.

**Comment by Emdek** [comment]
Cannot reproduce, which version are you using?

**Comment by Emdek** [comment]
@TiriliPiitPiit, is that reproducible on clean profile (you can use ``--profile <path>`` for testing)?

**Comment by TiriliPiitPiit** [comment]
Yes, when I use a new profile, the bug appears in a way that the first new entry becomes the same as the second new entry and the keywords are empty + maybe some more mess.

I use Otter-0.9.07-dev, WebKit Backend 538.1, qt 5.4.1.

**Comment by Emdek** [comment]
@TiriliPiitPiit, OK, now I can reproduce that, I've noticed that new entries don't have unique identifiers for some reason.
