### ISSUE TITLE
QtWebEngine processes single-key hotkeys inside forms

### ISSUE THREAD

**Issue by jernejs** [OtterBrowser/otter-browser#894]
The 2015-07-15 QtWebEngine Win64 version responds to hotkeys (such as - and .) while typing in forms, which makes entering text practically impossible (the key isn't passed to the form).

**Comment by komoku** [comment]
Confirmed in my machine. And it only happens with QtWebEngine (if the backend is changed back to qtwebkit, the bug doesn't happen).

**Comment by Frenzie** [comment]
I'm not sure if this is quite the same issue or not, but similarly using e.g. Ctrl + left/right arrow results in back/forward while entering text instead of skipping to the previous/next word as expected.
