### ISSUE TITLE
Support for new builds based of forket qt !!!  WebKit must be alive for Otter !!!

### ISSUE THREAD

**Issue by DI555** [OtterBrowser/otter-browser#895]
Since qtTeeam plans to drop WebKit in 4Q of 2015 with ~qt5.8....((( It would be great to stay with WebKit nevertheless....because qtBlink now is very heavy - eats a lots of memory, proccesses and CPU resources... and most of it not possible yet to switch off - like multi-proccesses and Hardware acceleration...((( And even more Blink looks very suspicious for BigG's backdors and communication with G.sites ....
 - and plus ,like I new, qtTeam not so friendly for new requests from developers to apply some new futures in qt (((((....So I started to look for... brave harts who forked qt...

And finally found !!!! Is it the CopperSpice project !!!!? - http://www.copperspice.com  ...
And developers look very friendly for implementing new futures/api !!!!
I like WebKit so much !!!! It's very fast and takes not much PC resources!
For example, take a look what new WebKit futures may bring for browser....like in gtkWebKit for examle - http://blogs.igalia.com/carlosgc/2015/03/23/webkitgtk-2-8-0/
So would be great imo not to drop WebKit for Otter!!!

**Comment by Felipefpl** [comment]
copperspice seems interesting but i dont like GTK at all, it's heavy last time i testesd it (years ago) unless this changed in the last years.

**Comment by DI555** [comment]
WebKitGTK is just for an example - what WebKit can do now....    and CopperSpice is Qt port ;) ...

**Comment by Emdek** [comment]
@DI555, moving to different framework (Qt4 != Qt5, and that fork is based on Qt4) is out of scope.
Note that QtWebKit will be still available in source form and better solution could be to switch to fork of that module (if one would show up) than to different framework.
