### ISSUE TITLE
Lack of independence of sidebar

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#898]
1. Open up two Otter windows side by side
2. Open up sidebar in one window
3. Sidebar pops up in the other window too

Sidebars should be manageable independently in separate windows.

And open tabs should be draggable from one window to another. 

There should also be a sidebar item that lets arrange tabs not only within the currently focused window, but between all Otter windows. In old Opera it was called Windows Panel.

**Comment by Emdek** [comment]
That is open for discussion while this separate ticket is superseded by #1086.
