### ISSUE TITLE
crash when saving files

### ISSUE THREAD

**Issue by pmattern** [OtterBrowser/otter-browser#899]
Since a couple of days Otter Browser crashes on a regular basis when download links are clicked.

The crash normally happens before the download dialogue comes up but sometimes when it's available already and the user is about to chose the path.
Backtrace can be found on https://gist.github.com/pmattern/6e0d9db544711a9a6e46.
A probably related finding is affecting phpBB's language packs like https://www.phpbb.com/customise/db/translation/german_casual_honorifics/ (green box "3.1.5" at the right) where the download dialog gets opened but displays a wrong filename before Otter crashes.

Otter from latest Git checkout on Arch Linux i686 or x86_64 running either LXQt or Xfce4 using their respective download dialogues.

Problem is is somewhat similar to #701 but involves simply clicking a link without opening the context menu, takes places on Linux and is apparently technically different.

**Comment by Chocimier** [comment]
I found that Otter crashes when downloading ends, but location to save file on disk isn't chosen by user yet.

**Comment by pmattern** [comment]
The issue isn't fixed yet.

It isn't reproducible all the time but rather reliably like this (latest VCS checkout compiled against QtWebKit or QtWebEngine 5.5):

1. launch Otter using a new profile, open http://aur.archlinux.org/packages
1. open an arbitrary package from the list in a new tab by middle-click
1. click `Download snapshot` in box `Package Actions` in the upper right and save the archive as usual using the dialog window that comes up; sometimes this will trigger the crash at once, otherwise
1. close all tabs except the one containing the package listing stated above and repeat steps 2 and 3 several times choosing different packages

**Comment by Emdek** [comment]
@pmattern, is it still reproducible after above change?

**Comment by pmattern** [comment]
Problem can still be reproduced as depicted in my previous post with 65d6b76 compiled against QtWebKit or QtWebEngine from Qt 5.5.0 on Arch Linux i686 or x86_64.

**Comment by Emdek** [comment]
@pmattern, now it's different crash. ;-)
http://www.wklej.org/id/1777535/

For me it happens totally randomly and it's something more common, I've found similar backtraces from back to 2010...
Most likely it's something trivial, we had similar issue more than one year ago.

**Comment by Emdek** [comment]
New ticket: #925.
