### ISSUE TITLE
address bar: drop-down history saving unneeded entries

### ISSUE THREAD

**Issue by pmattern** [OtterBrowser/otter-browser#900]
The history from the drop-down in address bar sometimes saves topics which definitely shouldn't be saved.

So far I stumbled upon this at two occasions:
Links opened in a new tab or window, either from the context menu or tab by middle click, are always saved.
On http://dict.leo.org each query that's submitted by filing some string and hitting enter key gets saved as well.

Otter from latest Git checkout on Arch Linux i686 or x86_64.

**Comment by Emdek** [comment]
It appears that `QWebPage::acceptNavigationRequest()` started to return invalid values which prevented clearing of flag that indicated that URL was typed-in.

**Comment by pmattern** [comment]
24a7b44e5 is fixing the problem on dict.leo.org while addresses opened in new tabs or windows are still added.
Commit compiled against QtWebKit or QtWebEngine on Arch Linux x86_64.
