### ISSUE TITLE
Open in New Tab menu item behaviour

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#902]
In Opera, there was a subtle feature in Open in New Tab menu item (right-click on a link and select Open in New Tab).

When you click it, it opens in new foreground tab. But Ctrl+click opens it in background tab. This made Open in Background Tab item unnecessary for me and shortened the menu. 

Can we have this in Otter too?

**Comment by Frenzie** [comment]
While I agree that Opera's keyboard modification of menu entries is very nice, don't Shift + click and Ctrl + click make both menu entries unnecessary provided you have two hands available? (That's why I never removed both — in rare circumstances it does makes sense to only use the mouse.)

**Comment by ersi-dnd** [comment]
I didn't mean to remove any of the menu items *by default.* I meant to suggest a feature to a menu item that could be used by those who use it that way. 

But yeah. One way to put it is to say that I am asking for luxury.

**Comment by ersi-dnd** [comment]
Thanks, but in the name of consistency, the same should apply to Open Image in New Tab...

**Comment by Emdek** [comment]
@ersi-dnd, yeah, the same applies to frames.
