### ISSUE TITLE
Avatar view of regular GitHub accounts not working

### ISSUE THREAD

**Issue by pmattern** [OtterBrowser/otter-browser#904]
The large view of regular users' (no organizations) avatars on GitHub isn't working but just displays an empty page.

Steps to reproduce: open a suitable account like e. g. https://github.com/Emdek - click on the avatar above the name at the left (Albert Einstein in this example). An empty page will be shown.

Problem can be seen with latest VCS checkout of Otter compiled against QtWebKit or QtWebEngine but not with Chromium, Firefox or QupZilla, the latter compiled against QtWebKit or QtWebEngine as well, all of which do display an enlarged view of the avatar.

All findings on Arch Linux i686 and x86_64.

**Comment by Emdek** [comment]
Github uses restrictions that break our workflow.

@Frenzie, could you please remind me why are we using extra IMG? ;-)
I think the one only way to fix it would be to use original one.

**Comment by Frenzie** [comment]
@Emdek Webkit keeps changing attributes on the first IMG constantly, perhaps most obnoxiously the -webkit-user-select one which interferes with dragging. By using a cloned IMG all of Webkit's tinkering is avoided. I'm surprised this security policy stuff even does anything for user scripts, which are supposed to have a form of elevated privileges anyway.

**Comment by Frenzie** [comment]
Could we do something with this as a workaround or is that unrelated? http://doc.qt.io/qt-5/qwebsecurityorigin.html

**Comment by Emdek** [comment]
@Frenzie, thanks.
Nope, this won't help and wouldn't help with QtWebEngine anyway...
Sadly our calls to execute JS are not privileged (the same applies to QtWebEngine).
I think that I've managed to solve it (at least mostly) by removing newly added attributes using this:
https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver

**Comment by Frenzie** [comment]
Oh, those work properly in the Webkit backend? Mkay, cool.

**Comment by Emdek** [comment]
@Frenzie, yeah, they support them but they do not have support for this:
https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mutation_events
