### ISSUE TITLE
Open Image in New Tab should not display the file name

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#905]
Open Image in New Tab should not display the file name, because file names can be long and this makes the menu wide and ugly.

Image file name belongs under Image Properties. 

Under Image Properties we have right now the image URL field concatenated, but I think there's enough space to wrap the URL so that the complete URL would be visible. Just in case, maybe limit the display of wrapped URL to six lines or so, but this should not affect selecting and copying. At selecting and copying, the user should get the full URL.

**Comment by Emdek** [comment]
There are plans to allow to overwrite action text for menus in generic way, so we don't need to remove this feature. ;-)

Labels in Image Properties are scrollable, it's not perfect but is good enough in most cases, more useful feature would be to allow to resize that dialog.
I'll reevaluate that feature.
