### ISSUE TITLE
support Pepper API

### ISSUE THREAD

**Issue by DI555** [OtterBrowser/otter-browser#908]
I don't know... may be it's an upstream...but could be really great if Otter could support pepper api!

**Comment by The-Compiler** [comment]
Yep, that's the responsibility of the engine - QtWebKit never will support PPAPI, and I believe QtWebEngine will starting with the Qt 5.6 version (at least for flash): [change](https://codereview.qt-project.org/#/c/104669/)

**Comment by Emdek** [comment]
Duplicate of #221.
