### ISSUE TITLE
Sidebar issue

### ISSUE THREAD

**Issue by resbro** [OtterBrowser/otter-browser#910]
The highlighted name of the panel you have open (on top of the sidebar) covers the "Open Panel as Tab" button on most of the panels making the button not work. The Configuration button and the bookmarks buttons have a long enough name that it doesn't get covered. On the  transfers button I can just touch the farthest point to the right and anything with a shorter name get covered by the panel name highlighting.

Sidebar on the left side
Widows 10x64
Otter weekly 81x32

**Comment by Emdek** [comment]
Could you please post screenshot showing this issue?
Is this specific to that version of Windows (in this case it could be classified as upstream theming issue) or was also reproducible using older versions?

**Comment by resbro** [comment]
I'll Try. I dont think it's Win 10 specific.It did it in win 8.1 before I updated to 10. Alas, my Win 7 machine died a glorious death not long ago and I think it did it too, but am not sure.

file:///C:/Users/Robert/Desktop/cap 01.png
file:///C:/Users/Robert/Desktop/cap 02.png
file:///C:/Users/Robert/Desktop/cap 03.png, 
file:///C:/Users/Robert/Desktop/cap 04.png

**Comment by resbro** [comment]
Nope. apparently I can't.

**Comment by Emdek** [comment]
@resbro, just use some external image hosting (for example [this one](http://simplest-image-hosting.net/)) and post link in comment.

**Comment by resbro** [comment]
![cap 01](https://cloud.githubusercontent.com/assets/8714625/9156370/53f55ae6-3e8c-11e5-95b0-4362120aafae.png)

**Comment by resbro** [comment]
![cap 02](https://cloud.githubusercontent.com/assets/8714625/9156371/75ef5bce-3e8c-11e5-86d3-79fc5b5d5e6d.png)

**Comment by resbro** [comment]
![cap 03](https://cloud.githubusercontent.com/assets/8714625/9156374/856c6600-3e8c-11e5-88a0-c1488f80f406.png)

**Comment by resbro** [comment]
![cap 04](https://cloud.githubusercontent.com/assets/8714625/9156375/9009bdb0-3e8c-11e5-9cb2-4f6ce63a7a66.png)

**Comment by resbro** [comment]
Maybe just a spacing thing? I don't know, but you can't select the arrow button if it's highlighted over.

**Comment by Emdek** [comment]
@resbro, more like sizing issue.
That bluish rectangle is drawn when widget has focus, right?

I can't reproduce this on Windows 7, I'll try on 8.1 when VM will be ready.

**Comment by resbro** [comment]
Blue Box (highlighted area) appears when moused over, yes. but it appears to only highlight the name. It doesn't do anything if you click on it.

**Comment by resbro** [comment]
The Panel name highlighting is a constant size (aprox 30 % of top bar)for all panels, but the "Open Panel asTab" button moves depending on the spelling of the name of the panel opened.

**Comment by resbro** [comment]
Tried a fresh install. Deleted everything and started over. It isn't doing it now so it must have been some conflict in my settings. Sorry to waste your time.

**Comment by Emdek** [comment]
@resbro, it couldn't be caused by settings.
Let me know if it would show up again.

**Comment by resbro** [comment]
OK, I'll keep an eye on it.
