### ISSUE TITLE
[Feature request] Add support for WebRTC

### ISSUE THREAD

**Issue by CarbonFixer** [OtterBrowser/otter-browser#911]
Otter browser currently does not support web conferencing (http://www.webrtc.org/).

Support can be tested on:
http://iswebrtcready.appear.in/

Note that QupZilla (1.9) does support WebRTC, so the needed functionality must exist in Qt.

**Comment by Emdek** [comment]
Apparently it's available with QtWebEngine (see #615) but not QtWebKit.
I think that 1.9 is already QtWebEngine based.
