### ISSUE TITLE
QtWebKit does not support WebAudio

### ISSUE THREAD

**Issue by fguzm** [OtterBrowser/otter-browser#912]
I want to download a driver at http://support.amd.com/en-us/download
but my selection always resets and nothing happens.

Before that I wanted to test some online noise generators, none of them worked:
http://onlinetonegenerator.com/
http://mynoise.net/NoiseMachines/rainNoiseGenerator.php
http://www.soundsnap.com/tags/generator
and so on

That's totally annoying as I do not want to use vivaldi shit browser.

**Comment by resetnow** [comment]
My guess is that tone generators use relatively new Web Audio API and QtWebkit doesn't support it. Have you tried using QtWebEngine instead?

**Comment by Emdek** [comment]
@fguzm, as noted by @resetnow, WebAudio is not supported by QtWebKit (it has switch to enable it but it's broken) and works with QtWebEngine (see #615).
