### ISSUE TITLE
Saved sessions now only open in new window?

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#913]
In session manager there's a place to check "Open in current window". It seems to have no effect any more. Saved sessions open in new window despite of this setting.

**Comment by Emdek** [comment]
Cannot reproduce.
Does that session contain more than one main window?

**Comment by ersi-dnd** [comment]
Just one window. I tried again by saving a new session. The issue persists.

On the other hand, it does not occur in a clean profile. There must be something with my settings.

**Comment by ersi-dnd** [comment]
When I have Otter open, and then I launch a link into Otter from another app, Otter opens a new window. I think this is related. I don't know the setting that tweaks whether links from other apps open a new window in Otter or a new tab in the existing window.

**Comment by Emdek** [comment]
@ersi-dnd, yes, this could be related.

**Comment by Emdek** [comment]
After all it was a corrupted session file.
