### ISSUE TITLE
[MDI] Regression, last subwindow not always maximized

### ISSUE THREAD

**Issue by fguzm** [OtterBrowser/otter-browser#915]
I know this is a feature, but I cannot find the switch to disable it.

**Comment by Emdek** [comment]
Try setting *Browser/EnableTrayIcon* to **false** (in about:config or In preferences -> Advanced -> Other).

**Comment by fguzm** [comment]
I start otter with "otter-browser -geometry 1100x1040".
When I enable the tray icon, otter opens as if not using this geometry thing: a tiny window and not remembering the window size for the next launch. And yes, the inner window fills the root window then. But alas, this is not what I want.

debian amd64, openbox

**Comment by Emdek** [comment]
@fguzm, it appears to be at least related to #597.
Could you please provide screenshot showing this issue?

**Comment by fguzm** [comment]
I have made a sreenshot, but how can I upload it?
BTW new tabs are maximized

**Comment by Emdek** [comment]
@fguzm, you can use some external image hosting and post link in comment.

**Comment by fguzm** [comment]
http://postimg.org/image/s37em8121/

**Comment by Emdek** [comment]
@fguzm, ah, MDI. :-)
Are you using master? This appears to be regression after recent changes, although in my case it only happens sometimes when restoring session.
I'll investigate that later today.

**Comment by fguzm** [comment]
git reset --hard
HEAD is now at 1874592 Remove Interface/EnableMdi, now QMdiArea is created on demand (restoring session that uses it, triggering some actions etc.), references #212
Is this master? Don't know.

**Comment by Emdek** [comment]
@fguzm, yes, so it's regression described above.

**Comment by fguzm** [comment]
Does not work for me

**Comment by Emdek** [comment]
@fguzm, so session still starts with not maximized window for you?
Which values are set for *Interface/NewTabOpeningAction* and *Browser/StartupBehavior* in *about:config*?

**Comment by fguzm** [comment]
Yes, nothing changed
Interface/NewTabOpeningAction maximize Tab
Browser/StartupBehavior startStartPage

**Comment by VSHY** [comment]
People ask where MDI disappeared? "Minimize" button for tabs (on the right), corresponding context menu item and option for MDI in Configuration manager are missing.

**Comment by Emdek** [comment]
@fguzm, is this ticket still valid?
f27bc64 should fix it.

@VSHY, MDI is now always enabled, what exactly is missing?

**Comment by VSHY** [comment]
@Emdek 
There are no control buttons for tabs: Minimize, etc.

**Comment by fguzm** [comment]
All is good now

**Comment by Emdek** [comment]
@fguzm, thanks for confirmation.

@VSHY, I guess that I could at least Minimize and Maximize to context menu.
There were no such buttons earlier, other than side effect of unwanted feature of ``QMdiArea``, for now you can add these actions to toolbar (it will work better with option to set custom icon for button which should be available soon). In future there might be special widget for tab controls.

**Comment by VSHY** [comment]
@Emdek 
I found out what it means "to fold tab" (not Minimize, I'm sorry).
If one click on current tab then the tab will be hidden, focus will be moved to the previous used tab. And so on to first opened tab. At the end browser should show gray background.
If one click on hidden tab then that tab will be revealed.
As it works it's possible to see in the Opera Presto.

**Comment by Emdek** [comment]
@VSHY, this behavior will be achievable when #77 will be done, by adding gestures for tab bar.

BTW, Maximize and Minimize are now available in context menu of tab bar.

**Comment by VSHY** [comment]
@Emdek 
Thanks for your answer!

**Comment by VSHY** [comment]
There is small bug in the build 94 - "Minimize" context menu item shows content of previous tab in tab that should be minimized.

**Comment by Emdek** [comment]
@VSHY, do you mean graphical glitch or something else?

**Comment by VSHY** [comment]
@Emdek 
It looks like that. The focus does not move to the previous tab.
