### ISSUE TITLE
Import bookmarks and settings

### ISSUE THREAD

**Issue by mariokamenjak** [OtterBrowser/otter-browser#918]
Is the browse able to import bookmarks and optionally other settings from Firefox,Chrome/Chromium and IE/Edge?
(eventually you could add Opera to the list)

**Comment by Chocimier** [comment]
Yes, but first you need to export bookmarks to HTML format, then import in  
Otter from created file.
It's also possible to import bookmarks direct from Opera bookmarks file.

**Comment by mariokamenjak** [comment]
Aha,cool.
