### ISSUE TITLE
URL in the address field should be draggable

### ISSUE THREAD

**Issue by ersi-dnd** [OtterBrowser/otter-browser#924]
In other GUI browsers, it's ordinary to drag the URL from the address field to the Bookmarks bar. Now, Opera did not have a way to drop URL's to the Bookmarks bar (Personal bar), but URL's were draggable from the address field, to drop them to email composer window, to Notes, or to another program. 

Otter should at least have dragging from address field.

**Comment by Frenzie** [comment]
I see. In Firefox you can do that by dragging on the little world or lock icon. Same for Opera. But it might be planned along with when the icon appears?
