### ISSUE TITLE
Windows - Crash when having download dialogue

### ISSUE THREAD

**Issue by SJ-Diamond** [OtterBrowser/otter-browser#925]
Tried to download a file from Dropbox, download dialogue appeared where i can pick the application to open the file and save it, dropdown arrow click for chosing the application triggered an instant crash, same like just trying to save the file.

Error message is this i found in the event manager:

Faulting application Name: otter-browser.exe Version: 0.9.0.7, time stamp: 0x55dd57fb
Name of the faulty module: Qt5Widgets.dll Version: 5.5.0.0, time stamp: 0x55912083
Exception code: 0xc0000005
Fault offset: 0x00000000002a306c
ID of the faulty process: 0x1b48
Start time of the faulting application: 0x01d0e358501d56b2
Path of the faulty application: C:\Users\SaphirJD\Desktop\Otter\otter-browser.exe
Path of the faulty module: C:\Users\SaphirJD\Desktop\Otter\Qt5Widgets.dll
Report ID: 9dca974a-4f4b-11e5-8482-bdf40ab1bd6c

**Comment by SJ-Diamond** [comment]
What does work are the 2 right mouse context menu entries save to downloads and save link target as.

Crashes appear on both Win8 and Win7 64 bit

**Comment by Arandhras** [comment]
I have the same issue, left-clicking any web link to a file triggers a browser crash.

**Comment by VSHY** [comment]
I had a crash in beta 7 and build 88 when I tried to download otter-browser-win32-weekly88.zip.

**Comment by ZarkBit** [comment]
Seems fixed.

Can anyone else confirm?

Otter 0.9.08 Weekly 91
Windows 7 64bit

**Comment by VSHY** [comment]
@Emdek 
Try to download otter-browser-win32-weekly91.zip:
1. A temporary file are downloading to profile dir (c:\Users\{user}\AppData\Local\Temp\); it don't use Paths/Downloads setting.
2. If to click on Save button then empty FileSave dialog appears; try to click the Save button, - sametimes this leads to a crash (it reminds #701).
I used weekly91 with QtWebKit.

**Comment by Emdek** [comment]
@VSHY, that temporary file was always there (we need some buffer to store data before user decides what to do with download), but save dialog crash most likely caused auto deletion or was occurring too early to even create it.

Could you please post screenshot of that empty file dialog?
I'm getting instant crash after clicking Save in ``TransferDialog`` under Windows 7 32 bit (but works fine with Windows 10 64 bit).

BTW, it's possible to configure downloads using *handlers.ini* so this dialog won't show at all and won't create temporary files.
I'll add UI for that soon after releasing v2.

**Comment by VSHY** [comment]
Dropbox.
Upload to Dropbox some photos. Exit from Dropbox.
Open url with photos.
Click "Download -> Download as .zip" and close dialog "Create Account", as result - processor is busy on 25%, nothing happens. Click button Stop in browser.
Click "Download -> Download as .zip" newly, click Save button in Download dialog, as result - crash.

**Comment by VSHY** [comment]
@Emdek 
> Could you please post screenshot of that empty file dialog?
> I'm getting instant crash after clicking Save in  TransferDialog  under Windows 7 32 bit
Now I have the same result on that environment and I can't reproduce the empty FileSave dialog, sorry. Maybe later.

**Comment by uahim** [comment]
91 crashes on Win XP, the dialog opens and the file is being downloaded completely/to 100% (to a temporary directory I guess), and when you click e.g. "save", the file save dialog opens for less than a second  - and Otter dies

**Comment by Emdek** [comment]
@VSHY, @uahim, Save crash should be fixed now (at least I can no longer reproduce it using Windows 7 VM where it was almost 100% reproducible), although use of combobox still causes crash due to upstream issue (use of *-style fusion* command line switch might help in this case).
