### ISSUE TITLE
Selecting text in addressbar not possible

### ISSUE THREAD

**Issue by fguzm** [OtterBrowser/otter-browser#927]
at least with my mouse

debian amd64
qtwebkit, Qt version 5.4.2, Otter 0.9.07 beta 7

**Comment by Frenzie** [comment]
Confirmed. It's probably related to #924, because I'm pretty sure it used to work.

**Comment by VSHY** [comment]
On Win7, qtwebkit, Qt 5.5.0, Otter beta 7 too.
