### ISSUE TITLE
mouse gestures not working regularly on some parts of the page

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#928]
Hi,
I'd like to mention some differences in handling the mouse gestures in Otter comparing to classic Opera.
In some cases, the gesture somehow isn't recognised and the context menu is shown instead.
The most consistent case seems to be the gestures starting in the link text (e.g. gesture up+down with right mouse button pressed - for reloading the page. (There may be other cases, but I wasn't able to simulate them consistently.)
Similarly, the gestures in Opera are even available in other parts of the browser (tabs, empty tabbar spase, some other bars etc.)
Could this be achieved in Otter somehow, or is it not possible currently?

regards,
   vbr

**Comment by Emdek** [comment]
These two issues (fallbacking to generic context if there is no link specific gesture and adding support for them elsewhere) are being worked on as part of #77, so it can be considered as duplicate.
