### ISSUE TITLE
Hope to be able to add the following functions

### ISSUE THREAD

**Issue by macos15** [OtterBrowser/otter-browser#929]
Hope to be able to add the following functions:
Custom mouse gestures; The custom text drag, links drag, images drag; User js and CSS;
Filtering advertisements; Firefox extension support with Google, the above function made a world-beater.
thank you.

**Comment by Frenzie** [comment]
UserJS will be coming, but UserCSS is actually already available! :) At least the site preferences version; quickly toggleable user styles aren't available yet.

**Comment by Emdek** [comment]
@macos15, all missing features have own tickets, like #336 or #42. ;-)
