### ISSUE TITLE
A few beta 7 issues (blank page, updater, missing dll)

### ISSUE THREAD

**Issue by uahim** [OtterBrowser/otter-browser#931]
1. selecting "blank page" from the startup dialog leads to a little blank page as seen below, rather than a maximized one is this the desired/expected behavior?
![](http://thewilderness.bplaced.net/otter/blank_page.png)

2. updater (via help|update) suggests weekly 86 which is obviously (or am I mistaken here?) older than beta 7

3. on a clean/fresh install, Otter claims "MSVCP120.dll is missing from your computer." which can of course be fixed by seperately installing Visual C++ Redistributable Packages for Visual Studio 2013. just wondering why because this did not happen before.

thanks.

**Comment by fguzm** [comment]
Very annoying, I more and more often use Vivaldi because of this and #923 and #915

**Comment by Felipefpl** [comment]
it sucks when dlls are missing, i had problems with other apps because of them, in fact it's better if there is no need of redistributable at all.

**Comment by uahim** [comment]
@Emdek with beta 88, the update notifcation problem is fixed, but apparently updater.exe is not built to run on WinXP? ("...is not a valid Win32 application")

the blank-page-bug (if it is one) is still present

**Comment by Emdek** [comment]
Missing DLLs should be fixed in weekly 89 (probably they got lost while preparing new virtual machine...).
I'll try to fix remaining issues in time for v2 packages for beta7 (hopefully it will be ready in this week).
