### ISSUE TITLE
Middle-clicking on links pastes clipboard contents to edit boxes/text areas

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#932]
Like the title says, if I have focus on some edit box or text area and I middle-click a link to open it, Otter pastes the clipboard contents then opens the link.

To repeat:
1. copy text
2. click some edit box or text area
3. middle-click a link

I think this is a new issue. At least I don't remember seeing it before.

**Comment by beastie1** [comment]
Can we re-open this issue?

**Comment by Emdek** [comment]
@beastie1, above change solves that issue for me, but I can try to find another approach.

**Comment by Emdek** [comment]
@beastie1, could you please check if recent changes had impact on this issue?

**Comment by beastie1** [comment]
It's still there in the master build :/

**Comment by Emdek** [comment]
@Chocimier, perhaps we should force desired behavior using defaults gestures, not relying on QtWebKit to behave properly?
