### ISSUE TITLE
Update User Agent Strings

### ISSUE THREAD

**Issue by opticyclic** [OtterBrowser/otter-browser#934]
The provided user agent strings are now a bit dated due to the rapid development of other browsers.
e.g. if you mask as Firefox GitHub will overlay a warning.

It is also strange that the Opera UA String is 12.14 and not 12.17 as that was the last classic version released.

**Comment by Felipefpl** [comment]
I agree, it's a small but necessary change.

**Comment by beastie1** [comment]
For Opera make that 12.16. I don't know if it matters for UA strings, but IIRC 12.17 was a Windows-specific release.
