### ISSUE TITLE
link-open dialog (hardcoded style?)

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#937]
Hi, thanks for the many improvements in latest versions.
I noticed a small glitch in weekly 88 in the newly added enhanced link-open dialog.
It show with different window styling comparing to other dialogs in Otter.
I am using window 7 with an ancient theming like win98 and the dialogs in Otter generally respect this setting. The open dialog, however, shows in an more modern style - regarding caption bar and closing cross icon.
It is just a minor issue, of course.
         regards,
              vbr

**Comment by vbr** [comment]
Sorry, I am recognising now, that the style of that dialog is the same like e.g. javascript alerts and other dialogs; in this sense the download dialog looks consistent with these elements, while I previously expected the theming of main app dialogs main.
Regards,
     vbr

**Comment by Emdek** [comment]
@vbr, yeah, all these dialogs have the same style, we could try to make them look more native, but often such dialogs have independent style.

**Comment by Emdek** [comment]
Closing since there was no feedback.
