### ISSUE TITLE
History unstable on Windows builds

### ISSUE THREAD

**Issue by SJ-Diamond** [OtterBrowser/otter-browser#938]
From time to time all history gets suddenly lost in the browser.

Even if the function to clear stuff automatically is turned off, from time to time the whole history is just resetting to zero. Can happen when the browser is just started, can happen if the browser is running for a longer time.

Suddenly, all gone :(

**Comment by ZarkBit** [comment]
I noticed that yesterday, I have otter set to remember browsing/downloads history, and yet the history windows is pretty much empty, the option to clear the records is off.

Transfers history seems fine.

Otter 0.9.08 Weekly 91
Windows 7 64bit
