### ISSUE TITLE
default rendering - selected <select> text

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#940]
Hi,
I'd like to mention a bit strange default rendering of the selected <select> text (in weekly 88, win7; most likely in older versions too).
If no css styling is specified, there is black text on white background, the pulled down options under the mouse during the selecting are inverted to white text, the selection background is dark blue.
However, in the selected state (without other <option>s being visible) there is no inversion and there is mostly unreadable black text on dark blue background.

A workaround I could find via user css
select { background-color: silver;}
select { color: black;}

is somehow viable, but interestingly, in this case the selection/focussing of this element (after closing the options or via tabbing) isn't rendered at all (no dotted border or background colour).
Are there maybe some other possibilities to tweak the default rendering or should the user css approach reflect some other parameters?

thanks,
    vbr

**Comment by Emdek** [comment]
Could you please confirm it using *test-qtwebkit.exe*?
It looks like some kind of upstream issue.

**Comment by vbr** [comment]
Hi, unfortunately, I am not able to run test-qtwebkit.exe properly right now (weekly 88 32bit, Win7, Czech).
On running the testing exe, i get the following Error (roughly translated from Czech):
"Entry point of the procedure _ZN10QArrayData10dealocateEPS_jj could not be found in the dynamically linked library Qr5Core.dll."

I was thinking, this was due to my way of updating the weeklies (just overwriting all files from the 7z archive all the time), but now I am getting the same error after a clean install from the exe-installer.
However, the main otter executable doesn't have this error.
Could I test the original issue or this problem in some other way?
vbr

**Comment by vbr** [comment]
Hi,
using test-qtwebkit.exe from weekly 89 I can now confirm, that it shows the same rendering like Otter - i.e. black taxt on dark blue background for the selected/focussed <select>.
regards,
    vbr

**Comment by Emdek** [comment]
There exists a bit similar upstream report:
https://bugreports.qt.io/browse/QTBUG-30140

Although I doubt that it will get fixed at all...
