### ISSUE TITLE
Not all languages supported by nativeLanguageName(), nativeCountryName()

### ISSUE THREAD

**Issue by lagleki** [OtterBrowser/otter-browser#942]
Lojban language is supported by Otter but isn't supported by the following code:

https://github.com/OtterBrowser/otter-browser/blob/master/src/ui/LocaleDialog.cpp#L41

```m_ui->languageComboBox->addItem(QStringLiteral("%1 (%2) [%3]").arg(locale.nativeLanguageName()).arg(locale.nativeCountryName()).arg(identifier), identifier);```

For this case I suggest storing its nativeLanguageName in Otter, and not showing nativeCountryName (since it's not bound to any particular country). I suggest the result to be

locale.nativeLanguageName()="la .lojban.";
getting "la .lojban. [jbo]" as the string shown to end users.

**Comment by Emdek** [comment]
@lagleki, we depend on that stuff to be handled by Qt, this is not something critical.
I've modified code to skip extra arguments if they are empty but forgot to update this ticket.
