### ISSUE TITLE
OpenLinkInNewPrivateTab/Window actions create non-private tabs

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#944]
The following actions don't create **private** tabs/windows when added to the **link** context menu:

OpenLinkInNewPrivateTab
OpenLinkInNewPrivateTabBackground
OpenLinkInNewPrivateWindow
OpenLinkInNewPrivateWindowBackground

**Comment by beastie1** [comment]
See http://thedndsanctuary.eu/index.php?topic=1453.msg46103#msg46103

**Comment by beastie1** [comment]
It seems it's still not working :\

**Comment by Emdek** [comment]
@beastie1, all of them?
I've just checked it again and they all work fine for me.

**Comment by beastie1** [comment]
All of them. I created a /menu/webWidget.json file with the defaults and added the 4 lines. If I'm logged-in (on GitHub or elsewhere) I'm still logged-in in the newly-created private tabs. The 4 *private actions behave like the normal actions.

I've also tried with a new profile.

I'm using Qt 5.4.1.

**Comment by beastie1** [comment]
By the way, the new private tabs do have the anonymous favicon, but login information is persistent.

**Comment by beastie1** [comment]
Great! Now it works fine. :)
