### ISSUE TITLE
otter-browser.org blocked selectively?

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#945]
Hi,
I am encountering problems (for a few weeks now) in accessing otter-browser.org using my home internet connection ( provider Ada-Net.cz). Otter simply shows Error 99 - Connection timed out.
At work or using vpn from there the page can be displayed normally.
Can there possibly remain some selective blocking (mentione in the past).
thanks and regards,
    vbr

**Comment by Emdek** [comment]
Thanks for report, should be fixed now.

**Comment by vbr** [comment]
Thanks, now I can access the homepage without problems.
vbr
