### ISSUE TITLE
closing windows in a manner similar to Firefox

### ISSUE THREAD

**Issue by msjasinski** [OtterBrowser/otter-browser#946]
It is a minor issue but still. If you want to close a window, you should be able to do it by clicking in the X of its last tab. Doesn't matter if it is your first, second or third open window. Firefox works this way and it is better ImHO.

**Comment by Frenzie** [comment]
Should be configurable. I strongly dislike Firefox' behavior, at least for the last window. I'm looking to close a page, not the program.

**Comment by msjasinski** [comment]
Ctrl+W should also do it.

**Comment by msjasinski** [comment]
@Frenzie I agree.

**Comment by Frenzie** [comment]
Note that Opera/Presto closes the window upon closing the last tab only if there are still other windows open.

**Comment by Frenzie** [comment]
@msjasinski Most of this behavior is already there. In about:config > LastTabClosingAction you can choose openTab, closeWindow or doNothing.

**Comment by msjasinski** [comment]
Thanks! I didn't know that.
Except that I can't make my Opera 12 close its second window in this manner. But nevermind, it's not a bug tracker for Opera.
I think we can close this ticket.

**Comment by Frenzie** [comment]
In Opera, if you have an empty tab (speed dial) you can't close it, but if you have something in it, it closes the window.

**Comment by msjasinski** [comment]
It does.
