### ISSUE TITLE
Prevent window snapping

### ISSUE THREAD

**Issue by Plaristote** [OtterBrowser/otter-browser#947]
I've seen that recent versions of Otter allow us to display the tabs as windows, in cascade or tile mode.

The problem with this is that sometimes, the windows try to snap together, and the snap works really bad: it's just impossible to move the windows where you want them to be.

Is it possible to disable that snap feature ? Or even better, to make it configurable ?

**Comment by Plaristote** [comment]
I've inspected the source, and as far as I can tell, it seems to be coming from upstream. I'm even wondering now if it's truly a snapping issue or just an issue with mouse events.

I can't tell why the window move like crazy everywhere when I start moving them. Considering the activity in here, I'm guessing I'm the only one going through this ?

**Comment by Frenzie** [comment]
I'm not seeing any snapping, but I didn't test it with a clean profile. I believe that on the open-source drivers Qt drawing may be a tad slow on Linux; could that be it?

**Comment by Emdek** [comment]
@Plaristote, which platform are you using?
This might be something platform specific, MDI implementation in Qt is quite complex and has some odd and unwanted features that had to be disabled...
We can try to create own implementation in future, although current should be good enough for most cases.

**Comment by Plaristote** [comment]
Well, at least my environment isn't too hard to reproduce: it's a VirtualBox VM, and it's compiled with Qt 5.5.0.
I was guessing that with such a configuration, I wouldn't be the only one dealing with this bug.

**Comment by Frenzie** [comment]
And what's in the VirtualBox VM? A Linux distro? Windows? I don't see any
MDI window snapping with Qt 5.5 in both Linux (Debian Jessie x64) and
Windows (10 x64).

**Comment by Plaristote** [comment]
It's an Archlinux. The real issue is that my window manager is Kwin (KF5). I noticed it works fine when the composite mode is disabled.

**Comment by VSHY** [comment]
There is similar problem I have wrote in https://github.com/OtterBrowser/otter-browser/issues/915 at the end of that discussion.

**Comment by Emdek** [comment]
I'm planning to go for custom MDI workspace, this will prevent any unwanted "extra features.
See #1077.
