### ISSUE TITLE
Sidebar should always be on the left edge of the window, or its position should be customizable

### ISSUE THREAD

**Issue by Plaristote** [OtterBrowser/otter-browser#948]
When the tab widget is placed on the left of the window, it moves the sidebar to the right (the layout is tab bar / sidebar / page content)

It ends up looking kinda weird... whereas Vivaldi's browser has the sidebar on the left of the tabs, and it looks perfectly natural (sidebar / tab bar / page content).

I think the sidebar should always be to the left of everything else, even when the tab widget is put to the left of the windows. Or even better yet, we should be able to move the sidebar (have it on the right of the window would be pretty neat as well).

**Comment by Felipefpl** [comment]
one more suggestion: make the sidebar EXACTLY the same size as the one from Opera 12.

**Comment by VSHY** [comment]
And yet I would like to have the additional setting "Widgets of sidebar to open in tabs". Not to duplicate tabs with widgets, only move the focus to the appropriate tab.

**Comment by Emdek** [comment]
@Plaristote, current behavior is the same like in classic Opera.
We could again try to experiment with making it to behave like ordinary toolbar (previously we were hitting QtWebKit bugs with caused crash while moving ``QDockWidget``, but we aren't using that widget anymore anyway), that way it could be placed in any combination.
We could combine this with support for multiple sidebars (plus option to hide switcher buttons) and it would become very flexible.

**Comment by Emdek** [comment]
Superseded by #1086.
