### ISSUE TITLE
Crash on CTRL+Left-click

### ISSUE THREAD

**Issue by mmirco** [OtterBrowser/otter-browser#950]
Crashes, whenever trying to open a link in a new tab via CTRL+Left-click.

(Otter 0.9.05 beta 5; WebKit 538.1; OpenSSL 1.0.1p-freebsd)

**Comment by VSHY** [comment]
On Otter 0.9.08 weekly 89 WebKit... this crash is absent.

**Comment by Emdek** [comment]
@mmirco, this looks like issue that was fixed soon after release of that beta (which is very outdated, we had beta 7 one month ago...), hopefully maintainers will finally update to new version soon...
