### ISSUE TITLE
Gmail loading on restoring session

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#951]
Hi, I just encountered some possible cornercase problem with opening Gmail on a new start of Otter where this page ( https://mail.google.com/mail/#inbox ) should be opened automatically within the autosaved session.
The pane with Gmail hangs with its loading gauge, but it loads correctly after a manual reload.
This might as well be a problem in the webmail interpreting the saved url. 
Regular opening of that page e.g. from startpage works ok without reloading.
(using Otter weekly 90, 32bit, on Win XPp).
regards,
      vbr

**Comment by vbr** [comment]
This problem seems to be resolved (for me) in the build 95 (win7, Otter 32bit, webkit). Unless it reappears again somehow, this can probably be closed.
vbr

**Comment by Emdek** [comment]
@vbr, I guess that was some regression in Qt 5.5.0 then, as that weekly uses 5.5.1.
