### ISSUE TITLE
report - command line option

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#954]
Hi,
I'd like to ask about the expected usage of the command line option --report .
I must be missing something trivial, but I can't find any output of this call.
I simply tried to start Otter as 
... \OtterBrowser>       otter-browser.exe --portable --report
or
... \OtterBrowser>       otter-browser.exe --portable --report "report.txt"
But I can't see any reported text or saved file etc. and the browser doesn't start.

The command line optione seems to be interpreted somehow though - the call is only "swallowed" silently (e.g. with an option like --repoRRRRt I get an error message about the unknown option)
(using Otter weekly 91, 32bit webkit on Win7).

regards,
    vbr

**Comment by Emdek** [comment]
@vbr, under Windows you need to redirect output to a file, for example:
`otter-browser.exe --portable --report > report.txt`

Probably there is some way to fix that without side effects (like command prompt window always shown in background...).

**Comment by vbr** [comment]
Ok, thanks, I thought, it was something that trivial.

**Comment by VSHY** [comment]
If one paste this string
<code>...\otter-browser.exe --portable --report > report.txt</code>
to Object field in Otter shortcut on Windows then browser does not start.

**Comment by Emdek** [comment]
@VSHY, that is normal, use of ``--report`` doesn't allow to show GUI at all, application just prints the report and closes.

**Comment by VSHY** [comment]
@Emdek 
Sorry, where is placed the file which was created after start with that commandline parameters? I don't find it.

**Comment by vbr** [comment]
Hi, the report file shoud be saved at the path given after > 
If only a filename is given, the folder of otter-browser.exe itself is used.
(It might be possible, that the write doesn't succede somehow - e.g. in Windows-protected folders like Program Files etc?)

**Comment by Emdek** [comment]
I guess that we should use dialog for this option under Windows, Qt already uses this way for `--help` and `--version` there.
