### ISSUE TITLE
Scolling on pages with many images freezes computer

### ISSUE THREAD

**Issue by fguzm** [OtterBrowser/otter-browser#955]
As an example, go to http://www.mainhattan-webcam.de/
click the 'Archiv' button in the upper left corner, select a previous day
and sroll a bit in the now opened frame. 
My computer freezes with otter..

**Comment by Emdek** [comment]
@fguzm, sadly this is one of these issues that we can't fix in way other than suggesting to try QtWebEngine backend (#615, should be way more usable with Qt 5.6, to be released before end of this year or soon after) or to workaround by disabling JS or images.
