### ISSUE TITLE
Trimmed button labels in the Preferences

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#959]
In the Preferences window, the labels of some buttons are too close to the border. This can easily be fixed by making the window a few pixels wider.

![screenshot-otter_15102015-214719](https://cloud.githubusercontent.com/assets/6757832/10524407/071a3a3a-7388-11e5-8fff-09f74bf215fd.jpg)

**Comment by Emdek** [comment]
Duplicate of #917.
