### ISSUE TITLE
Bookmarks icon doesn't reflect page's (un)bookmarked state

### ISSUE THREAD

**Issue by msjasinski** [OtterBrowser/otter-browser#960]
The problem only concerns the icon; at least I haven't come across any issues with bookmark database items.

Sometimes the icon is yellow when it should be white (unbookmarked)
Sometimes the icon is white (ubookmarked) when it should be yellow (bookmarked)

When it is unmarked but should be marked, and you click it, it becomes marked and doesn't open add bookmark dialog (the latter behaviour is right). E.g. when you click a link that is bookmarked, after loading the page it never shows "bookmarked" in the icon.

There are more scenarios. If need be I can try to describe them but I think the general picture is now clear.

**Comment by Emdek** [comment]
@msjasinski, is there any pattern that could help with reproducing this issue?

**Comment by msjasinski** [comment]
Since Beta 8 introduced URL completion in address field from bookmarks, it is hard for me to reproduce the bug. Maybe it should be closed for now.

One thing though. When I type in a new URL in a bookmarked tab, it doesn't get unbookmarked. In Firefox it loses the star, and when I click ESCAPE, it regains the star. -- I think Firefox has a better, more intuitive approach to this.

**Comment by msjasinski** [comment]
OK, I managed to reproduce the bug.

Go to page 

   http://www.ifpan.edu.pl/index_en.php

Bookmark it.

Choose from menu

Institute's offer > Ultrapure materials

You should be on page

http://info.ifpan.edu.pl/ultrapure/

which looks like it is bookmarked, but in fact it is not.

Checked on WinXP and Fedora23.
