### ISSUE TITLE
Build error & runtime crash

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#961]
The change happened between 16/10 and today.

While building I get
```
[ 36%] Building CXX object CMakeFiles/otter-browser.dir/src/ui/toolbars/GoBackActionWidget.cpp.o
/tmp/otter-master/src/ui/toolbars/GoBackActionWidget.cpp:176:1: warning: control reaches end of
      non-void function [-Wreturn-type]
}
^
1 warning generated.
[ 37%] Building CXX object CMakeFiles/otter-browser.dir/src/ui/toolbars/GoForwardActionWidget.cpp.o
/tmp/otter-master/src/ui/toolbars/GoForwardActionWidget.cpp:176:1: warning: control reaches end of
      non-void function [-Wreturn-type]
}
^
1 warning generated.
```

But it builds fine otherwise and finishes without further warnings or errors.

However when I run it with my existing profile it crashes every time I create a new tab.

If I try it with a blank profile it also crashes and just says "Illegal instruction" unless **otter.conf** has at least **LastTabClosingAction=doNothing** (I haven't tried other options).
But even when I have that, it still crashes when creating a new tab.

**Comment by Emdek** [comment]
@beastie1, do you have any backtrace for that crash?
Please try running it with gdb or using debug mode in QtCreator.

**Comment by beastie1** [comment]
Well it seems the above commit fixes it! :)

**Comment by Emdek** [comment]
@beastie1, thanks for information, it's odd that it was able to cause crash.
