### ISSUE TITLE
Better support for IP URLs

### ISSUE THREAD

**Issue by beastie1** [OtterBrowser/otter-browser#962]
**192.168.1.185:8080** doesn't work.

It works only when I add **http://**.

**Comment by komoku** [comment]
It doesn't seem specific to IP URLs, the problem seems to be the port, although the problem is slightly different with IP's and hostnames:

192.168.0.1:80 -> searches for the string in search engine
example.com:80 -> Error 301, Protocol "example.com" is unknown

**Comment by Chocimier** [comment]
I want add that IDN like яндекс.рф or kraków.pl are opened in default  
search engine, unless they are prefixed with protocol: http://яндекс.рф ;  
maybe this may be fixed together with above.
