### ISSUE TITLE
Otter - browser lacks a function:

### ISSUE THREAD

**Issue by macos15** [OtterBrowser/otter-browser#964]
Otter - browser lacks a function:

1. Drag and drop and gestures of the custom

2. The script does not support?

3. Password management. Can not save the password.

4. Plug-in should be placed where? 

5. Smooth scrolling

6. No MAC version ?

**Comment by Emdek** [comment]
You can find some answers in dedicated tickets, like: #832, #77, #622, #336.
Note that NPAPI based plugins are close to being obsolete by now...

**Comment by macos15** [comment]
Can directly to link?
Too complicated to understand.

**Comment by Emdek** [comment]
@macos15, here you can find notes and link for MacOS X packages:
https://github.com/OtterBrowser/otter-browser/wiki/Packages
