### ISSUE TITLE
faster tab switching (Ctrl+Tab)

### ISSUE THREAD

**Issue by vbr** [OtterBrowser/otter-browser#966]
Hi,
I'd like to ask about the initial delay of the tab switching via Ctrl+Tab.
Sometimes I find it useful to switch quickly to the next tab (and possibly back again), but it seems, that there is some delay before the switching is performed (possibly due to showing the switcher gui with page titles and thumbnails).
Fast Ctrl+Tab shortcus are ignored, it is necessary to hold the Ctrl key a bit longer (maybe a second or more).
Interestingly, even fast Ctrl+Tab+Tab seems to work without delay.

Would it be possible to keep both ways like in Opera, i.e. a quick switching, if the user wants the next page in the tab cycle immediately, as well as the slower mode (until the Ctrl is released), if the needed tab is first checked visually in the switcher gui?
(Win7, Otter webkit 32bit, weekly 94).

Thanks and regards,
         vbr

**Comment by ZarkBit** [comment]
Also noticed a slight delay before the tab switching window appears

Windows 7 64bit
Otter 0.9.08 Weekly 94

**Comment by xploSEoF** [comment]
This is either a Windows issue or an issue introduced in a later version - it doesn't happen in KDE weekly 83

**Comment by ZarkBit** [comment]
Tested Weekly 94 on Linux Mint and same thing happens

**Comment by Frenzie** [comment]
Same here on Debian Jessie testing the latest code from trunk as well as on
a build from last month or so.

**Comment by ersi-dnd** [comment]
sustained

**Comment by Emdek** [comment]
Then we have a problem, as current behavior was added to fix different issue, see e9daac0cf3855b043c0508d2f228a7654972f86a.

**Comment by ZarkBit** [comment]
I have check Weekly 62 2015-03-11 (please confirm that it's this one), which should be the one before the 200ms timer was added, and it works great to be honest

**Comment by Emdek** [comment]
@ZarkBit, I guess that I can give it a try, but not before beta.

**Comment by lc-guy** [comment]
confirming it is stlil happening on latest xubuntu
