### ISSUE TITLE
Style sheet

### ISSUE THREAD

**Issue by AcarBurak** [OtterBrowser/otter-browser#967]
Some time ago I've tried to use a custom style sheet, but failed. A wiki page would be fine. 

Having said that, all those dark and semi-dark user styles I've tried in Firefox have issues and are unusable. There's only one real solution (without any issue) to overcome the bright windows: https://userstyles.org/styles/45663/global-pseudo-brightness-control

Having this option built-in would be a very fine convenience.

**Comment by Emdek** [comment]
@AcarBurak, well, this is a task for user script or extension.
