### ISSUE TITLE
QtWebEngine: drop-down history unavailable

### ISSUE THREAD

**Issue by pmattern** [OtterBrowser/otter-browser#974]
If Otter Browser is using QtWebEngine the drop-down history in address bar isn't available.

Steps to reproduce on Linux
* Make sure no Otter instance is running. Remove `~/.cache/Otter` and `~/.config/otter`.
* Launch Otter, set Backends - Web to "qtwebengine" in `about:config`. Restart Otter.
* Visit some sites by filing their URLs manually in the address bar. Unlike when using QtWebkit there will be no drop-down history in address bar.

Seen with dea7b19 compiled against Qt 5.5.1 on Arch Linux x86_64. Problem can *not* be seen with the same commit compiled to use QtWebKit or recent VCS checkouts of QupZilla using any of the two web backends under otherwise identical conditions.

**Comment by Emdek** [comment]
QtWebEngine backend doesn't support global history yet as currently there is no sane way to keep track of it as of Qt 5.6.

**Comment by pmattern** [comment]
So how come the problem can't be seen in QupZilla? Did the QupZilla devs implement some workaround?

**Comment by Emdek** [comment]
@pmattern, we are using feature available only in QtWebKit to make sure that navigating through history tab history (back and forward) won't mess up global history by adding duplicated entries.
QtWebEngine backend requires different approach which will be investigated when Qt 5.6 beta will be ready to use.
You can track progress on that backend by following #615.
