### ISSUE TITLE
QtWebEngine: Opening links by middle mouse click yields two new tabs

### ISSUE THREAD

**Issue by pmattern** [OtterBrowser/otter-browser#975]
If Otter Browser is using QtWebEngine attempts to open links in new tabs by clicking middle mouse button are yielding two new tabs displaying the same link.

Seen with dea7b19 compiled against Qt 5.5.1 on Arch Linux x86_64. Problem can *not* be seen with the same commit compiled to use QtWebKit or recent VCS checkouts of QupZilla using any of the two web backends under otherwise identical conditions.

**Comment by AcarBurak** [comment]
Exactly the same situation on the same platform here.

**Comment by Emdek** [comment]
And it's no longer valid as now middle clicking link does nothing. ;-)
Middle clicking will return after updating backend against Qt 5.6 beta,until then it's officially broken.
Please follow its development using #615 until it will advance to stable state.
