### ISSUE TITLE
Weekly 95 Win.exe

### ISSUE THREAD

**Issue by resbro** [OtterBrowser/otter-browser#978]
![capture](https://cloud.githubusercontent.com/assets/8714625/10793341/c424cf5e-7d4d-11e5-80bf-135a8834cb8f.PNG)

**Comment by Emdek** [comment]
Try again, I've re-uploaded all packages.

**Comment by resbro** [comment]
New one works great, Thanks!

**Comment by Emdek** [comment]
@resbro, thanks for confirmation.
I've finally managed to connect to connect to sf.net using their SFTP service, that way is far more reliable, so corrupted packages should be a thing of the past, hopefully. ;-)

**Comment by resbro** [comment]
Cool, thanks again!
