### ISSUE TITLE
HtmlBookmarksImporter::import() and m_file.

### ISSUE THREAD

**Issue by textbrowser** [OtterBrowser/otter-browser#979]
The public slot import() hopes that setPath() will be issued before it. You may also see "QTextStream: No device" on the console for other import-like classes which possess m_file objects if their import() slots are reached before their m_file objects are initialized.

```
bool HtmlBookmarksImporter::import()
{
    if(!m_file)
      return false;

	QWebPage page;

	handleOptions();

	page.mainFrame()->setHtml(m_file->readAll()); // m_file is initialized to 0.

	processElement(page.mainFrame()->documentElement());

	return true;
}
```

**Comment by Chocimier** [comment]
How do you achieve calling import() before setPath()?

**Comment by textbrowser** [comment]
I don't use Otter. You should be able to answer that question. I was curious of the possibility. The proposed change only requires two new statements.
