### ISSUE TITLE
self-signed ssl error checkbox message is incorrect

### ISSUE THREAD

**Issue by habys** [OtterBrowser/otter-browser#982]
The checkbox to not ask again only works if you choose to continue, if you don't want to load the page, it will ask you every time. Since I am seeing this mostly with ads and other junk, I don't care to load the offending code.

**Comment by myier** [comment]
If you allow it while visiting the page, it will still not work when the page is in the start page because of the SSL error.
And checking 'do not show this message again' will still show it over and over, when the page has an automatic reload thing like squirrelmail.

**Comment by myier** [comment]
Ok, let me correct this last message for the latest version: the start page invalid certificate page is still not displaying because of the ssl error, but the 'do not show this message again' popup has disappeared, even when reopening otter.
