### ISSUE TITLE
Crash into the Search Preferences dialog

### ISSUE THREAD

**Issue by VSHY** [OtterBrowser/otter-browser#994]
Open Search Preferences dialog (Search field -> Manage Search Engines...) and click the "All settings" button, as result - crash.

If to open Tools -> Preferences -> Search tab -> "All settings" button, - the crash doesn't happens.

P.S. The Search Preferences dialog is not saving own size.

**Comment by resbro** [comment]
Cannot confirm the crash. I can't make it happen in windows 10.
Can confirm the dialog size thingy. None of my dialog boxes retain the size I set them. Nor does the Main window.

win 10 x64
Otter weekly 98 x32

**Comment by Emdek** [comment]
@VSHY, there used to be such crash many weeklies ago, which one are you using now?
You should provide such information every time when reporting issues, for example using the same way as @resbro. :-)

**Comment by ZarkBit** [comment]
Might need a clean install, updating started to create some problems for me.

**Comment by VSHY** [comment]
@ZarkBit 
I have never used a installer (setup-file).

**Comment by ZarkBit** [comment]
what about %localappdata%

**Comment by VSHY** [comment]
%localappdata% is the same as the "profile folder"

**Comment by Emdek** [comment]
@VSHY, could you please try to purge target folder (the one containing *otter-browser.exe*) and extract package one more time, just in case?

**Comment by VSHY** [comment]
When I install Otter, I do it always.
Done, but it is no helped.

**Comment by VSHY** [comment]
In build 99 that crash does not reproduce. I'll close this ticket.
