### ISSUE TITLE
Drag&Drop - AddressField::DropAction="paste" works as "copy+past"

### ISSUE THREAD

**Issue by VSHY** [OtterBrowser/otter-browser#995]
In the SearchField I write text "test", select "es" and drag&drop it to end of line, as result I nave "testes". Must be "ttes".

Win7 x64, Otter 32-bit; this glitch has appeared since the last revision of DropAction.

**Comment by ZarkBit** [comment]
hmm, different behavior in here
https://dl.dropboxusercontent.com/s/ylsnw8fjq97c5j5/2015-11-19_19-53-22.mp4

Windows 7 64bit
Otter 0.9.08 Weekly 98

**Comment by VSHY** [comment]
@ZarkBit 
Probably, you have DropAction="replace".

**Comment by ZarkBit** [comment]
yep, had replace, checked again, confirmed then.

**Comment by Emdek** [comment]
@VSHY, are you 100% sure that it ever worked in different way?
I've tested that on standard ``QLineEdit`` and it behaves exactly the same way (copying, not moving, at least under X11).
Although I've found a way to force it to move text, so I'll workaround this.
