### ISSUE TITLE
No mouse wheel scroll function on tabs bar

### ISSUE THREAD

**Issue by ZarkBit** [OtterBrowser/otter-browser#996]
Screenshot just shows a considerable amount of websites opened, the scroll arrows appear but cannot use the mouse wheel to scroll through it.

https://dl.dropboxusercontent.com/s/uwprz59gmlhfjuq/Tecnologia.com.pt_-_O_Portal_da_Tecnologia_-_Otter_2015-11-19_20-05-03.png

Otter 0.9.08 Weekly 98
Windows 7 64bit

**Comment by Emdek** [comment]
@ZarkBit, sadly ``QTabBar`` doesn't allow to do that (at least not without switching to some tab first).
We can solve this as part of #190.
